// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { StaticModifierRef } from "@pdx-ts/sdk";

export type VanillaStaticModifierTrieDeficit = {
  readonly alloys_deficit: StaticModifierRef & {
    readonly id: "alloys_deficit";
  };
  readonly consumer_goods_deficit: StaticModifierRef & {
    readonly id: "consumer_goods_deficit";
  };
  readonly consumer_goods_rationing: StaticModifierRef & {
    readonly id: "consumer_goods_rationing";
  };
  readonly country_defaulted: StaticModifierRef & {
    readonly id: "country_defaulted";
  };
  readonly country_defaulted_wilderness: StaticModifierRef & {
    readonly id: "country_defaulted_wilderness";
  };
  readonly dark_matter_deficit: StaticModifierRef & {
    readonly id: "dark_matter_deficit";
  };
  readonly energy_deficit: StaticModifierRef & {
    readonly id: "energy_deficit";
  };
  readonly exotic_gases_deficit: StaticModifierRef & {
    readonly id: "exotic_gases_deficit";
  };
  readonly faction_loan_taken: StaticModifierRef & {
    readonly id: "faction_loan_taken";
  };
  readonly food_deficit: StaticModifierRef & {
    readonly id: "food_deficit";
  };
  readonly influence_deficit: StaticModifierRef & {
    readonly id: "influence_deficit";
  };
  readonly minerals_deficit: StaticModifierRef & {
    readonly id: "minerals_deficit";
  };
  readonly nanites_deficit: StaticModifierRef & {
    readonly id: "nanites_deficit";
  };
  readonly rare_crystals_deficit: StaticModifierRef & {
    readonly id: "rare_crystals_deficit";
  };
  readonly sr_living_metal_deficit: StaticModifierRef & {
    readonly id: "sr_living_metal_deficit";
  };
  readonly sr_zro_deficit: StaticModifierRef & {
    readonly id: "sr_zro_deficit";
  };
  readonly trade_deficit: StaticModifierRef & {
    readonly id: "trade_deficit";
  };
  readonly unity_deficit: StaticModifierRef & {
    readonly id: "unity_deficit";
  };
  readonly volatile_motes_deficit: StaticModifierRef & {
    readonly id: "volatile_motes_deficit";
  };
};
