// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { StaticModifierRef } from "@pdx-ts/sdk";

export type VanillaStaticModifierTrieFactions = {
  readonly embraced_another_faction: StaticModifierRef & {
    readonly id: "embraced_another_faction";
  };
  readonly embraced_faction: StaticModifierRef & {
    readonly id: "embraced_faction";
  };
  readonly embraced_faction_timer: StaticModifierRef & {
    readonly id: "embraced_faction_timer";
  };
  readonly faction_approval_average: StaticModifierRef & {
    readonly id: "faction_approval_average";
  };
  readonly faction_approval_high: StaticModifierRef & {
    readonly id: "faction_approval_high";
  };
  readonly faction_approval_low: StaticModifierRef & {
    readonly id: "faction_approval_low";
  };
  readonly faction_approval_very_high: StaticModifierRef & {
    readonly id: "faction_approval_very_high";
  };
  readonly faction_approval_very_low: StaticModifierRef & {
    readonly id: "faction_approval_very_low";
  };
  readonly promoted_authoritarian: StaticModifierRef & {
    readonly id: "promoted_authoritarian";
  };
  readonly promoted_egalitarian: StaticModifierRef & {
    readonly id: "promoted_egalitarian";
  };
  readonly promoted_materialist: StaticModifierRef & {
    readonly id: "promoted_materialist";
  };
  readonly promoted_militarist: StaticModifierRef & {
    readonly id: "promoted_militarist";
  };
  readonly promoted_pacifist: StaticModifierRef & {
    readonly id: "promoted_pacifist";
  };
  readonly promoted_spiritualist: StaticModifierRef & {
    readonly id: "promoted_spiritualist";
  };
  readonly promoted_xenophile: StaticModifierRef & {
    readonly id: "promoted_xenophile";
  };
  readonly promoted_xenophobe: StaticModifierRef & {
    readonly id: "promoted_xenophobe";
  };
  readonly suppressed_authoritarian: StaticModifierRef & {
    readonly id: "suppressed_authoritarian";
  };
  readonly suppressed_egalitarian: StaticModifierRef & {
    readonly id: "suppressed_egalitarian";
  };
  readonly suppressed_faction: StaticModifierRef & {
    readonly id: "suppressed_faction";
  };
  readonly suppressed_materialist: StaticModifierRef & {
    readonly id: "suppressed_materialist";
  };
  readonly suppressed_militarist: StaticModifierRef & {
    readonly id: "suppressed_militarist";
  };
  readonly suppressed_pacifist: StaticModifierRef & {
    readonly id: "suppressed_pacifist";
  };
  readonly suppressed_spiritualist: StaticModifierRef & {
    readonly id: "suppressed_spiritualist";
  };
  readonly suppressed_xenophile: StaticModifierRef & {
    readonly id: "suppressed_xenophile";
  };
  readonly suppressed_xenophobe: StaticModifierRef & {
    readonly id: "suppressed_xenophobe";
  };
};
