// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { StaticModifierRef } from "@pdx-ts/sdk";

export type VanillaStaticModifierTrieStrangeWorlds = {
  readonly ladder_wars_pre_ftl: StaticModifierRef & {
    readonly id: "ladder_wars_pre_ftl";
  };
  readonly living_metal_mega_construction_insight: StaticModifierRef & {
    readonly id: "living_metal_mega_construction_insight";
  };
  readonly pm_bd_creativity: StaticModifierRef & {
    readonly id: "pm_bd_creativity";
  };
  readonly pm_bd_reproduction: StaticModifierRef & {
    readonly id: "pm_bd_reproduction";
  };
  readonly pm_bd_strength: StaticModifierRef & {
    readonly id: "pm_bd_strength";
  };
  readonly pm_bleeding_planet: StaticModifierRef & {
    readonly id: "pm_bleeding_planet";
  };
  readonly pm_catalytic_excrement: StaticModifierRef & {
    readonly id: "pm_catalytic_excrement";
  };
  readonly pm_contruction_coagulate: StaticModifierRef & {
    readonly id: "pm_contruction_coagulate";
  };
  readonly pm_dark_matter_geyser: StaticModifierRef & {
    readonly id: "pm_dark_matter_geyser";
  };
  readonly pm_dark_matter_statue: StaticModifierRef & {
    readonly id: "pm_dark_matter_statue";
  };
  readonly pm_frying_fauna: StaticModifierRef & {
    readonly id: "pm_frying_fauna";
  };
  readonly pm_frying_fauna_2: StaticModifierRef & {
    readonly id: "pm_frying_fauna_2";
  };
  readonly pm_frying_fauna_2_machine: StaticModifierRef & {
    readonly id: "pm_frying_fauna_2_machine";
  };
  readonly pm_frying_fauna_machine: StaticModifierRef & {
    readonly id: "pm_frying_fauna_machine";
  };
  readonly pm_gaseous_fauna: StaticModifierRef & {
    readonly id: "pm_gaseous_fauna";
  };
  readonly pm_hemosymbiosis: StaticModifierRef & {
    readonly id: "pm_hemosymbiosis";
  };
  readonly pm_parasitic_production: StaticModifierRef & {
    readonly id: "pm_parasitic_production";
  };
  readonly pm_peacekeeper_deployment: StaticModifierRef & {
    readonly id: "pm_peacekeeper_deployment";
  };
  readonly pm_perpetual_lightning: StaticModifierRef & {
    readonly id: "pm_perpetual_lightning";
  };
  readonly pm_population_quarantine: StaticModifierRef & {
    readonly id: "pm_population_quarantine";
  };
  readonly pm_raining_corpses: StaticModifierRef & {
    readonly id: "pm_raining_corpses";
  };
  readonly pm_raining_corpses_no_ancrel: StaticModifierRef & {
    readonly id: "pm_raining_corpses_no_ancrel";
  };
  readonly pm_revolting_pests: StaticModifierRef & {
    readonly id: "pm_revolting_pests";
  };
  readonly pm_rural_privilege_broken_shackles: StaticModifierRef & {
    readonly id: "pm_rural_privilege_broken_shackles";
  };
  readonly pm_rural_privilege_regular: StaticModifierRef & {
    readonly id: "pm_rural_privilege_regular";
  };
  readonly pm_strange_sandstorm: StaticModifierRef & {
    readonly id: "pm_strange_sandstorm";
  };
  readonly pm_urban_privilege_broken_shackles: StaticModifierRef & {
    readonly id: "pm_urban_privilege_broken_shackles";
  };
  readonly pm_urban_privilege_regular: StaticModifierRef & {
    readonly id: "pm_urban_privilege_regular";
  };
};
