// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { StaticModifierRef } from "@pdx-ts/sdk/stellaris";

export type VanillaStaticModifierTrieLeviathans = {
  readonly asteroid_hive_weak_points: StaticModifierRef & {
    readonly id: "asteroid_hive_weak_points";
  };
  readonly automated_dreadnought_weak_points: StaticModifierRef & {
    readonly id: "automated_dreadnought_weak_points";
  };
  readonly black_hole_pantagruel: StaticModifierRef & {
    readonly id: "black_hole_pantagruel";
  };
  readonly black_hole_pantagruel_research: StaticModifierRef & {
    readonly id: "black_hole_pantagruel_research";
  };
  readonly curator_buff_sphere: StaticModifierRef & {
    readonly id: "curator_buff_sphere";
  };
  readonly curator_buff_stellarite: StaticModifierRef & {
    readonly id: "curator_buff_stellarite";
  };
  readonly curator_insight: StaticModifierRef & {
    readonly id: "curator_insight";
  };
  readonly dimensional_horror_weak_points: StaticModifierRef & {
    readonly id: "dimensional_horror_weak_points";
  };
  readonly draconic_beats: StaticModifierRef & {
    readonly id: "draconic_beats";
  };
  readonly enclave_artist_festival: StaticModifierRef & {
    readonly id: "enclave_artist_festival";
  };
  readonly enclave_artist_festival_outrage: StaticModifierRef & {
    readonly id: "enclave_artist_festival_outrage";
  };
  readonly enclave_artist_patron: StaticModifierRef & {
    readonly id: "enclave_artist_patron";
  };
  readonly germinating_wraith: StaticModifierRef & {
    readonly id: "germinating_wraith";
  };
  readonly infinity_calculations: StaticModifierRef & {
    readonly id: "infinity_calculations";
  };
  readonly infinity_calculations_hacked: StaticModifierRef & {
    readonly id: "infinity_calculations_hacked";
  };
  readonly spectral_residue_studies: StaticModifierRef & {
    readonly id: "spectral_residue_studies";
  };
  readonly technosphere_praising: StaticModifierRef & {
    readonly id: "technosphere_praising";
  };
  readonly war_in_heaven_is_over: StaticModifierRef & {
    readonly id: "war_in_heaven_is_over";
  };
  readonly wraith_frequency_sync: StaticModifierRef & {
    readonly id: "wraith_frequency_sync";
  };
};
