// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSoundEffectTrieToxoids = {
  readonly events: {
    readonly tox_events: {
      readonly event_first_contact_toxoid: SoundEffectRef & {
        readonly id: "event_first_contact_toxoid";
      };
      readonly evn_tox_knights_of_the_toxic_god: SoundEffectRef & {
        readonly id: "evn_tox_knights_of_the_toxic_god";
      };
      readonly evn_tox_overtuned_origin: SoundEffectRef & {
        readonly id: "evn_tox_overtuned_origin";
      };
    };
  };
  readonly planets: {
    readonly tox_planets: {
      readonly tox_amb_star_hum: SoundEffectRef & {
        readonly id: "tox_amb_star_hum";
      };
    };
  };
  readonly portraits: {
    readonly tox_portraits: {
      readonly tox_portrait_01: SoundEffectRef & {
        readonly id: "tox_portrait_01";
      };
      readonly tox_portrait_02: SoundEffectRef & {
        readonly id: "tox_portrait_02";
      };
      readonly tox_portrait_03: SoundEffectRef & {
        readonly id: "tox_portrait_03";
      };
      readonly tox_portrait_04: SoundEffectRef & {
        readonly id: "tox_portrait_04";
      };
      readonly tox_portrait_05: SoundEffectRef & {
        readonly id: "tox_portrait_05";
      };
      readonly tox_portrait_06: SoundEffectRef & {
        readonly id: "tox_portrait_06";
      };
      readonly tox_portrait_07: SoundEffectRef & {
        readonly id: "tox_portrait_07";
      };
      readonly tox_portrait_08: SoundEffectRef & {
        readonly id: "tox_portrait_08";
      };
      readonly tox_portrait_09: SoundEffectRef & {
        readonly id: "tox_portrait_09";
      };
      readonly tox_portrait_10: SoundEffectRef & {
        readonly id: "tox_portrait_10";
      };
      readonly tox_portrait_11: SoundEffectRef & {
        readonly id: "tox_portrait_11";
      };
      readonly tox_portrait_12: SoundEffectRef & {
        readonly id: "tox_portrait_12";
      };
      readonly tox_portrait_13: SoundEffectRef & {
        readonly id: "tox_portrait_13";
      };
      readonly tox_portrait_14: SoundEffectRef & {
        readonly id: "tox_portrait_14";
      };
      readonly tox_portrait_15: SoundEffectRef & {
        readonly id: "tox_portrait_15";
      };
      readonly tox_portrait_machine: SoundEffectRef & {
        readonly id: "tox_portrait_machine";
      };
    };
  };
  readonly ships: {
    readonly tox_ships_idles: {
      readonly tox_god_idle: SoundEffectRef & {
        readonly id: "tox_god_idle";
      };
      readonly tox_ship_battleship_idle: SoundEffectRef & {
        readonly id: "tox_ship_battleship_idle";
      };
      readonly tox_ship_colony_ship_idle: SoundEffectRef & {
        readonly id: "tox_ship_colony_ship_idle";
      };
      readonly tox_ship_colossus_closing: SoundEffectRef & {
        readonly id: "tox_ship_colossus_closing";
      };
      readonly tox_ship_colossus_idle: SoundEffectRef & {
        readonly id: "tox_ship_colossus_idle";
      };
      readonly tox_ship_colossus_open: SoundEffectRef & {
        readonly id: "tox_ship_colossus_open";
      };
      readonly tox_ship_construction_ship_idle: SoundEffectRef & {
        readonly id: "tox_ship_construction_ship_idle";
      };
      readonly tox_ship_corvette_idle: SoundEffectRef & {
        readonly id: "tox_ship_corvette_idle";
      };
      readonly tox_ship_cruiser_idle: SoundEffectRef & {
        readonly id: "tox_ship_cruiser_idle";
      };
      readonly tox_ship_destroyer_idle: SoundEffectRef & {
        readonly id: "tox_ship_destroyer_idle";
      };
      readonly tox_ship_habitat_idle: SoundEffectRef & {
        readonly id: "tox_ship_habitat_idle";
      };
      readonly tox_ship_juggernaut_idle: SoundEffectRef & {
        readonly id: "tox_ship_juggernaut_idle";
      };
      readonly tox_ship_science_ship_idle: SoundEffectRef & {
        readonly id: "tox_ship_science_ship_idle";
      };
      readonly tox_ship_starbase_idle: SoundEffectRef & {
        readonly id: "tox_ship_starbase_idle";
      };
      readonly tox_ship_titan_idle: SoundEffectRef & {
        readonly id: "tox_ship_titan_idle";
      };
      readonly tox_ship_transport_ship_idle: SoundEffectRef & {
        readonly id: "tox_ship_transport_ship_idle";
      };
    };
    readonly tox_ships_moves: {
      readonly tox_god_move: SoundEffectRef & {
        readonly id: "tox_god_move";
      };
      readonly tox_ship_battleship_move: SoundEffectRef & {
        readonly id: "tox_ship_battleship_move";
      };
      readonly tox_ship_colony_ship_move: SoundEffectRef & {
        readonly id: "tox_ship_colony_ship_move";
      };
      readonly tox_ship_colossus_move: SoundEffectRef & {
        readonly id: "tox_ship_colossus_move";
      };
      readonly tox_ship_construction_ship_move: SoundEffectRef & {
        readonly id: "tox_ship_construction_ship_move";
      };
      readonly tox_ship_corvette_move: SoundEffectRef & {
        readonly id: "tox_ship_corvette_move";
      };
      readonly tox_ship_cruiser_move: SoundEffectRef & {
        readonly id: "tox_ship_cruiser_move";
      };
      readonly tox_ship_destroyer_move: SoundEffectRef & {
        readonly id: "tox_ship_destroyer_move";
      };
      readonly tox_ship_juggernaut_move: SoundEffectRef & {
        readonly id: "tox_ship_juggernaut_move";
      };
      readonly tox_ship_science_ship_move: SoundEffectRef & {
        readonly id: "tox_ship_science_ship_move";
      };
      readonly tox_ship_titan_move: SoundEffectRef & {
        readonly id: "tox_ship_titan_move";
      };
      readonly tox_ship_transport_ship_move: SoundEffectRef & {
        readonly id: "tox_ship_transport_ship_move";
      };
    };
  };
  readonly stations: {
    readonly tox_stations: {
      readonly tox_ship_military_station_idle: SoundEffectRef & {
        readonly id: "tox_ship_military_station_idle";
      };
      readonly tox_ship_mining_station_idle: SoundEffectRef & {
        readonly id: "tox_ship_mining_station_idle";
      };
      readonly tox_ship_research_station_idle: SoundEffectRef & {
        readonly id: "tox_ship_research_station_idle";
      };
    };
  };
  readonly weapons: {
    readonly toxic_god_weapons: {
      readonly toxic_god_wep_megastructure_hit: SoundEffectRef & {
        readonly id: "toxic_god_wep_megastructure_hit";
      };
      readonly toxic_god_wep_muzzle: SoundEffectRef & {
        readonly id: "toxic_god_wep_muzzle";
      };
      readonly toxic_god_wep_planet_hit: SoundEffectRef & {
        readonly id: "toxic_god_wep_planet_hit";
      };
      readonly toxic_god_wep_windup: SoundEffectRef & {
        readonly id: "toxic_god_wep_windup";
      };
    };
  };
};
