// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { AnomalyCategoryRef } from "@pdx-ts/sdk/stellaris";

export type VanillaAnomalyCategoryTrieAnomalyCategoriesUnplugged = {
  readonly MACHINE_LEGACY_CREATORS_CAT: AnomalyCategoryRef & {
    readonly id: "MACHINE_LEGACY_CREATORS_CAT";
  };
  readonly MACHINE_LEGACY_MAKERS_CAT: AnomalyCategoryRef & {
    readonly id: "MACHINE_LEGACY_MAKERS_CAT";
  };
  readonly MACHINE_LEGACY_MAKERS_UNPLUGGED_CAT: AnomalyCategoryRef & {
    readonly id: "MACHINE_LEGACY_MAKERS_UNPLUGGED_CAT";
  };
  readonly MACHINE_LEGACY_TAKEN_CAT: AnomalyCategoryRef & {
    readonly id: "MACHINE_LEGACY_TAKEN_CAT";
  };
};
