// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { VanillaAnomalyCategoryTrieAnomalyCategoriesAi } from "./anomaly-categories-ai.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesAncientRelics } from "./anomaly-categories-ancient-relics.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesAstralPlanes } from "./anomaly-categories-astral-planes.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesCosmicStorms } from "./anomaly-categories-cosmic-storms.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesDistantStars } from "./anomaly-categories-distant-stars.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesExtremeFrontiers } from "./anomaly-categories-extreme-frontiers.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesFederations } from "./anomaly-categories-federations.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesInfernals } from "./anomaly-categories-infernals.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesParagon } from "./anomaly-categories-paragon.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesPrecursors } from "./anomaly-categories-precursors.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesTutorial } from "./anomaly-categories-tutorial.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategoriesUnplugged } from "./anomaly-categories-unplugged.ts";
import type { VanillaAnomalyCategoryTrieAnomalyCategories } from "./anomaly-categories.ts";

export interface VanillaAnomalyCategoryTrie {
  readonly anomaly_categories: VanillaAnomalyCategoryTrieAnomalyCategories;
  readonly anomaly_categories_ai: VanillaAnomalyCategoryTrieAnomalyCategoriesAi;
  readonly anomaly_categories_ancient_relics: VanillaAnomalyCategoryTrieAnomalyCategoriesAncientRelics;
  readonly anomaly_categories_astral_planes: VanillaAnomalyCategoryTrieAnomalyCategoriesAstralPlanes;
  readonly anomaly_categories_cosmic_storms: VanillaAnomalyCategoryTrieAnomalyCategoriesCosmicStorms;
  readonly anomaly_categories_distant_stars: VanillaAnomalyCategoryTrieAnomalyCategoriesDistantStars;
  readonly anomaly_categories_extreme_frontiers: VanillaAnomalyCategoryTrieAnomalyCategoriesExtremeFrontiers;
  readonly anomaly_categories_federations: VanillaAnomalyCategoryTrieAnomalyCategoriesFederations;
  readonly anomaly_categories_infernals: VanillaAnomalyCategoryTrieAnomalyCategoriesInfernals;
  readonly anomaly_categories_paragon: VanillaAnomalyCategoryTrieAnomalyCategoriesParagon;
  readonly anomaly_categories_precursors: VanillaAnomalyCategoryTrieAnomalyCategoriesPrecursors;
  readonly anomaly_categories_tutorial: VanillaAnomalyCategoryTrieAnomalyCategoriesTutorial;
  readonly anomaly_categories_unplugged: VanillaAnomalyCategoryTrieAnomalyCategoriesUnplugged;
}
