// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { ModelMeshRef } from "@pdx-ts/sdk/stellaris";

export type VanillaPdxmeshTrieTestgalaxy01Meshes = {
  readonly spacedust_mesh: ModelMeshRef & {
    readonly id: "spacedust_mesh";
  };
};
