// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { ModelMeshRef } from "@pdx-ts/sdk/stellaris";

export type VanillaPdxmeshTrieCombatItems = {
  readonly _apocalypse_weapon_meshes: {
    readonly assimilate_hit_effect_mesh: ModelMeshRef & {
      readonly id: "assimilate_hit_effect_mesh";
    };
    readonly necroid_01_ion_cannon_windup_effect_mesh: ModelMeshRef & {
      readonly id: "necroid_01_ion_cannon_windup_effect_mesh";
    };
    readonly perdition_beam_muzzle_windup_part1_mesh: ModelMeshRef & {
      readonly id: "perdition_beam_muzzle_windup_part1_mesh";
    };
    readonly perdition_beam_muzzle_windup_part2_mesh: ModelMeshRef & {
      readonly id: "perdition_beam_muzzle_windup_part2_mesh";
    };
    readonly perdition_beam_muzzle_windup_part3_mesh: ModelMeshRef & {
      readonly id: "perdition_beam_muzzle_windup_part3_mesh";
    };
    readonly shielded_planet_laser_hit_mesh: ModelMeshRef & {
      readonly id: "shielded_planet_laser_hit_mesh";
    };
  };
  readonly _ballistics_meshes: {
    readonly adv_kinetic_artillery_tracer_round_mesh: ModelMeshRef & {
      readonly id: "adv_kinetic_artillery_tracer_round_mesh";
    };
    readonly advanced_railgun_tracer_round_mesh: ModelMeshRef & {
      readonly id: "advanced_railgun_tracer_round_mesh";
    };
    readonly coilgun_tracer_round_mesh: ModelMeshRef & {
      readonly id: "coilgun_tracer_round_mesh";
    };
    readonly crystal_projectile_mesh: ModelMeshRef & {
      readonly id: "crystal_projectile_mesh";
    };
    readonly gauss_cannon_tracer_round_mesh: ModelMeshRef & {
      readonly id: "gauss_cannon_tracer_round_mesh";
    };
    readonly green_crystal_projectile_mesh: ModelMeshRef & {
      readonly id: "green_crystal_projectile_mesh";
    };
    readonly kinetic_artillery_tracer_round_mesh: ModelMeshRef & {
      readonly id: "kinetic_artillery_tracer_round_mesh";
    };
    readonly mass_driver_tracer_round_mesh: ModelMeshRef & {
      readonly id: "mass_driver_tracer_round_mesh";
    };
    readonly meteoroid_slinger_tracer_round_mesh: ModelMeshRef & {
      readonly id: "meteoroid_slinger_tracer_round_mesh";
    };
    readonly railgun_tracer_round_mesh: ModelMeshRef & {
      readonly id: "railgun_tracer_round_mesh";
    };
    readonly red_crystal_projectile_mesh: ModelMeshRef & {
      readonly id: "red_crystal_projectile_mesh";
    };
    readonly space_amoeba_projectile_mesh: ModelMeshRef & {
      readonly id: "space_amoeba_projectile_mesh";
    };
    readonly yellow_crystal_projectile_mesh: ModelMeshRef & {
      readonly id: "yellow_crystal_projectile_mesh";
    };
  };
  readonly _missiles_meshes: {
    readonly arthropoid_01_missile_mesh: ModelMeshRef & {
      readonly id: "arthropoid_01_missile_mesh";
    };
    readonly spikespore_mesh: ModelMeshRef & {
      readonly id: "spikespore_mesh";
    };
    readonly swarmer_missile_mesh: ModelMeshRef & {
      readonly id: "swarmer_missile_mesh";
    };
  };
  readonly torpedo: {
    readonly torpedo_mesh: ModelMeshRef & {
      readonly id: "torpedo_mesh";
    };
  };
};
