// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { ModelMeshRef } from "@pdx-ts/sdk/stellaris";

export type VanillaPdxmeshTrieEffects = {
  readonly _nebula_mesh: {
    readonly nebula_1_mesh: ModelMeshRef & {
      readonly id: "nebula_1_mesh";
    };
    readonly nebula_2_mesh: ModelMeshRef & {
      readonly id: "nebula_2_mesh";
    };
    readonly nebula_3_mesh: ModelMeshRef & {
      readonly id: "nebula_3_mesh";
    };
    readonly nebula_4_color_2_mesh: ModelMeshRef & {
      readonly id: "nebula_4_color_2_mesh";
    };
    readonly nebula_4_color_mesh: ModelMeshRef & {
      readonly id: "nebula_4_color_mesh";
    };
    readonly nebula_4_mesh: ModelMeshRef & {
      readonly id: "nebula_4_mesh";
    };
    readonly nebula_5_2_mesh: ModelMeshRef & {
      readonly id: "nebula_5_2_mesh";
    };
    readonly nebula_5_3_mesh: ModelMeshRef & {
      readonly id: "nebula_5_3_mesh";
    };
    readonly nebula_5_color_2_mesh: ModelMeshRef & {
      readonly id: "nebula_5_color_2_mesh";
    };
    readonly nebula_5_color_3_mesh: ModelMeshRef & {
      readonly id: "nebula_5_color_3_mesh";
    };
    readonly nebula_5_color_mesh: ModelMeshRef & {
      readonly id: "nebula_5_color_mesh";
    };
    readonly nebula_5_mesh: ModelMeshRef & {
      readonly id: "nebula_5_mesh";
    };
    readonly nebula_6_2_mesh: ModelMeshRef & {
      readonly id: "nebula_6_2_mesh";
    };
    readonly nebula_6_3_mesh: ModelMeshRef & {
      readonly id: "nebula_6_3_mesh";
    };
    readonly nebula_6_color_2_mesh: ModelMeshRef & {
      readonly id: "nebula_6_color_2_mesh";
    };
    readonly nebula_6_color_mesh: ModelMeshRef & {
      readonly id: "nebula_6_color_mesh";
    };
    readonly nebula_6_mesh: ModelMeshRef & {
      readonly id: "nebula_6_mesh";
    };
    readonly nebula_7_2_mesh: ModelMeshRef & {
      readonly id: "nebula_7_2_mesh";
    };
    readonly nebula_7_3_mesh: ModelMeshRef & {
      readonly id: "nebula_7_3_mesh";
    };
    readonly nebula_7_mesh: ModelMeshRef & {
      readonly id: "nebula_7_mesh";
    };
    readonly nebula_8_2_mesh: ModelMeshRef & {
      readonly id: "nebula_8_2_mesh";
    };
    readonly nebula_8_3_mesh: ModelMeshRef & {
      readonly id: "nebula_8_3_mesh";
    };
    readonly nebula_8_mesh: ModelMeshRef & {
      readonly id: "nebula_8_mesh";
    };
    readonly nebula_turbulent_2_mesh: ModelMeshRef & {
      readonly id: "nebula_turbulent_2_mesh";
    };
    readonly nebula_turbulent_mesh: ModelMeshRef & {
      readonly id: "nebula_turbulent_mesh";
    };
    readonly system_lightning_1_mesh: ModelMeshRef & {
      readonly id: "system_lightning_1_mesh";
    };
    readonly system_lightning_locations_mesh: ModelMeshRef & {
      readonly id: "system_lightning_locations_mesh";
    };
  };
  readonly _system_effects_mesh: {
    readonly psi_storm_core_mesh: ModelMeshRef & {
      readonly id: "psi_storm_core_mesh";
    };
    readonly starlit_core_mesh: ModelMeshRef & {
      readonly id: "starlit_core_mesh";
    };
    readonly starlit_core_stars_mesh: ModelMeshRef & {
      readonly id: "starlit_core_stars_mesh";
    };
  };
  readonly cosmic_storms: {
    readonly GravityL: {
      readonly GravityL_mesh: ModelMeshRef & {
        readonly id: "GravityL_mesh";
      };
    };
    readonly GravityLines: {
      readonly GravityLines_mesh: ModelMeshRef & {
        readonly id: "GravityLines_mesh";
      };
    };
    readonly GravityM: {
      readonly GravityM_mesh: ModelMeshRef & {
        readonly id: "GravityM_mesh";
      };
    };
    readonly GravityPoints: {
      readonly GravityPoints_mesh: ModelMeshRef & {
        readonly id: "GravityPoints_mesh";
      };
    };
    readonly GravityS: {
      readonly GravityS_mesh: ModelMeshRef & {
        readonly id: "GravityS_mesh";
      };
    };
    readonly GravityXS: {
      readonly GravityXS_mesh: ModelMeshRef & {
        readonly id: "GravityXS_mesh";
      };
    };
    readonly Magnetic_Aurora: {
      readonly Magnetic_Aurora_1: ModelMeshRef & {
        readonly id: "Magnetic_Aurora_1";
      };
    };
    readonly Magnetic_Aurora2: {
      readonly Magnetic_Aurora_2: ModelMeshRef & {
        readonly id: "Magnetic_Aurora_2";
      };
    };
    readonly Magnetic_Aurora3: {
      readonly Magnetic_Aurora_3: ModelMeshRef & {
        readonly id: "Magnetic_Aurora_3";
      };
    };
    readonly Magnetic_Aurora4: {
      readonly Magnetic_Aurora_4: ModelMeshRef & {
        readonly id: "Magnetic_Aurora_4";
      };
    };
    readonly Magnetic_Aurora5: {
      readonly Magnetic_Aurora_5: ModelMeshRef & {
        readonly id: "Magnetic_Aurora_5";
      };
    };
    readonly Magnetic_storm: {
      readonly Magnetic_Storm_mesh1: ModelMeshRef & {
        readonly id: "Magnetic_Storm_mesh1";
      };
    };
    readonly Magnetic_storm2: {
      readonly Magnetic_Storm_mesh2: ModelMeshRef & {
        readonly id: "Magnetic_Storm_mesh2";
      };
    };
    readonly Magnetic_storm3: {
      readonly Magnetic_Storm_mesh3: ModelMeshRef & {
        readonly id: "Magnetic_Storm_mesh3";
      };
    };
    readonly Magnetic_storm4: {
      readonly Magnetic_Storm_mesh4: ModelMeshRef & {
        readonly id: "Magnetic_Storm_mesh4";
      };
    };
    readonly Magnetic_storm5: {
      readonly Magnetic_Storm_mesh5: ModelMeshRef & {
        readonly id: "Magnetic_Storm_mesh5";
      };
    };
    readonly Magnetic_stormCenter: {
      readonly Magnetic_Center: ModelMeshRef & {
        readonly id: "Magnetic_Center";
      };
    };
    readonly Nexus_wisp1: {
      readonly Nexus_wisp1_mesh: ModelMeshRef & {
        readonly id: "Nexus_wisp1_mesh";
      };
    };
    readonly Nexus_wisp2: {
      readonly Nexus_wisp2_mesh: ModelMeshRef & {
        readonly id: "Nexus_wisp2_mesh";
      };
    };
    readonly SM_CelestialStorm: {
      readonly SM_Celestial_Storm_mesh: ModelMeshRef & {
        readonly id: "SM_Celestial_Storm_mesh";
      };
    };
    readonly SM_CelestialStormCap: {
      readonly SM_Celestial_StormCap_mesh: ModelMeshRef & {
        readonly id: "SM_Celestial_StormCap_mesh";
      };
    };
    readonly SM_CelestialStormSides: {
      readonly SM_Celestial_StormSide_mesh: ModelMeshRef & {
        readonly id: "SM_Celestial_StormSide_mesh";
      };
    };
    readonly SM_CelestialStormTop: {
      readonly SM_Celestial_StormTop_mesh: ModelMeshRef & {
        readonly id: "SM_Celestial_StormTop_mesh";
      };
    };
    readonly SM_CelestialWispsB: {
      readonly Celestial_wispB_mesh: ModelMeshRef & {
        readonly id: "Celestial_wispB_mesh";
      };
    };
    readonly SM_CelestialWispsG: {
      readonly Celestial_wispG1_mesh: ModelMeshRef & {
        readonly id: "Celestial_wispG1_mesh";
      };
    };
    readonly SM_CelestialWispsG2: {
      readonly Celestial_wispG2_mesh: ModelMeshRef & {
        readonly id: "Celestial_wispG2_mesh";
      };
    };
    readonly SM_CoasterStorm: {
      readonly SM_CoasterStorm_mesh: ModelMeshRef & {
        readonly id: "SM_CoasterStorm_mesh";
      };
    };
    readonly SM_CoasterStorm_2: {
      readonly SM_CoasterStorm_mesh_2: ModelMeshRef & {
        readonly id: "SM_CoasterStorm_mesh_2";
      };
    };
    readonly SM_Lightning_Mesh: {
      readonly SM_lightning_strike_mesh: ModelMeshRef & {
        readonly id: "SM_lightning_strike_mesh";
      };
    };
    readonly SM_Lightning_Mesh2: {
      readonly SM_lightning_strike_mesh2: ModelMeshRef & {
        readonly id: "SM_lightning_strike_mesh2";
      };
    };
    readonly SM_ShroudCoaster: {
      readonly SM_ShroudCoaster_mesh: ModelMeshRef & {
        readonly id: "SM_ShroudCoaster_mesh";
      };
    };
    readonly SM_ShroudCoaster2: {
      readonly SM_ShroudCoaster_mesh2: ModelMeshRef & {
        readonly id: "SM_ShroudCoaster_mesh2";
      };
    };
    readonly SM_ShroudCoaster3: {
      readonly SM_ShroudCoaster_mesh3: ModelMeshRef & {
        readonly id: "SM_ShroudCoaster_mesh3";
      };
    };
    readonly SM_ShroudStorm: {
      readonly SM_ShroudStorm_mesh: ModelMeshRef & {
        readonly id: "SM_ShroudStorm_mesh";
      };
    };
    readonly SM_ShroudStorm_Tube: {
      readonly SM_ShroudStorm_tube_mesh: ModelMeshRef & {
        readonly id: "SM_ShroudStorm_tube_mesh";
      };
    };
    readonly Solar_Ends: {
      readonly Solar_ends_mesh: ModelMeshRef & {
        readonly id: "Solar_ends_mesh";
      };
    };
    readonly Solar_EndsBig: {
      readonly Solar_endsB_mesh: ModelMeshRef & {
        readonly id: "Solar_endsB_mesh";
      };
    };
    readonly Solar_tube: {
      readonly Solar_tube_mesh: ModelMeshRef & {
        readonly id: "Solar_tube_mesh";
      };
    };
    readonly Solar_tube2: {
      readonly Solar_tube2_mesh: ModelMeshRef & {
        readonly id: "Solar_tube2_mesh";
      };
    };
    readonly Solar_tubeB: {
      readonly Solar_tubeB_mesh: ModelMeshRef & {
        readonly id: "Solar_tubeB_mesh";
      };
    };
    readonly Solar_tubeB2: {
      readonly Solar_tubeB2_mesh: ModelMeshRef & {
        readonly id: "Solar_tubeB2_mesh";
      };
    };
    readonly Solar_tubeS: {
      readonly Solar_tubeS_mesh: ModelMeshRef & {
        readonly id: "Solar_tubeS_mesh";
      };
    };
    readonly Solar_wisp1: {
      readonly Solar_wisp1_mesh: ModelMeshRef & {
        readonly id: "Solar_wisp1_mesh";
      };
    };
    readonly Solar_wisp2: {
      readonly Solar_wisp2_mesh: ModelMeshRef & {
        readonly id: "Solar_wisp2_mesh";
      };
    };
    readonly Solar_wisp3: {
      readonly Solar_wisp3_mesh: ModelMeshRef & {
        readonly id: "Solar_wisp3_mesh";
      };
    };
    readonly nexus_lightning: {
      readonly Nexus_lightning_mesh: ModelMeshRef & {
        readonly id: "Nexus_lightning_mesh";
      };
    };
    readonly nexus_storm: {
      readonly Nexus_storm_mesh: ModelMeshRef & {
        readonly id: "Nexus_storm_mesh";
      };
    };
    readonly stormbhole: {
      readonly stormbhole: ModelMeshRef & {
        readonly id: "stormbhole";
      };
    };
    readonly storminfluence: {
      readonly storminfluence: ModelMeshRef & {
        readonly id: "storminfluence";
      };
    };
    readonly storminfluence2: {
      readonly storminfluenceflow: ModelMeshRef & {
        readonly id: "storminfluenceflow";
      };
    };
  };
  readonly crisis: {
    readonly _horizon_edge_system_effect: {
      readonly horizon_edge_system_effect_mesh: ModelMeshRef & {
        readonly id: "horizon_edge_system_effect_mesh";
      };
    };
    readonly contingency_crisis_system_effect: {
      readonly contingency_crisis_system_effect_10_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_10_mesh";
      };
      readonly contingency_crisis_system_effect_11_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_11_mesh";
      };
      readonly contingency_crisis_system_effect_2_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_2_mesh";
      };
      readonly contingency_crisis_system_effect_3_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_3_mesh";
      };
      readonly contingency_crisis_system_effect_4_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_4_mesh";
      };
      readonly contingency_crisis_system_effect_5_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_5_mesh";
      };
      readonly contingency_crisis_system_effect_6_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_6_mesh";
      };
      readonly contingency_crisis_system_effect_7_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_7_mesh";
      };
      readonly contingency_crisis_system_effect_8_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_8_mesh";
      };
      readonly contingency_crisis_system_effect_9_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_9_mesh";
      };
      readonly contingency_crisis_system_effect_mesh: ModelMeshRef & {
        readonly id: "contingency_crisis_system_effect_mesh";
      };
    };
    readonly extra_dimensional_crisis_effect: {
      readonly extra_dimensional_color_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_color_mesh";
      };
      readonly extra_dimensional_cracks_2_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_cracks_2_mesh";
      };
      readonly extra_dimensional_cracks_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_cracks_mesh";
      };
      readonly extra_dimensional_crisis_rift_2_sides_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_crisis_rift_2_sides_mesh";
      };
      readonly extra_dimensional_crisis_rift_sides_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_crisis_rift_sides_mesh";
      };
      readonly extra_dimensional_lights_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_lights_mesh";
      };
      readonly extra_dimensional_portal_color_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_portal_color_mesh";
      };
      readonly extra_dimensional_portal_cracks_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_portal_cracks_mesh";
      };
      readonly extra_dimensional_portal_light_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_portal_light_mesh";
      };
      readonly extra_dimensional_portal_stars_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_portal_stars_mesh";
      };
      readonly extra_dimensional_stars_mesh: ModelMeshRef & {
        readonly id: "extra_dimensional_stars_mesh";
      };
      readonly extra_dimensional_system_core: ModelMeshRef & {
        readonly id: "extra_dimensional_system_core";
      };
    };
    readonly prethoryn_swarm_crisis_effect: {
      readonly prethoryn_swarm_crisis_2_effect_mesh: ModelMeshRef & {
        readonly id: "prethoryn_swarm_crisis_2_effect_mesh";
      };
      readonly prethoryn_swarm_crisis_3_effect_mesh: ModelMeshRef & {
        readonly id: "prethoryn_swarm_crisis_3_effect_mesh";
      };
      readonly prethoryn_swarm_crisis_4_effect_mesh: ModelMeshRef & {
        readonly id: "prethoryn_swarm_crisis_4_effect_mesh";
      };
      readonly prethoryn_swarm_crisis_effect_mesh: ModelMeshRef & {
        readonly id: "prethoryn_swarm_crisis_effect_mesh";
      };
    };
  };
  readonly fusion_trail: {
    readonly aurora_mesh_1: ModelMeshRef & {
      readonly id: "aurora_mesh_1";
    };
    readonly aurora_mesh_2: ModelMeshRef & {
      readonly id: "aurora_mesh_2";
    };
    readonly aurora_mesh_mesh: ModelMeshRef & {
      readonly id: "aurora_mesh_mesh";
    };
    readonly fusion_trail_mesh_2: ModelMeshRef & {
      readonly id: "fusion_trail_mesh_2";
    };
    readonly fusion_trail_mesh_3: ModelMeshRef & {
      readonly id: "fusion_trail_mesh_3";
    };
    readonly fusion_trail_mesh_mesh: ModelMeshRef & {
      readonly id: "fusion_trail_mesh_mesh";
    };
  };
  readonly infernal: {
    readonly infernal_effects: {
      readonly infernal_ember_battleship_bow_effect_mesh: ModelMeshRef & {
        readonly id: "infernal_ember_battleship_bow_effect_mesh";
      };
      readonly infernal_ember_battleship_mid_effect_mesh: ModelMeshRef & {
        readonly id: "infernal_ember_battleship_mid_effect_mesh";
      };
      readonly infernal_ember_battleship_stern_effect_mesh: ModelMeshRef & {
        readonly id: "infernal_ember_battleship_stern_effect_mesh";
      };
      readonly infernal_ember_cruiser_mid_effect_mesh: ModelMeshRef & {
        readonly id: "infernal_ember_cruiser_mid_effect_mesh";
      };
      readonly infernal_ember_cruiser_stern_effect_mesh: ModelMeshRef & {
        readonly id: "infernal_ember_cruiser_stern_effect_mesh";
      };
      readonly infernal_galactic_crucible_spiral_mesh: ModelMeshRef & {
        readonly id: "infernal_galactic_crucible_spiral_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_cap_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_cap_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_main_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_main_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_side_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_side_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_wispP_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_wispP_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_wispR1_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_wispR1_mesh";
      };
      readonly infernal_red_giant_supernova_nebula_wispR2_mesh: ModelMeshRef & {
        readonly id: "infernal_red_giant_supernova_nebula_wispR2_mesh";
      };
      readonly infernal_subspace_tunnel_portal_mesh: ModelMeshRef & {
        readonly id: "infernal_subspace_tunnel_portal_mesh";
      };
      readonly infernal_subspace_tunnel_spiral_mesh: ModelMeshRef & {
        readonly id: "infernal_subspace_tunnel_spiral_mesh";
      };
      readonly infernal_subspace_tunnel_spiral_ship_to_star_mesh: ModelMeshRef & {
        readonly id: "infernal_subspace_tunnel_spiral_ship_to_star_mesh";
      };
      readonly infernal_subspace_tunnel_spiral_tunnel_to_star_mesh: ModelMeshRef & {
        readonly id: "infernal_subspace_tunnel_spiral_tunnel_to_star_mesh";
      };
    };
  };
  readonly kaleidoscope_system_effect: {
    readonly kaleidoscope_system_effect_frame_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_frame_mesh";
    };
    readonly kaleidoscope_system_effect_inner_happy_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_inner_happy_mesh";
    };
    readonly kaleidoscope_system_effect_inner_mad_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_inner_mad_mesh";
    };
    readonly kaleidoscope_system_effect_inner_neutral_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_inner_neutral_mesh";
    };
    readonly kaleidoscope_system_effect_outer_happy_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_outer_happy_mesh";
    };
    readonly kaleidoscope_system_effect_outer_mad_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_outer_mad_mesh";
    };
    readonly kaleidoscope_system_effect_outer_neutral_mesh: ModelMeshRef & {
      readonly id: "kaleidoscope_system_effect_outer_neutral_mesh";
    };
  };
  readonly nemesis_system_effect_1: {
    readonly nemesis_system_effect_1_mesh: ModelMeshRef & {
      readonly id: "nemesis_system_effect_1_mesh";
    };
    readonly nemesis_system_effect_2_mesh: ModelMeshRef & {
      readonly id: "nemesis_system_effect_2_mesh";
    };
  };
  readonly nomads: {
    readonly stellar_ignition_endsB_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_endsB_mesh";
    };
    readonly stellar_ignition_ends_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_ends_mesh";
    };
    readonly stellar_ignition_tube2_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_tube2_mesh";
    };
    readonly stellar_ignition_tubeB2_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_tubeB2_mesh";
    };
    readonly stellar_ignition_tubeB_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_tubeB_mesh";
    };
    readonly stellar_ignition_tubeS_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_tubeS_mesh";
    };
    readonly stellar_ignition_tube_mesh: ModelMeshRef & {
      readonly id: "stellar_ignition_tube_mesh";
    };
  };
  readonly psionic_auras: {
    readonly _psionic_auras_meshes: {
      readonly composer_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level1_part1_mesh";
      };
      readonly composer_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level1_part2_mesh";
      };
      readonly composer_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level1_part3_mesh";
      };
      readonly composer_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level2_part1_mesh";
      };
      readonly composer_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level2_part2_mesh";
      };
      readonly composer_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level3_part1_mesh";
      };
      readonly composer_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level3_part2_mesh";
      };
      readonly composer_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "composer_aura_level3_part3_mesh";
      };
      readonly desire_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level1_part1_mesh";
      };
      readonly desire_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level1_part2_mesh";
      };
      readonly desire_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level1_part3_mesh";
      };
      readonly desire_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level2_part1_mesh";
      };
      readonly desire_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level2_part2_mesh";
      };
      readonly desire_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level3_part1_mesh";
      };
      readonly desire_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level3_part2_mesh";
      };
      readonly desire_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "desire_aura_level3_part3_mesh";
      };
      readonly eater_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level1_part1_mesh";
      };
      readonly eater_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level1_part2_mesh";
      };
      readonly eater_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level1_part3_mesh";
      };
      readonly eater_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level2_part1_mesh";
      };
      readonly eater_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level2_part2_mesh";
      };
      readonly eater_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level3_part1_mesh";
      };
      readonly eater_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level3_part2_mesh";
      };
      readonly eater_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "eater_aura_level3_part3_mesh";
      };
      readonly end_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "end_aura_level1_part1_mesh";
      };
      readonly end_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "end_aura_level1_part2_mesh";
      };
      readonly end_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "end_aura_level1_part3_mesh";
      };
      readonly end_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "end_aura_level2_part1_mesh";
      };
      readonly end_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "end_aura_level2_part2_mesh";
      };
      readonly end_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "end_aura_level3_part1_mesh";
      };
      readonly end_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "end_aura_level3_part2_mesh";
      };
      readonly end_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "end_aura_level3_part3_mesh";
      };
      readonly souls_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level1_part1_mesh";
      };
      readonly souls_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level1_part2_mesh";
      };
      readonly souls_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level1_part3_mesh";
      };
      readonly souls_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level2_part1_mesh";
      };
      readonly souls_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level2_part2_mesh";
      };
      readonly souls_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level3_part1_mesh";
      };
      readonly souls_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level3_part2_mesh";
      };
      readonly souls_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "souls_aura_level3_part3_mesh";
      };
      readonly whisperers_aura_level1_part1_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level1_part1_mesh";
      };
      readonly whisperers_aura_level1_part2_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level1_part2_mesh";
      };
      readonly whisperers_aura_level1_part3_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level1_part3_mesh";
      };
      readonly whisperers_aura_level2_part1_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level2_part1_mesh";
      };
      readonly whisperers_aura_level2_part2_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level2_part2_mesh";
      };
      readonly whisperers_aura_level3_part1_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level3_part1_mesh";
      };
      readonly whisperers_aura_level3_part2_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level3_part2_mesh";
      };
      readonly whisperers_aura_level3_part3_mesh: ModelMeshRef & {
        readonly id: "whisperers_aura_level3_part3_mesh";
      };
    };
  };
  readonly synth_queen: {
    readonly synth_queen_system_orb: {
      readonly synth_queen_system_arms_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_arms_mesh";
      };
      readonly synth_queen_system_cylinder_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_cylinder_mesh";
      };
      readonly synth_queen_system_locators_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_locators_mesh";
      };
      readonly synth_queen_system_orb_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_orb_mesh";
      };
      readonly synth_queen_system_short_arms_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_short_arms_mesh";
      };
      readonly synth_queen_system_swarm_mesh: ModelMeshRef & {
        readonly id: "synth_queen_system_swarm_mesh";
      };
    };
  };
  readonly system_plane_collision: {
    readonly system_plane_collision_mesh: ModelMeshRef & {
      readonly id: "system_plane_collision_mesh";
    };
  };
};
