// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { DepositRef } from "@pdx-ts/sdk";

export type VanillaDepositTrieAncientRelicsDeposits = {
  readonly d_abandoned_mining_tunnels: DepositRef & {
    readonly id: "d_abandoned_mining_tunnels";
  };
  readonly d_ancient_reactor_pits: DepositRef & {
    readonly id: "d_ancient_reactor_pits";
  };
  readonly d_artifacts_mining_1: DepositRef & {
    readonly id: "d_artifacts_mining_1";
  };
  readonly d_artifacts_mining_2: DepositRef & {
    readonly id: "d_artifacts_mining_2";
  };
  readonly d_artifacts_mining_3: DepositRef & {
    readonly id: "d_artifacts_mining_3";
  };
  readonly d_artifacts_planet_1: DepositRef & {
    readonly id: "d_artifacts_planet_1";
  };
  readonly d_artifacts_planet_2: DepositRef & {
    readonly id: "d_artifacts_planet_2";
  };
  readonly d_artifacts_planet_3: DepositRef & {
    readonly id: "d_artifacts_planet_3";
  };
  readonly d_artifacts_research_1: DepositRef & {
    readonly id: "d_artifacts_research_1";
  };
  readonly d_artifacts_research_2: DepositRef & {
    readonly id: "d_artifacts_research_2";
  };
  readonly d_artifacts_research_3: DepositRef & {
    readonly id: "d_artifacts_research_3";
  };
  readonly d_baol_growth: DepositRef & {
    readonly id: "d_baol_growth";
  };
  readonly d_central_spire: DepositRef & {
    readonly id: "d_central_spire";
  };
  readonly d_collapsed_spire: DepositRef & {
    readonly id: "d_collapsed_spire";
  };
  readonly d_crumbling_mining_tunnels: DepositRef & {
    readonly id: "d_crumbling_mining_tunnels";
  };
  readonly d_flooded_reactor_pits: DepositRef & {
    readonly id: "d_flooded_reactor_pits";
  };
  readonly d_former_relic_world: DepositRef & {
    readonly id: "d_former_relic_world";
  };
  readonly d_immense_solar_array: DepositRef & {
    readonly id: "d_immense_solar_array";
  };
  readonly d_industrial_sector: DepositRef & {
    readonly id: "d_industrial_sector";
  };
  readonly d_massive_crevice: DepositRef & {
    readonly id: "d_massive_crevice";
  };
  readonly d_mutation_vats: DepositRef & {
    readonly id: "d_mutation_vats";
  };
  readonly d_relic_dense_ruins: DepositRef & {
    readonly id: "d_relic_dense_ruins";
  };
  readonly d_relic_metal_boneyard: DepositRef & {
    readonly id: "d_relic_metal_boneyard";
  };
  readonly d_shattered_solar_array: DepositRef & {
    readonly id: "d_shattered_solar_array";
  };
};
