// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { DepositRef } from "@pdx-ts/sdk/stellaris";

export type VanillaDepositTrieGrandArchiveDeposits = {
  readonly d_abandoned_black_needle_base: DepositRef & {
    readonly id: "d_abandoned_black_needle_base";
  };
  readonly d_black_needle_base: DepositRef & {
    readonly id: "d_black_needle_base";
  };
  readonly d_hive_dwelling: DepositRef & {
    readonly id: "d_hive_dwelling";
  };
  readonly d_radioactive_ruins: DepositRef & {
    readonly id: "d_radioactive_ruins";
  };
  readonly d_ruined_hive_dwelling: DepositRef & {
    readonly id: "d_ruined_hive_dwelling";
  };
  readonly d_treasure_planet: DepositRef & {
    readonly id: "d_treasure_planet";
  };
};
