// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { DepositRef } from "@pdx-ts/sdk";

export type VanillaDepositTrieStartingDeposits = {
  readonly d_boswash_metropolitan_axis: DepositRef & {
    readonly id: "d_boswash_metropolitan_axis";
  };
  readonly d_delhi_sprawl: DepositRef & {
    readonly id: "d_delhi_sprawl";
  };
  readonly d_exotic_mountain: DepositRef & {
    readonly id: "d_exotic_mountain";
  };
  readonly d_failing_infrastructure_earth: DepositRef & {
    readonly id: "d_failing_infrastructure_earth";
  };
  readonly d_great_albertan_crater: DepositRef & {
    readonly id: "d_great_albertan_crater";
  };
  readonly d_great_pacific_garbage_patch: DepositRef & {
    readonly id: "d_great_pacific_garbage_patch";
  };
  readonly d_mauritanian_security_zone: DepositRef & {
    readonly id: "d_mauritanian_security_zone";
  };
  readonly d_mesopotamian_urban_corridor: DepositRef & {
    readonly id: "d_mesopotamian_urban_corridor";
  };
  readonly d_pacific_algae_tracts: DepositRef & {
    readonly id: "d_pacific_algae_tracts";
  };
  readonly d_pearl_river_agglomerate: DepositRef & {
    readonly id: "d_pearl_river_agglomerate";
  };
  readonly d_saharan_irrigation_project: DepositRef & {
    readonly id: "d_saharan_irrigation_project";
  };
  readonly d_scandinavian_reclamation_sector: DepositRef & {
    readonly id: "d_scandinavian_reclamation_sector";
  };
};
