/** Complex enums the deliberately small fake install has no selector-bearing file for. */
export const FAKE_INSTALL_UNMATCHED_COMPLEX_ENUMS = [
  "mission_counter",
  "starbase_module_category",
  "event_chain_counter",
  "model_animation",
  "model_state",
  "model_locator",
  "model_attachment",
  "particle_force",
  "intel_token",
  "job_tag",
  "name_list_category",
  "deed_counter",
  "calling_counter",
  "district_set",
  "policy_option",
  "policy_flag",
  "pop_faction_parameter",
  "pop_faction_action",
  "trait_tag",
  "light_animation",
  "scrollbar_type",
  "extended_scrollbar_type",
  "map_setup_scenario_system_id",
] as const;
