/**
 * The vanilla identifier generator, measured against a fixture install.
 *
 * Hermetic and always-run: the install-gated gate (regenerating against the
 * real 4.4.6 install and comparing to committed output) can only run next to a
 * copy of the game, so everything that can be proved without one is proved
 * here — the readers' three id layouts, parameter optionality, the trie's
 * shape, and determinism.
 *
 * The fixture lowers the trie threshold rather than shipping 2,000 fake
 * sprites: the threshold is an option precisely so the *logic* can be
 * exercised at ten ids instead of ten thousand.
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { formatEmitted } from "../src/format.ts";
import { generateVanillaPackage } from "../src/generate.ts";
import { bucketPath, fileBucketKey } from "../src/trie.ts";

/** The repo root, from this module — never the directory vitest was started in. */
const ROOT = fileURLToPath(new URL("../../../", import.meta.url));

const OPTIONS = {
  installRoot: path.join(ROOT, "fixtures/fake-install"),
  gameVersion: "4.4.6",
  configRoot: path.join(ROOT, "vendor/cwtools-stellaris-config/config"),
  docsRoot: path.join(ROOT, "vendor/cwtools-stellaris-config/script-docs/v4.4.1"),
  trieThreshold: 5,
};

const generated = generateVanillaPackage(OPTIONS);
const files = await formatEmitted(generated.files, path.join(ROOT, "packages/stellaris-ids/src"));

function file(name: string): string {
  const text = files.get(name);
  if (text === undefined) {
    throw new Error(`no emitted file ${name}; emitted ${[...files.keys()].join(", ")}`);
  }
  return text;
}

function registryReport(name: string) {
  const found = generated.report.registries.find((one) => one.registry === name);
  if (found === undefined) {
    throw new Error(`no report row for ${name}`);
  }
  return found;
}

describe("emitted file set", () => {
  it("emits one file per registry, plus the barrel and the augmentation", () => {
    expect(files.has("index.ts")).toBe(true);
    expect(files.has("augment.ts")).toBe(true);
    for (const row of generated.report.registries) {
      expect(files.has(`registries/${row.registry.replaceAll("_", "-")}.ts`)).toBe(true);
    }
    expect(files.has("scripted-triggers.ts")).toBe(true);
    expect(files.has("scripted-effects.ts")).toBe(true);
  });

  it("names every emitted registry in the augmentation", () => {
    const augment = file("augment.ts");
    for (const row of generated.report.registries) {
      expect(augment).toContain(`readonly ${row.registry}:`);
    }
    expect(augment).toContain(
      "interface VanillaScriptedTriggers extends VanillaScriptedTriggerParams {}"
    );
    expect(augment).toContain(
      "interface VanillaScriptedEffects extends VanillaScriptedEffectParams {}"
    );
  });

  it("re-exports every public type from the barrel with no runtime exports", () => {
    const barrel = file("index.ts");
    expect(barrel).toContain('import "./augment.ts";');
    expect(barrel).toContain(
      'export type { VanillaSpriteTrie } from "./registries/sprite/index.ts";'
    );
    expect(barrel).not.toMatch(/export (const|function|class|default)\b/);
  });

  it("carries the game version in every header", () => {
    for (const [name, text] of files) {
      expect(
        text.startsWith("// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6."),
        name
      ).toBe(true);
    }
  });
});

describe("registry readers", () => {
  it("reads id-keyed registries from the top-level keys", () => {
    expect(file("registries/technology.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export type VanillaTechnologyId = "tech_fake_farming" | "tech_gene_tailoring";
      "
    `);
  });

  it("does not descend a path_strict registry's subdirectories", () => {
    // `common/technology/category` holds `technology_category` definitions, a
    // different CWT type; the fixture puts `biology` there. Reading it as a
    // technology is exactly the silent over-approximation `path_strict = yes`
    // exists to prevent, and `stellaris.load()` skips the same two subdirs.
    expect(registryReport("technology").ids).toBe(2);
    expect(file("registries/technology.ts")).not.toContain("biology");
  });

  it("reads name_field registries from the keyword's body field", () => {
    expect(registryReport("ambient_object").ids).toBe(2);
    expect(file("registries/ambient-object.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export type VanillaAmbientObjectId = "fake_ambient_beacon" | "fake_ambient_relay";
      "
    `);
  });

  it("walks nested directories and honours the declared extension", () => {
    // Three `.asset` files, two of them directories down; `category` is a
    // different CWT type and contributes nothing.
    expect(registryReport("sound").files).toBe(3);
    expect(file("registries/sound.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export type VanillaSoundId =
        | "fake.dotted.alert"
        | "fake_alert_one"
        | "fake_alert_three"
        | "fake_alert_two"
        | "fake_deep_hum"
        | "fake_deep_pulse";
      "
    `);
    expect(file("registries/sound-effect.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export type VanillaSoundEffectId =
        | "fake.dotted.effect"
        | "fake_effect_alpha"
        | "fake_effect_beta"
        | "fake_effect_deep_one"
        | "fake_effect_deep_two"
        | "fake_effect_gamma";
      "
    `);
  });

  it("descends skip_root_key registries by the presence of the name field", () => {
    // Six of the ten sprites are written under a subtype keyword other than
    // `spriteType`; matching on keywords would have dropped them.
    expect(registryReport("sprite").ids).toBe(10);
    expect(file("registries/sprite.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export type VanillaSpriteId =
        | "GFX_icon_alert"
        | "GFX_icon_warning"
        | "GFX_odd.name"
        | "GFX_planet_barren"
        | "GFX_planet_ocean"
        | "GFX_planet_toxic"
        | "GFX_ship"
        | "GFX_ship_combat"
        | "GFX_ship_combat_1"
        | "GFX_ship_combat_2";
      "
    `);
  });

  it("reports a registry the install does not have rather than failing", () => {
    const missing = registryReport("building");
    expect(missing).toMatchObject({ ids: 0, files: 0, missing: true });
    expect(file("registries/building.ts")).toContain("= never;");
  });
});

describe("scripted parameters", () => {
  it("makes defaulted and conditional parameters optional and the rest required", () => {
    expect(file("scripted-triggers.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export interface VanillaScriptedTriggerParams {
        readonly fake_conditional: {
          readonly FLAG?: string | number;
          readonly NAME?: string | number;
        };
        readonly fake_defaulted: {
          readonly YEARS: string | number;
        };
        readonly fake_no_params: {};
        readonly fake_required: {
          readonly TECH: string | number;
        };
      }
      "
    `);
  });

  it("unions a redefined trigger's parameters, required winning over optional", () => {
    // `$YEARS|10$` in the first file, bare `$YEARS$` in the second: a caller
    // who passes it satisfies whichever body the game loads.
    expect(file("scripted-triggers.ts")).toContain("readonly YEARS: string | number;");
  });

  it("reads effects the same way", () => {
    expect(file("scripted-effects.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      export interface VanillaScriptedEffectParams {
        readonly fake_effect_params: {
          readonly AMOUNT: string | number;
          readonly REASON?: string | number;
        };
        readonly fake_effect_simple: {};
      }
      "
    `);
  });

  it("counts definitions and parameterized definitions", () => {
    expect(generated.report.scripted).toMatchObject([
      { registry: "scripted_trigger", definitions: 4, parameterized: 3, files: 2 },
      { registry: "scripted_effect", definitions: 2, parameterized: 1, files: 1 },
    ]);
  });
});

describe("bucket paths", () => {
  it("takes the whole directory path plus the stem for a directory layout", () => {
    // Real 4.4.6 layout: `sound/toxoids/ships/tox_ships_moves.asset`.
    expect(bucketPath("toxoids/ships/tox_ships_moves.asset", "directory", "sound")).toEqual([
      "toxoids",
      "ships",
      "tox_ships_moves",
    ]);
    expect(bucketPath("soundeffects.asset", "directory", "sound")).toEqual(["soundeffects"]);
  });

  it("takes the stem verbatim for a file layout, stripping nothing", () => {
    // `interface/interface.gfx` is a real file, and the token rule would
    // strip it to nothing and lose the bucket. `interface/` carries no
    // load-order numbers either, so there is nothing to strip.
    expect(bucketPath("eventpictures.gfx", "file", "interface")).toEqual(["eventpictures"]);
    expect(bucketPath("interface.gfx", "file", "interface")).toEqual(["interface"]);
    expect(bucketPath("common/buttons.gfx", "file", "interface")).toEqual(["buttons"]);
  });

  it("puts a stripped-file stem that strips to nothing at the root", () => {
    expect(bucketPath("00_static_modifiers.txt", "stripped-file", "static_modifiers")).toEqual([]);
    expect(
      bucketPath("09_static_modifiers_deficit.txt", "stripped-file", "static_modifiers")
    ).toEqual(["deficit"]);
  });
});

describe("file bucket keys", () => {
  it("strips the load-order number and the registry's own token", () => {
    // Every name below is a real 4.4.6 filename under
    // `common/static_modifiers/`.
    expect(fileBucketKey("09_static_modifiers_deficit", "static_modifiers")).toBe("deficit");
    expect(fileBucketKey("14_static_modifiers_clone_army_origin", "static_modifiers")).toBe(
      "clone_army_origin"
    );
  });

  it("merges files that differ only in load order", () => {
    expect(fileBucketKey("16_static_modifiers_paragon", "static_modifiers")).toBe(
      fileBucketKey("19_static_modifiers_paragon", "static_modifiers")
    );
  });

  it("gives a token-only stem no bucket at all", () => {
    expect(fileBucketKey("00_static_modifiers", "static_modifiers")).toBe("");
  });

  it("keeps the whole stripped stem when the token is absent", () => {
    expect(fileBucketKey("000_readme", "static_modifiers")).toBe("readme");
  });
});

describe("trie", () => {
  it("buckets a registry by its vanilla source files, ids at the root when a file names no subject", () => {
    // The fixture's `common/static_modifiers/` mirrors vanilla's own layout:
    // `00_static_modifiers.txt` and `01_static_modifiers.txt` strip to nothing
    // and put their ids at the root; `09_static_modifiers_deficit.txt` names a
    // bucket; `16_` and `19_static_modifiers_paragon.txt` name the *same*
    // bucket and merge, because load order is not a category; `000_readme.txt`
    // defines nothing and so contributes no bucket despite not carrying the
    // registry token at all.
    expect(registryReport("static_modifier").trie).toMatchObject({
      buckets: 5,
      rootLeaves: 3,
      flatOnly: 0,
    });
    expect(file("registries/static-modifier/index.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      import type { StaticModifierRef } from "@pdx-ts/sdk";

      import type { VanillaStaticModifierTrieDeficit } from "./deficit.ts";
      import type { VanillaStaticModifierTrieParagon } from "./paragon.ts";

      export interface VanillaStaticModifierTrie {
        readonly deficit: VanillaStaticModifierTrieDeficit;
        readonly fake_empire_base: StaticModifierRef & {
          readonly id: "fake_empire_base";
        };
        readonly fake_orbital_base: StaticModifierRef & {
          readonly id: "fake_orbital_base";
        };
        readonly fake_planet_base: StaticModifierRef & {
          readonly id: "fake_planet_base";
        };
        readonly paragon: VanillaStaticModifierTrieParagon;
      }
      "
    `);
  });

  it("spells every leaf with the whole id, never a path join", () => {
    // The load-bearing property of the whole trie: `paragon` is a filename and
    // no part of any id, so `.id` is the leaf key alone.
    expect(file("registries/static-modifier/paragon.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      import type { StaticModifierRef } from "@pdx-ts/sdk";

      export type VanillaStaticModifierTrieParagon = {
        readonly fake_crisis_studied: StaticModifierRef & {
          readonly id: "fake_crisis_studied";
        };
        readonly fake_legend_inspired: StaticModifierRef & {
          readonly id: "fake_legend_inspired";
        };
      };
      "
    `);
  });

  it("buckets sprites by their .gfx file and never splits an id inside one", () => {
    // `GFX_ship` and `GFX_ship_combat_1` are neighbours in one bucket, not a
    // node and its descendant: a `.gfx` file is the category, and the shared
    // `GFX_ship` prefix is not.
    expect(registryReport("sprite").trie).toMatchObject({
      buckets: 2,
      rootLeaves: 0,
      flatOnly: 0,
    });
    expect(file("registries/sprite/fake-sprites.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      import type { SpriteRef } from "@pdx-ts/sdk";

      export type VanillaSpriteTrieFakeSprites = {
        readonly GFX_planet_barren: SpriteRef & {
          readonly id: "GFX_planet_barren";
        };
        readonly GFX_planet_ocean: SpriteRef & {
          readonly id: "GFX_planet_ocean";
        };
        readonly GFX_ship: SpriteRef & {
          readonly id: "GFX_ship";
        };
        readonly GFX_ship_combat: SpriteRef & {
          readonly id: "GFX_ship_combat";
        };
        readonly GFX_ship_combat_1: SpriteRef & {
          readonly id: "GFX_ship_combat_1";
        };
        readonly GFX_ship_combat_2: SpriteRef & {
          readonly id: "GFX_ship_combat_2";
        };
      };
      "
    `);
  });

  it("keeps an id a property path could not spell, as a quoted verbatim key", () => {
    // `GFX_odd.name` used to be routed to the flat union only, because a dot
    // cannot be a segment of a joined path. A verbatim leaf key has no such
    // limit, so nothing is flat-only any more.
    expect(file("registries/sprite.ts")).toContain('"GFX_odd.name"');
    expect(file("registries/sprite/fake-more.ts")).toContain(
      'readonly "GFX_odd.name": SpriteRef & {'
    );
  });

  it("nests a directory-layout registry one segment per directory level", () => {
    // `sound/nested/deeper/fake_deep.asset` is two directories and a stem, and
    // all three are navigation.
    expect(registryReport("sound").trie).toMatchObject({
      buckets: 2,
      rootLeaves: 0,
      flatOnly: 0,
    });
    expect(file("registries/sound/nested.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      import type { SoundRef } from "@pdx-ts/sdk";

      export type VanillaSoundTrieNested = {
        readonly deeper: {
          readonly fake_deep: {
            readonly fake_deep_hum: SoundRef & {
              readonly id: "fake_deep_hum";
            };
            readonly fake_deep_pulse: SoundRef & {
              readonly id: "fake_deep_pulse";
            };
          };
        };
        readonly fake_more: {
          readonly "fake.dotted.alert": SoundRef & {
            readonly id: "fake.dotted.alert";
          };
          readonly fake_alert_two: SoundRef & {
            readonly id: "fake_alert_two";
          };
        };
      };
      "
    `);
    expect(file("registries/sound/index.ts")).toMatchInlineSnapshot(`
      "// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

      import type { VanillaSoundTrieFakeSounds } from "./fake-sounds.ts";
      import type { VanillaSoundTrieNested } from "./nested.ts";

      export interface VanillaSoundTrie {
        readonly fake_sounds: VanillaSoundTrieFakeSounds;
        readonly nested: VanillaSoundTrieNested;
      }
      "
    `);
  });

  it("emits one file per top-level bucket and nothing else", () => {
    // The whole trie directory, so a change of file scheme — the first-character
    // partition this replaced, or a deeper split — has to be stated here. The
    // shell removes every emitted-set orphan, so this is also what keeps stale
    // files from surviving a regeneration.
    expect([...files.keys()].filter((name) => name.includes("/sprite/")).sort()).toEqual([
      "registries/sprite/fake-more.ts",
      "registries/sprite/fake-sprites.ts",
      "registries/sprite/index.ts",
    ]);
    expect([...files.keys()].filter((name) => name.includes("/sound-effect/")).sort()).toEqual([
      "registries/sound-effect/fake-sounds.ts",
      "registries/sound-effect/index.ts",
      "registries/sound-effect/nested.ts",
    ]);
  });

  it("leaves registries under the threshold flat", () => {
    expect(registryReport("technology").trie).toBeNull();
    expect(files.has("registries/technology/index.ts")).toBe(false);
  });
});

describe("determinism", () => {
  it("emits byte-identical output on a second run", () => {
    const again = generateVanillaPackage(OPTIONS);
    expect([...again.files.keys()]).toEqual([...generated.files.keys()]);
    for (const [name, text] of again.files) {
      expect(text, name).toBe(generated.files.get(name));
    }
    expect(again.report).toEqual(generated.report);
  });
});

describe("report", () => {
  it("counts what it read and what the licensing gate saw", () => {
    expect(generated.report.rejections).toBe(0);
    expect(generated.report.identifiersChecked).toBeGreaterThan(50);
    expect(generated.report.diagnostics).toBe(0);
    expect(generated.report.emittedFiles).toBe(generated.files.size);
  });
});
