// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

export type VanillaCountryShipOfSizeLimitId =
  | "colossus_ships_limit"
  | "juggernaut_ships_limit"
  | "nomadic_constructor_limit"
  | "paladin_ship_limit"
  | "progenitor_ships_limit"
  | "space_dragon_origin_babies_limit"
  | "titan_ships_limit";
