// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

/** Identifiers defined in Stellaris 4.4.6 for the `situation_log_category` registry. */
export type VanillaSituationLogCategoryId =
  | "ambitions"
  | "anomalies"
  | "astral_rifts"
  | "contracts"
  | "crises"
  | "developments"
  | "dig_sites"
  | "empire_concerns"
  | "first_contacts"
  | "other_findings"
  | "others"
  | "precursors"
  | "priority"
  | "tutorial"
  | "urgent_matters";
