/**
 * Emitted TypeScript, and the one gate every identifier passes to get there.
 *
 * {@link assertVanillaIdentifier} is the licensing chokepoint. The package is
 * allowed to carry the *names* Paradox's files define and nothing else — no
 * script bodies, no localized text, no descriptions, no asset data — and the
 * only way to keep that true as the generator grows is to make it impossible to
 * write a string into an emitted file without passing it here first. Every
 * quoted literal in every emitter goes through {@link Chokepoint.literal},
 * which asserts and then quotes.
 *
 * The rejections are shaped after what a leak would actually look like: a
 * localisation sentence, a line of script, a fragment of a body. A name has no
 * braces, no `=`, no `$`, no quotes, no newlines, at most a couple of spaces,
 * and is short.
 */

import { pascalCase } from "../codegen/naming.ts";
import type { ScriptedDefinition } from "./read-scripted.ts";
import type { TrieNode } from "./trie.ts";

/**
 * Longest a real identifier gets; anything longer reads as prose.
 *
 * Measured, not guessed: across the whole 4.4.6 install the longest identifier
 * any of these registries defines is 84 characters
 * (`GFX_species_selected_background_trait_machine_pc_shattered_ring_habitable_preference`),
 * so a bound of 80 rejects real vanilla names. This is a backstop for "a whole
 * body slipped through" rather than the load-bearing rule — the forbidden
 * characters and the space limit are what actually separate a name from a
 * sentence — so it sits above the observed maximum with room for a patch to add
 * a longer one.
 */
const MAX_LENGTH = 120;

/** Characters no identifier contains, each of which script and prose do. */
const FORBIDDEN = ["\n", "\r", "\t", "{", "}", "=", '"', "$", "#"];

/** `has_country_flag = x`, `count < 3` — an assignment or comparison, not a name. */
const SCRIPT_SHAPE = /\w+\s*(=|<|>)/;

/**
 * Passes an identifier through, or throws naming what it was and where it came
 * from. Never returns a "safe" substitute: a silently repaired name would be a
 * wrong id emitted as a right-looking one.
 */
export function assertVanillaIdentifier(candidate: string, context: string): string {
  const reject = (reason: string): never => {
    throw new Error(
      `${context}: refusing to emit ${JSON.stringify(candidate.slice(0, 120))} — ${reason}. ` +
        "The vanilla package carries identifiers only; this looks like game content."
    );
  };
  if (candidate === "") {
    reject("empty");
  }
  if (candidate.length > MAX_LENGTH) {
    reject(`${candidate.length} characters, over the ${MAX_LENGTH} an identifier takes`);
  }
  for (const character of FORBIDDEN) {
    if (candidate.includes(character)) {
      reject(`contains ${JSON.stringify(character)}`);
    }
  }
  if ((candidate.match(/ /g) ?? []).length > 2) {
    reject("more spaces than a name has");
  }
  if (SCRIPT_SHAPE.test(candidate)) {
    reject("reads as a script assignment or comparison");
  }
  return candidate;
}

/**
 * Byte order, not locale order. Emission has to be reproducible on every
 * machine, and `localeCompare` is not: it treats `_` and case differently
 * depending on the environment's collation.
 */
export function compareIdentifiers(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Counts what the gate has seen, so the report can show it ran. */
export interface Chokepoint {
  /** Asserts, then quotes. The only way a string reaches emitted text. */
  literal(candidate: string, context: string): string;
  readonly checked: () => number;
}

export function createChokepoint(): Chokepoint {
  let seen = 0;
  return {
    literal(candidate, context) {
      seen += 1;
      return JSON.stringify(assertVanillaIdentifier(candidate, context));
    },
    checked: () => seen,
  };
}

export function header(gameVersion: string): string {
  return `// Generated by tools/vanilla-codegen from Stellaris ${gameVersion}. Do not edit.\n\n`;
}

/** `ascension_perk` -> `ascension-perk`, matching the repo's generated files. */
export function kebabCase(name: string): string {
  return name.replaceAll("_", "-");
}

export function idTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Id`;
}

export function trieTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Trie`;
}

export function scriptedTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Params`;
}

/** `sprite` -> `SpriteRef`, the SDK's branded reference for that registry. */
export function refTypeName(registry: string): string {
  return `${pascalCase(registry)}Ref`;
}

export function registryFile(registry: string): string {
  return `registries/${kebabCase(registry)}.ts`;
}

export function trieIndexFile(registry: string): string {
  return `registries/${kebabCase(registry)}/index.ts`;
}

/**
 * The plural file the scripted parameter table lands in — `scripted_trigger`
 * defines many scripted triggers, and the interface is the whole table.
 */
export function scriptedFile(registry: string): string {
  return `${kebabCase(registry)}s.ts`;
}

export function emitIdUnion(
  registry: string,
  ids: readonly string[],
  gate: Chokepoint,
  gameVersion: string
): string {
  const context = `${registry} id`;
  const union = ids.length === 0 ? "never" : ids.map((id) => gate.literal(id, context)).join(" | ");
  return `${header(gameVersion)}export type ${idTypeName(registry)} = ${union};\n`;
}

export interface TrieEmission {
  /** Emitted path -> file text, the bucket files and the registry's index. */
  readonly files: ReadonlyMap<string, string>;
  /** Every exported type name, so the barrel can re-export them. */
  readonly exports: readonly { readonly name: string; readonly file: string }[];
}

/**
 * Which file a top-level bucket's type lands in: its key's first character.
 *
 * "One file per bucket" was the plan, and the real install argues against it in
 * both directions — 3,081 static modifiers share only their first *word*, so
 * they produce 1,028 buckets and would produce 1,028 two-line files, while
 * sprites produce nine buckets of which one holds 9,171 ids. Grouping by first
 * character keeps the count bounded at both ends and, unlike packing by size,
 * is *stable*: a bucket stays in its file as the game gains and loses ids, so a
 * regeneration diff still reads as a local change.
 */
function bucketStem(key: string): string {
  const first = key[0] ?? "_";
  return /[A-Za-z0-9]/.test(first) ? first.toLowerCase() : "_";
}

export function emitTrie(
  registry: string,
  buckets: ReadonlyMap<string, TrieNode>,
  budget: number,
  gate: Chokepoint,
  gameVersion: string
): TrieEmission {
  const context = `${registry} trie key`;
  const reference = refTypeName(registry);
  const root = trieTypeName(registry);
  const taken = new Set<string>([root]);
  const chunks: TrieChunk[] = [];

  /**
   * Lifts a node out into its own exported type. Applied to every top-level
   * bucket, and then again to the children of any node whose subtree is larger
   * than one file should carry — which is what keeps a registry where one
   * bucket holds 9,171 of 9,197 ids from emitting a single megabyte file that
   * rewrites itself on every game patch.
   */
  const extract = (key: string, node: TrieNode, path: string): string => {
    const name = unique(`${root}${pascalCase(path)}`, taken, "");
    const deps: string[] = [];
    const body = render(node, path, deps);
    chunks.push({ name, stem: bucketStem(key), body, deps });
    return name;
  };

  /**
   * One node as a type.
   *
   * A node is a leaf, a branch, or both — an id that is also the prefix of
   * longer ids. The intersection is what makes the third case navigable *and*
   * usable: `.id` reads the complete id, and the remaining keys keep descending.
   */
  const render = (node: TrieNode, path: string, deps: string[]): string => {
    const members: string[] = [];
    if (node.id !== null) {
      members.push(`readonly id: ${gate.literal(node.id, `${context} leaf`)};`);
    }
    const split = node.children.size > 1 && leafCount(node) > budget;
    for (const [key, child] of node.children) {
      let type: string;
      if (split) {
        type = extract(key, child, `${path}_${key}`);
        deps.push(type);
      } else {
        type = render(child, `${path}_${key}`, deps);
      }
      members.push(`readonly ${gate.literal(key, context)}: ${type};`);
    }
    const body = `{\n${members.join("\n")}\n}`;
    return node.id === null ? body : `${reference} & ${body}`;
  };

  const rootDeps: string[] = [];
  const rootMembers: string[] = [];
  for (const [key, node] of buckets) {
    const name = extract(key, node, key);
    rootDeps.push(name);
    rootMembers.push(`readonly ${gate.literal(key, context)}: ${name};`);
  }

  const dir = `registries/${kebabCase(registry)}`;
  const stemOf = new Map(chunks.map((chunk) => [chunk.name, chunk.stem]));
  const byStem = new Map<string, TrieChunk[]>();
  for (const chunk of chunks) {
    byStem.set(chunk.stem, [...(byStem.get(chunk.stem) ?? []), chunk]);
  }

  const files = new Map<string, string>();
  for (const [stem, members] of sorted(byStem)) {
    const defined = new Set(members.map((chunk) => chunk.name));
    const body = members.map((chunk) => `export type ${chunk.name} = ${chunk.body};\n`).join("\n");
    const external = members.flatMap((chunk) => chunk.deps).filter((name) => !defined.has(name));
    files.set(
      `${dir}/${stem}.ts`,
      header(gameVersion) +
        (body.includes(reference) ? `import type { ${reference} } from "@pdx-ts/sdk";\n` : "") +
        importsFrom(external, stemOf, "./") +
        "\n" +
        body
    );
  }
  files.set(
    trieIndexFile(registry),
    header(gameVersion) +
      importsFrom(rootDeps, stemOf, "./") +
      `\nexport interface ${root} {\n${rootMembers.join("\n")}\n}\n`
  );
  // Only the root is public API. The per-node types are structural
  // intermediates the root already reaches; re-exporting a thousand of them
  // from the barrel would make the package's surface the trie's shape.
  return { files, exports: [{ name: root, file: trieIndexFile(registry) }] };
}

interface TrieChunk {
  readonly name: string;
  /** File stem the type lands in. */
  readonly stem: string;
  readonly body: string;
  /** Other chunk types the body references. */
  readonly deps: readonly string[];
}

function leafCount(node: TrieNode): number {
  let total = node.id === null ? 0 : 1;
  for (const child of node.children.values()) {
    total += leafCount(child);
  }
  return total;
}

function sorted<T>(map: ReadonlyMap<string, T>): [string, T][] {
  return [...map].sort(([left], [right]) => compareIdentifiers(left, right));
}

function importsFrom(
  names: readonly string[],
  stemOf: ReadonlyMap<string, string>,
  prefix: string
): string {
  const byStem = new Map<string, Set<string>>();
  for (const name of [...new Set(names)].sort(compareIdentifiers)) {
    const stem = stemOf.get(name)!;
    byStem.set(stem, (byStem.get(stem) ?? new Set()).add(name));
  }
  return sorted(byStem)
    .map(([stem, used]) => `import type { ${[...used].join(", ")} } from "${prefix}${stem}.ts";\n`)
    .join("");
}

export function emitScriptedParams(
  registry: string,
  definitions: readonly ScriptedDefinition[],
  gate: Chokepoint,
  gameVersion: string
): string {
  const members = definitions.map((definition) => {
    const name = gate.literal(definition.name, `${registry} name`);
    const params = definition.params.map((param) => {
      const key = gate.literal(param.name, `${registry} ${definition.name} parameter`);
      return `readonly ${key}${param.optional ? "?" : ""}: string | number;`;
    });
    const shape = params.length === 0 ? "{}" : `{\n${params.join("\n")}\n}`;
    return `readonly ${name}: ${shape};`;
  });
  return (
    `${header(gameVersion)}export interface ${scriptedTypeName(registry)} {\n` +
    `${members.join("\n")}\n}\n`
  );
}

export interface AugmentPlan {
  /** Registry name -> its id union type and the file it lives in. */
  readonly ids: readonly { readonly registry: string; readonly file: string }[];
  /** Registry name -> its trie root type and file, for oversized registries. */
  readonly tries: readonly { readonly registry: string; readonly file: string }[];
  /** SDK merge target -> the emitted params interface, e.g. scripted triggers. */
  readonly scripted: readonly {
    readonly target: string;
    readonly registry: string;
    readonly file: string;
  }[];
}

/**
 * The single augmentation module.
 *
 * It is a `.ts` file with real imports on purpose: a file whose only statement
 * is `declare module` is a *script*, and a script's `declare module` declares a
 * new ambient module that shadows the SDK rather than merging into it. The
 * imports are what make this a module, and therefore an augmentation.
 */
export function emitAugment(plan: AugmentPlan, gate: Chokepoint, gameVersion: string): string {
  const imports = [
    ...plan.ids.map(({ registry, file }) => ({ name: idTypeName(registry), file })),
    ...plan.tries.map(({ registry, file }) => ({ name: trieTypeName(registry), file })),
    ...plan.scripted.map(({ registry, file }) => ({ name: scriptedTypeName(registry), file })),
  ]
    .map(({ name, file }) => `import type { ${name} } from "./${file}";\n`)
    .join("");

  const idMembers = plan.ids
    .map(
      ({ registry }) =>
        `readonly ${gate.literal(registry, "registry name")}: ${idTypeName(registry)};`
    )
    .join("\n");
  const trieMembers = plan.tries
    .map(
      ({ registry }) =>
        `readonly ${gate.literal(registry, "registry name")}: ${trieTypeName(registry)};`
    )
    .join("\n");
  const scriptedMembers = plan.scripted
    .map(({ target, registry }) => `interface ${target} extends ${scriptedTypeName(registry)} {}`)
    .join("\n");

  return (
    header(gameVersion) +
    imports +
    '\ndeclare module "@pdx-ts/sdk" {\n' +
    `interface VanillaIds {\n${idMembers}\n}\n` +
    (scriptedMembers === "" ? "" : `${scriptedMembers}\n`) +
    (plan.tries.length === 0 ? "" : `interface VanillaTries {\n${trieMembers}\n}\n`) +
    "}\n"
  );
}

/**
 * The barrel. The side-effect import of `./augment.ts` is the activation
 * guarantee — a type-only re-export would be erased in a build that never reads
 * the types, and the augmentation would silently not apply. Nothing else here
 * is a runtime export: the package is types and a version number.
 */
export function emitIndex(
  exports: readonly { readonly name: string; readonly file: string }[],
  gameVersion: string
): string {
  const lines = [...exports]
    .sort((left, right) => compareIdentifiers(left.name, right.name))
    .map(({ name, file }) => `export type { ${name} } from "./${file}";\n`)
    .join("");
  return `${header(gameVersion)}import "./augment.ts";\n\n${lines}`;
}

/**
 * Two bucket keys can mangle onto one name — `GFX_ship` and `gfx-ship` share a
 * file stem on a case-insensitive filesystem. Buckets are walked in sorted
 * order, so the numbering is deterministic rather than machine-dependent.
 */
function unique(candidate: string, taken: Set<string>, separator: string): string {
  let name = candidate;
  let suffix = 2;
  while (taken.has(name)) {
    name = `${candidate}${separator}${suffix}`;
    suffix += 1;
  }
  taken.add(name);
  return name;
}
