// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieDiplomacyVotingView = {
  readonly GFX_alliance_vote_status: SpriteRef & {
    readonly id: "GFX_alliance_vote_status";
  };
};
