// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieFleetView = {
  readonly GFX_arkship_fleetview_civilian: SpriteRef & {
    readonly id: "GFX_arkship_fleetview_civilian";
  };
  readonly GFX_arkship_fleetview_military: SpriteRef & {
    readonly id: "GFX_arkship_fleetview_military";
  };
  readonly GFX_arkship_fleetview_science: SpriteRef & {
    readonly id: "GFX_arkship_fleetview_science";
  };
  readonly GFX_armada_command_button_force: SpriteRef & {
    readonly id: "GFX_armada_command_button_force";
  };
  readonly GFX_armada_command_button_none: SpriteRef & {
    readonly id: "GFX_armada_command_button_none";
  };
  readonly GFX_armada_command_button_queue: SpriteRef & {
    readonly id: "GFX_armada_command_button_queue";
  };
  readonly GFX_building_icon: SpriteRef & {
    readonly id: "GFX_building_icon";
  };
  readonly GFX_button_back: SpriteRef & {
    readonly id: "GFX_button_back";
  };
  readonly GFX_button_down: SpriteRef & {
    readonly id: "GFX_button_down";
  };
  readonly GFX_button_pdx: SpriteRef & {
    readonly id: "GFX_button_pdx";
  };
  readonly GFX_button_up: SpriteRef & {
    readonly id: "GFX_button_up";
  };
  readonly GFX_button_update: SpriteRef & {
    readonly id: "GFX_button_update";
  };
  readonly GFX_cloaking_detection_icon: SpriteRef & {
    readonly id: "GFX_cloaking_detection_icon";
  };
  readonly GFX_cloaking_level_0: SpriteRef & {
    readonly id: "GFX_cloaking_level_0";
  };
  readonly GFX_cloaking_level_1: SpriteRef & {
    readonly id: "GFX_cloaking_level_1";
  };
  readonly GFX_cloaking_level_10: SpriteRef & {
    readonly id: "GFX_cloaking_level_10";
  };
  readonly GFX_cloaking_level_2: SpriteRef & {
    readonly id: "GFX_cloaking_level_2";
  };
  readonly GFX_cloaking_level_3: SpriteRef & {
    readonly id: "GFX_cloaking_level_3";
  };
  readonly GFX_cloaking_level_4: SpriteRef & {
    readonly id: "GFX_cloaking_level_4";
  };
  readonly GFX_cloaking_level_5: SpriteRef & {
    readonly id: "GFX_cloaking_level_5";
  };
  readonly GFX_cloaking_level_6: SpriteRef & {
    readonly id: "GFX_cloaking_level_6";
  };
  readonly GFX_cloaking_level_7: SpriteRef & {
    readonly id: "GFX_cloaking_level_7";
  };
  readonly GFX_cloaking_level_8: SpriteRef & {
    readonly id: "GFX_cloaking_level_8";
  };
  readonly GFX_cloaking_level_9: SpriteRef & {
    readonly id: "GFX_cloaking_level_9";
  };
  readonly GFX_cloaking_level_unknown: SpriteRef & {
    readonly id: "GFX_cloaking_level_unknown";
  };
  readonly GFX_cloaking_strength_icon: SpriteRef & {
    readonly id: "GFX_cloaking_strength_icon";
  };
  readonly GFX_delete_template_button: SpriteRef & {
    readonly id: "GFX_delete_template_button";
  };
  readonly GFX_dismantle_megastructure: SpriteRef & {
    readonly id: "GFX_dismantle_megastructure";
  };
  readonly GFX_dropdown_indicator: SpriteRef & {
    readonly id: "GFX_dropdown_indicator";
  };
  readonly GFX_federation_fleet_view_main_military_bg: SpriteRef & {
    readonly id: "GFX_federation_fleet_view_main_military_bg";
  };
  readonly GFX_federation_fleet_view_top_panel_bg: SpriteRef & {
    readonly id: "GFX_federation_fleet_view_top_panel_bg";
  };
  readonly GFX_federation_ship_entry_bg: SpriteRef & {
    readonly id: "GFX_federation_ship_entry_bg";
  };
  readonly GFX_fleet_action_button_active_reconnaissance: SpriteRef & {
    readonly id: "GFX_fleet_action_button_active_reconnaissance";
  };
  readonly GFX_fleet_action_button_active_reconnaissance_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_active_reconnaissance_selected";
  };
  readonly GFX_fleet_action_button_arkship_deep_scan: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_deep_scan";
  };
  readonly GFX_fleet_action_button_arkship_empty_spine: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_empty_spine";
  };
  readonly GFX_fleet_action_button_arkship_exodus_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_exodus_jump";
  };
  readonly GFX_fleet_action_button_arkship_harvest_resources: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_harvest_resources";
  };
  readonly GFX_fleet_action_button_arkship_reprocess_planet: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_reprocess_planet";
  };
  readonly GFX_fleet_action_button_arkship_stellar_ignition: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_stellar_ignition";
  };
  readonly GFX_fleet_action_button_arkship_strip_mine: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_strip_mine";
  };
  readonly GFX_fleet_action_button_arkship_subspace_image: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_subspace_image";
  };
  readonly GFX_fleet_action_button_assist_detection: SpriteRef & {
    readonly id: "GFX_fleet_action_button_assist_detection";
  };
  readonly GFX_fleet_action_button_assist_detection_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_assist_detection_selected";
  };
  readonly GFX_fleet_action_button_astral_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_astral_jump";
  };
  readonly GFX_fleet_action_button_astral_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_astral_jump_selected";
  };
  readonly GFX_fleet_action_button_behemoth_blink: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_blink";
  };
  readonly GFX_fleet_action_button_behemoth_buff: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_buff";
  };
  readonly GFX_fleet_action_button_behemoth_cloak: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_cloak";
  };
  readonly GFX_fleet_action_button_behemoth_damage: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_damage";
  };
  readonly GFX_fleet_action_button_behemoth_egg: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_egg";
  };
  readonly GFX_fleet_action_button_behemoth_rage: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_rage";
  };
  readonly GFX_fleet_action_button_behemoth_speed: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_speed";
  };
  readonly GFX_fleet_action_button_behemoth_superweapon: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_superweapon";
  };
  readonly GFX_fleet_action_button_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_jump";
  };
  readonly GFX_fleet_action_button_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_jump_selected";
  };
  readonly GFX_fleet_action_button_logistic_harvest_resources: SpriteRef & {
    readonly id: "GFX_fleet_action_button_logistic_harvest_resources";
  };
  readonly GFX_fleet_action_button_move_capital: SpriteRef & {
    readonly id: "GFX_fleet_action_button_move_capital";
  };
  readonly GFX_fleet_action_button_move_capital_solid: SpriteRef & {
    readonly id: "GFX_fleet_action_button_move_capital_solid";
  };
  readonly GFX_fleet_action_button_new: SpriteRef & {
    readonly id: "GFX_fleet_action_button_new";
  };
  readonly GFX_fleet_action_button_new_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_new_large";
  };
  readonly GFX_fleet_action_button_paladin_air_superiority: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_air_superiority";
  };
  readonly GFX_fleet_action_button_paladin_field_repairs: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_field_repairs";
  };
  readonly GFX_fleet_action_button_paladin_field_testing: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_field_testing";
  };
  readonly GFX_fleet_action_button_paladin_for_the_order: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_for_the_order";
  };
  readonly GFX_fleet_action_button_paladin_harmony: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_harmony";
  };
  readonly GFX_fleet_action_button_paladin_hold_the_line: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_hold_the_line";
  };
  readonly GFX_fleet_action_button_paladin_on_my_command: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_on_my_command";
  };
  readonly GFX_fleet_action_button_paladin_plan_b: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_plan_b";
  };
  readonly GFX_fleet_action_button_paladin_recall: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_recall";
  };
  readonly GFX_fleet_action_button_paladin_sudden_strike: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_sudden_strike";
  };
  readonly GFX_fleet_action_button_paladin_super_shield: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_super_shield";
  };
  readonly GFX_fleet_action_button_paladin_taunt: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_taunt";
  };
  readonly GFX_fleet_action_button_paladin_thunderclap: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_thunderclap";
  };
  readonly GFX_fleet_action_button_patrol: SpriteRef & {
    readonly id: "GFX_fleet_action_button_patrol";
  };
  readonly GFX_fleet_action_button_patrol_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_patrol_selected";
  };
  readonly GFX_fleet_action_button_phase_fleet: SpriteRef & {
    readonly id: "GFX_fleet_action_button_phase_fleet";
  };
  readonly GFX_fleet_action_button_phase_fleet_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_phase_fleet_selected";
  };
  readonly GFX_fleet_action_button_quantum_catapult: SpriteRef & {
    readonly id: "GFX_fleet_action_button_quantum_catapult";
  };
  readonly GFX_fleet_action_button_quantum_catapult_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_quantum_catapult_selected";
  };
  readonly GFX_fleet_action_button_reinforce: SpriteRef & {
    readonly id: "GFX_fleet_action_button_reinforce";
  };
  readonly GFX_fleet_action_button_repair: SpriteRef & {
    readonly id: "GFX_fleet_action_button_repair";
  };
  readonly GFX_fleet_action_button_repair_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_repair_large";
  };
  readonly GFX_fleet_action_button_split: SpriteRef & {
    readonly id: "GFX_fleet_action_button_split";
  };
  readonly GFX_fleet_action_button_split_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_split_large";
  };
  readonly GFX_fleet_action_button_toggle_cloak: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak";
  };
  readonly GFX_fleet_action_button_toggle_cloak_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_large";
  };
  readonly GFX_fleet_action_button_toggle_cloak_off: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off";
  };
  readonly GFX_fleet_action_button_toggle_cloak_off_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off_large";
  };
  readonly GFX_fleet_action_button_toggle_cloak_off_waystation: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off_waystation";
  };
  readonly GFX_fleet_action_button_toggle_cloak_waystation: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_waystation";
  };
  readonly GFX_fleet_action_button_turn_into_merc: SpriteRef & {
    readonly id: "GFX_fleet_action_button_turn_into_merc";
  };
  readonly GFX_fleet_action_button_upgrade: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade";
  };
  readonly GFX_fleet_action_button_upgrade_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_large";
  };
  readonly GFX_fleet_action_button_upgrade_station: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_station";
  };
  readonly GFX_fleet_action_button_upgrade_station_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_station_large";
  };
  readonly GFX_fleet_disband: SpriteRef & {
    readonly id: "GFX_fleet_disband";
  };
  readonly GFX_fleet_manager_button: SpriteRef & {
    readonly id: "GFX_fleet_manager_button";
  };
  readonly GFX_fleet_manager_fleet_bg: SpriteRef & {
    readonly id: "GFX_fleet_manager_fleet_bg";
  };
  readonly GFX_fleet_manager_fleet_bg_horizontal: SpriteRef & {
    readonly id: "GFX_fleet_manager_fleet_bg_horizontal";
  };
  readonly GFX_fleet_manager_minus: SpriteRef & {
    readonly id: "GFX_fleet_manager_minus";
  };
  readonly GFX_fleet_manager_plus: SpriteRef & {
    readonly id: "GFX_fleet_manager_plus";
  };
  readonly GFX_fleet_mission_button_passive_observation: SpriteRef & {
    readonly id: "GFX_fleet_mission_button_passive_observation";
  };
  readonly GFX_fleet_mission_button_passive_observation_selected: SpriteRef & {
    readonly id: "GFX_fleet_mission_button_passive_observation_selected";
  };
  readonly GFX_fleet_order_auto_construct: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_construct";
  };
  readonly GFX_fleet_order_auto_construct_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_construct_selected";
  };
  readonly GFX_fleet_order_auto_explore: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore";
  };
  readonly GFX_fleet_order_auto_explore_arkship: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_arkship";
  };
  readonly GFX_fleet_order_auto_explore_arkship_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_arkship_selected";
  };
  readonly GFX_fleet_order_auto_explore_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_selected";
  };
  readonly GFX_fleet_order_automate: SpriteRef & {
    readonly id: "GFX_fleet_order_automate";
  };
  readonly GFX_fleet_order_automate_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_automate_selected";
  };
  readonly GFX_fleet_order_blow_up_planet_action: SpriteRef & {
    readonly id: "GFX_fleet_order_blow_up_planet_action";
  };
  readonly GFX_fleet_order_blow_up_planet_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_blow_up_planet_selected";
  };
  readonly GFX_fleet_order_button_assist_research: SpriteRef & {
    readonly id: "GFX_fleet_order_button_assist_research";
  };
  readonly GFX_fleet_order_button_assist_research_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_assist_research_selected";
  };
  readonly GFX_fleet_order_button_attack: SpriteRef & {
    readonly id: "GFX_fleet_order_button_attack";
  };
  readonly GFX_fleet_order_button_attack_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_attack_selected";
  };
  readonly GFX_fleet_order_button_build_megastructure: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_megastructure";
  };
  readonly GFX_fleet_order_button_build_megastructure_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_megastructure_selected";
  };
  readonly GFX_fleet_order_button_build_military_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_military_station";
  };
  readonly GFX_fleet_order_button_build_military_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_military_station_selected";
  };
  readonly GFX_fleet_order_button_build_mining_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_mining_station";
  };
  readonly GFX_fleet_order_button_build_mining_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_mining_station_selected";
  };
  readonly GFX_fleet_order_button_build_observation_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_observation_station";
  };
  readonly GFX_fleet_order_button_build_observation_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_observation_station_selected";
  };
  readonly GFX_fleet_order_button_build_research_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_research_station";
  };
  readonly GFX_fleet_order_button_build_research_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_research_station_selected";
  };
  readonly GFX_fleet_order_button_build_ruler_military_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_ruler_military_station";
  };
  readonly GFX_fleet_order_button_build_ruler_military_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_ruler_military_station_selected";
  };
  readonly GFX_fleet_order_button_build_starbase_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_starbase_station";
  };
  readonly GFX_fleet_order_button_build_starbase_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_starbase_station_selected";
  };
  readonly GFX_fleet_order_button_build_terraforming_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_terraforming_station";
  };
  readonly GFX_fleet_order_button_build_terraforming_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_terraforming_station_selected";
  };
  readonly GFX_fleet_order_button_build_wormhole_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_wormhole_station";
  };
  readonly GFX_fleet_order_button_build_wormhole_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_wormhole_station_selected";
  };
  readonly GFX_fleet_order_button_colonize: SpriteRef & {
    readonly id: "GFX_fleet_order_button_colonize";
  };
  readonly GFX_fleet_order_button_colonize_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_colonize_selected";
  };
  readonly GFX_fleet_order_button_drop_off_prisoners: SpriteRef & {
    readonly id: "GFX_fleet_order_button_drop_off_prisoners";
  };
  readonly GFX_fleet_order_button_follow_friendlies_off: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_off";
  };
  readonly GFX_fleet_order_button_follow_friendlies_off_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_off_large";
  };
  readonly GFX_fleet_order_button_follow_friendlies_on: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_on";
  };
  readonly GFX_fleet_order_button_follow_friendlies_on_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_on_large";
  };
  readonly GFX_fleet_order_button_ground_support_armageddon: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_armageddon";
  };
  readonly GFX_fleet_order_button_ground_support_armageddon_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_armageddon_selected";
  };
  readonly GFX_fleet_order_button_ground_support_behemoth_invasion: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_behemoth_invasion";
  };
  readonly GFX_fleet_order_button_ground_support_behemoth_invasion_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_behemoth_invasion_selected";
  };
  readonly GFX_fleet_order_button_ground_support_firestorm: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_firestorm";
  };
  readonly GFX_fleet_order_button_ground_support_firestorm_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_firestorm_selected";
  };
  readonly GFX_fleet_order_button_ground_support_indiscriminate: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_indiscriminate";
  };
  readonly GFX_fleet_order_button_ground_support_indiscriminate_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_indiscriminate_selected";
  };
  readonly GFX_fleet_order_button_ground_support_plundering: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_plundering";
  };
  readonly GFX_fleet_order_button_ground_support_plundering_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_plundering_selected";
  };
  readonly GFX_fleet_order_button_ground_support_pox: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_pox";
  };
  readonly GFX_fleet_order_button_ground_support_pox_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_pox_selected";
  };
  readonly GFX_fleet_order_button_ground_support_raiding: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_raiding";
  };
  readonly GFX_fleet_order_button_ground_support_raiding_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_raiding_selected";
  };
  readonly GFX_fleet_order_button_ground_support_seed_bombing: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seed_bombing";
  };
  readonly GFX_fleet_order_button_ground_support_seed_bombing_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seed_bombing_selected";
  };
  readonly GFX_fleet_order_button_ground_support_seismic_bombing: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seismic_bombing";
  };
  readonly GFX_fleet_order_button_ground_support_seismic_bombing_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seismic_bombing_selected";
  };
  readonly GFX_fleet_order_button_ground_support_selective: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_selective";
  };
  readonly GFX_fleet_order_button_ground_support_selective_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_selective_selected";
  };
  readonly GFX_fleet_order_button_ground_support_voidworm_invasion: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion";
  };
  readonly GFX_fleet_order_button_ground_support_voidworm_invasion_crisis: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_crisis";
  };
  readonly GFX_fleet_order_button_ground_support_voidworm_invasion_crisis_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_crisis_selected";
  };
  readonly GFX_fleet_order_button_ground_support_voidworm_invasion_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_selected";
  };
  readonly GFX_fleet_order_button_growth_stance_controlled: SpriteRef & {
    readonly id: "GFX_fleet_order_button_growth_stance_controlled";
  };
  readonly GFX_fleet_order_button_growth_stance_excessive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_growth_stance_excessive";
  };
  readonly GFX_fleet_order_button_land_armies: SpriteRef & {
    readonly id: "GFX_fleet_order_button_land_armies";
  };
  readonly GFX_fleet_order_button_land_armies_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_land_armies_selected";
  };
  readonly GFX_fleet_order_button_merge: SpriteRef & {
    readonly id: "GFX_fleet_order_button_merge";
  };
  readonly GFX_fleet_order_button_merge_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_merge_large";
  };
  readonly GFX_fleet_order_button_mia_jump: SpriteRef & {
    readonly id: "GFX_fleet_order_button_mia_jump";
  };
  readonly GFX_fleet_order_button_mia_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_mia_jump_selected";
  };
  readonly GFX_fleet_order_button_move: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move";
  };
  readonly GFX_fleet_order_button_move_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_large";
  };
  readonly GFX_fleet_order_button_move_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_selected";
  };
  readonly GFX_fleet_order_button_move_selected_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_selected_large";
  };
  readonly GFX_fleet_order_button_rally_armies_off: SpriteRef & {
    readonly id: "GFX_fleet_order_button_rally_armies_off";
  };
  readonly GFX_fleet_order_button_rally_armies_on: SpriteRef & {
    readonly id: "GFX_fleet_order_button_rally_armies_on";
  };
  readonly GFX_fleet_order_button_research: SpriteRef & {
    readonly id: "GFX_fleet_order_button_research";
  };
  readonly GFX_fleet_order_button_research_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_research_selected";
  };
  readonly GFX_fleet_order_button_return: SpriteRef & {
    readonly id: "GFX_fleet_order_button_return";
  };
  readonly GFX_fleet_order_button_return_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_return_large";
  };
  readonly GFX_fleet_order_button_shipyard: SpriteRef & {
    readonly id: "GFX_fleet_order_button_shipyard";
  };
  readonly GFX_fleet_order_button_shipyard_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_shipyard_selected";
  };
  readonly GFX_fleet_order_button_special_project: SpriteRef & {
    readonly id: "GFX_fleet_order_button_special_project";
  };
  readonly GFX_fleet_order_button_special_project_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_special_project_selected";
  };
  readonly GFX_fleet_order_button_stance_aggressive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_aggressive";
  };
  readonly GFX_fleet_order_button_stance_evasive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_evasive";
  };
  readonly GFX_fleet_order_button_stance_passive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_passive";
  };
  readonly GFX_fleet_order_button_stop: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stop";
  };
  readonly GFX_fleet_order_button_stop_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stop_large";
  };
  readonly GFX_fleet_order_button_survey: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey";
  };
  readonly GFX_fleet_order_button_survey_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_selected";
  };
  readonly GFX_fleet_order_button_survey_small: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_small";
  };
  readonly GFX_fleet_order_button_survey_small_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_small_selected";
  };
  readonly GFX_fleet_order_set_home_base: SpriteRef & {
    readonly id: "GFX_fleet_order_set_home_base";
  };
  readonly GFX_fleet_task_covert_infiltration_action: SpriteRef & {
    readonly id: "GFX_fleet_task_covert_infiltration_action";
  };
  readonly GFX_fleet_task_covert_infiltration_action_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_covert_infiltration_action_selected";
  };
  readonly GFX_fleet_task_indoctrination: SpriteRef & {
    readonly id: "GFX_fleet_task_indoctrination";
  };
  readonly GFX_fleet_task_indoctrination_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_indoctrination_selected";
  };
  readonly GFX_fleet_task_passive_observation: SpriteRef & {
    readonly id: "GFX_fleet_task_passive_observation";
  };
  readonly GFX_fleet_task_passive_observation_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_passive_observation_selected";
  };
  readonly GFX_fleet_task_specimen_collection: SpriteRef & {
    readonly id: "GFX_fleet_task_specimen_collection";
  };
  readonly GFX_fleet_task_specimen_collection_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_specimen_collection_selected";
  };
  readonly GFX_fleet_task_technological_enlightenment_action: SpriteRef & {
    readonly id: "GFX_fleet_task_technological_enlightenment_action";
  };
  readonly GFX_fleet_task_technological_enlightenment_action_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_technological_enlightenment_action_selected";
  };
  readonly GFX_fleet_view_armor: SpriteRef & {
    readonly id: "GFX_fleet_view_armor";
  };
  readonly GFX_fleet_view_armor_2: SpriteRef & {
    readonly id: "GFX_fleet_view_armor_2";
  };
  readonly GFX_fleet_view_behemoth_stage_2: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_2";
  };
  readonly GFX_fleet_view_behemoth_stage_3: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_3";
  };
  readonly GFX_fleet_view_behemoth_stage_4: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_4";
  };
  readonly GFX_fleet_view_health: SpriteRef & {
    readonly id: "GFX_fleet_view_health";
  };
  readonly GFX_fleet_view_health_2: SpriteRef & {
    readonly id: "GFX_fleet_view_health_2";
  };
  readonly GFX_fleet_view_main_civilian_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_civilian_bg";
  };
  readonly GFX_fleet_view_main_mercenaries_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_mercenaries_bg";
  };
  readonly GFX_fleet_view_main_military_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_military_bg";
  };
  readonly GFX_fleet_view_main_military_bg_long: SpriteRef & {
    readonly id: "GFX_fleet_view_main_military_bg_long";
  };
  readonly GFX_fleet_view_main_precom_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_precom_bg";
  };
  readonly GFX_fleet_view_main_science_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_science_bg";
  };
  readonly GFX_fleet_view_main_shipyard_padding_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_shipyard_padding_bg";
  };
  readonly GFX_fleet_view_main_transport_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_transport_bg";
  };
  readonly GFX_fleet_view_paladin_ship: SpriteRef & {
    readonly id: "GFX_fleet_view_paladin_ship";
  };
  readonly GFX_fleet_view_shields: SpriteRef & {
    readonly id: "GFX_fleet_view_shields";
  };
  readonly GFX_fleet_view_shields_2: SpriteRef & {
    readonly id: "GFX_fleet_view_shields_2";
  };
  readonly GFX_fleet_view_top_panel_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_top_panel_bg";
  };
  readonly GFX_fleet_view_upgradable_design: SpriteRef & {
    readonly id: "GFX_fleet_view_upgradable_design";
  };
  readonly GFX_fleetview_break_fleet_contract: SpriteRef & {
    readonly id: "GFX_fleetview_break_fleet_contract";
  };
  readonly GFX_fleetview_delete: SpriteRef & {
    readonly id: "GFX_fleetview_delete";
  };
  readonly GFX_fleetview_destroy_fleet: SpriteRef & {
    readonly id: "GFX_fleetview_destroy_fleet";
  };
  readonly GFX_fleetview_destroy_fleet_large: SpriteRef & {
    readonly id: "GFX_fleetview_destroy_fleet_large";
  };
  readonly GFX_fleetview_focus: SpriteRef & {
    readonly id: "GFX_fleetview_focus";
  };
  readonly GFX_fleetview_focus_solid: SpriteRef & {
    readonly id: "GFX_fleetview_focus_solid";
  };
  readonly GFX_fleetview_inspect_army: SpriteRef & {
    readonly id: "GFX_fleetview_inspect_army";
  };
  readonly GFX_fleetview_inspect_ship: SpriteRef & {
    readonly id: "GFX_fleetview_inspect_ship";
  };
  readonly GFX_fleetview_lock_focus: SpriteRef & {
    readonly id: "GFX_fleetview_lock_focus";
  };
  readonly GFX_fleetview_open_observation_post: SpriteRef & {
    readonly id: "GFX_fleetview_open_observation_post";
  };
  readonly GFX_fleetview_open_observation_post_solid: SpriteRef & {
    readonly id: "GFX_fleetview_open_observation_post_solid";
  };
  readonly GFX_fleetview_open_planet: SpriteRef & {
    readonly id: "GFX_fleetview_open_planet";
  };
  readonly GFX_fleetview_set_leader: SpriteRef & {
    readonly id: "GFX_fleetview_set_leader";
  };
  readonly GFX_ftl_escape: SpriteRef & {
    readonly id: "GFX_ftl_escape";
  };
  readonly GFX_governor_progressbar: SpriteRef & {
    readonly id: "GFX_governor_progressbar";
  };
  readonly GFX_leader_progressbar: SpriteRef & {
    readonly id: "GFX_leader_progressbar";
  };
  readonly GFX_overwrite_fleet_template: SpriteRef & {
    readonly id: "GFX_overwrite_fleet_template";
  };
  readonly GFX_precom_fleet_neutral: SpriteRef & {
    readonly id: "GFX_precom_fleet_neutral";
  };
  readonly GFX_precom_fleet_xenophile: SpriteRef & {
    readonly id: "GFX_precom_fleet_xenophile";
  };
  readonly GFX_precom_fleet_xenophobe: SpriteRef & {
    readonly id: "GFX_precom_fleet_xenophobe";
  };
  readonly GFX_progressbar_green: SpriteRef & {
    readonly id: "GFX_progressbar_green";
  };
  readonly GFX_rallypoint_toggle_off: SpriteRef & {
    readonly id: "GFX_rallypoint_toggle_off";
  };
  readonly GFX_rallypoint_toggle_off_large: SpriteRef & {
    readonly id: "GFX_rallypoint_toggle_off_large";
  };
  readonly GFX_rallypoint_toggle_on: SpriteRef & {
    readonly id: "GFX_rallypoint_toggle_on";
  };
  readonly GFX_rallypoint_toggle_on_large: SpriteRef & {
    readonly id: "GFX_rallypoint_toggle_on_large";
  };
  readonly GFX_scripted_action_behemoth_rage: SpriteRef & {
    readonly id: "GFX_scripted_action_behemoth_rage";
  };
  readonly GFX_ship_entry_bg: SpriteRef & {
    readonly id: "GFX_ship_entry_bg";
  };
  readonly GFX_ship_growth_progressbar: SpriteRef & {
    readonly id: "GFX_ship_growth_progressbar";
  };
  readonly GFX_shipyard_entry_bg: SpriteRef & {
    readonly id: "GFX_shipyard_entry_bg";
  };
  readonly GFX_tiles_dark_area_cut_8: SpriteRef & {
    readonly id: "GFX_tiles_dark_area_cut_8";
  };
  readonly GFX_tiles_dark_area_cut_8_hover: SpriteRef & {
    readonly id: "GFX_tiles_dark_area_cut_8_hover";
  };
  readonly GFX_tiles_green_frame_top: SpriteRef & {
    readonly id: "GFX_tiles_green_frame_top";
  };
  readonly GFX_tiles_green_side_frame_top: SpriteRef & {
    readonly id: "GFX_tiles_green_side_frame_top";
  };
  readonly GFX_tiles_green_top_left_corner_frame: SpriteRef & {
    readonly id: "GFX_tiles_green_top_left_corner_frame";
  };
  readonly GFX_unknown_leader: SpriteRef & {
    readonly id: "GFX_unknown_leader";
  };
};
