// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieGFX4 = {
  readonly senate_floor_empire_portrait_bg: SpriteRef & {
    readonly id: "GFX_4_senate_floor_empire_portrait_bg";
  };
  readonly senate_floor_portrait_bg: SpriteRef & {
    readonly id: "GFX_4_senate_floor_portrait_bg";
  };
};

export type VanillaSpriteTrieGFXText4 = SpriteRef & {
  readonly id: "GFX_text_4";
};
