// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieAdditionalContent = {
  readonly GFX_additional_content_checkmark_dlc: SpriteRef & {
    readonly id: "GFX_additional_content_checkmark_dlc";
  };
  readonly GFX_additional_content_loading: SpriteRef & {
    readonly id: "GFX_additional_content_loading";
  };
  readonly GFX_additional_content_shipset_name_bg: SpriteRef & {
    readonly id: "GFX_additional_content_shipset_name_bg";
  };
  readonly GFX_additional_content_thumbnail_fallback: SpriteRef & {
    readonly id: "GFX_additional_content_thumbnail_fallback";
  };
  readonly GFX_arrow_left: SpriteRef & {
    readonly id: "GFX_arrow_left";
  };
  readonly GFX_arrow_right: SpriteRef & {
    readonly id: "GFX_arrow_right";
  };
  readonly GFX_dark_area_window_bg: SpriteRef & {
    readonly id: "GFX_dark_area_window_bg";
  };
  readonly GFX_discount_frame: SpriteRef & {
    readonly id: "GFX_discount_frame";
  };
  readonly GFX_faded_gradient_tile_acb: SpriteRef & {
    readonly id: "GFX_faded_gradient_tile_acb";
  };
  readonly GFX_image_frame: SpriteRef & {
    readonly id: "GFX_image_frame";
  };
  readonly GFX_label_discount: SpriteRef & {
    readonly id: "GFX_label_discount";
  };
  readonly GFX_label_new: SpriteRef & {
    readonly id: "GFX_label_new";
  };
  readonly GFX_label_recommended: SpriteRef & {
    readonly id: "GFX_label_recommended";
  };
  readonly GFX_new_frame: SpriteRef & {
    readonly id: "GFX_new_frame";
  };
  readonly GFX_owned_frame: SpriteRef & {
    readonly id: "GFX_owned_frame";
  };
  readonly GFX_recommended_frame: SpriteRef & {
    readonly id: "GFX_recommended_frame";
  };
  readonly GFX_ship_preview_window_blue: SpriteRef & {
    readonly id: "GFX_ship_preview_window_blue";
  };
  readonly GFX_tab_1_long_active_acb: SpriteRef & {
    readonly id: "GFX_tab_1_long_active_acb";
  };
  readonly GFX_tab_1_long_inactive_acb: SpriteRef & {
    readonly id: "GFX_tab_1_long_inactive_acb";
  };
  readonly GFX_tab_2_long_active_acb: SpriteRef & {
    readonly id: "GFX_tab_2_long_active_acb";
  };
  readonly GFX_tab_2_long_inactive_acb: SpriteRef & {
    readonly id: "GFX_tab_2_long_inactive_acb";
  };
  readonly GFX_tile_large_bg_plain_solid: SpriteRef & {
    readonly id: "GFX_tile_large_bg_plain_solid";
  };
  readonly GFX_top_frame_large: SpriteRef & {
    readonly id: "GFX_top_frame_large";
  };
  readonly GFX_top_frame_large_subscription: SpriteRef & {
    readonly id: "GFX_top_frame_large_subscription";
  };
  readonly GFX_top_frame_small: SpriteRef & {
    readonly id: "GFX_top_frame_small";
  };
  readonly GFX_top_frame_small_subscription: SpriteRef & {
    readonly id: "GFX_top_frame_small_subscription";
  };
  readonly GFX_window_background: SpriteRef & {
    readonly id: "GFX_window_background";
  };
};
