// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieCombatView = {
  readonly GFX_emergency_ftl: SpriteRef & {
    readonly id: "GFX_emergency_ftl";
  };
  readonly GFX_fleet_combat_progress_bar_glow: SpriteRef & {
    readonly id: "GFX_fleet_combat_progress_bar_glow";
  };
  readonly GFX_fleet_combat_progressbar: SpriteRef & {
    readonly id: "GFX_fleet_combat_progressbar";
  };
  readonly GFX_fleet_order_in_progress: SpriteRef & {
    readonly id: "GFX_fleet_order_in_progress";
  };
  readonly GFX_ship_armor_radial_progress: SpriteRef & {
    readonly id: "GFX_ship_armor_radial_progress";
  };
  readonly GFX_ship_destroyed: SpriteRef & {
    readonly id: "GFX_ship_destroyed";
  };
  readonly GFX_ship_disengaged: SpriteRef & {
    readonly id: "GFX_ship_disengaged";
  };
  readonly GFX_ship_life_full: SpriteRef & {
    readonly id: "GFX_ship_life_full";
  };
  readonly GFX_ship_life_radial_progress: SpriteRef & {
    readonly id: "GFX_ship_life_radial_progress";
  };
  readonly GFX_ship_shield_radial_progress: SpriteRef & {
    readonly id: "GFX_ship_shield_radial_progress";
  };
  readonly GFX_small_hex_bg: SpriteRef & {
    readonly id: "GFX_small_hex_bg";
  };
  readonly GFX_tile_combat_stats_lost_bg: SpriteRef & {
    readonly id: "GFX_tile_combat_stats_lost_bg";
  };
  readonly GFX_tile_combat_stats_won_bg: SpriteRef & {
    readonly id: "GFX_tile_combat_stats_won_bg";
  };
  readonly GFX_vertical_line: SpriteRef & {
    readonly id: "GFX_vertical_line";
  };
};
