// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieGFXFC = {
  readonly portrait_character_masked: SpriteRef & {
    readonly id: "GFX_FC_portrait_character_masked";
  };
  readonly separator: SpriteRef & {
    readonly id: "GFX_FC_separator";
  };
  readonly specie_BG: SpriteRef & {
    readonly id: "GFX_FC_specie_BG";
  };
  readonly specie_foreground: SpriteRef & {
    readonly id: "GFX_FC_specie_foreground";
  };
  readonly specie_frame: SpriteRef & {
    readonly id: "GFX_FC_specie_frame";
  };
  readonly specie_scan: SpriteRef & {
    readonly id: "GFX_FC_specie_scan";
  };
};

export type VanillaSpriteTrieGFXEvtFace = {
  readonly off_in_space: SpriteRef & {
    readonly id: "GFX_evt_face_off_in_space";
  };
  readonly off_in_space_nomask: SpriteRef & {
    readonly id: "GFX_evt_face_off_in_space_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFailed = {
  readonly observation: SpriteRef & {
    readonly id: "GFX_evt_failed_observation";
  };
  readonly observation_nomask: SpriteRef & {
    readonly id: "GFX_evt_failed_observation_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFallen = {
  readonly empire: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire";
  };
  readonly empire_awakes: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire_awakes";
  };
  readonly empire_awakes_nomask: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire_awakes_nomask";
  };
  readonly empire_nomask: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire_nomask";
  };
  readonly empire_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire_zoom_1";
  };
  readonly empire_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_fallen_empire_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFauna = {
  readonly debris: SpriteRef & {
    readonly id: "GFX_evt_fauna_debris";
  };
  readonly debris_nomask: SpriteRef & {
    readonly id: "GFX_evt_fauna_debris_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFear = {
  readonly of_the_dark: SpriteRef & {
    readonly id: "GFX_evt_fear_of_the_dark";
  };
  readonly of_the_dark_nomask: SpriteRef & {
    readonly id: "GFX_evt_fear_of_the_dark_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFederation = {
  readonly fleet: SpriteRef & {
    readonly id: "GFX_evt_federation_fleet";
  };
  readonly fleet_nomask: SpriteRef & {
    readonly id: "GFX_evt_federation_fleet_nomask";
  };
  readonly fleet_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_federation_fleet_zoom_1";
  };
  readonly fleet_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_federation_fleet_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFinancial = {
  readonly instruments: SpriteRef & {
    readonly id: "GFX_evt_financial_instruments";
  };
  readonly instruments_nomask: SpriteRef & {
    readonly id: "GFX_evt_financial_instruments_nomask";
  };
  readonly instruments_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_financial_instruments_zoom_1";
  };
  readonly instruments_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_financial_instruments_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFleet = {
  readonly evil: SpriteRef & {
    readonly id: "GFX_evt_fleet_evil";
  };
  readonly evil_nomask: SpriteRef & {
    readonly id: "GFX_evt_fleet_evil_nomask";
  };
  readonly from_surface: SpriteRef & {
    readonly id: "GFX_evt_fleet_from_surface";
  };
  readonly from_surface_nomask: SpriteRef & {
    readonly id: "GFX_evt_fleet_from_surface_nomask";
  };
  readonly good: SpriteRef & {
    readonly id: "GFX_evt_fleet_good";
  };
  readonly good_nomask: SpriteRef & {
    readonly id: "GFX_evt_fleet_good_nomask";
  };
  readonly neutral: SpriteRef & {
    readonly id: "GFX_evt_fleet_neutral";
  };
  readonly neutral_nomask: SpriteRef & {
    readonly id: "GFX_evt_fleet_neutral_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtForever = {
  readonly cruise: SpriteRef & {
    readonly id: "GFX_evt_forever_cruise";
  };
  readonly cruise_nomask: SpriteRef & {
    readonly id: "GFX_evt_forever_cruise_nomask";
  };
  readonly cruise_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_forever_cruise_zoom_1";
  };
  readonly cruise_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_forever_cruise_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFormless = {
  readonly system: SpriteRef & {
    readonly id: "GFX_evt_formless_system";
  };
  readonly system_nomask: SpriteRef & {
    readonly id: "GFX_evt_formless_system_nomask";
  };
  readonly system_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_formless_system_zoom_1";
  };
  readonly system_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_formless_system_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFrenzied = {
  readonly voidworms: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms";
  };
  readonly voidworms_destroyed: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_destroyed";
  };
  readonly voidworms_destroyed_nomask: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_destroyed_nomask";
  };
  readonly voidworms_nomask: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_nomask";
  };
  readonly voidworms_pacified: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_pacified";
  };
  readonly voidworms_pacified_nomask: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_pacified_nomask";
  };
  readonly voidworms_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_zoom_1";
  };
  readonly voidworms_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_frenzied_voidworms_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtFriendly = {
  readonly amoeba: SpriteRef & {
    readonly id: "GFX_evt_friendly_amoeba";
  };
  readonly amoeba_nomask: SpriteRef & {
    readonly id: "GFX_evt_friendly_amoeba_nomask";
  };
  readonly enlightenment: SpriteRef & {
    readonly id: "GFX_evt_friendly_enlightenment";
  };
  readonly enlightenment_nomask: SpriteRef & {
    readonly id: "GFX_evt_friendly_enlightenment_nomask";
  };
  readonly enlightenment_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_friendly_enlightenment_zoom_1";
  };
  readonly enlightenment_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_friendly_enlightenment_zoom_2";
  };
  readonly infiltration: SpriteRef & {
    readonly id: "GFX_evt_friendly_infiltration";
  };
  readonly infiltration_nomask: SpriteRef & {
    readonly id: "GFX_evt_friendly_infiltration_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFrozen = SpriteRef & {
  readonly id: "GFX_evt_frozen";
  readonly inferno: SpriteRef & {
    readonly id: "GFX_evt_frozen_inferno";
  };
  readonly inferno_nomask: SpriteRef & {
    readonly id: "GFX_evt_frozen_inferno_nomask";
  };
  readonly nomask: SpriteRef & {
    readonly id: "GFX_evt_frozen_nomask";
  };
};

export type VanillaSpriteTrieGFXEvtFruitful = {
  readonly partnership: SpriteRef & {
    readonly id: "GFX_evt_fruitful_partnership";
  };
};

export type VanillaSpriteTrieGFXFaction = {
  readonly attraction_icon: SpriteRef & {
    readonly id: "GFX_faction_attraction_icon";
  };
  readonly header_blue: SpriteRef & {
    readonly id: "GFX_faction_header_blue";
  };
  readonly header_brown: SpriteRef & {
    readonly id: "GFX_faction_header_brown";
  };
  readonly header_cyan: SpriteRef & {
    readonly id: "GFX_faction_header_cyan";
  };
  readonly header_green: SpriteRef & {
    readonly id: "GFX_faction_header_green";
  };
  readonly header_purple: SpriteRef & {
    readonly id: "GFX_faction_header_purple";
  };
  readonly header_red: SpriteRef & {
    readonly id: "GFX_faction_header_red";
  };
  readonly header_yellow: SpriteRef & {
    readonly id: "GFX_faction_header_yellow";
  };
  readonly icon_colonialist: SpriteRef & {
    readonly id: "GFX_faction_icon_colonialist";
  };
  readonly icon_cyber_creed_construction: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_construction";
  };
  readonly icon_cyber_creed_construction_2: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_construction_2";
  };
  readonly icon_cyber_creed_general: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_general";
  };
  readonly icon_cyber_creed_labor: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_labor";
  };
  readonly icon_cyber_creed_labor_2: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_labor_2";
  };
  readonly icon_cyber_creed_research: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_research";
  };
  readonly icon_cyber_creed_research_2: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_research_2";
  };
  readonly icon_cyber_creed_war: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_war";
  };
  readonly icon_cyber_creed_war_2: SpriteRef & {
    readonly id: "GFX_faction_icon_cyber_creed_war_2";
  };
  readonly icon_fire_cult: SpriteRef & {
    readonly id: "GFX_faction_icon_fire_cult";
  };
  readonly icon_imperialist: SpriteRef & {
    readonly id: "GFX_faction_icon_imperialist";
  };
  readonly icon_imperialist_small: SpriteRef & {
    readonly id: "GFX_faction_icon_imperialist_small";
  };
  readonly icon_interlink: SpriteRef & {
    readonly id: "GFX_faction_icon_interlink";
  };
  readonly icon_isolationist: SpriteRef & {
    readonly id: "GFX_faction_icon_isolationist";
  };
  readonly icon_isolationists_small: SpriteRef & {
    readonly id: "GFX_faction_icon_isolationists_small";
  };
  readonly icon_manifesti: SpriteRef & {
    readonly id: "GFX_faction_icon_manifesti";
  };
  readonly icon_manifesti_small: SpriteRef & {
    readonly id: "GFX_faction_icon_manifesti_small";
  };
  readonly icon_progressive: SpriteRef & {
    readonly id: "GFX_faction_icon_progressive";
  };
  readonly icon_progressives_small: SpriteRef & {
    readonly id: "GFX_faction_icon_progressives_small";
  };
  readonly icon_prosperity: SpriteRef & {
    readonly id: "GFX_faction_icon_prosperity";
  };
  readonly icon_prosperity_small: SpriteRef & {
    readonly id: "GFX_faction_icon_prosperity_small";
  };
  readonly icon_rebellious_slaves: SpriteRef & {
    readonly id: "GFX_faction_icon_rebellious_slaves";
  };
  readonly icon_separatist: SpriteRef & {
    readonly id: "GFX_faction_icon_separatist";
  };
  readonly icon_supremacist: SpriteRef & {
    readonly id: "GFX_faction_icon_supremacist";
  };
  readonly icon_supremacists_small: SpriteRef & {
    readonly id: "GFX_faction_icon_supremacists_small";
  };
  readonly icon_technologist: SpriteRef & {
    readonly id: "GFX_faction_icon_technologist";
  };
  readonly icon_technologists_small: SpriteRef & {
    readonly id: "GFX_faction_icon_technologists_small";
  };
  readonly icon_the_curtain: SpriteRef & {
    readonly id: "GFX_faction_icon_the_curtain";
  };
  readonly icon_the_grand_dance: SpriteRef & {
    readonly id: "GFX_faction_icon_the_grand_dance";
  };
  readonly icon_the_masquerade: SpriteRef & {
    readonly id: "GFX_faction_icon_the_masquerade";
  };
  readonly icon_totalitarian: SpriteRef & {
    readonly id: "GFX_faction_icon_totalitarian";
  };
  readonly icon_totalitarians_small: SpriteRef & {
    readonly id: "GFX_faction_icon_totalitarians_small";
  };
  readonly icon_traditionalist: SpriteRef & {
    readonly id: "GFX_faction_icon_traditionalist";
  };
  readonly icon_traditionalist_small: SpriteRef & {
    readonly id: "GFX_faction_icon_traditionalist_small";
  };
  readonly icon_xenoist: SpriteRef & {
    readonly id: "GFX_faction_icon_xenoist";
  };
  readonly icon_xenoists_small: SpriteRef & {
    readonly id: "GFX_faction_icon_xenoists_small";
  };
  readonly support_icon: SpriteRef & {
    readonly id: "GFX_faction_support_icon";
  };
};

export type VanillaSpriteTrieGFXFaded = {
  readonly border_bottom: SpriteRef & {
    readonly id: "GFX_faded_border_bottom";
  };
  readonly border_bottom_tech: SpriteRef & {
    readonly id: "GFX_faded_border_bottom_tech";
  };
  readonly border_top: SpriteRef & {
    readonly id: "GFX_faded_border_top";
  };
  readonly gradient_bottom_tile: SpriteRef & {
    readonly id: "GFX_faded_gradient_bottom_tile";
  };
  readonly gradient_right_tile: SpriteRef & {
    readonly id: "GFX_faded_gradient_right_tile";
  };
  readonly gradient_tile: SpriteRef & {
    readonly id: "GFX_faded_gradient_tile";
  };
  readonly gradient_tile_acb: SpriteRef & {
    readonly id: "GFX_faded_gradient_tile_acb";
  };
  readonly gradient_top_tile: SpriteRef & {
    readonly id: "GFX_faded_gradient_top_tile";
  };
};

export type VanillaSpriteTrieGFXFailure = {
  readonly risk_icon: SpriteRef & {
    readonly id: "GFX_failure_risk_icon";
  };
};

export type VanillaSpriteTrieGFXFanatic = {
  readonly purifier: SpriteRef & {
    readonly id: "GFX_fanatic_purifier";
  };
};

export type VanillaSpriteTrieGFXFavor = SpriteRef & {
  readonly id: "GFX_favor";
};

export type VanillaSpriteTrieGFXFederation = {
  readonly cohesion_bar_bg: SpriteRef & {
    readonly id: "GFX_federation_cohesion_bar_bg";
  };
  readonly cohesion_negative_progressbar: SpriteRef & {
    readonly id: "GFX_federation_cohesion_negative_progressbar";
  };
  readonly cohesion_positive_progressbar: SpriteRef & {
    readonly id: "GFX_federation_cohesion_positive_progressbar";
  };
  readonly ethic_issue_ring: SpriteRef & {
    readonly id: "GFX_federation_ethic_issue_ring";
  };
  readonly flag_bg: SpriteRef & {
    readonly id: "GFX_federation_flag_bg";
  };
  readonly fleet_view_main_military_bg: SpriteRef & {
    readonly id: "GFX_federation_fleet_view_main_military_bg";
  };
  readonly fleet_view_top_panel_bg: SpriteRef & {
    readonly id: "GFX_federation_fleet_view_top_panel_bg";
  };
  readonly leader_border: SpriteRef & {
    readonly id: "GFX_federation_leader_border";
  };
  readonly name_bg: SpriteRef & {
    readonly id: "GFX_federation_name_bg";
  };
  readonly perk_bg: SpriteRef & {
    readonly id: "GFX_federation_perk_bg";
  };
  readonly perk_lock: SpriteRef & {
    readonly id: "GFX_federation_perk_lock";
  };
  readonly perk_lost: SpriteRef & {
    readonly id: "GFX_federation_perk_lost";
  };
  readonly portraitframe: SpriteRef & {
    readonly id: "GFX_federation_portraitframe";
  };
  readonly portraitframe_shadow: SpriteRef & {
    readonly id: "GFX_federation_portraitframe_shadow";
  };
  readonly progressBar_cohesion_centerPiece: SpriteRef & {
    readonly id: "GFX_federation_progressBar_cohesion_centerPiece";
  };
  readonly ship_entry_bg: SpriteRef & {
    readonly id: "GFX_federation_ship_entry_bg";
  };
  readonly stripes: SpriteRef & {
    readonly id: "GFX_federation_stripes";
  };
  readonly type_default_bg: SpriteRef & {
    readonly id: "GFX_federation_type_default_bg";
  };
  readonly xp_progressbar: SpriteRef & {
    readonly id: "GFX_federation_xp_progressbar";
  };
};

export type VanillaSpriteTrieGFXFederations = SpriteRef & {
  readonly id: "GFX_federations";
  readonly big: SpriteRef & {
    readonly id: "GFX_federations_big";
  };
  readonly small: SpriteRef & {
    readonly id: "GFX_federations_small";
  };
};

export type VanillaSpriteTrieGFXFilter = {
  readonly tab_active: SpriteRef & {
    readonly id: "GFX_filter_tab_active";
  };
  readonly tab_inactive: SpriteRef & {
    readonly id: "GFX_filter_tab_inactive";
  };
};

export type VanillaSpriteTrieGFXFind = SpriteRef & {
  readonly id: "GFX_find";
};

export type VanillaSpriteTrieGFXFirstcontact = {
  readonly blocked_contact: SpriteRef & {
    readonly id: "GFX_firstcontact_blocked_contact";
  };
  readonly difficulty_easy: SpriteRef & {
    readonly id: "GFX_firstcontact_difficulty_easy";
  };
  readonly difficulty_hard: SpriteRef & {
    readonly id: "GFX_firstcontact_difficulty_hard";
  };
  readonly difficulty_hell: SpriteRef & {
    readonly id: "GFX_firstcontact_difficulty_hell";
  };
  readonly difficulty_normal: SpriteRef & {
    readonly id: "GFX_firstcontact_difficulty_normal";
  };
  readonly file_bg: SpriteRef & {
    readonly id: "GFX_firstcontact_file_bg";
  };
  readonly icon: SpriteRef & {
    readonly id: "GFX_firstcontact_icon";
  };
  readonly icon_blocked: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_blocked";
  };
  readonly icon_fail: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_fail";
  };
  readonly icon_progress: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_progress";
  };
  readonly icon_question: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_question";
  };
  readonly icon_saucer: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_saucer";
  };
  readonly icon_starter: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_starter";
  };
  readonly icon_success: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_success";
  };
  readonly icon_warship_progress: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_warship_progress";
  };
  readonly icon_warship_success: SpriteRef & {
    readonly id: "GFX_firstcontact_icon_warship_success";
  };
  readonly progressframe: SpriteRef & {
    readonly id: "GFX_firstcontact_progressframe";
  };
  readonly specie_title: SpriteRef & {
    readonly id: "GFX_firstcontact_specie_title";
  };
  readonly ui_icon: SpriteRef & {
    readonly id: "GFX_firstcontact_ui_icon";
  };
};

export type VanillaSpriteTrieGFXFirstcontactstorypack = SpriteRef & {
  readonly id: "GFX_firstcontactstorypack";
  readonly big: SpriteRef & {
    readonly id: "GFX_firstcontactstorypack_big";
  };
  readonly small: SpriteRef & {
    readonly id: "GFX_firstcontactstorypack_small";
  };
};

export type VanillaSpriteTrieGFXFlag = {
  readonly "64_frame": SpriteRef & {
    readonly id: "GFX_flag_64_frame";
  };
  readonly "64_frame_highlight": SpriteRef & {
    readonly id: "GFX_flag_64_frame_highlight";
  };
  readonly highlight: SpriteRef & {
    readonly id: "GFX_flag_highlight";
  };
  readonly no_mask: SpriteRef & {
    readonly id: "GFX_flag_no_mask";
  };
};

export type VanillaSpriteTrieGFXFleet = {
  readonly action_button_active_reconnaissance: SpriteRef & {
    readonly id: "GFX_fleet_action_button_active_reconnaissance";
  };
  readonly action_button_active_reconnaissance_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_active_reconnaissance_selected";
  };
  readonly action_button_arkship_deep_scan: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_deep_scan";
  };
  readonly action_button_arkship_empty_spine: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_empty_spine";
  };
  readonly action_button_arkship_exodus_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_exodus_jump";
  };
  readonly action_button_arkship_harvest_resources: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_harvest_resources";
  };
  readonly action_button_arkship_reprocess_planet: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_reprocess_planet";
  };
  readonly action_button_arkship_stellar_ignition: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_stellar_ignition";
  };
  readonly action_button_arkship_strip_mine: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_strip_mine";
  };
  readonly action_button_arkship_subspace_image: SpriteRef & {
    readonly id: "GFX_fleet_action_button_arkship_subspace_image";
  };
  readonly action_button_assist_detection: SpriteRef & {
    readonly id: "GFX_fleet_action_button_assist_detection";
  };
  readonly action_button_assist_detection_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_assist_detection_selected";
  };
  readonly action_button_astral_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_astral_jump";
  };
  readonly action_button_astral_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_astral_jump_selected";
  };
  readonly action_button_behemoth_blink: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_blink";
  };
  readonly action_button_behemoth_buff: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_buff";
  };
  readonly action_button_behemoth_cloak: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_cloak";
  };
  readonly action_button_behemoth_damage: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_damage";
  };
  readonly action_button_behemoth_egg: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_egg";
  };
  readonly action_button_behemoth_rage: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_rage";
  };
  readonly action_button_behemoth_speed: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_speed";
  };
  readonly action_button_behemoth_superweapon: SpriteRef & {
    readonly id: "GFX_fleet_action_button_behemoth_superweapon";
  };
  readonly action_button_jump: SpriteRef & {
    readonly id: "GFX_fleet_action_button_jump";
  };
  readonly action_button_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_jump_selected";
  };
  readonly action_button_logistic_harvest_resources: SpriteRef & {
    readonly id: "GFX_fleet_action_button_logistic_harvest_resources";
  };
  readonly action_button_move_capital: SpriteRef & {
    readonly id: "GFX_fleet_action_button_move_capital";
  };
  readonly action_button_move_capital_solid: SpriteRef & {
    readonly id: "GFX_fleet_action_button_move_capital_solid";
  };
  readonly action_button_new: SpriteRef & {
    readonly id: "GFX_fleet_action_button_new";
  };
  readonly action_button_new_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_new_large";
  };
  readonly action_button_paladin_air_superiority: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_air_superiority";
  };
  readonly action_button_paladin_field_repairs: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_field_repairs";
  };
  readonly action_button_paladin_field_testing: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_field_testing";
  };
  readonly action_button_paladin_for_the_order: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_for_the_order";
  };
  readonly action_button_paladin_harmony: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_harmony";
  };
  readonly action_button_paladin_hold_the_line: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_hold_the_line";
  };
  readonly action_button_paladin_on_my_command: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_on_my_command";
  };
  readonly action_button_paladin_plan_b: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_plan_b";
  };
  readonly action_button_paladin_recall: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_recall";
  };
  readonly action_button_paladin_sudden_strike: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_sudden_strike";
  };
  readonly action_button_paladin_super_shield: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_super_shield";
  };
  readonly action_button_paladin_taunt: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_taunt";
  };
  readonly action_button_paladin_thunderclap: SpriteRef & {
    readonly id: "GFX_fleet_action_button_paladin_thunderclap";
  };
  readonly action_button_patrol: SpriteRef & {
    readonly id: "GFX_fleet_action_button_patrol";
  };
  readonly action_button_patrol_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_patrol_selected";
  };
  readonly action_button_phase_fleet: SpriteRef & {
    readonly id: "GFX_fleet_action_button_phase_fleet";
  };
  readonly action_button_phase_fleet_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_phase_fleet_selected";
  };
  readonly action_button_quantum_catapult: SpriteRef & {
    readonly id: "GFX_fleet_action_button_quantum_catapult";
  };
  readonly action_button_quantum_catapult_selected: SpriteRef & {
    readonly id: "GFX_fleet_action_button_quantum_catapult_selected";
  };
  readonly action_button_reinforce: SpriteRef & {
    readonly id: "GFX_fleet_action_button_reinforce";
  };
  readonly action_button_repair: SpriteRef & {
    readonly id: "GFX_fleet_action_button_repair";
  };
  readonly action_button_repair_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_repair_large";
  };
  readonly action_button_split: SpriteRef & {
    readonly id: "GFX_fleet_action_button_split";
  };
  readonly action_button_split_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_split_large";
  };
  readonly action_button_toggle_cloak: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak";
  };
  readonly action_button_toggle_cloak_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_large";
  };
  readonly action_button_toggle_cloak_off: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off";
  };
  readonly action_button_toggle_cloak_off_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off_large";
  };
  readonly action_button_toggle_cloak_off_waystation: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_off_waystation";
  };
  readonly action_button_toggle_cloak_waystation: SpriteRef & {
    readonly id: "GFX_fleet_action_button_toggle_cloak_waystation";
  };
  readonly action_button_turn_into_merc: SpriteRef & {
    readonly id: "GFX_fleet_action_button_turn_into_merc";
  };
  readonly action_button_upgrade: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade";
  };
  readonly action_button_upgrade_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_large";
  };
  readonly action_button_upgrade_station: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_station";
  };
  readonly action_button_upgrade_station_large: SpriteRef & {
    readonly id: "GFX_fleet_action_button_upgrade_station_large";
  };
  readonly armor_bar: SpriteRef & {
    readonly id: "GFX_fleet_armor_bar";
  };
  readonly capacity_icon: SpriteRef & {
    readonly id: "GFX_fleet_capacity_icon";
  };
  readonly cloaked: SpriteRef & {
    readonly id: "GFX_fleet_cloaked";
  };
  readonly combat_progress_bar_glow: SpriteRef & {
    readonly id: "GFX_fleet_combat_progress_bar_glow";
  };
  readonly combat_progressbar: SpriteRef & {
    readonly id: "GFX_fleet_combat_progressbar";
  };
  readonly disband: SpriteRef & {
    readonly id: "GFX_fleet_disband";
  };
  readonly health_bar: SpriteRef & {
    readonly id: "GFX_fleet_health_bar";
  };
  readonly manager_button: SpriteRef & {
    readonly id: "GFX_fleet_manager_button";
  };
  readonly manager_fleet_bg: SpriteRef & {
    readonly id: "GFX_fleet_manager_fleet_bg";
  };
  readonly manager_fleet_bg_horizontal: SpriteRef & {
    readonly id: "GFX_fleet_manager_fleet_bg_horizontal";
  };
  readonly manager_minus: SpriteRef & {
    readonly id: "GFX_fleet_manager_minus";
  };
  readonly manager_plus: SpriteRef & {
    readonly id: "GFX_fleet_manager_plus";
  };
  readonly mission_button_passive_observation: SpriteRef & {
    readonly id: "GFX_fleet_mission_button_passive_observation";
  };
  readonly mission_button_passive_observation_selected: SpriteRef & {
    readonly id: "GFX_fleet_mission_button_passive_observation_selected";
  };
  readonly offensive_power: SpriteRef & {
    readonly id: "GFX_fleet_offensive_power";
  };
  readonly order_auto_construct: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_construct";
  };
  readonly order_auto_construct_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_construct_selected";
  };
  readonly order_auto_explore: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore";
  };
  readonly order_auto_explore_arkship: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_arkship";
  };
  readonly order_auto_explore_arkship_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_arkship_selected";
  };
  readonly order_auto_explore_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_auto_explore_selected";
  };
  readonly order_automate: SpriteRef & {
    readonly id: "GFX_fleet_order_automate";
  };
  readonly order_automate_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_automate_selected";
  };
  readonly order_blow_up_planet_action: SpriteRef & {
    readonly id: "GFX_fleet_order_blow_up_planet_action";
  };
  readonly order_blow_up_planet_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_blow_up_planet_selected";
  };
  readonly order_button_assist_research: SpriteRef & {
    readonly id: "GFX_fleet_order_button_assist_research";
  };
  readonly order_button_assist_research_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_assist_research_selected";
  };
  readonly order_button_attack: SpriteRef & {
    readonly id: "GFX_fleet_order_button_attack";
  };
  readonly order_button_attack_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_attack_selected";
  };
  readonly order_button_build_megastructure: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_megastructure";
  };
  readonly order_button_build_megastructure_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_megastructure_selected";
  };
  readonly order_button_build_military_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_military_station";
  };
  readonly order_button_build_military_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_military_station_selected";
  };
  readonly order_button_build_mining_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_mining_station";
  };
  readonly order_button_build_mining_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_mining_station_selected";
  };
  readonly order_button_build_observation_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_observation_station";
  };
  readonly order_button_build_observation_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_observation_station_selected";
  };
  readonly order_button_build_research_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_research_station";
  };
  readonly order_button_build_research_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_research_station_selected";
  };
  readonly order_button_build_ruler_military_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_ruler_military_station";
  };
  readonly order_button_build_ruler_military_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_ruler_military_station_selected";
  };
  readonly order_button_build_starbase_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_starbase_station";
  };
  readonly order_button_build_starbase_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_starbase_station_selected";
  };
  readonly order_button_build_terraforming_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_terraforming_station";
  };
  readonly order_button_build_terraforming_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_terraforming_station_selected";
  };
  readonly order_button_build_wormhole_station: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_wormhole_station";
  };
  readonly order_button_build_wormhole_station_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_build_wormhole_station_selected";
  };
  readonly order_button_colonize: SpriteRef & {
    readonly id: "GFX_fleet_order_button_colonize";
  };
  readonly order_button_colonize_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_colonize_selected";
  };
  readonly order_button_drop_off_prisoners: SpriteRef & {
    readonly id: "GFX_fleet_order_button_drop_off_prisoners";
  };
  readonly order_button_follow_friendlies_off: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_off";
  };
  readonly order_button_follow_friendlies_off_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_off_large";
  };
  readonly order_button_follow_friendlies_on: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_on";
  };
  readonly order_button_follow_friendlies_on_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_follow_friendlies_on_large";
  };
  readonly order_button_ground_support_armageddon: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_armageddon";
  };
  readonly order_button_ground_support_armageddon_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_armageddon_selected";
  };
  readonly order_button_ground_support_behemoth_invasion: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_behemoth_invasion";
  };
  readonly order_button_ground_support_behemoth_invasion_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_behemoth_invasion_selected";
  };
  readonly order_button_ground_support_firestorm: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_firestorm";
  };
  readonly order_button_ground_support_firestorm_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_firestorm_selected";
  };
  readonly order_button_ground_support_indiscriminate: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_indiscriminate";
  };
  readonly order_button_ground_support_indiscriminate_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_indiscriminate_selected";
  };
  readonly order_button_ground_support_plundering: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_plundering";
  };
  readonly order_button_ground_support_plundering_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_plundering_selected";
  };
  readonly order_button_ground_support_pox: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_pox";
  };
  readonly order_button_ground_support_pox_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_pox_selected";
  };
  readonly order_button_ground_support_raiding: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_raiding";
  };
  readonly order_button_ground_support_raiding_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_raiding_selected";
  };
  readonly order_button_ground_support_seed_bombing: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seed_bombing";
  };
  readonly order_button_ground_support_seed_bombing_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seed_bombing_selected";
  };
  readonly order_button_ground_support_seismic_bombing: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seismic_bombing";
  };
  readonly order_button_ground_support_seismic_bombing_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_seismic_bombing_selected";
  };
  readonly order_button_ground_support_selective: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_selective";
  };
  readonly order_button_ground_support_selective_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_selective_selected";
  };
  readonly order_button_ground_support_voidworm_invasion: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion";
  };
  readonly order_button_ground_support_voidworm_invasion_crisis: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_crisis";
  };
  readonly order_button_ground_support_voidworm_invasion_crisis_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_crisis_selected";
  };
  readonly order_button_ground_support_voidworm_invasion_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_ground_support_voidworm_invasion_selected";
  };
  readonly order_button_growth_stance_controlled: SpriteRef & {
    readonly id: "GFX_fleet_order_button_growth_stance_controlled";
  };
  readonly order_button_growth_stance_excessive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_growth_stance_excessive";
  };
  readonly order_button_land_armies: SpriteRef & {
    readonly id: "GFX_fleet_order_button_land_armies";
  };
  readonly order_button_land_armies_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_land_armies_selected";
  };
  readonly order_button_merge: SpriteRef & {
    readonly id: "GFX_fleet_order_button_merge";
  };
  readonly order_button_merge_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_merge_large";
  };
  readonly order_button_mia_jump: SpriteRef & {
    readonly id: "GFX_fleet_order_button_mia_jump";
  };
  readonly order_button_mia_jump_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_mia_jump_selected";
  };
  readonly order_button_move: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move";
  };
  readonly order_button_move_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_large";
  };
  readonly order_button_move_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_selected";
  };
  readonly order_button_move_selected_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_move_selected_large";
  };
  readonly order_button_rally_armies_off: SpriteRef & {
    readonly id: "GFX_fleet_order_button_rally_armies_off";
  };
  readonly order_button_rally_armies_on: SpriteRef & {
    readonly id: "GFX_fleet_order_button_rally_armies_on";
  };
  readonly order_button_research: SpriteRef & {
    readonly id: "GFX_fleet_order_button_research";
  };
  readonly order_button_research_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_research_selected";
  };
  readonly order_button_return: SpriteRef & {
    readonly id: "GFX_fleet_order_button_return";
  };
  readonly order_button_return_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_return_large";
  };
  readonly order_button_shipyard: SpriteRef & {
    readonly id: "GFX_fleet_order_button_shipyard";
  };
  readonly order_button_shipyard_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_shipyard_selected";
  };
  readonly order_button_special_project: SpriteRef & {
    readonly id: "GFX_fleet_order_button_special_project";
  };
  readonly order_button_special_project_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_special_project_selected";
  };
  readonly order_button_stance_aggressive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_aggressive";
  };
  readonly order_button_stance_evasive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_evasive";
  };
  readonly order_button_stance_passive: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stance_passive";
  };
  readonly order_button_stop: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stop";
  };
  readonly order_button_stop_large: SpriteRef & {
    readonly id: "GFX_fleet_order_button_stop_large";
  };
  readonly order_button_survey: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey";
  };
  readonly order_button_survey_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_selected";
  };
  readonly order_button_survey_small: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_small";
  };
  readonly order_button_survey_small_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_survey_small_selected";
  };
  readonly order_button_transfix_terraformation_nucleus_action: SpriteRef & {
    readonly id: "GFX_fleet_order_button_transfix_terraformation_nucleus_action";
  };
  readonly order_button_transfix_terraformation_nucleus_selected: SpriteRef & {
    readonly id: "GFX_fleet_order_button_transfix_terraformation_nucleus_selected";
  };
  readonly order_in_progress: SpriteRef & {
    readonly id: "GFX_fleet_order_in_progress";
  };
  readonly order_set_home_base: SpriteRef & {
    readonly id: "GFX_fleet_order_set_home_base";
  };
  readonly presence_cloaked_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_cloaked_icons";
  };
  readonly presence_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_icons";
  };
  readonly presence_kaiju_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_kaiju_icons";
  };
  readonly presence_kaiju_icons_cloaked: SpriteRef & {
    readonly id: "GFX_fleet_presence_kaiju_icons_cloaked";
  };
  readonly presence_kaiju_icons_mixed: SpriteRef & {
    readonly id: "GFX_fleet_presence_kaiju_icons_mixed";
  };
  readonly presence_mixed_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_mixed_icons";
  };
  readonly presence_overlay_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_overlay_icons";
  };
  readonly presence_paladin_icons: SpriteRef & {
    readonly id: "GFX_fleet_presence_paladin_icons";
  };
  readonly presence_paladin_icons_cloaked: SpriteRef & {
    readonly id: "GFX_fleet_presence_paladin_icons_cloaked";
  };
  readonly presence_paladin_icons_mixed: SpriteRef & {
    readonly id: "GFX_fleet_presence_paladin_icons_mixed";
  };
  readonly shield_bar: SpriteRef & {
    readonly id: "GFX_fleet_shield_bar";
  };
  readonly size_icon: SpriteRef & {
    readonly id: "GFX_fleet_size_icon";
  };
  readonly status_icon: SpriteRef & {
    readonly id: "GFX_fleet_status_icon";
  };
  readonly task_covert_infiltration_action: SpriteRef & {
    readonly id: "GFX_fleet_task_covert_infiltration_action";
  };
  readonly task_covert_infiltration_action_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_covert_infiltration_action_selected";
  };
  readonly task_indoctrination: SpriteRef & {
    readonly id: "GFX_fleet_task_indoctrination";
  };
  readonly task_indoctrination_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_indoctrination_selected";
  };
  readonly task_passive_observation: SpriteRef & {
    readonly id: "GFX_fleet_task_passive_observation";
  };
  readonly task_passive_observation_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_passive_observation_selected";
  };
  readonly task_planetfall_action: SpriteRef & {
    readonly id: "GFX_fleet_task_planetfall_action";
  };
  readonly task_planetfall_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_planetfall_selected";
  };
  readonly task_specimen_collection: SpriteRef & {
    readonly id: "GFX_fleet_task_specimen_collection";
  };
  readonly task_specimen_collection_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_specimen_collection_selected";
  };
  readonly task_technological_enlightenment_action: SpriteRef & {
    readonly id: "GFX_fleet_task_technological_enlightenment_action";
  };
  readonly task_technological_enlightenment_action_selected: SpriteRef & {
    readonly id: "GFX_fleet_task_technological_enlightenment_action_selected";
  };
  readonly type_icons: SpriteRef & {
    readonly id: "GFX_fleet_type_icons";
  };
  readonly view_armor: SpriteRef & {
    readonly id: "GFX_fleet_view_armor";
  };
  readonly view_armor_2: SpriteRef & {
    readonly id: "GFX_fleet_view_armor_2";
  };
  readonly view_behemoth_stage_2: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_2";
  };
  readonly view_behemoth_stage_3: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_3";
  };
  readonly view_behemoth_stage_4: SpriteRef & {
    readonly id: "GFX_fleet_view_behemoth_stage_4";
  };
  readonly view_health: SpriteRef & {
    readonly id: "GFX_fleet_view_health";
  };
  readonly view_health_2: SpriteRef & {
    readonly id: "GFX_fleet_view_health_2";
  };
  readonly view_main_civilian_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_civilian_bg";
  };
  readonly view_main_mercenaries_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_mercenaries_bg";
  };
  readonly view_main_military_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_military_bg";
  };
  readonly view_main_military_bg_long: SpriteRef & {
    readonly id: "GFX_fleet_view_main_military_bg_long";
  };
  readonly view_main_precom_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_precom_bg";
  };
  readonly view_main_science_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_science_bg";
  };
  readonly view_main_shipyard_padding_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_shipyard_padding_bg";
  };
  readonly view_main_transport_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_main_transport_bg";
  };
  readonly view_paladin_ship: SpriteRef & {
    readonly id: "GFX_fleet_view_paladin_ship";
  };
  readonly view_shields: SpriteRef & {
    readonly id: "GFX_fleet_view_shields";
  };
  readonly view_shields_2: SpriteRef & {
    readonly id: "GFX_fleet_view_shields_2";
  };
  readonly view_top_panel_bg: SpriteRef & {
    readonly id: "GFX_fleet_view_top_panel_bg";
  };
  readonly view_upgradable_design: SpriteRef & {
    readonly id: "GFX_fleet_view_upgradable_design";
  };
};

export type VanillaSpriteTrieGFXFleetview = {
  readonly break_fleet_contract: SpriteRef & {
    readonly id: "GFX_fleetview_break_fleet_contract";
  };
  readonly delete: SpriteRef & {
    readonly id: "GFX_fleetview_delete";
  };
  readonly destroy_fleet: SpriteRef & {
    readonly id: "GFX_fleetview_destroy_fleet";
  };
  readonly destroy_fleet_large: SpriteRef & {
    readonly id: "GFX_fleetview_destroy_fleet_large";
  };
  readonly focus: SpriteRef & {
    readonly id: "GFX_fleetview_focus";
  };
  readonly focus_artist: SpriteRef & {
    readonly id: "GFX_fleetview_focus_artist";
  };
  readonly focus_caravaneer: SpriteRef & {
    readonly id: "GFX_fleetview_focus_caravaneer";
  };
  readonly focus_champions_forge: SpriteRef & {
    readonly id: "GFX_fleetview_focus_champions_forge";
  };
  readonly focus_curator: SpriteRef & {
    readonly id: "GFX_fleetview_focus_curator";
  };
  readonly focus_mercenary: SpriteRef & {
    readonly id: "GFX_fleetview_focus_mercenary";
  };
  readonly focus_solid: SpriteRef & {
    readonly id: "GFX_fleetview_focus_solid";
  };
  readonly focus_trader: SpriteRef & {
    readonly id: "GFX_fleetview_focus_trader";
  };
  readonly inspect_army: SpriteRef & {
    readonly id: "GFX_fleetview_inspect_army";
  };
  readonly inspect_ship: SpriteRef & {
    readonly id: "GFX_fleetview_inspect_ship";
  };
  readonly lock_focus: SpriteRef & {
    readonly id: "GFX_fleetview_lock_focus";
  };
  readonly open_observation_post: SpriteRef & {
    readonly id: "GFX_fleetview_open_observation_post";
  };
  readonly open_observation_post_solid: SpriteRef & {
    readonly id: "GFX_fleetview_open_observation_post_solid";
  };
  readonly open_planet: SpriteRef & {
    readonly id: "GFX_fleetview_open_planet";
  };
  readonly set_leader: SpriteRef & {
    readonly id: "GFX_fleetview_set_leader";
  };
};

export type VanillaSpriteTrieGFXFocus = SpriteRef & {
  readonly id: "GFX_focus";
  readonly button_dismiss: SpriteRef & {
    readonly id: "GFX_focus_button_dismiss";
  };
  readonly card_background_conquest_tier_1: SpriteRef & {
    readonly id: "GFX_focus_card_background_conquest_tier_1";
  };
  readonly card_background_conquest_tier_2: SpriteRef & {
    readonly id: "GFX_focus_card_background_conquest_tier_2";
  };
  readonly card_background_conquest_tier_3: SpriteRef & {
    readonly id: "GFX_focus_card_background_conquest_tier_3";
  };
  readonly card_background_conquest_tier_4: SpriteRef & {
    readonly id: "GFX_focus_card_background_conquest_tier_4";
  };
  readonly card_background_conquest_tier_5: SpriteRef & {
    readonly id: "GFX_focus_card_background_conquest_tier_5";
  };
  readonly card_background_core_tier_1: SpriteRef & {
    readonly id: "GFX_focus_card_background_core_tier_1";
  };
  readonly card_background_core_tier_2: SpriteRef & {
    readonly id: "GFX_focus_card_background_core_tier_2";
  };
  readonly card_background_core_tier_3: SpriteRef & {
    readonly id: "GFX_focus_card_background_core_tier_3";
  };
  readonly card_background_core_tier_4: SpriteRef & {
    readonly id: "GFX_focus_card_background_core_tier_4";
  };
  readonly card_background_core_tier_5: SpriteRef & {
    readonly id: "GFX_focus_card_background_core_tier_5";
  };
  readonly card_background_development_tier_1: SpriteRef & {
    readonly id: "GFX_focus_card_background_development_tier_1";
  };
  readonly card_background_development_tier_2: SpriteRef & {
    readonly id: "GFX_focus_card_background_development_tier_2";
  };
  readonly card_background_development_tier_3: SpriteRef & {
    readonly id: "GFX_focus_card_background_development_tier_3";
  };
  readonly card_background_development_tier_4: SpriteRef & {
    readonly id: "GFX_focus_card_background_development_tier_4";
  };
  readonly card_background_development_tier_5: SpriteRef & {
    readonly id: "GFX_focus_card_background_development_tier_5";
  };
  readonly card_background_exploration_tier_1: SpriteRef & {
    readonly id: "GFX_focus_card_background_exploration_tier_1";
  };
  readonly card_background_exploration_tier_2: SpriteRef & {
    readonly id: "GFX_focus_card_background_exploration_tier_2";
  };
  readonly card_background_exploration_tier_3: SpriteRef & {
    readonly id: "GFX_focus_card_background_exploration_tier_3";
  };
  readonly card_background_exploration_tier_4: SpriteRef & {
    readonly id: "GFX_focus_card_background_exploration_tier_4";
  };
  readonly card_background_exploration_tier_5: SpriteRef & {
    readonly id: "GFX_focus_card_background_exploration_tier_5";
  };
  readonly card_background_highlight: SpriteRef & {
    readonly id: "GFX_focus_card_background_highlight";
  };
  readonly card_progressbar: SpriteRef & {
    readonly id: "GFX_focus_card_progressbar";
  };
  readonly card_tier: SpriteRef & {
    readonly id: "GFX_focus_card_tier";
  };
  readonly icon_core_focus: SpriteRef & {
    readonly id: "GFX_focus_icon_core_focus";
  };
  readonly on: SpriteRef & {
    readonly id: "GFX_focus_on";
  };
  readonly priority_background_conquest: SpriteRef & {
    readonly id: "GFX_focus_priority_background_conquest";
  };
  readonly priority_background_development: SpriteRef & {
    readonly id: "GFX_focus_priority_background_development";
  };
  readonly priority_background_expanded_conquest: SpriteRef & {
    readonly id: "GFX_focus_priority_background_expanded_conquest";
  };
  readonly priority_background_expanded_development: SpriteRef & {
    readonly id: "GFX_focus_priority_background_expanded_development";
  };
  readonly priority_background_expanded_exploration: SpriteRef & {
    readonly id: "GFX_focus_priority_background_expanded_exploration";
  };
  readonly priority_background_exploration: SpriteRef & {
    readonly id: "GFX_focus_priority_background_exploration";
  };
  readonly priority_expanded_progressbar: SpriteRef & {
    readonly id: "GFX_focus_priority_expanded_progressbar";
  };
  readonly priority_icon_conquest: SpriteRef & {
    readonly id: "GFX_focus_priority_icon_conquest";
  };
  readonly priority_icon_development: SpriteRef & {
    readonly id: "GFX_focus_priority_icon_development";
  };
  readonly priority_icon_exploration: SpriteRef & {
    readonly id: "GFX_focus_priority_icon_exploration";
  };
  readonly priority_progressbar: SpriteRef & {
    readonly id: "GFX_focus_priority_progressbar";
  };
  readonly progression_end: SpriteRef & {
    readonly id: "GFX_focus_progression_end";
  };
  readonly progression_end_completed: SpriteRef & {
    readonly id: "GFX_focus_progression_end_completed";
  };
  readonly progression_left: SpriteRef & {
    readonly id: "GFX_focus_progression_left";
  };
  readonly progression_left_completed: SpriteRef & {
    readonly id: "GFX_focus_progression_left_completed";
  };
  readonly progression_progress_tile: SpriteRef & {
    readonly id: "GFX_focus_progression_progress_tile";
  };
  readonly progression_right: SpriteRef & {
    readonly id: "GFX_focus_progression_right";
  };
  readonly progression_right_completed: SpriteRef & {
    readonly id: "GFX_focus_progression_right_completed";
  };
  readonly progression_root: SpriteRef & {
    readonly id: "GFX_focus_progression_root";
  };
  readonly progression_root_completed: SpriteRef & {
    readonly id: "GFX_focus_progression_root_completed";
  };
  readonly reward_background: SpriteRef & {
    readonly id: "GFX_focus_reward_background";
  };
};

export type VanillaSpriteTrieGFXForeign = {
  readonly claim: SpriteRef & {
    readonly id: "GFX_foreign_claim";
  };
};

export type VanillaSpriteTrieGFXFragment = {
  readonly of_reckoning: SpriteRef & {
    readonly id: "GFX_fragment_of_reckoning";
  };
};

export type VanillaSpriteTrieGFXFrame = {
  readonly portrait: SpriteRef & {
    readonly id: "GFX_frame_portrait";
  };
};

export type VanillaSpriteTrieGFXFramed = {
  readonly area_tile: SpriteRef & {
    readonly id: "GFX_framed_area_tile";
  };
};

export type VanillaSpriteTrieGFXFreeze = {
  readonly resolution: SpriteRef & {
    readonly id: "GFX_freeze_resolution";
  };
};

export type VanillaSpriteTrieGFXFront = {
  readonly menu_achievements: SpriteRef & {
    readonly id: "GFX_front_menu_achievements";
  };
  readonly menu_facebook: SpriteRef & {
    readonly id: "GFX_front_menu_facebook";
  };
  readonly menu_forum: SpriteRef & {
    readonly id: "GFX_front_menu_forum";
  };
  readonly menu_homepage: SpriteRef & {
    readonly id: "GFX_front_menu_homepage";
  };
  readonly menu_privacy: SpriteRef & {
    readonly id: "GFX_front_menu_privacy";
  };
  readonly menu_twitter: SpriteRef & {
    readonly id: "GFX_front_menu_twitter";
  };
};

export type VanillaSpriteTrieGFXFrontend = {
  readonly animated_bg: SpriteRef & {
    readonly id: "GFX_frontend_animated_bg";
  };
  readonly bg: SpriteRef & {
    readonly id: "GFX_frontend_bg";
  };
  readonly dev_logo: SpriteRef & {
    readonly id: "GFX_frontend_dev_logo";
  };
};

export type VanillaSpriteTrieGFXFtl = {
  readonly escape: SpriteRef & {
    readonly id: "GFX_ftl_escape";
  };
};

export type VanillaSpriteTrieGFXTextF = SpriteRef & {
  readonly id: "GFX_text_f";
};

export type VanillaSpriteTrieGFXTextF1 = SpriteRef & {
  readonly id: "GFX_text_f1";
};

export type VanillaSpriteTrieGFXTextF10 = SpriteRef & {
  readonly id: "GFX_text_f10";
};

export type VanillaSpriteTrieGFXTextF2 = SpriteRef & {
  readonly id: "GFX_text_f2";
};

export type VanillaSpriteTrieGFXTextF3 = SpriteRef & {
  readonly id: "GFX_text_f3";
};

export type VanillaSpriteTrieGFXTextF4 = SpriteRef & {
  readonly id: "GFX_text_f4";
};

export type VanillaSpriteTrieGFXTextF5 = SpriteRef & {
  readonly id: "GFX_text_f5";
};

export type VanillaSpriteTrieGFXTextF6 = SpriteRef & {
  readonly id: "GFX_text_f6";
};

export type VanillaSpriteTrieGFXTextF7 = SpriteRef & {
  readonly id: "GFX_text_f7";
};

export type VanillaSpriteTrieGFXTextF8 = SpriteRef & {
  readonly id: "GFX_text_f8";
};

export type VanillaSpriteTrieGFXTextF9 = SpriteRef & {
  readonly id: "GFX_text_f9";
};

export type VanillaSpriteTrieGFXTextFavor = SpriteRef & {
  readonly id: "GFX_text_favor";
};

export type VanillaSpriteTrieGFXTextFederation = SpriteRef & {
  readonly id: "GFX_text_federation";
};

export type VanillaSpriteTrieGFXTextFirstcontact = SpriteRef & {
  readonly id: "GFX_text_firstcontact";
};

export type VanillaSpriteTrieGFXTextFleet = {
  readonly management: SpriteRef & {
    readonly id: "GFX_text_fleet_management";
  };
  readonly size: SpriteRef & {
    readonly id: "GFX_text_fleet_size";
  };
  readonly status: SpriteRef & {
    readonly id: "GFX_text_fleet_status";
  };
  readonly template_size: SpriteRef & {
    readonly id: "GFX_text_fleet_template_size";
  };
};

export type VanillaSpriteTrieGFXTextFlight = {
  readonly schools: SpriteRef & {
    readonly id: "GFX_text_flight_schools";
  };
};

export type VanillaSpriteTrieGFXTextFocus = {
  readonly conquest: SpriteRef & {
    readonly id: "GFX_text_focus_conquest";
  };
  readonly conquest_yellow: SpriteRef & {
    readonly id: "GFX_text_focus_conquest_yellow";
  };
  readonly core: SpriteRef & {
    readonly id: "GFX_text_focus_core";
  };
  readonly development: SpriteRef & {
    readonly id: "GFX_text_focus_development";
  };
  readonly exploration: SpriteRef & {
    readonly id: "GFX_text_focus_exploration";
  };
};

export type VanillaSpriteTrieGFXTextFrozen = {
  readonly resolution: SpriteRef & {
    readonly id: "GFX_text_frozen_resolution";
  };
};

export type VanillaSpriteTrieGFXTextFtl = {
  readonly retreat: SpriteRef & {
    readonly id: "GFX_text_ftl_retreat";
  };
};
