// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieGFXEvtKaleidoscopic = {
  readonly lights: SpriteRef & {
    readonly id: "GFX_evt_kaleidoscopic_lights";
  };
  readonly lights_nomask: SpriteRef & {
    readonly id: "GFX_evt_kaleidoscopic_lights_nomask";
  };
  readonly lights_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_kaleidoscopic_lights_zoom_1";
  };
  readonly lights_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_kaleidoscopic_lights_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtKhan = {
  readonly throne_room: SpriteRef & {
    readonly id: "GFX_evt_khan_throne_room";
  };
  readonly throne_room_nomask: SpriteRef & {
    readonly id: "GFX_evt_khan_throne_room_nomask";
  };
  readonly throne_room_zoom_1: SpriteRef & {
    readonly id: "GFX_evt_khan_throne_room_zoom_1";
  };
  readonly throne_room_zoom_2: SpriteRef & {
    readonly id: "GFX_evt_khan_throne_room_zoom_2";
  };
};

export type VanillaSpriteTrieGFXEvtKnights = SpriteRef & {
  readonly id: "GFX_evt_knights";
  readonly nomask: SpriteRef & {
    readonly id: "GFX_evt_knights_nomask";
  };
};

export type VanillaSpriteTrieGFXKick = {
  readonly player: SpriteRef & {
    readonly id: "GFX_kick_player";
  };
};

export type VanillaSpriteTrieGFXTextK = SpriteRef & {
  readonly id: "GFX_text_k";
};

export type VanillaSpriteTrieGFXTextKp = {
  readonly minus: SpriteRef & {
    readonly id: "GFX_text_kp_minus";
  };
  readonly plus: SpriteRef & {
    readonly id: "GFX_text_kp_plus";
  };
};
