// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTrieGFXTextY = SpriteRef & {
  readonly id: "GFX_text_y";
};
