// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSoundTrieNecroids = {
  readonly necroids: {
    readonly event_death_cult_01: SoundRef & {
      readonly id: "event_death_cult_01";
    };
    readonly event_death_cult_02: SoundRef & {
      readonly id: "event_death_cult_02";
    };
    readonly event_necrophage_01: SoundRef & {
      readonly id: "event_necrophage_01";
    };
    readonly juggernaut_necroid_idle_01: SoundRef & {
      readonly id: "juggernaut_necroid_idle_01";
    };
    readonly juggernaut_necroid_move_01: SoundRef & {
      readonly id: "juggernaut_necroid_move_01";
    };
    readonly juggernaut_necroid_move_02: SoundRef & {
      readonly id: "juggernaut_necroid_move_02";
    };
    readonly juggernaut_necroid_move_03: SoundRef & {
      readonly id: "juggernaut_necroid_move_03";
    };
    readonly necroid_amb_battleship_hum_01: SoundRef & {
      readonly id: "necroid_amb_battleship_hum_01";
    };
    readonly necroid_amb_battleship_hum_02: SoundRef & {
      readonly id: "necroid_amb_battleship_hum_02";
    };
    readonly necroid_amb_colony_ship_hum_01: SoundRef & {
      readonly id: "necroid_amb_colony_ship_hum_01";
    };
    readonly necroid_amb_colony_ship_hum_02: SoundRef & {
      readonly id: "necroid_amb_colony_ship_hum_02";
    };
    readonly necroid_amb_construction_ship_hum_01: SoundRef & {
      readonly id: "necroid_amb_construction_ship_hum_01";
    };
    readonly necroid_amb_construction_ship_hum_02: SoundRef & {
      readonly id: "necroid_amb_construction_ship_hum_02";
    };
    readonly necroid_amb_corvette_hum_01: SoundRef & {
      readonly id: "necroid_amb_corvette_hum_01";
    };
    readonly necroid_amb_corvette_hum_02: SoundRef & {
      readonly id: "necroid_amb_corvette_hum_02";
    };
    readonly necroid_amb_cruiser_hum_01: SoundRef & {
      readonly id: "necroid_amb_cruiser_hum_01";
    };
    readonly necroid_amb_cruiser_hum_02: SoundRef & {
      readonly id: "necroid_amb_cruiser_hum_02";
    };
    readonly necroid_amb_defense_station_idle_hum_01: SoundRef & {
      readonly id: "necroid_amb_defense_station_idle_hum_01";
    };
    readonly necroid_amb_destroyer_hum_01: SoundRef & {
      readonly id: "necroid_amb_destroyer_hum_01";
    };
    readonly necroid_amb_destroyer_hum_02: SoundRef & {
      readonly id: "necroid_amb_destroyer_hum_02";
    };
    readonly necroid_amb_mining_station_idle_01: SoundRef & {
      readonly id: "necroid_amb_mining_station_idle_01";
    };
    readonly necroid_amb_outpost_station_01: SoundRef & {
      readonly id: "necroid_amb_outpost_station_01";
    };
    readonly necroid_amb_research_station_idle_01: SoundRef & {
      readonly id: "necroid_amb_research_station_idle_01";
    };
    readonly necroid_amb_science_ship_01: SoundRef & {
      readonly id: "necroid_amb_science_ship_01";
    };
    readonly necroid_amb_starbase_citadel_01: SoundRef & {
      readonly id: "necroid_amb_starbase_citadel_01";
    };
    readonly necroid_amb_transport_ship_hum_01: SoundRef & {
      readonly id: "necroid_amb_transport_ship_hum_01";
    };
    readonly necroid_amb_transport_ship_hum_02: SoundRef & {
      readonly id: "necroid_amb_transport_ship_hum_02";
    };
    readonly necroid_amb_wormhole_station_idle_01: SoundRef & {
      readonly id: "necroid_amb_wormhole_station_idle_01";
    };
    readonly necroid_colossus_closing_01: SoundRef & {
      readonly id: "necroid_colossus_closing_01";
    };
    readonly necroid_colossus_idle_01: SoundRef & {
      readonly id: "necroid_colossus_idle_01";
    };
    readonly necroid_colossus_opening_01: SoundRef & {
      readonly id: "necroid_colossus_opening_01";
    };
    readonly necroid_moving_out_battleship_01: SoundRef & {
      readonly id: "necroid_moving_out_battleship_01";
    };
    readonly necroid_moving_out_battleship_02: SoundRef & {
      readonly id: "necroid_moving_out_battleship_02";
    };
    readonly necroid_moving_out_battleship_03: SoundRef & {
      readonly id: "necroid_moving_out_battleship_03";
    };
    readonly necroid_moving_out_colony_ship_01: SoundRef & {
      readonly id: "necroid_moving_out_colony_ship_01";
    };
    readonly necroid_moving_out_colony_ship_02: SoundRef & {
      readonly id: "necroid_moving_out_colony_ship_02";
    };
    readonly necroid_moving_out_colony_ship_03: SoundRef & {
      readonly id: "necroid_moving_out_colony_ship_03";
    };
    readonly necroid_moving_out_colossus_01: SoundRef & {
      readonly id: "necroid_moving_out_colossus_01";
    };
    readonly necroid_moving_out_colossus_02: SoundRef & {
      readonly id: "necroid_moving_out_colossus_02";
    };
    readonly necroid_moving_out_construction_01: SoundRef & {
      readonly id: "necroid_moving_out_construction_01";
    };
    readonly necroid_moving_out_construction_02: SoundRef & {
      readonly id: "necroid_moving_out_construction_02";
    };
    readonly necroid_moving_out_construction_03: SoundRef & {
      readonly id: "necroid_moving_out_construction_03";
    };
    readonly necroid_moving_out_corvette_01: SoundRef & {
      readonly id: "necroid_moving_out_corvette_01";
    };
    readonly necroid_moving_out_corvette_02: SoundRef & {
      readonly id: "necroid_moving_out_corvette_02";
    };
    readonly necroid_moving_out_corvette_03: SoundRef & {
      readonly id: "necroid_moving_out_corvette_03";
    };
    readonly necroid_moving_out_cruiser_01: SoundRef & {
      readonly id: "necroid_moving_out_cruiser_01";
    };
    readonly necroid_moving_out_cruiser_02: SoundRef & {
      readonly id: "necroid_moving_out_cruiser_02";
    };
    readonly necroid_moving_out_cruiser_03: SoundRef & {
      readonly id: "necroid_moving_out_cruiser_03";
    };
    readonly necroid_moving_out_destroyer_01: SoundRef & {
      readonly id: "necroid_moving_out_destroyer_01";
    };
    readonly necroid_moving_out_destroyer_02: SoundRef & {
      readonly id: "necroid_moving_out_destroyer_02";
    };
    readonly necroid_moving_out_destroyer_03: SoundRef & {
      readonly id: "necroid_moving_out_destroyer_03";
    };
    readonly necroid_moving_out_science_01: SoundRef & {
      readonly id: "necroid_moving_out_science_01";
    };
    readonly necroid_moving_out_science_02: SoundRef & {
      readonly id: "necroid_moving_out_science_02";
    };
    readonly necroid_moving_out_science_03: SoundRef & {
      readonly id: "necroid_moving_out_science_03";
    };
    readonly necroid_moving_out_transport_01: SoundRef & {
      readonly id: "necroid_moving_out_transport_01";
    };
    readonly necroid_moving_out_transport_02: SoundRef & {
      readonly id: "necroid_moving_out_transport_02";
    };
    readonly necroid_moving_out_transport_03: SoundRef & {
      readonly id: "necroid_moving_out_transport_03";
    };
  };
  readonly portraits: {
    readonly necroids_greetings: {
      readonly necroid_portrait_01_boneworshipper_01: SoundRef & {
        readonly id: "necroid_portrait_01_boneworshipper_01";
      };
      readonly necroid_portrait_01_boneworshipper_02: SoundRef & {
        readonly id: "necroid_portrait_01_boneworshipper_02";
      };
      readonly necroid_portrait_01_boneworshipper_03: SoundRef & {
        readonly id: "necroid_portrait_01_boneworshipper_03";
      };
      readonly necroid_portrait_01_boneworshipper_04: SoundRef & {
        readonly id: "necroid_portrait_01_boneworshipper_04";
      };
      readonly necroid_portrait_01_boneworshipper_05: SoundRef & {
        readonly id: "necroid_portrait_01_boneworshipper_05";
      };
      readonly necroid_portrait_02_mummalien_01: SoundRef & {
        readonly id: "necroid_portrait_02_mummalien_01";
      };
      readonly necroid_portrait_02_mummalien_02: SoundRef & {
        readonly id: "necroid_portrait_02_mummalien_02";
      };
      readonly necroid_portrait_02_mummalien_03: SoundRef & {
        readonly id: "necroid_portrait_02_mummalien_03";
      };
      readonly necroid_portrait_02_mummalien_04: SoundRef & {
        readonly id: "necroid_portrait_02_mummalien_04";
      };
      readonly necroid_portrait_02_mummalien_05: SoundRef & {
        readonly id: "necroid_portrait_02_mummalien_05";
      };
      readonly necroid_portrait_03_suited_corpse_01: SoundRef & {
        readonly id: "necroid_portrait_03_suited_corpse_01";
      };
      readonly necroid_portrait_03_suited_corpse_02: SoundRef & {
        readonly id: "necroid_portrait_03_suited_corpse_02";
      };
      readonly necroid_portrait_03_suited_corpse_03: SoundRef & {
        readonly id: "necroid_portrait_03_suited_corpse_03";
      };
      readonly necroid_portrait_03_suited_corpse_04: SoundRef & {
        readonly id: "necroid_portrait_03_suited_corpse_04";
      };
      readonly necroid_portrait_03_suited_corpse_05: SoundRef & {
        readonly id: "necroid_portrait_03_suited_corpse_05";
      };
      readonly necroid_portrait_04_overgrown_01: SoundRef & {
        readonly id: "necroid_portrait_04_overgrown_01";
      };
      readonly necroid_portrait_04_overgrown_02: SoundRef & {
        readonly id: "necroid_portrait_04_overgrown_02";
      };
      readonly necroid_portrait_04_overgrown_03: SoundRef & {
        readonly id: "necroid_portrait_04_overgrown_03";
      };
      readonly necroid_portrait_04_overgrown_04: SoundRef & {
        readonly id: "necroid_portrait_04_overgrown_04";
      };
      readonly necroid_portrait_04_overgrown_05: SoundRef & {
        readonly id: "necroid_portrait_04_overgrown_05";
      };
      readonly necroid_portrait_05_hologram_01: SoundRef & {
        readonly id: "necroid_portrait_05_hologram_01";
      };
      readonly necroid_portrait_05_hologram_02: SoundRef & {
        readonly id: "necroid_portrait_05_hologram_02";
      };
      readonly necroid_portrait_05_hologram_03: SoundRef & {
        readonly id: "necroid_portrait_05_hologram_03";
      };
      readonly necroid_portrait_05_hologram_04: SoundRef & {
        readonly id: "necroid_portrait_05_hologram_04";
      };
      readonly necroid_portrait_05_hologram_05: SoundRef & {
        readonly id: "necroid_portrait_05_hologram_05";
      };
      readonly necroid_portrait_06_ascended_01: SoundRef & {
        readonly id: "necroid_portrait_06_ascended_01";
      };
      readonly necroid_portrait_06_ascended_02: SoundRef & {
        readonly id: "necroid_portrait_06_ascended_02";
      };
      readonly necroid_portrait_06_ascended_03: SoundRef & {
        readonly id: "necroid_portrait_06_ascended_03";
      };
      readonly necroid_portrait_06_ascended_04: SoundRef & {
        readonly id: "necroid_portrait_06_ascended_04";
      };
      readonly necroid_portrait_06_ascended_05: SoundRef & {
        readonly id: "necroid_portrait_06_ascended_05";
      };
      readonly necroid_portrait_07_exoskeletoid_01: SoundRef & {
        readonly id: "necroid_portrait_07_exoskeletoid_01";
      };
      readonly necroid_portrait_07_exoskeletoid_02: SoundRef & {
        readonly id: "necroid_portrait_07_exoskeletoid_02";
      };
      readonly necroid_portrait_07_exoskeletoid_03: SoundRef & {
        readonly id: "necroid_portrait_07_exoskeletoid_03";
      };
      readonly necroid_portrait_07_exoskeletoid_04: SoundRef & {
        readonly id: "necroid_portrait_07_exoskeletoid_04";
      };
      readonly necroid_portrait_07_exoskeletoid_05: SoundRef & {
        readonly id: "necroid_portrait_07_exoskeletoid_05";
      };
      readonly necroid_portrait_08_masked_01: SoundRef & {
        readonly id: "necroid_portrait_08_masked_01";
      };
      readonly necroid_portrait_08_masked_02: SoundRef & {
        readonly id: "necroid_portrait_08_masked_02";
      };
      readonly necroid_portrait_08_masked_03: SoundRef & {
        readonly id: "necroid_portrait_08_masked_03";
      };
      readonly necroid_portrait_08_masked_04: SoundRef & {
        readonly id: "necroid_portrait_08_masked_04";
      };
      readonly necroid_portrait_08_masked_05: SoundRef & {
        readonly id: "necroid_portrait_08_masked_05";
      };
      readonly necroid_portrait_09_connectoid_01: SoundRef & {
        readonly id: "necroid_portrait_09_connectoid_01";
      };
      readonly necroid_portrait_09_connectoid_02: SoundRef & {
        readonly id: "necroid_portrait_09_connectoid_02";
      };
      readonly necroid_portrait_09_connectoid_03: SoundRef & {
        readonly id: "necroid_portrait_09_connectoid_03";
      };
      readonly necroid_portrait_09_connectoid_04: SoundRef & {
        readonly id: "necroid_portrait_09_connectoid_04";
      };
      readonly necroid_portrait_09_connectoid_05: SoundRef & {
        readonly id: "necroid_portrait_09_connectoid_05";
      };
      readonly necroid_portrait_10_stasis_being_01: SoundRef & {
        readonly id: "necroid_portrait_10_stasis_being_01";
      };
      readonly necroid_portrait_10_stasis_being_02: SoundRef & {
        readonly id: "necroid_portrait_10_stasis_being_02";
      };
      readonly necroid_portrait_10_stasis_being_03: SoundRef & {
        readonly id: "necroid_portrait_10_stasis_being_03";
      };
      readonly necroid_portrait_10_stasis_being_04: SoundRef & {
        readonly id: "necroid_portrait_10_stasis_being_04";
      };
      readonly necroid_portrait_10_stasis_being_05: SoundRef & {
        readonly id: "necroid_portrait_10_stasis_being_05";
      };
      readonly necroid_portrait_11_reaper_01: SoundRef & {
        readonly id: "necroid_portrait_11_reaper_01";
      };
      readonly necroid_portrait_11_reaper_02: SoundRef & {
        readonly id: "necroid_portrait_11_reaper_02";
      };
      readonly necroid_portrait_11_reaper_03: SoundRef & {
        readonly id: "necroid_portrait_11_reaper_03";
      };
      readonly necroid_portrait_11_reaper_04: SoundRef & {
        readonly id: "necroid_portrait_11_reaper_04";
      };
      readonly necroid_portrait_11_reaper_05: SoundRef & {
        readonly id: "necroid_portrait_11_reaper_05";
      };
      readonly necroid_portrait_12_skeletoid_01: SoundRef & {
        readonly id: "necroid_portrait_12_skeletoid_01";
      };
      readonly necroid_portrait_12_skeletoid_02: SoundRef & {
        readonly id: "necroid_portrait_12_skeletoid_02";
      };
      readonly necroid_portrait_12_skeletoid_03: SoundRef & {
        readonly id: "necroid_portrait_12_skeletoid_03";
      };
      readonly necroid_portrait_12_skeletoid_04: SoundRef & {
        readonly id: "necroid_portrait_12_skeletoid_04";
      };
      readonly necroid_portrait_12_skeletoid_05: SoundRef & {
        readonly id: "necroid_portrait_12_skeletoid_05";
      };
      readonly necroid_portrait_13_palien_01: SoundRef & {
        readonly id: "necroid_portrait_13_palien_01";
      };
      readonly necroid_portrait_13_palien_02: SoundRef & {
        readonly id: "necroid_portrait_13_palien_02";
      };
      readonly necroid_portrait_13_palien_03: SoundRef & {
        readonly id: "necroid_portrait_13_palien_03";
      };
      readonly necroid_portrait_13_palien_04: SoundRef & {
        readonly id: "necroid_portrait_13_palien_04";
      };
      readonly necroid_portrait_13_palien_05: SoundRef & {
        readonly id: "necroid_portrait_13_palien_05";
      };
      readonly necroid_portrait_14_energy_being_01: SoundRef & {
        readonly id: "necroid_portrait_14_energy_being_01";
      };
      readonly necroid_portrait_14_energy_being_02: SoundRef & {
        readonly id: "necroid_portrait_14_energy_being_02";
      };
      readonly necroid_portrait_14_energy_being_03: SoundRef & {
        readonly id: "necroid_portrait_14_energy_being_03";
      };
      readonly necroid_portrait_14_energy_being_04: SoundRef & {
        readonly id: "necroid_portrait_14_energy_being_04";
      };
      readonly necroid_portrait_14_energy_being_05: SoundRef & {
        readonly id: "necroid_portrait_14_energy_being_05";
      };
      readonly necroid_portrait_15_feral_zombie_01: SoundRef & {
        readonly id: "necroid_portrait_15_feral_zombie_01";
      };
      readonly necroid_portrait_15_feral_zombie_02: SoundRef & {
        readonly id: "necroid_portrait_15_feral_zombie_02";
      };
      readonly necroid_portrait_15_feral_zombie_03: SoundRef & {
        readonly id: "necroid_portrait_15_feral_zombie_03";
      };
      readonly necroid_portrait_15_feral_zombie_04: SoundRef & {
        readonly id: "necroid_portrait_15_feral_zombie_04";
      };
      readonly necroid_portrait_15_feral_zombie_05: SoundRef & {
        readonly id: "necroid_portrait_15_feral_zombie_05";
      };
      readonly necroid_portrait_16_death_worshipper_01: SoundRef & {
        readonly id: "necroid_portrait_16_death_worshipper_01";
      };
      readonly necroid_portrait_16_death_worshipper_02: SoundRef & {
        readonly id: "necroid_portrait_16_death_worshipper_02";
      };
      readonly necroid_portrait_16_death_worshipper_03: SoundRef & {
        readonly id: "necroid_portrait_16_death_worshipper_03";
      };
      readonly necroid_portrait_16_death_worshipper_04: SoundRef & {
        readonly id: "necroid_portrait_16_death_worshipper_04";
      };
      readonly necroid_portrait_16_death_worshipper_05: SoundRef & {
        readonly id: "necroid_portrait_16_death_worshipper_05";
      };
    };
  };
};
