// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSoundTriePdxAccountSignup = {
  readonly pdx_account_signup_portrait: {
    readonly pdx_account_signup_portrait_01: SoundRef & {
      readonly id: "pdx_account_signup_portrait_01";
    };
    readonly pdx_account_signup_portrait_02: SoundRef & {
      readonly id: "pdx_account_signup_portrait_02";
    };
    readonly pdx_account_signup_portrait_03: SoundRef & {
      readonly id: "pdx_account_signup_portrait_03";
    };
    readonly pdx_account_signup_portrait_04: SoundRef & {
      readonly id: "pdx_account_signup_portrait_04";
    };
    readonly pdx_account_signup_portrait_05: SoundRef & {
      readonly id: "pdx_account_signup_portrait_05";
    };
  };
};
