// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSoundTrieStrangeWorlds = {
  readonly strange_worlds: {
    readonly sw_evn_blue_lava: SoundRef & {
      readonly id: "sw_evn_blue_lava";
    };
    readonly sw_evn_bubbling_swamp: SoundRef & {
      readonly id: "sw_evn_bubbling_swamp";
    };
    readonly sw_evn_creeping_coagulation: SoundRef & {
      readonly id: "sw_evn_creeping_coagulation";
    };
    readonly sw_evn_darkmatter_aftermath: SoundRef & {
      readonly id: "sw_evn_darkmatter_aftermath";
    };
    readonly sw_evn_darkmatter_eruption: SoundRef & {
      readonly id: "sw_evn_darkmatter_eruption";
    };
    readonly sw_evn_eggs_hatching: SoundRef & {
      readonly id: "sw_evn_eggs_hatching";
    };
    readonly sw_evn_falling_bodies: SoundRef & {
      readonly id: "sw_evn_falling_bodies";
    };
    readonly sw_evn_ice_cracking: SoundRef & {
      readonly id: "sw_evn_ice_cracking";
    };
    readonly sw_evn_magnetic_metal: SoundRef & {
      readonly id: "sw_evn_magnetic_metal";
    };
    readonly sw_evn_mountain_forging: SoundRef & {
      readonly id: "sw_evn_mountain_forging";
    };
    readonly sw_evn_nature_shock: SoundRef & {
      readonly id: "sw_evn_nature_shock";
    };
    readonly sw_evn_shifting_sands: SoundRef & {
      readonly id: "sw_evn_shifting_sands";
    };
    readonly sw_evn_sinister_slurping: SoundRef & {
      readonly id: "sw_evn_sinister_slurping";
    };
    readonly sw_evn_small_explosions: SoundRef & {
      readonly id: "sw_evn_small_explosions";
    };
    readonly sw_evn_thunderstorm: SoundRef & {
      readonly id: "sw_evn_thunderstorm";
    };
  };
};
