// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSoundTrieToxoids = {
  readonly events: {
    readonly tox_events: {
      readonly event_first_contact_toxoid_01: SoundRef & {
        readonly id: "event_first_contact_toxoid_01";
      };
      readonly event_first_contact_toxoid_02: SoundRef & {
        readonly id: "event_first_contact_toxoid_02";
      };
      readonly evn_tox_knights_of_the_toxic_god_01: SoundRef & {
        readonly id: "evn_tox_knights_of_the_toxic_god_01";
      };
      readonly evn_tox_overtuned_origin_01: SoundRef & {
        readonly id: "evn_tox_overtuned_origin_01";
      };
    };
  };
  readonly planets: {
    readonly tox_planets: {
      readonly tox_amb_star_hum_01: SoundRef & {
        readonly id: "tox_amb_star_hum_01";
      };
    };
  };
  readonly portraits: {
    readonly tox_portraits: {
      readonly tox_portrait_01_01: SoundRef & {
        readonly id: "tox_portrait_01_01";
      };
      readonly tox_portrait_01_02: SoundRef & {
        readonly id: "tox_portrait_01_02";
      };
      readonly tox_portrait_01_03: SoundRef & {
        readonly id: "tox_portrait_01_03";
      };
      readonly tox_portrait_01_04: SoundRef & {
        readonly id: "tox_portrait_01_04";
      };
      readonly tox_portrait_01_05: SoundRef & {
        readonly id: "tox_portrait_01_05";
      };
      readonly tox_portrait_02_01: SoundRef & {
        readonly id: "tox_portrait_02_01";
      };
      readonly tox_portrait_02_02: SoundRef & {
        readonly id: "tox_portrait_02_02";
      };
      readonly tox_portrait_02_03: SoundRef & {
        readonly id: "tox_portrait_02_03";
      };
      readonly tox_portrait_02_04: SoundRef & {
        readonly id: "tox_portrait_02_04";
      };
      readonly tox_portrait_02_05: SoundRef & {
        readonly id: "tox_portrait_02_05";
      };
      readonly tox_portrait_03_01: SoundRef & {
        readonly id: "tox_portrait_03_01";
      };
      readonly tox_portrait_03_02: SoundRef & {
        readonly id: "tox_portrait_03_02";
      };
      readonly tox_portrait_03_03: SoundRef & {
        readonly id: "tox_portrait_03_03";
      };
      readonly tox_portrait_03_04: SoundRef & {
        readonly id: "tox_portrait_03_04";
      };
      readonly tox_portrait_03_05: SoundRef & {
        readonly id: "tox_portrait_03_05";
      };
      readonly tox_portrait_04_01: SoundRef & {
        readonly id: "tox_portrait_04_01";
      };
      readonly tox_portrait_04_02: SoundRef & {
        readonly id: "tox_portrait_04_02";
      };
      readonly tox_portrait_04_03: SoundRef & {
        readonly id: "tox_portrait_04_03";
      };
      readonly tox_portrait_04_04: SoundRef & {
        readonly id: "tox_portrait_04_04";
      };
      readonly tox_portrait_04_05: SoundRef & {
        readonly id: "tox_portrait_04_05";
      };
      readonly tox_portrait_05_01: SoundRef & {
        readonly id: "tox_portrait_05_01";
      };
      readonly tox_portrait_05_02: SoundRef & {
        readonly id: "tox_portrait_05_02";
      };
      readonly tox_portrait_05_03: SoundRef & {
        readonly id: "tox_portrait_05_03";
      };
      readonly tox_portrait_05_04: SoundRef & {
        readonly id: "tox_portrait_05_04";
      };
      readonly tox_portrait_05_05: SoundRef & {
        readonly id: "tox_portrait_05_05";
      };
      readonly tox_portrait_06_01: SoundRef & {
        readonly id: "tox_portrait_06_01";
      };
      readonly tox_portrait_06_02: SoundRef & {
        readonly id: "tox_portrait_06_02";
      };
      readonly tox_portrait_06_03: SoundRef & {
        readonly id: "tox_portrait_06_03";
      };
      readonly tox_portrait_06_04: SoundRef & {
        readonly id: "tox_portrait_06_04";
      };
      readonly tox_portrait_06_05: SoundRef & {
        readonly id: "tox_portrait_06_05";
      };
      readonly tox_portrait_07_01: SoundRef & {
        readonly id: "tox_portrait_07_01";
      };
      readonly tox_portrait_07_02: SoundRef & {
        readonly id: "tox_portrait_07_02";
      };
      readonly tox_portrait_07_03: SoundRef & {
        readonly id: "tox_portrait_07_03";
      };
      readonly tox_portrait_07_04: SoundRef & {
        readonly id: "tox_portrait_07_04";
      };
      readonly tox_portrait_07_05: SoundRef & {
        readonly id: "tox_portrait_07_05";
      };
      readonly tox_portrait_08_01: SoundRef & {
        readonly id: "tox_portrait_08_01";
      };
      readonly tox_portrait_08_02: SoundRef & {
        readonly id: "tox_portrait_08_02";
      };
      readonly tox_portrait_08_03: SoundRef & {
        readonly id: "tox_portrait_08_03";
      };
      readonly tox_portrait_08_04: SoundRef & {
        readonly id: "tox_portrait_08_04";
      };
      readonly tox_portrait_08_05: SoundRef & {
        readonly id: "tox_portrait_08_05";
      };
      readonly tox_portrait_09_01: SoundRef & {
        readonly id: "tox_portrait_09_01";
      };
      readonly tox_portrait_09_02: SoundRef & {
        readonly id: "tox_portrait_09_02";
      };
      readonly tox_portrait_09_03: SoundRef & {
        readonly id: "tox_portrait_09_03";
      };
      readonly tox_portrait_09_04: SoundRef & {
        readonly id: "tox_portrait_09_04";
      };
      readonly tox_portrait_09_05: SoundRef & {
        readonly id: "tox_portrait_09_05";
      };
      readonly tox_portrait_10_01: SoundRef & {
        readonly id: "tox_portrait_10_01";
      };
      readonly tox_portrait_10_02: SoundRef & {
        readonly id: "tox_portrait_10_02";
      };
      readonly tox_portrait_10_03: SoundRef & {
        readonly id: "tox_portrait_10_03";
      };
      readonly tox_portrait_10_04: SoundRef & {
        readonly id: "tox_portrait_10_04";
      };
      readonly tox_portrait_10_05: SoundRef & {
        readonly id: "tox_portrait_10_05";
      };
      readonly tox_portrait_11_01: SoundRef & {
        readonly id: "tox_portrait_11_01";
      };
      readonly tox_portrait_11_02: SoundRef & {
        readonly id: "tox_portrait_11_02";
      };
      readonly tox_portrait_11_03: SoundRef & {
        readonly id: "tox_portrait_11_03";
      };
      readonly tox_portrait_11_04: SoundRef & {
        readonly id: "tox_portrait_11_04";
      };
      readonly tox_portrait_11_05: SoundRef & {
        readonly id: "tox_portrait_11_05";
      };
      readonly tox_portrait_12_01: SoundRef & {
        readonly id: "tox_portrait_12_01";
      };
      readonly tox_portrait_12_02: SoundRef & {
        readonly id: "tox_portrait_12_02";
      };
      readonly tox_portrait_12_03: SoundRef & {
        readonly id: "tox_portrait_12_03";
      };
      readonly tox_portrait_12_04: SoundRef & {
        readonly id: "tox_portrait_12_04";
      };
      readonly tox_portrait_12_05: SoundRef & {
        readonly id: "tox_portrait_12_05";
      };
      readonly tox_portrait_13_01: SoundRef & {
        readonly id: "tox_portrait_13_01";
      };
      readonly tox_portrait_13_02: SoundRef & {
        readonly id: "tox_portrait_13_02";
      };
      readonly tox_portrait_13_03: SoundRef & {
        readonly id: "tox_portrait_13_03";
      };
      readonly tox_portrait_13_04: SoundRef & {
        readonly id: "tox_portrait_13_04";
      };
      readonly tox_portrait_13_05: SoundRef & {
        readonly id: "tox_portrait_13_05";
      };
      readonly tox_portrait_14_01: SoundRef & {
        readonly id: "tox_portrait_14_01";
      };
      readonly tox_portrait_14_02: SoundRef & {
        readonly id: "tox_portrait_14_02";
      };
      readonly tox_portrait_14_03: SoundRef & {
        readonly id: "tox_portrait_14_03";
      };
      readonly tox_portrait_14_04: SoundRef & {
        readonly id: "tox_portrait_14_04";
      };
      readonly tox_portrait_14_05: SoundRef & {
        readonly id: "tox_portrait_14_05";
      };
      readonly tox_portrait_15_01: SoundRef & {
        readonly id: "tox_portrait_15_01";
      };
      readonly tox_portrait_15_02: SoundRef & {
        readonly id: "tox_portrait_15_02";
      };
      readonly tox_portrait_15_03: SoundRef & {
        readonly id: "tox_portrait_15_03";
      };
      readonly tox_portrait_15_04: SoundRef & {
        readonly id: "tox_portrait_15_04";
      };
      readonly tox_portrait_15_05: SoundRef & {
        readonly id: "tox_portrait_15_05";
      };
      readonly tox_portrait_machine_01: SoundRef & {
        readonly id: "tox_portrait_machine_01";
      };
      readonly tox_portrait_machine_02: SoundRef & {
        readonly id: "tox_portrait_machine_02";
      };
      readonly tox_portrait_machine_03: SoundRef & {
        readonly id: "tox_portrait_machine_03";
      };
      readonly tox_portrait_machine_04: SoundRef & {
        readonly id: "tox_portrait_machine_04";
      };
      readonly tox_portrait_machine_05: SoundRef & {
        readonly id: "tox_portrait_machine_05";
      };
    };
  };
  readonly ships: {
    readonly tox_ships_idles: {
      readonly tox_god_idle_01: SoundRef & {
        readonly id: "tox_god_idle_01";
      };
      readonly tox_ship_battleship_idle_01: SoundRef & {
        readonly id: "tox_ship_battleship_idle_01";
      };
      readonly tox_ship_battleship_idle_02: SoundRef & {
        readonly id: "tox_ship_battleship_idle_02";
      };
      readonly tox_ship_battleship_idle_03: SoundRef & {
        readonly id: "tox_ship_battleship_idle_03";
      };
      readonly tox_ship_colony_ship_idle_01: SoundRef & {
        readonly id: "tox_ship_colony_ship_idle_01";
      };
      readonly tox_ship_colony_ship_idle_02: SoundRef & {
        readonly id: "tox_ship_colony_ship_idle_02";
      };
      readonly tox_ship_colony_ship_idle_03: SoundRef & {
        readonly id: "tox_ship_colony_ship_idle_03";
      };
      readonly tox_ship_colossus_closing_01: SoundRef & {
        readonly id: "tox_ship_colossus_closing_01";
      };
      readonly tox_ship_colossus_closing_02: SoundRef & {
        readonly id: "tox_ship_colossus_closing_02";
      };
      readonly tox_ship_colossus_closing_03: SoundRef & {
        readonly id: "tox_ship_colossus_closing_03";
      };
      readonly tox_ship_colossus_idle_01: SoundRef & {
        readonly id: "tox_ship_colossus_idle_01";
      };
      readonly tox_ship_colossus_idle_02: SoundRef & {
        readonly id: "tox_ship_colossus_idle_02";
      };
      readonly tox_ship_colossus_idle_03: SoundRef & {
        readonly id: "tox_ship_colossus_idle_03";
      };
      readonly tox_ship_colossus_open_01: SoundRef & {
        readonly id: "tox_ship_colossus_open_01";
      };
      readonly tox_ship_colossus_open_02: SoundRef & {
        readonly id: "tox_ship_colossus_open_02";
      };
      readonly tox_ship_colossus_open_03: SoundRef & {
        readonly id: "tox_ship_colossus_open_03";
      };
      readonly tox_ship_construction_ship_idle_01: SoundRef & {
        readonly id: "tox_ship_construction_ship_idle_01";
      };
      readonly tox_ship_construction_ship_idle_02: SoundRef & {
        readonly id: "tox_ship_construction_ship_idle_02";
      };
      readonly tox_ship_construction_ship_idle_03: SoundRef & {
        readonly id: "tox_ship_construction_ship_idle_03";
      };
      readonly tox_ship_corvette_idle_01: SoundRef & {
        readonly id: "tox_ship_corvette_idle_01";
      };
      readonly tox_ship_corvette_idle_02: SoundRef & {
        readonly id: "tox_ship_corvette_idle_02";
      };
      readonly tox_ship_corvette_idle_03: SoundRef & {
        readonly id: "tox_ship_corvette_idle_03";
      };
      readonly tox_ship_cruiser_idle_01: SoundRef & {
        readonly id: "tox_ship_cruiser_idle_01";
      };
      readonly tox_ship_cruiser_idle_02: SoundRef & {
        readonly id: "tox_ship_cruiser_idle_02";
      };
      readonly tox_ship_cruiser_idle_03: SoundRef & {
        readonly id: "tox_ship_cruiser_idle_03";
      };
      readonly tox_ship_destroyer_idle_01: SoundRef & {
        readonly id: "tox_ship_destroyer_idle_01";
      };
      readonly tox_ship_destroyer_idle_02: SoundRef & {
        readonly id: "tox_ship_destroyer_idle_02";
      };
      readonly tox_ship_destroyer_idle_03: SoundRef & {
        readonly id: "tox_ship_destroyer_idle_03";
      };
      readonly tox_ship_habitat_idle_01: SoundRef & {
        readonly id: "tox_ship_habitat_idle_01";
      };
      readonly tox_ship_habitat_idle_02: SoundRef & {
        readonly id: "tox_ship_habitat_idle_02";
      };
      readonly tox_ship_habitat_idle_03: SoundRef & {
        readonly id: "tox_ship_habitat_idle_03";
      };
      readonly tox_ship_juggernaut_idle_01: SoundRef & {
        readonly id: "tox_ship_juggernaut_idle_01";
      };
      readonly tox_ship_juggernaut_idle_02: SoundRef & {
        readonly id: "tox_ship_juggernaut_idle_02";
      };
      readonly tox_ship_juggernaut_idle_03: SoundRef & {
        readonly id: "tox_ship_juggernaut_idle_03";
      };
      readonly tox_ship_science_ship_idle_01: SoundRef & {
        readonly id: "tox_ship_science_ship_idle_01";
      };
      readonly tox_ship_science_ship_idle_02: SoundRef & {
        readonly id: "tox_ship_science_ship_idle_02";
      };
      readonly tox_ship_science_ship_idle_03: SoundRef & {
        readonly id: "tox_ship_science_ship_idle_03";
      };
      readonly tox_ship_starbase_idle_01: SoundRef & {
        readonly id: "tox_ship_starbase_idle_01";
      };
      readonly tox_ship_starbase_idle_02: SoundRef & {
        readonly id: "tox_ship_starbase_idle_02";
      };
      readonly tox_ship_starbase_idle_03: SoundRef & {
        readonly id: "tox_ship_starbase_idle_03";
      };
      readonly tox_ship_titan_idle_01: SoundRef & {
        readonly id: "tox_ship_titan_idle_01";
      };
      readonly tox_ship_titan_idle_02: SoundRef & {
        readonly id: "tox_ship_titan_idle_02";
      };
      readonly tox_ship_titan_idle_03: SoundRef & {
        readonly id: "tox_ship_titan_idle_03";
      };
      readonly tox_ship_transport_ship_idle_01: SoundRef & {
        readonly id: "tox_ship_transport_ship_idle_01";
      };
      readonly tox_ship_transport_ship_idle_02: SoundRef & {
        readonly id: "tox_ship_transport_ship_idle_02";
      };
      readonly tox_ship_transport_ship_idle_03: SoundRef & {
        readonly id: "tox_ship_transport_ship_idle_03";
      };
    };
    readonly tox_ships_moves: {
      readonly tox_god_move_01: SoundRef & {
        readonly id: "tox_god_move_01";
      };
      readonly tox_god_move_02: SoundRef & {
        readonly id: "tox_god_move_02";
      };
      readonly tox_god_move_03: SoundRef & {
        readonly id: "tox_god_move_03";
      };
      readonly tox_god_move_04: SoundRef & {
        readonly id: "tox_god_move_04";
      };
      readonly tox_ship_battleship_move_01: SoundRef & {
        readonly id: "tox_ship_battleship_move_01";
      };
      readonly tox_ship_battleship_move_02: SoundRef & {
        readonly id: "tox_ship_battleship_move_02";
      };
      readonly tox_ship_battleship_move_03: SoundRef & {
        readonly id: "tox_ship_battleship_move_03";
      };
      readonly tox_ship_colony_ship_move_01: SoundRef & {
        readonly id: "tox_ship_colony_ship_move_01";
      };
      readonly tox_ship_colony_ship_move_02: SoundRef & {
        readonly id: "tox_ship_colony_ship_move_02";
      };
      readonly tox_ship_colony_ship_move_03: SoundRef & {
        readonly id: "tox_ship_colony_ship_move_03";
      };
      readonly tox_ship_colossus_move_01: SoundRef & {
        readonly id: "tox_ship_colossus_move_01";
      };
      readonly tox_ship_colossus_move_02: SoundRef & {
        readonly id: "tox_ship_colossus_move_02";
      };
      readonly tox_ship_colossus_move_03: SoundRef & {
        readonly id: "tox_ship_colossus_move_03";
      };
      readonly tox_ship_construction_ship_move_01: SoundRef & {
        readonly id: "tox_ship_construction_ship_move_01";
      };
      readonly tox_ship_construction_ship_move_02: SoundRef & {
        readonly id: "tox_ship_construction_ship_move_02";
      };
      readonly tox_ship_construction_ship_move_03: SoundRef & {
        readonly id: "tox_ship_construction_ship_move_03";
      };
      readonly tox_ship_corvette_move_01: SoundRef & {
        readonly id: "tox_ship_corvette_move_01";
      };
      readonly tox_ship_corvette_move_02: SoundRef & {
        readonly id: "tox_ship_corvette_move_02";
      };
      readonly tox_ship_corvette_move_03: SoundRef & {
        readonly id: "tox_ship_corvette_move_03";
      };
      readonly tox_ship_cruiser_move_01: SoundRef & {
        readonly id: "tox_ship_cruiser_move_01";
      };
      readonly tox_ship_cruiser_move_02: SoundRef & {
        readonly id: "tox_ship_cruiser_move_02";
      };
      readonly tox_ship_cruiser_move_03: SoundRef & {
        readonly id: "tox_ship_cruiser_move_03";
      };
      readonly tox_ship_destroyer_move_01: SoundRef & {
        readonly id: "tox_ship_destroyer_move_01";
      };
      readonly tox_ship_destroyer_move_02: SoundRef & {
        readonly id: "tox_ship_destroyer_move_02";
      };
      readonly tox_ship_destroyer_move_03: SoundRef & {
        readonly id: "tox_ship_destroyer_move_03";
      };
      readonly tox_ship_juggernaut_move_01: SoundRef & {
        readonly id: "tox_ship_juggernaut_move_01";
      };
      readonly tox_ship_juggernaut_move_02: SoundRef & {
        readonly id: "tox_ship_juggernaut_move_02";
      };
      readonly tox_ship_juggernaut_move_03: SoundRef & {
        readonly id: "tox_ship_juggernaut_move_03";
      };
      readonly tox_ship_science_ship_move_01: SoundRef & {
        readonly id: "tox_ship_science_ship_move_01";
      };
      readonly tox_ship_science_ship_move_02: SoundRef & {
        readonly id: "tox_ship_science_ship_move_02";
      };
      readonly tox_ship_science_ship_move_03: SoundRef & {
        readonly id: "tox_ship_science_ship_move_03";
      };
      readonly tox_ship_titan_move_01: SoundRef & {
        readonly id: "tox_ship_titan_move_01";
      };
      readonly tox_ship_titan_move_02: SoundRef & {
        readonly id: "tox_ship_titan_move_02";
      };
      readonly tox_ship_titan_move_03: SoundRef & {
        readonly id: "tox_ship_titan_move_03";
      };
      readonly tox_ship_transport_ship_move_01: SoundRef & {
        readonly id: "tox_ship_transport_ship_move_01";
      };
      readonly tox_ship_transport_ship_move_02: SoundRef & {
        readonly id: "tox_ship_transport_ship_move_02";
      };
      readonly tox_ship_transport_ship_move_03: SoundRef & {
        readonly id: "tox_ship_transport_ship_move_03";
      };
    };
  };
  readonly stations: {
    readonly tox_stations: {
      readonly tox_ship_military_station_idle_01: SoundRef & {
        readonly id: "tox_ship_military_station_idle_01";
      };
      readonly tox_ship_military_station_idle_02: SoundRef & {
        readonly id: "tox_ship_military_station_idle_02";
      };
      readonly tox_ship_military_station_idle_03: SoundRef & {
        readonly id: "tox_ship_military_station_idle_03";
      };
      readonly tox_ship_mining_station_idle_01: SoundRef & {
        readonly id: "tox_ship_mining_station_idle_01";
      };
      readonly tox_ship_mining_station_idle_02: SoundRef & {
        readonly id: "tox_ship_mining_station_idle_02";
      };
      readonly tox_ship_mining_station_idle_03: SoundRef & {
        readonly id: "tox_ship_mining_station_idle_03";
      };
      readonly tox_ship_research_station_idle_01: SoundRef & {
        readonly id: "tox_ship_research_station_idle_01";
      };
      readonly tox_ship_research_station_idle_02: SoundRef & {
        readonly id: "tox_ship_research_station_idle_02";
      };
      readonly tox_ship_research_station_idle_03: SoundRef & {
        readonly id: "tox_ship_research_station_idle_03";
      };
    };
  };
  readonly weapons: {
    readonly toxic_god_weapons: {
      readonly toxic_god_megastructure_hit_01: SoundRef & {
        readonly id: "toxic_god_megastructure_hit_01";
      };
      readonly toxic_god_megastructure_hit_02: SoundRef & {
        readonly id: "toxic_god_megastructure_hit_02";
      };
      readonly toxic_god_megastructure_hit_03: SoundRef & {
        readonly id: "toxic_god_megastructure_hit_03";
      };
      readonly toxic_god_megastructure_hit_04: SoundRef & {
        readonly id: "toxic_god_megastructure_hit_04";
      };
      readonly toxic_god_megastructure_hit_05: SoundRef & {
        readonly id: "toxic_god_megastructure_hit_05";
      };
      readonly toxic_god_muzzle_01: SoundRef & {
        readonly id: "toxic_god_muzzle_01";
      };
      readonly toxic_god_muzzle_02: SoundRef & {
        readonly id: "toxic_god_muzzle_02";
      };
      readonly toxic_god_muzzle_03: SoundRef & {
        readonly id: "toxic_god_muzzle_03";
      };
      readonly toxic_god_planet_hit_01: SoundRef & {
        readonly id: "toxic_god_planet_hit_01";
      };
      readonly toxic_god_planet_hit_02: SoundRef & {
        readonly id: "toxic_god_planet_hit_02";
      };
      readonly toxic_god_planet_hit_03: SoundRef & {
        readonly id: "toxic_god_planet_hit_03";
      };
      readonly toxic_god_planet_hit_04: SoundRef & {
        readonly id: "toxic_god_planet_hit_04";
      };
      readonly toxic_god_planet_hit_05: SoundRef & {
        readonly id: "toxic_god_planet_hit_05";
      };
      readonly toxic_god_windup_01: SoundRef & {
        readonly id: "toxic_god_windup_01";
      };
      readonly toxic_god_windup_02: SoundRef & {
        readonly id: "toxic_god_windup_02";
      };
      readonly toxic_god_windup_03: SoundRef & {
        readonly id: "toxic_god_windup_03";
      };
    };
  };
};
