// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { EventRef } from "@pdx-ts/sdk";

export interface VanillaEventNamespaceBioship {
  readonly $1: EventRef<"ship", {}, "ship"> & { readonly id: "bioship.1" };
}
