// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { EventRef } from "@pdx-ts/sdk/stellaris";

export interface VanillaEventNamespaceDiplomatic {
  readonly $1000: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1000" };
  readonly $1001: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1001" };
  readonly $1005: EventRef<"ship", {}, "ship"> & { readonly id: "diplomatic.1005" };
  readonly $1006: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1006" };
  readonly $1010: EventRef<"ship", {}, "ship"> & { readonly id: "diplomatic.1010" };
  readonly $1011: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1011" };
  readonly $1012: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1012" };
  readonly $1013: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1013" };
  readonly $1014: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1014" };
  readonly $1020: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1020" };
  readonly $1021: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1021" };
  readonly $1022: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1022" };
  readonly $1023: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1023" };
  readonly $1024: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1024" };
  readonly $1025: EventRef<"ship", {}, "ship"> & { readonly id: "diplomatic.1025" };
  readonly $1026: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.1026" };
  readonly $14: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.14" };
  readonly $20: EventRef<"country", {}, "country"> & { readonly id: "diplomatic.20" };
}
