// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { EventRef } from "@pdx-ts/sdk";

export interface VanillaEventNamespaceExtremeFrontiers {
  readonly $100: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.100" };
  readonly $1000: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1000" };
  readonly $1005: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1005" };
  readonly $1010: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1010" };
  readonly $1015: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1015" };
  readonly $1020: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1020" };
  readonly $110: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.110" };
  readonly $1100: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1100" };
  readonly $1105: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1105" };
  readonly $1110: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1110" };
  readonly $1115: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1115" };
  readonly $1120: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1120" };
  readonly $120: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.120" };
  readonly $1200: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1200" };
  readonly $1205: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1205" };
  readonly $1210: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1210" };
  readonly $1215: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1215" };
  readonly $1220: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1220" };
  readonly $130: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.130" };
  readonly $1300: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1300" };
  readonly $1305: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1305" };
  readonly $1310: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1310" };
  readonly $1315: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1315" };
  readonly $1320: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1320" };
  readonly $1322: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1322";
  };
  readonly $1324: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1324";
  };
  readonly $1330: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1330";
  };
  readonly $140: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.140" };
  readonly $1400: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1400" };
  readonly $1405: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1405" };
  readonly $1410: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1410" };
  readonly $1415: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1415" };
  readonly $1420: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1420";
  };
  readonly $1425: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1425" };
  readonly $1426: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1426" };
  readonly $1430: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1430" };
  readonly $1435: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1435";
  };
  readonly $145: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.145" };
  readonly $150: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.150" };
  readonly $1500: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1500" };
  readonly $1505: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1505" };
  readonly $1510: EventRef<"fleet", undefined, "fleet"> & { readonly id: "extreme_frontiers.1510" };
  readonly $1515: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1515" };
  readonly $1520: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1520" };
  readonly $1525: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1525" };
  readonly $1530: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1530" };
  readonly $1531: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1531";
  };
  readonly $1532: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1532";
  };
  readonly $1533: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1533";
  };
  readonly $1534: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1534";
  };
  readonly $1535: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1535";
  };
  readonly $1540: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.1540" };
  readonly $1545: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.1545";
  };
  readonly $155: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.155" };
  readonly $160: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.160" };
  readonly $170: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.170" };
  readonly $180: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.180" };
  readonly $190: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.190" };
  readonly $200: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.200" };
  readonly $2000: EventRef<"situation", undefined, "situation"> & {
    readonly id: "extreme_frontiers.2000";
  };
  readonly $2005: EventRef<"situation", undefined, "situation"> & {
    readonly id: "extreme_frontiers.2005";
  };
  readonly $2010: EventRef<"situation", undefined, "situation"> & {
    readonly id: "extreme_frontiers.2010";
  };
  readonly $210: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.210" };
  readonly $220: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.220" };
  readonly $230: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.230" };
  readonly $240: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.240" };
  readonly $250: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.250" };
  readonly $260: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.260" };
  readonly $265: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.265" };
  readonly $270: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.270" };
  readonly $280: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.280" };
  readonly $285: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.285" };
  readonly $290: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.290" };
  readonly $295: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.295" };
  readonly $300: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.300" };
  readonly $310: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.310" };
  readonly $320: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.320" };
  readonly $330: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.330" };
  readonly $340: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.340" };
  readonly $350: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.350" };
  readonly $352: EventRef<"country", undefined, "country"> & {
    readonly id: "extreme_frontiers.352";
  };
  readonly $360: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.360" };
  readonly $365: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.365" };
  readonly $370: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.370" };
  readonly $375: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.375" };
  readonly $380: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.380" };
  readonly $385: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.385" };
  readonly $390: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.390" };
  readonly $400: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.400" };
  readonly $410: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.410" };
  readonly $420: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.420" };
  readonly $430: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.430" };
  readonly $435: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.435" };
  readonly $440: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.440" };
  readonly $445: EventRef<"ship", undefined, "ship"> & { readonly id: "extreme_frontiers.445" };
}
