// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { EventRef } from "@pdx-ts/sdk";

export interface VanillaEventNamespacePlant {
  readonly $100: EventRef<"carrier", {}, "carrier"> & { readonly id: "plant.100" };
  readonly $101: EventRef<"carrier", {}, "carrier"> & { readonly id: "plant.101" };
  readonly $105: EventRef<"country", {}, "country"> & { readonly id: "plant.105" };
  readonly $110: EventRef<"country", {}, "country"> & { readonly id: "plant.110" };
  readonly $115: EventRef<"carrier", {}, "carrier"> & { readonly id: "plant.115" };
}
