// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { EventRef, EventScopelessRef } from "@pdx-ts/sdk";

export interface VanillaEventNamespaceSyndaw {
  readonly $1000: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.1000" };
  readonly $1020: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.1020" };
  readonly $1022: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1022" };
  readonly $1025: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1025" };
  readonly $1030: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1030" };
  readonly $1035: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1035" };
  readonly $1050: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1050" };
  readonly $1200: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1200" };
  readonly $1201: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1201" };
  readonly $1205: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1205" };
  readonly $1206: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1206" };
  readonly $1300: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1300" };
  readonly $1305: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.1305" };
  readonly $1310: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.1310" };
  readonly $1311: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.1311" };
  readonly $1320: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.1320" };
  readonly $1330: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.1330" };
  readonly $2000: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.2000" };
  readonly $21: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.21" };
  readonly $25: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.25" };
  readonly $26: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.26" };
  readonly $32: EventRef<"fleet", undefined, "fleet"> & { readonly id: "syndaw.32" };
  readonly $400: EventScopelessRef & { readonly id: "syndaw.400" };
  readonly $401: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.401" };
  readonly $500: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.500" };
  readonly $501: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.501" };
  readonly $502: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.502" };
  readonly $505: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.505" };
  readonly $510: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.510" };
  readonly $511: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.511" };
  readonly $515: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.515" };
  readonly $520: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.520" };
  readonly $521: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.521" };
  readonly $522: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.522" };
  readonly $525: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.525" };
  readonly $526: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.526" };
  readonly $530: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.530" };
  readonly $535: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.535" };
  readonly $540: EventRef<"situation", undefined, "situation"> & { readonly id: "syndaw.540" };
  readonly $545: EventRef<"carrier", undefined, "carrier"> & { readonly id: "syndaw.545" };
  readonly $550: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.550" };
  readonly $555: EventRef<"country", undefined, "country"> & { readonly id: "syndaw.555" };
}
