// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieAlerts = {
  readonly GFX_alert_activate_relic: SpriteRef & {
    readonly id: "GFX_alert_activate_relic";
  };
  readonly GFX_alert_army_combat: SpriteRef & {
    readonly id: "GFX_alert_army_combat";
  };
  readonly GFX_alert_astral_action_available: SpriteRef & {
    readonly id: "GFX_alert_astral_action_available";
  };
  readonly GFX_alert_astral_rift_event: SpriteRef & {
    readonly id: "GFX_alert_astral_rift_event";
  };
  readonly GFX_alert_automation_resources: SpriteRef & {
    readonly id: "GFX_alert_automation_resources";
  };
  readonly GFX_alert_available_council_agenda: SpriteRef & {
    readonly id: "GFX_alert_available_council_agenda";
  };
  readonly GFX_alert_available_council_position: SpriteRef & {
    readonly id: "GFX_alert_available_council_position";
  };
  readonly GFX_alert_building: SpriteRef & {
    readonly id: "GFX_alert_building";
  };
  readonly GFX_alert_can_enter_shroud: SpriteRef & {
    readonly id: "GFX_alert_can_enter_shroud";
  };
  readonly GFX_alert_can_modify_species: SpriteRef & {
    readonly id: "GFX_alert_can_modify_species";
  };
  readonly GFX_alert_can_upgrade_government: SpriteRef & {
    readonly id: "GFX_alert_can_upgrade_government";
  };
  readonly GFX_alert_cannot_afford_monthly_trade: SpriteRef & {
    readonly id: "GFX_alert_cannot_afford_monthly_trade";
  };
  readonly GFX_alert_capped_resources: SpriteRef & {
    readonly id: "GFX_alert_capped_resources";
  };
  readonly GFX_alert_council_agenda_ready: SpriteRef & {
    readonly id: "GFX_alert_council_agenda_ready";
  };
  readonly GFX_alert_council_election: SpriteRef & {
    readonly id: "GFX_alert_council_election";
  };
  readonly GFX_alert_cycle_of_conflict: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_conflict";
  };
  readonly GFX_alert_cycle_of_fortune: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_fortune";
  };
  readonly GFX_alert_cycle_of_growth: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_growth";
  };
  readonly GFX_alert_cycle_of_harmony: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_harmony";
  };
  readonly GFX_alert_cycle_of_knowledge: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_knowledge";
  };
  readonly GFX_alert_cycle_of_omens: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_omens";
  };
  readonly GFX_alert_cycle_of_prosperity: SpriteRef & {
    readonly id: "GFX_alert_cycle_of_prosperity";
  };
  readonly GFX_alert_declining_pops: SpriteRef & {
    readonly id: "GFX_alert_declining_pops";
  };
  readonly GFX_alert_deprecated: SpriteRef & {
    readonly id: "GFX_alert_deprecated";
  };
  readonly GFX_alert_election: SpriteRef & {
    readonly id: "GFX_alert_election";
  };
  readonly GFX_alert_engineering_research: SpriteRef & {
    readonly id: "GFX_alert_engineering_research";
  };
  readonly GFX_alert_espionage_event: SpriteRef & {
    readonly id: "GFX_alert_espionage_event";
  };
  readonly GFX_alert_federation_losing_level: SpriteRef & {
    readonly id: "GFX_alert_federation_losing_level";
  };
  readonly GFX_alert_federation_losing_xp: SpriteRef & {
    readonly id: "GFX_alert_federation_losing_xp";
  };
  readonly GFX_alert_federation_low_cohesion: SpriteRef & {
    readonly id: "GFX_alert_federation_low_cohesion";
  };
  readonly GFX_alert_first_contact_stage_done: SpriteRef & {
    readonly id: "GFX_alert_first_contact_stage_done";
  };
  readonly GFX_alert_fleet_combat: SpriteRef & {
    readonly id: "GFX_alert_fleet_combat";
  };
  readonly GFX_alert_forced_to_decloak: SpriteRef & {
    readonly id: "GFX_alert_forced_to_decloak";
  };
  readonly GFX_alert_forced_to_decloak_by_us: SpriteRef & {
    readonly id: "GFX_alert_forced_to_decloak_by_us";
  };
  readonly GFX_alert_formless_reward_available: SpriteRef & {
    readonly id: "GFX_alert_formless_reward_available";
  };
  readonly GFX_alert_high_piracy_risk: SpriteRef & {
    readonly id: "GFX_alert_high_piracy_risk";
  };
  readonly GFX_alert_high_war_exhaustion: SpriteRef & {
    readonly id: "GFX_alert_high_war_exhaustion";
  };
  readonly GFX_alert_hopeless_war: SpriteRef & {
    readonly id: "GFX_alert_hopeless_war";
  };
  readonly GFX_alert_hostile_in_system: SpriteRef & {
    readonly id: "GFX_alert_hostile_in_system";
  };
  readonly GFX_alert_imminent_situation: SpriteRef & {
    readonly id: "GFX_alert_imminent_situation";
  };
  readonly GFX_alert_in_breach: SpriteRef & {
    readonly id: "GFX_alert_in_breach";
  };
  readonly GFX_alert_inactive_civics: SpriteRef & {
    readonly id: "GFX_alert_inactive_civics";
  };
  readonly GFX_alert_intel_negative: SpriteRef & {
    readonly id: "GFX_alert_intel_negative";
  };
  readonly GFX_alert_leader_available: SpriteRef & {
    readonly id: "GFX_alert_leader_available";
  };
  readonly GFX_alert_leader_level_up: SpriteRef & {
    readonly id: "GFX_alert_leader_level_up";
  };
  readonly GFX_alert_leader_trait_points_available: SpriteRef & {
    readonly id: "GFX_alert_leader_trait_points_available";
  };
  readonly GFX_alert_low_cohesion: SpriteRef & {
    readonly id: "GFX_alert_low_cohesion";
  };
  readonly GFX_alert_low_stability: SpriteRef & {
    readonly id: "GFX_alert_low_stability";
  };
  readonly GFX_alert_mia: SpriteRef & {
    readonly id: "GFX_alert_mia";
  };
  readonly GFX_alert_mia_forced_to_decloak: SpriteRef & {
    readonly id: "GFX_alert_mia_forced_to_decloak";
  };
  readonly GFX_alert_mia_forced_to_decloak_by_us: SpriteRef & {
    readonly id: "GFX_alert_mia_forced_to_decloak_by_us";
  };
  readonly GFX_alert_mia_phase_out_fleet: SpriteRef & {
    readonly id: "GFX_alert_mia_phase_out_fleet";
  };
  readonly GFX_alert_mia_reinforce: SpriteRef & {
    readonly id: "GFX_alert_mia_reinforce";
  };
  readonly GFX_alert_necrophage_low_pops: SpriteRef & {
    readonly id: "GFX_alert_necrophage_low_pops";
  };
  readonly GFX_alert_negative_income: SpriteRef & {
    readonly id: "GFX_alert_negative_income";
  };
  readonly GFX_alert_open_council_position: SpriteRef & {
    readonly id: "GFX_alert_open_council_position";
  };
  readonly GFX_alert_physics_research: SpriteRef & {
    readonly id: "GFX_alert_physics_research";
  };
  readonly GFX_alert_research_missing_scientist: SpriteRef & {
    readonly id: "GFX_alert_research_missing_scientist";
  };
  readonly GFX_alert_resource_shortage: SpriteRef & {
    readonly id: "GFX_alert_resource_shortage";
  };
  readonly GFX_alert_set_war_goal: SpriteRef & {
    readonly id: "GFX_alert_set_war_goal";
  };
  readonly GFX_alert_site_event: SpriteRef & {
    readonly id: "GFX_alert_site_event";
  };
  readonly GFX_alert_society_research: SpriteRef & {
    readonly id: "GFX_alert_society_research";
  };
  readonly GFX_alert_space_fauna_bombardment: SpriteRef & {
    readonly id: "GFX_alert_space_fauna_bombardment";
  };
  readonly GFX_alert_spynetwork_lacking_power: SpriteRef & {
    readonly id: "GFX_alert_spynetwork_lacking_power";
  };
  readonly GFX_alert_starvation: SpriteRef & {
    readonly id: "GFX_alert_starvation";
  };
  readonly GFX_alert_timed_project: SpriteRef & {
    readonly id: "GFX_alert_timed_project";
  };
  readonly GFX_alert_unemployed_pops: SpriteRef & {
    readonly id: "GFX_alert_unemployed_pops";
  };
  readonly GFX_alert_unlock_ascension_perk: SpriteRef & {
    readonly id: "GFX_alert_unlock_ascension_perk";
  };
  readonly GFX_alert_unlock_tradition: SpriteRef & {
    readonly id: "GFX_alert_unlock_tradition";
  };
  readonly GFX_alerticon_banner_high: SpriteRef & {
    readonly id: "GFX_alerticon_banner_high";
  };
  readonly GFX_alerticon_banner_low: SpriteRef & {
    readonly id: "GFX_alerticon_banner_low";
  };
  readonly GFX_alerticon_banner_med: SpriteRef & {
    readonly id: "GFX_alerticon_banner_med";
  };
  readonly GFX_alerticon_line: SpriteRef & {
    readonly id: "GFX_alerticon_line";
  };
  readonly GFX_alerticons: SpriteRef & {
    readonly id: "GFX_alerticons";
  };
  readonly GFX_border_legendary: SpriteRef & {
    readonly id: "GFX_border_legendary";
  };
  readonly GFX_border_rare: SpriteRef & {
    readonly id: "GFX_border_rare";
  };
  readonly GFX_border_veteran: SpriteRef & {
    readonly id: "GFX_border_veteran";
  };
  readonly GFX_toast_timing_progress_bar: SpriteRef & {
    readonly id: "GFX_toast_timing_progress_bar";
  };
};
