// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieArchaeologyView = {
  readonly GFX_archaeology_difficulty_easy: SpriteRef & {
    readonly id: "GFX_archaeology_difficulty_easy";
  };
  readonly GFX_archaeology_difficulty_hard: SpriteRef & {
    readonly id: "GFX_archaeology_difficulty_hard";
  };
  readonly GFX_archaeology_difficulty_hell: SpriteRef & {
    readonly id: "GFX_archaeology_difficulty_hell";
  };
  readonly GFX_archaeology_difficulty_normal: SpriteRef & {
    readonly id: "GFX_archaeology_difficulty_normal";
  };
  readonly GFX_archaeology_map_icon: SpriteRef & {
    readonly id: "GFX_archaeology_map_icon";
  };
  readonly GFX_archaeology_runes_A1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A1";
  };
  readonly GFX_archaeology_runes_A2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A2";
  };
  readonly GFX_archaeology_runes_A3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A3";
  };
  readonly GFX_archaeology_runes_A4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A4";
  };
  readonly GFX_archaeology_runes_A5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A5";
  };
  readonly GFX_archaeology_runes_A6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_A6";
  };
  readonly GFX_archaeology_runes_B1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B1";
  };
  readonly GFX_archaeology_runes_B2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B2";
  };
  readonly GFX_archaeology_runes_B3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B3";
  };
  readonly GFX_archaeology_runes_B4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B4";
  };
  readonly GFX_archaeology_runes_B5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B5";
  };
  readonly GFX_archaeology_runes_B6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_B6";
  };
  readonly GFX_archaeology_runes_C1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C1";
  };
  readonly GFX_archaeology_runes_C2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C2";
  };
  readonly GFX_archaeology_runes_C3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C3";
  };
  readonly GFX_archaeology_runes_C4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C4";
  };
  readonly GFX_archaeology_runes_C5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C5";
  };
  readonly GFX_archaeology_runes_C6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_C6";
  };
  readonly GFX_archaeology_runes_D1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D1";
  };
  readonly GFX_archaeology_runes_D2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D2";
  };
  readonly GFX_archaeology_runes_D3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D3";
  };
  readonly GFX_archaeology_runes_D4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D4";
  };
  readonly GFX_archaeology_runes_D5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D5";
  };
  readonly GFX_archaeology_runes_D6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_D6";
  };
  readonly GFX_archaeology_runes_E1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E1";
  };
  readonly GFX_archaeology_runes_E2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E2";
  };
  readonly GFX_archaeology_runes_E3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E3";
  };
  readonly GFX_archaeology_runes_E4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E4";
  };
  readonly GFX_archaeology_runes_E5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E5";
  };
  readonly GFX_archaeology_runes_E6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_E6";
  };
  readonly GFX_archaeology_runes_F1: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F1";
  };
  readonly GFX_archaeology_runes_F2: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F2";
  };
  readonly GFX_archaeology_runes_F3: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F3";
  };
  readonly GFX_archaeology_runes_F4: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F4";
  };
  readonly GFX_archaeology_runes_F5: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F5";
  };
  readonly GFX_archaeology_runes_F6: SpriteRef & {
    readonly id: "GFX_archaeology_runes_F6";
  };
  readonly GFX_archaeology_sign: SpriteRef & {
    readonly id: "GFX_archaeology_sign";
  };
  readonly GFX_archeology_data_bg: SpriteRef & {
    readonly id: "GFX_archeology_data_bg";
  };
  readonly GFX_chapter_0: SpriteRef & {
    readonly id: "GFX_chapter_0";
  };
  readonly GFX_chapter_button: SpriteRef & {
    readonly id: "GFX_chapter_button";
  };
  readonly GFX_chapter_container: SpriteRef & {
    readonly id: "GFX_chapter_container";
  };
  readonly GFX_chapter_event: SpriteRef & {
    readonly id: "GFX_chapter_event";
  };
  readonly GFX_chapter_in_progress: SpriteRef & {
    readonly id: "GFX_chapter_in_progress";
  };
  readonly GFX_chapter_progress_bar: SpriteRef & {
    readonly id: "GFX_chapter_progress_bar";
  };
  readonly GFX_clue: SpriteRef & {
    readonly id: "GFX_clue";
  };
  readonly GFX_difficulty_range: SpriteRef & {
    readonly id: "GFX_difficulty_range";
  };
  readonly GFX_evt_archaeological_site_in_progress: SpriteRef & {
    readonly id: "GFX_evt_archaeological_site_in_progress";
  };
  readonly GFX_expedition_details: SpriteRef & {
    readonly id: "GFX_expedition_details";
  };
  readonly GFX_expedition_file_bg: SpriteRef & {
    readonly id: "GFX_expedition_file_bg";
  };
  readonly GFX_expedition_file_blocked: SpriteRef & {
    readonly id: "GFX_expedition_file_blocked";
  };
  readonly GFX_expedition_file_blocked_doorLeft: SpriteRef & {
    readonly id: "GFX_expedition_file_blocked_doorLeft";
  };
  readonly GFX_expedition_file_blocked_doorRight: SpriteRef & {
    readonly id: "GFX_expedition_file_blocked_doorRight";
  };
  readonly GFX_expedition_log_tab: SpriteRef & {
    readonly id: "GFX_expedition_log_tab";
  };
  readonly GFX_expedition_title_bg: SpriteRef & {
    readonly id: "GFX_expedition_title_bg";
  };
  readonly GFX_icon_archaeology: SpriteRef & {
    readonly id: "GFX_icon_archaeology";
  };
  readonly GFX_icon_archaeology_dieroll: SpriteRef & {
    readonly id: "GFX_icon_archaeology_dieroll";
  };
  readonly GFX_leader_bonus: SpriteRef & {
    readonly id: "GFX_leader_bonus";
  };
  readonly GFX_log_clue: SpriteRef & {
    readonly id: "GFX_log_clue";
  };
  readonly GFX_queue_progressbar_100: SpriteRef & {
    readonly id: "GFX_queue_progressbar_100";
  };
  readonly GFX_rune_background_bar: SpriteRef & {
    readonly id: "GFX_rune_background_bar";
  };
};
