// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieDlcIcons = {
  readonly GFX_ancientrelicsstorypack: SpriteRef & {
    readonly id: "GFX_ancientrelicsstorypack";
  };
  readonly GFX_ancientrelicsstorypack_big: SpriteRef & {
    readonly id: "GFX_ancientrelicsstorypack_big";
  };
  readonly GFX_ancientrelicsstorypack_small: SpriteRef & {
    readonly id: "GFX_ancientrelicsstorypack_small";
  };
  readonly GFX_apocalypse: SpriteRef & {
    readonly id: "GFX_apocalypse";
  };
  readonly GFX_apocalypse_big: SpriteRef & {
    readonly id: "GFX_apocalypse_big";
  };
  readonly GFX_apocalypse_small: SpriteRef & {
    readonly id: "GFX_apocalypse_small";
  };
  readonly GFX_aquaticsspeciespack: SpriteRef & {
    readonly id: "GFX_aquaticsspeciespack";
  };
  readonly GFX_aquaticsspeciespack_big: SpriteRef & {
    readonly id: "GFX_aquaticsspeciespack_big";
  };
  readonly GFX_aquaticsspeciespack_small: SpriteRef & {
    readonly id: "GFX_aquaticsspeciespack_small";
  };
  readonly GFX_astralplanes: SpriteRef & {
    readonly id: "GFX_astralplanes";
  };
  readonly GFX_astralplanes_big: SpriteRef & {
    readonly id: "GFX_astralplanes_big";
  };
  readonly GFX_astralplanes_small: SpriteRef & {
    readonly id: "GFX_astralplanes_small";
  };
  readonly GFX_biogenesis: SpriteRef & {
    readonly id: "GFX_biogenesis";
  };
  readonly GFX_biogenesis_big: SpriteRef & {
    readonly id: "GFX_biogenesis_big";
  };
  readonly GFX_biogenesis_small: SpriteRef & {
    readonly id: "GFX_biogenesis_small";
  };
  readonly GFX_black_bg_tile: SpriteRef & {
    readonly id: "GFX_black_bg_tile";
  };
  readonly GFX_checkmark_icon: SpriteRef & {
    readonly id: "GFX_checkmark_icon";
  };
  readonly GFX_cosmicstorms: SpriteRef & {
    readonly id: "GFX_cosmicstorms";
  };
  readonly GFX_cosmicstorms_big: SpriteRef & {
    readonly id: "GFX_cosmicstorms_big";
  };
  readonly GFX_cosmicstorms_small: SpriteRef & {
    readonly id: "GFX_cosmicstorms_small";
  };
  readonly GFX_distantstarsstorypack: SpriteRef & {
    readonly id: "GFX_distantstarsstorypack";
  };
  readonly GFX_distantstarsstorypack_big: SpriteRef & {
    readonly id: "GFX_distantstarsstorypack_big";
  };
  readonly GFX_distantstarsstorypack_small: SpriteRef & {
    readonly id: "GFX_distantstarsstorypack_small";
  };
  readonly GFX_expansionframe_big: SpriteRef & {
    readonly id: "GFX_expansionframe_big";
  };
  readonly GFX_expansionframe_small: SpriteRef & {
    readonly id: "GFX_expansionframe_small";
  };
  readonly GFX_federations: SpriteRef & {
    readonly id: "GFX_federations";
  };
  readonly GFX_federations_big: SpriteRef & {
    readonly id: "GFX_federations_big";
  };
  readonly GFX_federations_small: SpriteRef & {
    readonly id: "GFX_federations_small";
  };
  readonly GFX_firstcontactstorypack: SpriteRef & {
    readonly id: "GFX_firstcontactstorypack";
  };
  readonly GFX_firstcontactstorypack_big: SpriteRef & {
    readonly id: "GFX_firstcontactstorypack_big";
  };
  readonly GFX_firstcontactstorypack_small: SpriteRef & {
    readonly id: "GFX_firstcontactstorypack_small";
  };
  readonly GFX_galacticparagons: SpriteRef & {
    readonly id: "GFX_galacticparagons";
  };
  readonly GFX_galacticparagons_big: SpriteRef & {
    readonly id: "GFX_galacticparagons_big";
  };
  readonly GFX_galacticparagons_small: SpriteRef & {
    readonly id: "GFX_galacticparagons_small";
  };
  readonly GFX_grandarchive: SpriteRef & {
    readonly id: "GFX_grandarchive";
  };
  readonly GFX_grandarchive_big: SpriteRef & {
    readonly id: "GFX_grandarchive_big";
  };
  readonly GFX_grandarchive_small: SpriteRef & {
    readonly id: "GFX_grandarchive_small";
  };
  readonly GFX_green_underlay: SpriteRef & {
    readonly id: "GFX_green_underlay";
  };
  readonly GFX_green_underlay_horizontal: SpriteRef & {
    readonly id: "GFX_green_underlay_horizontal";
  };
  readonly GFX_green_underlay_horizontal_HL: SpriteRef & {
    readonly id: "GFX_green_underlay_horizontal_HL";
  };
  readonly GFX_humanoidsspeciespack_big: SpriteRef & {
    readonly id: "GFX_humanoidsspeciespack_big";
  };
  readonly GFX_humanoidsspeciespack_small: SpriteRef & {
    readonly id: "GFX_humanoidsspeciespack_small";
  };
  readonly GFX_infernalsspeciespack: SpriteRef & {
    readonly id: "GFX_infernalsspeciespack";
  };
  readonly GFX_infernalsspeciespack_big: SpriteRef & {
    readonly id: "GFX_infernalsspeciespack_big";
  };
  readonly GFX_infernalsspeciespack_small: SpriteRef & {
    readonly id: "GFX_infernalsspeciespack_small";
  };
  readonly GFX_leviathansstorypack: SpriteRef & {
    readonly id: "GFX_leviathansstorypack";
  };
  readonly GFX_leviathansstorypack_big: SpriteRef & {
    readonly id: "GFX_leviathansstorypack_big";
  };
  readonly GFX_leviathansstorypack_small: SpriteRef & {
    readonly id: "GFX_leviathansstorypack_small";
  };
  readonly GFX_lithoidsspeciespack: SpriteRef & {
    readonly id: "GFX_lithoidsspeciespack";
  };
  readonly GFX_lithoidsspeciespack_big: SpriteRef & {
    readonly id: "GFX_lithoidsspeciespack_big";
  };
  readonly GFX_lithoidsspeciespack_small: SpriteRef & {
    readonly id: "GFX_lithoidsspeciespack_small";
  };
  readonly GFX_megacorp: SpriteRef & {
    readonly id: "GFX_megacorp";
  };
  readonly GFX_megacorp_big: SpriteRef & {
    readonly id: "GFX_megacorp_big";
  };
  readonly GFX_megacorp_small: SpriteRef & {
    readonly id: "GFX_megacorp_small";
  };
  readonly GFX_necroidsspeciespack: SpriteRef & {
    readonly id: "GFX_necroidsspeciespack";
  };
  readonly GFX_necroidsspeciespack_big: SpriteRef & {
    readonly id: "GFX_necroidsspeciespack_big";
  };
  readonly GFX_necroidsspeciespack_small: SpriteRef & {
    readonly id: "GFX_necroidsspeciespack_small";
  };
  readonly GFX_nemesis: SpriteRef & {
    readonly id: "GFX_nemesis";
  };
  readonly GFX_nemesis_big: SpriteRef & {
    readonly id: "GFX_nemesis_big";
  };
  readonly GFX_nemesis_small: SpriteRef & {
    readonly id: "GFX_nemesis_small";
  };
  readonly GFX_nomads: SpriteRef & {
    readonly id: "GFX_nomads";
  };
  readonly GFX_nomads_big: SpriteRef & {
    readonly id: "GFX_nomads_big";
  };
  readonly GFX_nomads_small: SpriteRef & {
    readonly id: "GFX_nomads_small";
  };
  readonly GFX_overlord: SpriteRef & {
    readonly id: "GFX_overlord";
  };
  readonly GFX_overlord_big: SpriteRef & {
    readonly id: "GFX_overlord_big";
  };
  readonly GFX_overlord_small: SpriteRef & {
    readonly id: "GFX_overlord_small";
  };
  readonly GFX_plantoidsspeciespack_big: SpriteRef & {
    readonly id: "GFX_plantoidsspeciespack_big";
  };
  readonly GFX_plantoidsspeciespack_small: SpriteRef & {
    readonly id: "GFX_plantoidsspeciespack_small";
  };
  readonly GFX_shadowsoftheshroud: SpriteRef & {
    readonly id: "GFX_shadowsoftheshroud";
  };
  readonly GFX_shadowsoftheshroud_big: SpriteRef & {
    readonly id: "GFX_shadowsoftheshroud_big";
  };
  readonly GFX_shadowsoftheshroud_small: SpriteRef & {
    readonly id: "GFX_shadowsoftheshroud_small";
  };
  readonly GFX_silver_underlay: SpriteRef & {
    readonly id: "GFX_silver_underlay";
  };
  readonly GFX_silver_underlay_horizontal: SpriteRef & {
    readonly id: "GFX_silver_underlay_horizontal";
  };
  readonly GFX_silver_underlay_horizontal_HL: SpriteRef & {
    readonly id: "GFX_silver_underlay_horizontal_HL";
  };
  readonly GFX_syntheticdawnstorypack: SpriteRef & {
    readonly id: "GFX_syntheticdawnstorypack";
  };
  readonly GFX_syntheticdawnstorypack_big: SpriteRef & {
    readonly id: "GFX_syntheticdawnstorypack_big";
  };
  readonly GFX_syntheticdawnstorypack_small: SpriteRef & {
    readonly id: "GFX_syntheticdawnstorypack_small";
  };
  readonly GFX_themachineage: SpriteRef & {
    readonly id: "GFX_themachineage";
  };
  readonly GFX_themachineage_big: SpriteRef & {
    readonly id: "GFX_themachineage_big";
  };
  readonly GFX_themachineage_small: SpriteRef & {
    readonly id: "GFX_themachineage_small";
  };
  readonly GFX_toxoidsspeciespack: SpriteRef & {
    readonly id: "GFX_toxoidsspeciespack";
  };
  readonly GFX_toxoidsspeciespack_big: SpriteRef & {
    readonly id: "GFX_toxoidsspeciespack_big";
  };
  readonly GFX_toxoidsspeciespack_small: SpriteRef & {
    readonly id: "GFX_toxoidsspeciespack_small";
  };
  readonly GFX_utopia: SpriteRef & {
    readonly id: "GFX_utopia";
  };
  readonly GFX_utopia_big: SpriteRef & {
    readonly id: "GFX_utopia_big";
  };
  readonly GFX_utopia_small: SpriteRef & {
    readonly id: "GFX_utopia_small";
  };
};
