// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTypeTrieEmpireView = {
  readonly GFX_black_box: SpriteRef & {
    readonly id: "GFX_black_box";
  };
  readonly GFX_black_box_orange: SpriteRef & {
    readonly id: "GFX_black_box_orange";
  };
  readonly GFX_close_button_planet: SpriteRef & {
    readonly id: "GFX_close_button_planet";
  };
  readonly GFX_empire_capital: SpriteRef & {
    readonly id: "GFX_empire_capital";
  };
  readonly GFX_planet_list_plus: SpriteRef & {
    readonly id: "GFX_planet_list_plus";
  };
  readonly GFX_rulers_button: SpriteRef & {
    readonly id: "GFX_rulers_button";
  };
  readonly GFX_sector_capital: SpriteRef & {
    readonly id: "GFX_sector_capital";
  };
  readonly GFX_thinking_bubble: SpriteRef & {
    readonly id: "GFX_thinking_bubble";
  };
};
