// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieSettingsView = {
  readonly GFX_horizontal_slider: SpriteRef & {
    readonly id: "GFX_horizontal_slider";
  };
  readonly GFX_setting_window_bg: SpriteRef & {
    readonly id: "GFX_setting_window_bg";
  };
  readonly GFX_settings_bar: SpriteRef & {
    readonly id: "GFX_settings_bar";
  };
  readonly GFX_settings_bg: SpriteRef & {
    readonly id: "GFX_settings_bg";
  };
  readonly GFX_settings_dropdown_button: SpriteRef & {
    readonly id: "GFX_settings_dropdown_button";
  };
  readonly GFX_settings_dropdown_item: SpriteRef & {
    readonly id: "GFX_settings_dropdown_item";
  };
  readonly GFX_settings_edit_indicator: SpriteRef & {
    readonly id: "GFX_settings_edit_indicator";
  };
  readonly GFX_settings_scroll_drager: SpriteRef & {
    readonly id: "GFX_settings_scroll_drager";
  };
  readonly GFX_tab_settings: SpriteRef & {
    readonly id: "GFX_tab_settings";
  };
  readonly GFX_tab_settings_smaller: SpriteRef & {
    readonly id: "GFX_tab_settings_smaller";
  };
  readonly button_left: SpriteRef & {
    readonly id: "button_left";
  };
  readonly button_right: SpriteRef & {
    readonly id: "button_right";
  };
  readonly gfx_horizontal_left_button: SpriteRef & {
    readonly id: "gfx_horizontal_left_button";
  };
  readonly gfx_horizontal_right_button: SpriteRef & {
    readonly id: "gfx_horizontal_right_button";
  };
  readonly gfx_horizontal_scroll_track: SpriteRef & {
    readonly id: "gfx_horizontal_scroll_track";
  };
  readonly scrollbar_background: SpriteRef & {
    readonly id: "scrollbar_background";
  };
  readonly scrollbar_leftbutton: SpriteRef & {
    readonly id: "scrollbar_leftbutton";
  };
  readonly scrollbar_rightbutton: SpriteRef & {
    readonly id: "scrollbar_rightbutton";
  };
};
