// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk";

export type VanillaSpriteTypeTrieSetup = {
  readonly GFX_authority_border_accent: SpriteRef & {
    readonly id: "GFX_authority_border_accent";
  };
  readonly GFX_difficulty_bar_1: SpriteRef & {
    readonly id: "GFX_difficulty_bar_1";
  };
  readonly GFX_difficulty_bar_2: SpriteRef & {
    readonly id: "GFX_difficulty_bar_2";
  };
  readonly GFX_difficulty_bar_3: SpriteRef & {
    readonly id: "GFX_difficulty_bar_3";
  };
  readonly GFX_difficulty_bar_4: SpriteRef & {
    readonly id: "GFX_difficulty_bar_4";
  };
  readonly GFX_difficulty_bar_5: SpriteRef & {
    readonly id: "GFX_difficulty_bar_5";
  };
  readonly GFX_difficulty_bar_6: SpriteRef & {
    readonly id: "GFX_difficulty_bar_6";
  };
  readonly GFX_difficulty_bar_7: SpriteRef & {
    readonly id: "GFX_difficulty_bar_7";
  };
  readonly GFX_frontend_bg: SpriteRef & {
    readonly id: "GFX_frontend_bg";
  };
  readonly GFX_galaxy_button_bar: SpriteRef & {
    readonly id: "GFX_galaxy_button_bar";
  };
  readonly GFX_galaxy_button_cartwheel: SpriteRef & {
    readonly id: "GFX_galaxy_button_cartwheel";
  };
  readonly GFX_galaxy_button_elliptical: SpriteRef & {
    readonly id: "GFX_galaxy_button_elliptical";
  };
  readonly GFX_galaxy_button_ring: SpriteRef & {
    readonly id: "GFX_galaxy_button_ring";
  };
  readonly GFX_galaxy_button_spiral_2: SpriteRef & {
    readonly id: "GFX_galaxy_button_spiral_2";
  };
  readonly GFX_galaxy_button_spiral_3: SpriteRef & {
    readonly id: "GFX_galaxy_button_spiral_3";
  };
  readonly GFX_galaxy_button_spiral_4: SpriteRef & {
    readonly id: "GFX_galaxy_button_spiral_4";
  };
  readonly GFX_galaxy_button_spiral_6: SpriteRef & {
    readonly id: "GFX_galaxy_button_spiral_6";
  };
  readonly GFX_galaxy_button_spoked: SpriteRef & {
    readonly id: "GFX_galaxy_button_spoked";
  };
  readonly GFX_galaxy_button_starburst: SpriteRef & {
    readonly id: "GFX_galaxy_button_starburst";
  };
  readonly GFX_galaxy_preview_bar: SpriteRef & {
    readonly id: "GFX_galaxy_preview_bar";
  };
  readonly GFX_galaxy_preview_cartwheel: SpriteRef & {
    readonly id: "GFX_galaxy_preview_cartwheel";
  };
  readonly GFX_galaxy_preview_elliptical: SpriteRef & {
    readonly id: "GFX_galaxy_preview_elliptical";
  };
  readonly GFX_galaxy_preview_ring: SpriteRef & {
    readonly id: "GFX_galaxy_preview_ring";
  };
  readonly GFX_galaxy_preview_spiral_2: SpriteRef & {
    readonly id: "GFX_galaxy_preview_spiral_2";
  };
  readonly GFX_galaxy_preview_spiral_3: SpriteRef & {
    readonly id: "GFX_galaxy_preview_spiral_3";
  };
  readonly GFX_galaxy_preview_spiral_4: SpriteRef & {
    readonly id: "GFX_galaxy_preview_spiral_4";
  };
  readonly GFX_galaxy_preview_spiral_6: SpriteRef & {
    readonly id: "GFX_galaxy_preview_spiral_6";
  };
  readonly GFX_galaxy_preview_spoked: SpriteRef & {
    readonly id: "GFX_galaxy_preview_spoked";
  };
  readonly GFX_galaxy_preview_starburst: SpriteRef & {
    readonly id: "GFX_galaxy_preview_starburst";
  };
  readonly GFX_galaxy_preview_stripes: SpriteRef & {
    readonly id: "GFX_galaxy_preview_stripes";
  };
  readonly GFX_precursor_adakkaria: SpriteRef & {
    readonly id: "GFX_precursor_adakkaria";
  };
  readonly GFX_precursor_baol: SpriteRef & {
    readonly id: "GFX_precursor_baol";
  };
  readonly GFX_precursor_button: SpriteRef & {
    readonly id: "GFX_precursor_button";
  };
  readonly GFX_precursor_cybrex: SpriteRef & {
    readonly id: "GFX_precursor_cybrex";
  };
  readonly GFX_precursor_first_league: SpriteRef & {
    readonly id: "GFX_precursor_first_league";
  };
  readonly GFX_precursor_inetian: SpriteRef & {
    readonly id: "GFX_precursor_inetian";
  };
  readonly GFX_precursor_irassian: SpriteRef & {
    readonly id: "GFX_precursor_irassian";
  };
  readonly GFX_precursor_vultaum: SpriteRef & {
    readonly id: "GFX_precursor_vultaum";
  };
  readonly GFX_precursor_yuth: SpriteRef & {
    readonly id: "GFX_precursor_yuth";
  };
  readonly GFX_precursor_zroni: SpriteRef & {
    readonly id: "GFX_precursor_zroni";
  };
  readonly GFX_random_ai_preview: SpriteRef & {
    readonly id: "GFX_random_ai_preview";
  };
  readonly GFX_random_player_preview: SpriteRef & {
    readonly id: "GFX_random_player_preview";
  };
  readonly GFX_tab_gamesetup: SpriteRef & {
    readonly id: "GFX_tab_gamesetup";
  };
  readonly GFX_tiles_dark_area_square_cut: SpriteRef & {
    readonly id: "GFX_tiles_dark_area_square_cut";
  };
};
