// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieStandardDialog = {
  readonly GFX_standard_dialog_bg: SpriteRef & {
    readonly id: "GFX_standard_dialog_bg";
  };
};
