// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

import type { SpriteRef } from "@pdx-ts/sdk/stellaris";

export type VanillaSpriteTypeTrieTraitsShared = {
  readonly GFX_trait_bg: SpriteRef & {
    readonly id: "GFX_trait_bg";
  };
  readonly GFX_trait_councilor: SpriteRef & {
    readonly id: "GFX_trait_councilor";
  };
  readonly GFX_trait_disabled: SpriteRef & {
    readonly id: "GFX_trait_disabled";
  };
  readonly GFX_trait_frame_destiny: SpriteRef & {
    readonly id: "GFX_trait_frame_destiny";
  };
  readonly GFX_trait_frame_veteran: SpriteRef & {
    readonly id: "GFX_trait_frame_veteran";
  };
  readonly GFX_trait_glow_destiny: SpriteRef & {
    readonly id: "GFX_trait_glow_destiny";
  };
  readonly GFX_trait_glow_veteran: SpriteRef & {
    readonly id: "GFX_trait_glow_veteran";
  };
  readonly GFX_trait_tier: SpriteRef & {
    readonly id: "GFX_trait_tier";
  };
  readonly GFX_trait_tier_1: SpriteRef & {
    readonly id: "GFX_trait_tier_1";
  };
  readonly GFX_trait_tier_2: SpriteRef & {
    readonly id: "GFX_trait_tier_2";
  };
  readonly GFX_trait_tier_3: SpriteRef & {
    readonly id: "GFX_trait_tier_3";
  };
  readonly GFX_trait_timed: SpriteRef & {
    readonly id: "GFX_trait_timed";
  };
};
