// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk";

export type VanillaSoundTrieBack = {
  readonly click: SoundRef & {
    readonly id: "back_click";
  };
};

export type VanillaSoundTrieBig = {
  readonly legs_swing_up_01: SoundRef & {
    readonly id: "big_legs_swing_up_01";
  };
  readonly legs_swoosh_down: SoundRef & {
    readonly id: "big_legs_swoosh_down";
  };
  readonly legs_swoosh_up: SoundRef & {
    readonly id: "big_legs_swoosh_up";
  };
  readonly legs_together: SoundRef & {
    readonly id: "big_legs_together";
  };
};

export type VanillaSoundTrieBiogenesis = {
  readonly portrait_01_f_01: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_01";
  };
  readonly portrait_01_f_02: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_02";
  };
  readonly portrait_01_f_03: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_03";
  };
  readonly portrait_01_f_04: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_04";
  };
  readonly portrait_01_f_05: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_05";
  };
  readonly portrait_01_f_06: SoundRef & {
    readonly id: "biogenesis_portrait_01_f_06";
  };
  readonly portrait_01_m_01: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_01";
  };
  readonly portrait_01_m_02: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_02";
  };
  readonly portrait_01_m_03: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_03";
  };
  readonly portrait_01_m_04: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_04";
  };
  readonly portrait_01_m_05: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_05";
  };
  readonly portrait_01_m_06: SoundRef & {
    readonly id: "biogenesis_portrait_01_m_06";
  };
  readonly portrait_02_01: SoundRef & {
    readonly id: "biogenesis_portrait_02_01";
  };
  readonly portrait_02_02: SoundRef & {
    readonly id: "biogenesis_portrait_02_02";
  };
  readonly portrait_02_03: SoundRef & {
    readonly id: "biogenesis_portrait_02_03";
  };
  readonly portrait_02_04: SoundRef & {
    readonly id: "biogenesis_portrait_02_04";
  };
  readonly portrait_02_05: SoundRef & {
    readonly id: "biogenesis_portrait_02_05";
  };
  readonly portrait_03_01: SoundRef & {
    readonly id: "biogenesis_portrait_03_01";
  };
  readonly portrait_03_02: SoundRef & {
    readonly id: "biogenesis_portrait_03_02";
  };
  readonly portrait_03_03: SoundRef & {
    readonly id: "biogenesis_portrait_03_03";
  };
  readonly portrait_03_04: SoundRef & {
    readonly id: "biogenesis_portrait_03_04";
  };
  readonly portrait_03_05: SoundRef & {
    readonly id: "biogenesis_portrait_03_05";
  };
  readonly portrait_04_01: SoundRef & {
    readonly id: "biogenesis_portrait_04_01";
  };
  readonly portrait_04_02: SoundRef & {
    readonly id: "biogenesis_portrait_04_02";
  };
  readonly portrait_04_03: SoundRef & {
    readonly id: "biogenesis_portrait_04_03";
  };
  readonly portrait_04_04: SoundRef & {
    readonly id: "biogenesis_portrait_04_04";
  };
  readonly portrait_04_05: SoundRef & {
    readonly id: "biogenesis_portrait_04_05";
  };
  readonly portrait_05_01: SoundRef & {
    readonly id: "biogenesis_portrait_05_01";
  };
  readonly portrait_05_02: SoundRef & {
    readonly id: "biogenesis_portrait_05_02";
  };
  readonly portrait_05_03: SoundRef & {
    readonly id: "biogenesis_portrait_05_03";
  };
  readonly portrait_05_04: SoundRef & {
    readonly id: "biogenesis_portrait_05_04";
  };
  readonly portrait_05_05: SoundRef & {
    readonly id: "biogenesis_portrait_05_05";
  };
  readonly portrait_06_01: SoundRef & {
    readonly id: "biogenesis_portrait_06_01";
  };
  readonly portrait_06_02: SoundRef & {
    readonly id: "biogenesis_portrait_06_02";
  };
  readonly portrait_06_03: SoundRef & {
    readonly id: "biogenesis_portrait_06_03";
  };
  readonly portrait_06_04: SoundRef & {
    readonly id: "biogenesis_portrait_06_04";
  };
  readonly portrait_06_05: SoundRef & {
    readonly id: "biogenesis_portrait_06_05";
  };
  readonly portrait_07_01: SoundRef & {
    readonly id: "biogenesis_portrait_07_01";
  };
  readonly portrait_07_02: SoundRef & {
    readonly id: "biogenesis_portrait_07_02";
  };
  readonly portrait_07_03: SoundRef & {
    readonly id: "biogenesis_portrait_07_03";
  };
  readonly portrait_07_04: SoundRef & {
    readonly id: "biogenesis_portrait_07_04";
  };
  readonly portrait_07_05: SoundRef & {
    readonly id: "biogenesis_portrait_07_05";
  };
  readonly portrait_08_01: SoundRef & {
    readonly id: "biogenesis_portrait_08_01";
  };
  readonly portrait_08_02: SoundRef & {
    readonly id: "biogenesis_portrait_08_02";
  };
  readonly portrait_08_03: SoundRef & {
    readonly id: "biogenesis_portrait_08_03";
  };
  readonly portrait_08_04: SoundRef & {
    readonly id: "biogenesis_portrait_08_04";
  };
  readonly portrait_08_05: SoundRef & {
    readonly id: "biogenesis_portrait_08_05";
  };
  readonly portrait_09_01: SoundRef & {
    readonly id: "biogenesis_portrait_09_01";
  };
  readonly portrait_09_02: SoundRef & {
    readonly id: "biogenesis_portrait_09_02";
  };
  readonly portrait_09_03: SoundRef & {
    readonly id: "biogenesis_portrait_09_03";
  };
  readonly portrait_09_04: SoundRef & {
    readonly id: "biogenesis_portrait_09_04";
  };
  readonly portrait_09_05: SoundRef & {
    readonly id: "biogenesis_portrait_09_05";
  };
  readonly portrait_10_01: SoundRef & {
    readonly id: "biogenesis_portrait_10_01";
  };
  readonly portrait_10_02: SoundRef & {
    readonly id: "biogenesis_portrait_10_02";
  };
  readonly portrait_10_03: SoundRef & {
    readonly id: "biogenesis_portrait_10_03";
  };
  readonly portrait_10_04: SoundRef & {
    readonly id: "biogenesis_portrait_10_04";
  };
  readonly portrait_10_05: SoundRef & {
    readonly id: "biogenesis_portrait_10_05";
  };
  readonly portrait_11_01: SoundRef & {
    readonly id: "biogenesis_portrait_11_01";
  };
  readonly portrait_11_02: SoundRef & {
    readonly id: "biogenesis_portrait_11_02";
  };
  readonly portrait_11_03: SoundRef & {
    readonly id: "biogenesis_portrait_11_03";
  };
  readonly portrait_11_04: SoundRef & {
    readonly id: "biogenesis_portrait_11_04";
  };
  readonly portrait_12_01: SoundRef & {
    readonly id: "biogenesis_portrait_12_01";
  };
  readonly portrait_12_02: SoundRef & {
    readonly id: "biogenesis_portrait_12_02";
  };
  readonly portrait_12_03: SoundRef & {
    readonly id: "biogenesis_portrait_12_03";
  };
  readonly portrait_12_04: SoundRef & {
    readonly id: "biogenesis_portrait_12_04";
  };
  readonly portrait_12_05: SoundRef & {
    readonly id: "biogenesis_portrait_12_05";
  };
};

export type VanillaSoundTrieBlack = {
  readonly hole_planet_01: SoundRef & {
    readonly id: "black_hole_planet_01";
  };
  readonly hole_planet_02: SoundRef & {
    readonly id: "black_hole_planet_02";
  };
};

export type VanillaSoundTrieBlackhole = {
  readonly hum_idle_01: SoundRef & {
    readonly id: "blackhole_hum_idle_01";
  };
};

export type VanillaSoundTrieBombardment = {
  readonly explosion_01: SoundRef & {
    readonly id: "bombardment_explosion_01";
  };
  readonly explosion_02: SoundRef & {
    readonly id: "bombardment_explosion_02";
  };
  readonly explosion_03: SoundRef & {
    readonly id: "bombardment_explosion_03";
  };
  readonly explosion_04: SoundRef & {
    readonly id: "bombardment_explosion_04";
  };
  readonly explosion_05: SoundRef & {
    readonly id: "bombardment_explosion_05";
  };
  readonly explosion_06: SoundRef & {
    readonly id: "bombardment_explosion_06";
  };
  readonly explosion_07: SoundRef & {
    readonly id: "bombardment_explosion_07";
  };
  readonly explosion_08: SoundRef & {
    readonly id: "bombardment_explosion_08";
  };
};

export type VanillaSoundTrieBot = {
  readonly ship_passby_01: SoundRef & {
    readonly id: "bot_ship_passby_01";
  };
  readonly ship_passby_02: SoundRef & {
    readonly id: "bot_ship_passby_02";
  };
  readonly ship_passby_03: SoundRef & {
    readonly id: "bot_ship_passby_03";
  };
  readonly ship_passby_04: SoundRef & {
    readonly id: "bot_ship_passby_04";
  };
  readonly ship_passby_05: SoundRef & {
    readonly id: "bot_ship_passby_05";
  };
  readonly ship_passby_06: SoundRef & {
    readonly id: "bot_ship_passby_06";
  };
};

export type VanillaSoundTrieBuilding = {
  readonly construction_complete_01: SoundRef & {
    readonly id: "building_construction_complete_01";
  };
};
