// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk";

export type VanillaSoundTrieS10 = {
  readonly portrait_01_01: SoundRef & {
    readonly id: "s10_portrait_01_01";
  };
  readonly portrait_01_02: SoundRef & {
    readonly id: "s10_portrait_01_02";
  };
  readonly portrait_01_03: SoundRef & {
    readonly id: "s10_portrait_01_03";
  };
  readonly portrait_01_04: SoundRef & {
    readonly id: "s10_portrait_01_04";
  };
  readonly portrait_01_05: SoundRef & {
    readonly id: "s10_portrait_01_05";
  };
};

export type VanillaSoundTrieSavannah = {
  readonly planet_01: SoundRef & {
    readonly id: "savannah_planet_01";
  };
  readonly planet_02: SoundRef & {
    readonly id: "savannah_planet_02";
  };
  readonly planet_03: SoundRef & {
    readonly id: "savannah_planet_03";
  };
};

export type VanillaSoundTrieScan = {
  readonly progress_loop_01: SoundRef & {
    readonly id: "scan_progress_loop_01";
  };
  readonly progress_loop_02: SoundRef & {
    readonly id: "scan_progress_loop_02";
  };
  readonly progress_loop_03: SoundRef & {
    readonly id: "scan_progress_loop_03";
  };
  readonly progress_loop_04: SoundRef & {
    readonly id: "scan_progress_loop_04";
  };
};

export type VanillaSoundTrieScience = {
  readonly arkship_idle_loop_01: SoundRef & {
    readonly id: "science_arkship_idle_loop_01";
  };
  readonly arkship_idle_loop_02: SoundRef & {
    readonly id: "science_arkship_idle_loop_02";
  };
  readonly arkship_idle_loop_03: SoundRef & {
    readonly id: "science_arkship_idle_loop_03";
  };
  readonly arkship_idle_loop_04: SoundRef & {
    readonly id: "science_arkship_idle_loop_04";
  };
  readonly arkship_move_01: SoundRef & {
    readonly id: "science_arkship_move_01";
  };
  readonly arkship_move_02: SoundRef & {
    readonly id: "science_arkship_move_02";
  };
  readonly arkship_move_03: SoundRef & {
    readonly id: "science_arkship_move_03";
  };
  readonly arkship_move_04: SoundRef & {
    readonly id: "science_arkship_move_04";
  };
};

export type VanillaSoundTrieSelect = {
  readonly click: SoundRef & {
    readonly id: "select_click";
  };
  readonly colony_ship01: SoundRef & {
    readonly id: "select_colony_ship01";
  };
  readonly construction_ship01: SoundRef & {
    readonly id: "select_construction_ship01";
  };
  readonly fleet01: SoundRef & {
    readonly id: "select_fleet01";
  };
  readonly mining_station: SoundRef & {
    readonly id: "select_mining_station";
  };
  readonly research_station: SoundRef & {
    readonly id: "select_research_station";
  };
  readonly science_ship01: SoundRef & {
    readonly id: "select_science_ship01";
  };
  readonly spacestation01: SoundRef & {
    readonly id: "select_spacestation01";
  };
  readonly starbase_01: SoundRef & {
    readonly id: "select_starbase_01";
  };
};

export type VanillaSoundTrieSet = {
  readonly war_goal_01: SoundRef & {
    readonly id: "set_war_goal_01";
  };
};

export type VanillaSoundTrieSfx = {
  readonly action_activation_astral_boost: SoundRef & {
    readonly id: "sfx_action_activation_astral_boost";
  };
  readonly action_activation_astral_hyperjump: SoundRef & {
    readonly id: "sfx_action_activation_astral_hyperjump";
  };
  readonly action_activation_astral_siphon: SoundRef & {
    readonly id: "sfx_action_activation_astral_siphon";
  };
  readonly action_activation_construct_lock: SoundRef & {
    readonly id: "sfx_action_activation_construct_lock";
  };
  readonly action_activation_phase_fleet: SoundRef & {
    readonly id: "sfx_action_activation_phase_fleet";
  };
  readonly action_activation_refresh_triumph: SoundRef & {
    readonly id: "sfx_action_activation_refresh_triumph";
  };
  readonly amb_celestial_storm_01: SoundRef & {
    readonly id: "sfx_amb_celestial_storm_01";
  };
  readonly amb_celestial_storm_02: SoundRef & {
    readonly id: "sfx_amb_celestial_storm_02";
  };
  readonly amb_consecrated_1_planet_01: SoundRef & {
    readonly id: "sfx_amb_consecrated_1_planet_01";
  };
  readonly amb_consecrated_2_planet_01: SoundRef & {
    readonly id: "sfx_amb_consecrated_2_planet_01";
  };
  readonly amb_consecrated_3_planet_01: SoundRef & {
    readonly id: "sfx_amb_consecrated_3_planet_01";
  };
  readonly amb_crisis_contingency_01: SoundRef & {
    readonly id: "sfx_amb_crisis_contingency_01";
  };
  readonly amb_crisis_extradimensional_01: SoundRef & {
    readonly id: "sfx_amb_crisis_extradimensional_01";
  };
  readonly amb_crisis_prethoryn_swarm_01: SoundRef & {
    readonly id: "sfx_amb_crisis_prethoryn_swarm_01";
  };
  readonly amb_electric_storm_01: SoundRef & {
    readonly id: "sfx_amb_electric_storm_01";
  };
  readonly amb_electric_storm_02: SoundRef & {
    readonly id: "sfx_amb_electric_storm_02";
  };
  readonly amb_gravity_storm_01: SoundRef & {
    readonly id: "sfx_amb_gravity_storm_01";
  };
  readonly amb_gravity_storm_02: SoundRef & {
    readonly id: "sfx_amb_gravity_storm_02";
  };
  readonly amb_magnetic_storm_01: SoundRef & {
    readonly id: "sfx_amb_magnetic_storm_01";
  };
  readonly amb_magnetic_storm_02: SoundRef & {
    readonly id: "sfx_amb_magnetic_storm_02";
  };
  readonly amb_nebula_turbulent_01: SoundRef & {
    readonly id: "sfx_amb_nebula_turbulent_01";
  };
  readonly amb_nexus_storm_01: SoundRef & {
    readonly id: "sfx_amb_nexus_storm_01";
  };
  readonly amb_nexus_storm_02: SoundRef & {
    readonly id: "sfx_amb_nexus_storm_02";
  };
  readonly amb_particle_storm_01: SoundRef & {
    readonly id: "sfx_amb_particle_storm_01";
  };
  readonly amb_particle_storm_02: SoundRef & {
    readonly id: "sfx_amb_particle_storm_02";
  };
  readonly amb_psi_storm_1_01: SoundRef & {
    readonly id: "sfx_amb_psi_storm_1_01";
  };
  readonly amb_shroud_storm_01: SoundRef & {
    readonly id: "sfx_amb_shroud_storm_01";
  };
  readonly amb_shroud_storm_02: SoundRef & {
    readonly id: "sfx_amb_shroud_storm_02";
  };
  readonly amb_solar_storm_01: SoundRef & {
    readonly id: "sfx_amb_solar_storm_01";
  };
  readonly amb_solar_storm_02: SoundRef & {
    readonly id: "sfx_amb_solar_storm_02";
  };
  readonly amb_space_storm_1_01: SoundRef & {
    readonly id: "sfx_amb_space_storm_1_01";
  };
  readonly amb_space_storm_2_01: SoundRef & {
    readonly id: "sfx_amb_space_storm_2_01";
  };
  readonly amb_vfx_thunderclap_01: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_01";
  };
  readonly amb_vfx_thunderclap_02: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_02";
  };
  readonly amb_vfx_thunderclap_03: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_03";
  };
  readonly amb_vfx_thunderclap_04: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_04";
  };
  readonly amb_vfx_thunderclap_05: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_05";
  };
  readonly amb_vfx_thunderclap_06: SoundRef & {
    readonly id: "sfx_amb_vfx_thunderclap_06";
  };
  readonly archeology_event_bad_omen_01: SoundRef & {
    readonly id: "sfx_archeology_event_bad_omen_01";
  };
  readonly archeology_event_bad_omen_02: SoundRef & {
    readonly id: "sfx_archeology_event_bad_omen_02";
  };
  readonly archeology_event_begin_expedition: SoundRef & {
    readonly id: "sfx_archeology_event_begin_expedition";
  };
  readonly archeology_event_big_door_opening_01: SoundRef & {
    readonly id: "sfx_archeology_event_big_door_opening_01";
  };
  readonly archeology_event_big_door_opening_02: SoundRef & {
    readonly id: "sfx_archeology_event_big_door_opening_02";
  };
  readonly archeology_event_collapsing_ruins_01: SoundRef & {
    readonly id: "sfx_archeology_event_collapsing_ruins_01";
  };
  readonly archeology_event_collapsing_ruins_02: SoundRef & {
    readonly id: "sfx_archeology_event_collapsing_ruins_02";
  };
  readonly archeology_event_dangerous_animals_01: SoundRef & {
    readonly id: "sfx_archeology_event_dangerous_animals_01";
  };
  readonly archeology_event_dangerous_animals_02: SoundRef & {
    readonly id: "sfx_archeology_event_dangerous_animals_02";
  };
  readonly archeology_event_dangerous_animals_03: SoundRef & {
    readonly id: "sfx_archeology_event_dangerous_animals_03";
  };
  readonly archeology_event_dig_site: SoundRef & {
    readonly id: "sfx_archeology_event_dig_site";
  };
  readonly archeology_event_door_opening_01: SoundRef & {
    readonly id: "sfx_archeology_event_door_opening_01";
  };
  readonly archeology_event_door_opening_02: SoundRef & {
    readonly id: "sfx_archeology_event_door_opening_02";
  };
  readonly archeology_event_door_opening_03: SoundRef & {
    readonly id: "sfx_archeology_event_door_opening_03";
  };
  readonly archeology_event_drilling_01: SoundRef & {
    readonly id: "sfx_archeology_event_drilling_01";
  };
  readonly archeology_event_energy_field_01: SoundRef & {
    readonly id: "sfx_archeology_event_energy_field_01";
  };
  readonly archeology_event_energy_field_02: SoundRef & {
    readonly id: "sfx_archeology_event_energy_field_02";
  };
  readonly archeology_event_energy_field_03: SoundRef & {
    readonly id: "sfx_archeology_event_energy_field_03";
  };
  readonly archeology_event_finding_loot_01: SoundRef & {
    readonly id: "sfx_archeology_event_finding_loot_01";
  };
  readonly archeology_event_finding_loot_02: SoundRef & {
    readonly id: "sfx_archeology_event_finding_loot_02";
  };
  readonly archeology_event_finding_loot_03: SoundRef & {
    readonly id: "sfx_archeology_event_finding_loot_03";
  };
  readonly archeology_event_machinery_01: SoundRef & {
    readonly id: "sfx_archeology_event_machinery_01";
  };
  readonly archeology_event_machinery_02: SoundRef & {
    readonly id: "sfx_archeology_event_machinery_02";
  };
  readonly archeology_event_metal_fatigue_01: SoundRef & {
    readonly id: "sfx_archeology_event_metal_fatigue_01";
  };
  readonly archeology_event_metal_fatigue_02: SoundRef & {
    readonly id: "sfx_archeology_event_metal_fatigue_02";
  };
  readonly archeology_event_metal_fatigue_03: SoundRef & {
    readonly id: "sfx_archeology_event_metal_fatigue_03";
  };
  readonly archeology_event_power_down_01: SoundRef & {
    readonly id: "sfx_archeology_event_power_down_01";
  };
  readonly archeology_event_power_down_02: SoundRef & {
    readonly id: "sfx_archeology_event_power_down_02";
  };
  readonly archeology_event_power_down_03: SoundRef & {
    readonly id: "sfx_archeology_event_power_down_03";
  };
  readonly archeology_event_screams_01: SoundRef & {
    readonly id: "sfx_archeology_event_screams_01";
  };
  readonly archeology_event_screams_02: SoundRef & {
    readonly id: "sfx_archeology_event_screams_02";
  };
  readonly archeology_event_trap_arrows_01: SoundRef & {
    readonly id: "sfx_archeology_event_trap_arrows_01";
  };
  readonly archeology_event_trap_arrows_02: SoundRef & {
    readonly id: "sfx_archeology_event_trap_arrows_02";
  };
  readonly archeology_event_trap_laser_01: SoundRef & {
    readonly id: "sfx_archeology_event_trap_laser_01";
  };
  readonly archeology_event_trap_laser_02: SoundRef & {
    readonly id: "sfx_archeology_event_trap_laser_02";
  };
  readonly archeology_event_trap_laser_03: SoundRef & {
    readonly id: "sfx_archeology_event_trap_laser_03";
  };
  readonly archeology_event_trap_spikes_01: SoundRef & {
    readonly id: "sfx_archeology_event_trap_spikes_01";
  };
  readonly archeology_event_trap_spikes_02: SoundRef & {
    readonly id: "sfx_archeology_event_trap_spikes_02";
  };
  readonly archeology_event_trap_spikes_03: SoundRef & {
    readonly id: "sfx_archeology_event_trap_spikes_03";
  };
  readonly archeology_event_whispering_01: SoundRef & {
    readonly id: "sfx_archeology_event_whispering_01";
  };
  readonly archeology_event_whispering_02: SoundRef & {
    readonly id: "sfx_archeology_event_whispering_02";
  };
  readonly archeology_event_whispering_03: SoundRef & {
    readonly id: "sfx_archeology_event_whispering_03";
  };
  readonly archeology_event_wind_ruins_01: SoundRef & {
    readonly id: "sfx_archeology_event_wind_ruins_01";
  };
  readonly archeology_event_wind_ruins_02: SoundRef & {
    readonly id: "sfx_archeology_event_wind_ruins_02";
  };
  readonly archeology_event_wind_ruins_03: SoundRef & {
    readonly id: "sfx_archeology_event_wind_ruins_03";
  };
  readonly archeology_log_entry_negative: SoundRef & {
    readonly id: "sfx_archeology_log_entry_negative";
  };
  readonly archeology_log_entry_neutral: SoundRef & {
    readonly id: "sfx_archeology_log_entry_neutral";
  };
  readonly archeology_log_entry_positive: SoundRef & {
    readonly id: "sfx_archeology_log_entry_positive";
  };
  readonly archeology_notifications_chapter_complete: SoundRef & {
    readonly id: "sfx_archeology_notifications_chapter_complete";
  };
  readonly archeology_notifications_new_dig_site: SoundRef & {
    readonly id: "sfx_archeology_notifications_new_dig_site";
  };
  readonly archeology_notifications_random_event: SoundRef & {
    readonly id: "sfx_archeology_notifications_random_event";
  };
  readonly bg_federation: SoundRef & {
    readonly id: "sfx_bg_federation";
  };
  readonly bg_galactic_community: SoundRef & {
    readonly id: "sfx_bg_galactic_community";
  };
  readonly bg_senate_floor: SoundRef & {
    readonly id: "sfx_bg_senate_floor";
  };
  readonly button_federation_centralization_vote: SoundRef & {
    readonly id: "sfx_button_federation_centralization_vote";
  };
  readonly button_senate_floor_propose_law: SoundRef & {
    readonly id: "sfx_button_senate_floor_propose_law";
  };
  readonly button_senate_floor_vote: SoundRef & {
    readonly id: "sfx_button_senate_floor_vote";
  };
  readonly caravaneer_cargo_ship_idle_01: SoundRef & {
    readonly id: "sfx_caravaneer_cargo_ship_idle_01";
  };
  readonly caravaneer_cruiser_idle_01: SoundRef & {
    readonly id: "sfx_caravaneer_cruiser_idle_01";
  };
  readonly caravaneer_destroyer_idle_01: SoundRef & {
    readonly id: "sfx_caravaneer_destroyer_idle_01";
  };
  readonly conclude_senate_session_01: SoundRef & {
    readonly id: "sfx_conclude_senate_session_01";
  };
  readonly elder_tiyanki_combat_idle: SoundRef & {
    readonly id: "sfx_elder_tiyanki_combat_idle";
  };
  readonly elder_tiyanki_combat_idle_vocal_01: SoundRef & {
    readonly id: "sfx_elder_tiyanki_combat_idle_vocal_01";
  };
  readonly elder_tiyanki_combat_idle_vocal_02: SoundRef & {
    readonly id: "sfx_elder_tiyanki_combat_idle_vocal_02";
  };
  readonly elder_tiyanki_combat_transition_moving: SoundRef & {
    readonly id: "sfx_elder_tiyanki_combat_transition_moving";
  };
  readonly elder_tiyanki_death: SoundRef & {
    readonly id: "sfx_elder_tiyanki_death";
  };
  readonly elder_tiyanki_idle: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle";
  };
  readonly elder_tiyanki_idle_vocal_01: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_01";
  };
  readonly elder_tiyanki_idle_vocal_02: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_02";
  };
  readonly elder_tiyanki_idle_vocal_03: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_03";
  };
  readonly elder_tiyanki_idle_vocal_04: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_04";
  };
  readonly elder_tiyanki_idle_vocal_05: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_05";
  };
  readonly elder_tiyanki_idle_vocal_06: SoundRef & {
    readonly id: "sfx_elder_tiyanki_idle_vocal_06";
  };
  readonly event_announcement: SoundRef & {
    readonly id: "sfx_event_announcement";
  };
  readonly event_assembly_fight: SoundRef & {
    readonly id: "sfx_event_assembly_fight";
  };
  readonly event_galactic_community: SoundRef & {
    readonly id: "sfx_event_galactic_community";
  };
  readonly event_vote: SoundRef & {
    readonly id: "sfx_event_vote";
  };
  readonly galactic_emperor_greeting_01: SoundRef & {
    readonly id: "sfx_galactic_emperor_greeting_01";
  };
  readonly galactic_emperor_greeting_02: SoundRef & {
    readonly id: "sfx_galactic_emperor_greeting_02";
  };
  readonly galactic_emperor_greeting_03: SoundRef & {
    readonly id: "sfx_galactic_emperor_greeting_03";
  };
  readonly humanoid_colossus_closing_01: SoundRef & {
    readonly id: "sfx_humanoid_colossus_closing_01";
  };
  readonly humanoid_colossus_opening_01: SoundRef & {
    readonly id: "sfx_humanoid_colossus_opening_01";
  };
  readonly interstellar_assembly_beats_01: SoundRef & {
    readonly id: "sfx_interstellar_assembly_beats_01";
  };
  readonly interstellar_assembly_hum_01: SoundRef & {
    readonly id: "sfx_interstellar_assembly_hum_01";
  };
  readonly interstellar_assembly_pulse_01: SoundRef & {
    readonly id: "sfx_interstellar_assembly_pulse_01";
  };
  readonly matter_decompressor_conveyor_01: SoundRef & {
    readonly id: "sfx_matter_decompressor_conveyor_01";
  };
  readonly matter_decompressor_distortion_01: SoundRef & {
    readonly id: "sfx_matter_decompressor_distortion_01";
  };
  readonly matter_decompressor_hum_01: SoundRef & {
    readonly id: "sfx_matter_decompressor_hum_01";
  };
  readonly matter_decompressor_hum_treble_01: SoundRef & {
    readonly id: "sfx_matter_decompressor_hum_treble_01";
  };
  readonly matter_decompressor_pulse_01: SoundRef & {
    readonly id: "sfx_matter_decompressor_pulse_01";
  };
  readonly mega_art_installation_energy_01: SoundRef & {
    readonly id: "sfx_mega_art_installation_energy_01";
  };
  readonly mega_art_installation_glitches_01: SoundRef & {
    readonly id: "sfx_mega_art_installation_glitches_01";
  };
  readonly mega_art_installation_hum_01: SoundRef & {
    readonly id: "sfx_mega_art_installation_hum_01";
  };
  readonly nemesis_battleship_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_battleship_moving_out_01";
  };
  readonly nemesis_battleship_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_battleship_moving_out_02";
  };
  readonly nemesis_battleship_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_battleship_moving_out_03";
  };
  readonly nemesis_colony_ship_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_colony_ship_moving_out_01";
  };
  readonly nemesis_colony_ship_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_colony_ship_moving_out_02";
  };
  readonly nemesis_colony_ship_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_colony_ship_moving_out_03";
  };
  readonly nemesis_colossus_closing_01: SoundRef & {
    readonly id: "sfx_nemesis_colossus_closing_01";
  };
  readonly nemesis_colossus_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_colossus_moving_out_01";
  };
  readonly nemesis_colossus_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_colossus_moving_out_02";
  };
  readonly nemesis_colossus_opening_01: SoundRef & {
    readonly id: "sfx_nemesis_colossus_opening_01";
  };
  readonly nemesis_construction_ship_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_construction_ship_moving_out_01";
  };
  readonly nemesis_construction_ship_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_construction_ship_moving_out_02";
  };
  readonly nemesis_construction_ship_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_construction_ship_moving_out_03";
  };
  readonly nemesis_corvette_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_corvette_moving_out_01";
  };
  readonly nemesis_corvette_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_corvette_moving_out_02";
  };
  readonly nemesis_corvette_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_corvette_moving_out_03";
  };
  readonly nemesis_cruiser_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_cruiser_moving_out_01";
  };
  readonly nemesis_cruiser_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_cruiser_moving_out_02";
  };
  readonly nemesis_cruiser_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_cruiser_moving_out_03";
  };
  readonly nemesis_destroyer_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_destroyer_moving_out_01";
  };
  readonly nemesis_destroyer_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_destroyer_moving_out_02";
  };
  readonly nemesis_destroyer_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_destroyer_moving_out_03";
  };
  readonly nemesis_juggernaut_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_juggernaut_moving_out_01";
  };
  readonly nemesis_juggernaut_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_juggernaut_moving_out_02";
  };
  readonly nemesis_research_station_lighteningSmall_01: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lighteningSmall_01";
  };
  readonly nemesis_research_station_lighteningSmall_02: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lighteningSmall_02";
  };
  readonly nemesis_research_station_lighteningSmall_03: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lighteningSmall_03";
  };
  readonly nemesis_research_station_lightening_01: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lightening_01";
  };
  readonly nemesis_research_station_lightening_02: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lightening_02";
  };
  readonly nemesis_research_station_lightening_03: SoundRef & {
    readonly id: "sfx_nemesis_research_station_lightening_03";
  };
  readonly nemesis_science_ship_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_science_ship_moving_out_01";
  };
  readonly nemesis_science_ship_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_science_ship_moving_out_02";
  };
  readonly nemesis_science_ship_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_science_ship_moving_out_03";
  };
  readonly nemesis_titan_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_titan_moving_out_01";
  };
  readonly nemesis_titan_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_titan_moving_out_02";
  };
  readonly nemesis_transport_ship_moving_out_01: SoundRef & {
    readonly id: "sfx_nemesis_transport_ship_moving_out_01";
  };
  readonly nemesis_transport_ship_moving_out_02: SoundRef & {
    readonly id: "sfx_nemesis_transport_ship_moving_out_02";
  };
  readonly nemesis_transport_ship_moving_out_03: SoundRef & {
    readonly id: "sfx_nemesis_transport_ship_moving_out_03";
  };
  readonly notification_alert_breach: SoundRef & {
    readonly id: "sfx_notification_alert_breach";
  };
  readonly notification_denounced: SoundRef & {
    readonly id: "sfx_notification_denounced";
  };
  readonly notification_galactic_focus: SoundRef & {
    readonly id: "sfx_notification_galactic_focus";
  };
  readonly notification_low_cohesion: SoundRef & {
    readonly id: "sfx_notification_low_cohesion";
  };
  readonly notification_player_level_up: SoundRef & {
    readonly id: "sfx_notification_player_level_up";
  };
  readonly notification_player_lose_xp: SoundRef & {
    readonly id: "sfx_notification_player_lose_xp";
  };
  readonly notification_resolution_defeated: SoundRef & {
    readonly id: "sfx_notification_resolution_defeated";
  };
  readonly notification_resolution_passed: SoundRef & {
    readonly id: "sfx_notification_resolution_passed";
  };
  readonly notification_resolution_vetoed: SoundRef & {
    readonly id: "sfx_notification_resolution_vetoed";
  };
  readonly precursor_event_baol_organism_animation: SoundRef & {
    readonly id: "sfx_precursor_event_baol_organism_animation";
  };
  readonly relic_activation_blade_of_the_huntress: SoundRef & {
    readonly id: "sfx_relic_activation_blade_of_the_huntress";
  };
  readonly relic_activation_celestial_tear: SoundRef & {
    readonly id: "sfx_relic_activation_celestial_tear";
  };
  readonly relic_activation_continuum: SoundRef & {
    readonly id: "sfx_relic_activation_continuum";
  };
  readonly relic_activation_cybrex_war_forge: SoundRef & {
    readonly id: "sfx_relic_activation_cybrex_war_forge";
  };
  readonly relic_activation_eternal_throne: SoundRef & {
    readonly id: "sfx_relic_activation_eternal_throne";
  };
  readonly relic_activation_ether_drake_trophy: SoundRef & {
    readonly id: "sfx_relic_activation_ether_drake_trophy";
  };
  readonly relic_activation_extradimensional_warlock: SoundRef & {
    readonly id: "sfx_relic_activation_extradimensional_warlock";
  };
  readonly relic_activation_generic: SoundRef & {
    readonly id: "sfx_relic_activation_generic";
  };
  readonly relic_activation_head_of_zarqlan: SoundRef & {
    readonly id: "sfx_relic_activation_head_of_zarqlan";
  };
  readonly relic_activation_intact_zro_soulstone: SoundRef & {
    readonly id: "sfx_relic_activation_intact_zro_soulstone";
  };
  readonly relic_activation_isolated_contingency_core: SoundRef & {
    readonly id: "sfx_relic_activation_isolated_contingency_core";
  };
  readonly relic_activation_javorian_pox_sample: SoundRef & {
    readonly id: "sfx_relic_activation_javorian_pox_sample";
  };
  readonly relic_activation_khans_throne: SoundRef & {
    readonly id: "sfx_relic_activation_khans_throne";
  };
  readonly relic_activation_miniature_galaxy: SoundRef & {
    readonly id: "sfx_relic_activation_miniature_galaxy";
  };
  readonly relic_activation_plasmic_core: SoundRef & {
    readonly id: "sfx_relic_activation_plasmic_core";
  };
  readonly relic_activation_prethoryn_blood_queen: SoundRef & {
    readonly id: "sfx_relic_activation_prethoryn_blood_queen";
  };
  readonly relic_activation_scales_of_the_worm: SoundRef & {
    readonly id: "sfx_relic_activation_scales_of_the_worm";
  };
  readonly relic_activation_spinning_top: SoundRef & {
    readonly id: "sfx_relic_activation_spinning_top";
  };
  readonly relic_activation_the_galatron: SoundRef & {
    readonly id: "sfx_relic_activation_the_galatron";
  };
  readonly relic_activation_the_last_baol: SoundRef & {
    readonly id: "sfx_relic_activation_the_last_baol";
  };
  readonly relic_activation_the_omnicodex: SoundRef & {
    readonly id: "sfx_relic_activation_the_omnicodex";
  };
  readonly relic_activation_the_rubricator: SoundRef & {
    readonly id: "sfx_relic_activation_the_rubricator";
  };
  readonly relic_activation_the_surveyor: SoundRef & {
    readonly id: "sfx_relic_activation_the_surveyor";
  };
  readonly relic_activation_vultaum_real_perforator: SoundRef & {
    readonly id: "sfx_relic_activation_vultaum_real_perforator";
  };
  readonly relic_activation_weather_manipulator: SoundRef & {
    readonly id: "sfx_relic_activation_weather_manipulator";
  };
  readonly relic_activation_yuht_cryo_core: SoundRef & {
    readonly id: "sfx_relic_activation_yuht_cryo_core";
  };
  readonly rift_algol_idle: SoundRef & {
    readonly id: "sfx_rift_algol_idle";
  };
  readonly rift_crystal_idle: SoundRef & {
    readonly id: "sfx_rift_crystal_idle";
  };
  readonly rift_idle: SoundRef & {
    readonly id: "sfx_rift_idle";
  };
  readonly rift_open: SoundRef & {
    readonly id: "sfx_rift_open";
  };
  readonly scavenger_bot_attack_main_weapon_muzzle: SoundRef & {
    readonly id: "sfx_scavenger_bot_attack_main_weapon_muzzle";
  };
  readonly scavenger_bot_attack_main_weapon_windup: SoundRef & {
    readonly id: "sfx_scavenger_bot_attack_main_weapon_windup";
  };
  readonly scavenger_bot_death: SoundRef & {
    readonly id: "sfx_scavenger_bot_death";
  };
  readonly scavenger_bot_idle: SoundRef & {
    readonly id: "sfx_scavenger_bot_idle";
  };
  readonly scavenger_bot_missile_01: SoundRef & {
    readonly id: "sfx_scavenger_bot_missile_01";
  };
  readonly scavenger_bot_missile_02: SoundRef & {
    readonly id: "sfx_scavenger_bot_missile_02";
  };
  readonly scavenger_bot_missile_03: SoundRef & {
    readonly id: "sfx_scavenger_bot_missile_03";
  };
  readonly scavenger_bot_missile_04: SoundRef & {
    readonly id: "sfx_scavenger_bot_missile_04";
  };
  readonly scavenger_bot_missile_05: SoundRef & {
    readonly id: "sfx_scavenger_bot_missile_05";
  };
  readonly scavenger_bot_move_loop: SoundRef & {
    readonly id: "sfx_scavenger_bot_move_loop";
  };
  readonly scavenger_bot_move_start: SoundRef & {
    readonly id: "sfx_scavenger_bot_move_start";
  };
  readonly scavenger_bot_work_loop: SoundRef & {
    readonly id: "sfx_scavenger_bot_work_loop";
  };
  readonly scavenger_bot_work_start: SoundRef & {
    readonly id: "sfx_scavenger_bot_work_start";
  };
  readonly star_eater_closing_01: SoundRef & {
    readonly id: "sfx_star_eater_closing_01";
  };
  readonly star_eater_moving_out_01: SoundRef & {
    readonly id: "sfx_star_eater_moving_out_01";
  };
  readonly star_eater_moving_out_02: SoundRef & {
    readonly id: "sfx_star_eater_moving_out_02";
  };
  readonly star_eater_opening_01: SoundRef & {
    readonly id: "sfx_star_eater_opening_01";
  };
  readonly star_eater_weapon_hit_01: SoundRef & {
    readonly id: "sfx_star_eater_weapon_hit_01";
  };
  readonly star_eater_weapon_hit_distance_01: SoundRef & {
    readonly id: "sfx_star_eater_weapon_hit_distance_01";
  };
  readonly star_eater_weapon_windup_starting_01: SoundRef & {
    readonly id: "sfx_star_eater_weapon_windup_starting_01";
  };
  readonly strategic_coordination_center_beeps_01: SoundRef & {
    readonly id: "sfx_strategic_coordination_center_beeps_01";
  };
  readonly strategic_coordination_center_hum_01: SoundRef & {
    readonly id: "sfx_strategic_coordination_center_hum_01";
  };
  readonly strategic_coordination_center_pulse_01: SoundRef & {
    readonly id: "sfx_strategic_coordination_center_pulse_01";
  };
  readonly system_reality_breach_spark_01: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_01";
  };
  readonly system_reality_breach_spark_02: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_02";
  };
  readonly system_reality_breach_spark_03: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_03";
  };
  readonly system_reality_breach_spark_04: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_04";
  };
  readonly system_reality_breach_spark_05: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_05";
  };
  readonly system_reality_breach_spark_06: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_06";
  };
  readonly system_reality_breach_spark_07: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_07";
  };
  readonly system_reality_breach_spark_08: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_08";
  };
  readonly system_reality_breach_spark_09: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_09";
  };
  readonly system_reality_breach_spark_10: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_10";
  };
  readonly system_reality_breach_spark_11: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_11";
  };
  readonly system_reality_breach_spark_12: SoundRef & {
    readonly id: "sfx_system_reality_breach_spark_12";
  };
  readonly voidspawn_death: SoundRef & {
    readonly id: "sfx_voidspawn_death";
  };
  readonly voidspawn_hatchling: SoundRef & {
    readonly id: "sfx_voidspawn_hatchling";
  };
  readonly voidspawn_idle: SoundRef & {
    readonly id: "sfx_voidspawn_idle";
  };
  readonly voidspawn_missile_01: SoundRef & {
    readonly id: "sfx_voidspawn_missile_01";
  };
  readonly voidspawn_missile_02: SoundRef & {
    readonly id: "sfx_voidspawn_missile_02";
  };
  readonly voidspawn_missile_03: SoundRef & {
    readonly id: "sfx_voidspawn_missile_03";
  };
  readonly voidspawn_missile_04: SoundRef & {
    readonly id: "sfx_voidspawn_missile_04";
  };
  readonly voidspawn_missile_05: SoundRef & {
    readonly id: "sfx_voidspawn_missile_05";
  };
  readonly voidspawn_moving_01: SoundRef & {
    readonly id: "sfx_voidspawn_moving_01";
  };
  readonly voidspawn_moving_02: SoundRef & {
    readonly id: "sfx_voidspawn_moving_02";
  };
  readonly world_hive_amb_loop: SoundRef & {
    readonly id: "sfx_world_hive_amb_loop";
  };
  readonly world_hivemind_show_planet_01: SoundRef & {
    readonly id: "sfx_world_hivemind_show_planet_01";
  };
  readonly world_hivemind_show_planet_02: SoundRef & {
    readonly id: "sfx_world_hivemind_show_planet_02";
  };
  readonly world_hivemind_show_planet_03: SoundRef & {
    readonly id: "sfx_world_hivemind_show_planet_03";
  };
  readonly world_machine_amb_loop: SoundRef & {
    readonly id: "sfx_world_machine_amb_loop";
  };
  readonly world_machine_show_planet_01: SoundRef & {
    readonly id: "sfx_world_machine_show_planet_01";
  };
  readonly world_machine_show_planet_02: SoundRef & {
    readonly id: "sfx_world_machine_show_planet_02";
  };
  readonly world_machine_show_planet_03: SoundRef & {
    readonly id: "sfx_world_machine_show_planet_03";
  };
  readonly world_relic_amb_loop: SoundRef & {
    readonly id: "sfx_world_relic_amb_loop";
  };
  readonly world_relic_show_planet_01: SoundRef & {
    readonly id: "sfx_world_relic_show_planet_01";
  };
  readonly world_relic_show_planet_02: SoundRef & {
    readonly id: "sfx_world_relic_show_planet_02";
  };
  readonly world_relic_show_planet_03: SoundRef & {
    readonly id: "sfx_world_relic_show_planet_03";
  };
};

export type VanillaSoundTrieShattered = {
  readonly planet_explosion_01: SoundRef & {
    readonly id: "shattered_planet_explosion_01";
  };
};

export type VanillaSoundTrieShield = {
  readonly effect_fade_01: SoundRef & {
    readonly id: "shield_effect_fade_01";
  };
  readonly effect_fade_02: SoundRef & {
    readonly id: "shield_effect_fade_02";
  };
  readonly effect_fade_03: SoundRef & {
    readonly id: "shield_effect_fade_03";
  };
  readonly effect_fade_04: SoundRef & {
    readonly id: "shield_effect_fade_04";
  };
  readonly effect_stop_01: SoundRef & {
    readonly id: "shield_effect_stop_01";
  };
  readonly effect_stop_02: SoundRef & {
    readonly id: "shield_effect_stop_02";
  };
  readonly effect_stop_03: SoundRef & {
    readonly id: "shield_effect_stop_03";
  };
  readonly effect_stop_04: SoundRef & {
    readonly id: "shield_effect_stop_04";
  };
  readonly hit_01: SoundRef & {
    readonly id: "shield_hit_01";
  };
  readonly hit_02: SoundRef & {
    readonly id: "shield_hit_02";
  };
  readonly hit_03: SoundRef & {
    readonly id: "shield_hit_03";
  };
  readonly hit_04: SoundRef & {
    readonly id: "shield_hit_04";
  };
  readonly hit_05: SoundRef & {
    readonly id: "shield_hit_05";
  };
  readonly hit_06: SoundRef & {
    readonly id: "shield_hit_06";
  };
};

export type VanillaSoundTrieShielded = {
  readonly planet_01: SoundRef & {
    readonly id: "shielded_planet_01";
  };
  readonly planet_02: SoundRef & {
    readonly id: "shielded_planet_02";
  };
};

export type VanillaSoundTrieShieled = {
  readonly fire_layer_01: SoundRef & {
    readonly id: "shieled_fire_layer_01";
  };
  readonly fire_layer_02: SoundRef & {
    readonly id: "shieled_fire_layer_02";
  };
  readonly fire_layer_03: SoundRef & {
    readonly id: "shieled_fire_layer_03";
  };
  readonly hit_layer_01: SoundRef & {
    readonly id: "shieled_hit_layer_01";
  };
  readonly hit_layer_02: SoundRef & {
    readonly id: "shieled_hit_layer_02";
  };
  readonly windup_layer_01: SoundRef & {
    readonly id: "shieled_windup_layer_01";
  };
  readonly windup_layer_02: SoundRef & {
    readonly id: "shieled_windup_layer_02";
  };
};

export type VanillaSoundTrieShip = {
  readonly designer_add_section_01: SoundRef & {
    readonly id: "ship_designer_add_section_01";
  };
  readonly designer_add_section_02: SoundRef & {
    readonly id: "ship_designer_add_section_02";
  };
  readonly designer_add_section_03: SoundRef & {
    readonly id: "ship_designer_add_section_03";
  };
  readonly designer_add_utility_01: SoundRef & {
    readonly id: "ship_designer_add_utility_01";
  };
  readonly designer_add_utility_02: SoundRef & {
    readonly id: "ship_designer_add_utility_02";
  };
  readonly designer_add_utility_03: SoundRef & {
    readonly id: "ship_designer_add_utility_03";
  };
  readonly designer_add_weapon_01: SoundRef & {
    readonly id: "ship_designer_add_weapon_01";
  };
  readonly designer_add_weapon_02: SoundRef & {
    readonly id: "ship_designer_add_weapon_02";
  };
  readonly designer_add_weapon_03: SoundRef & {
    readonly id: "ship_designer_add_weapon_03";
  };
  readonly destroyed_01: SoundRef & {
    readonly id: "ship_destroyed_01";
  };
  readonly destroyed_02: SoundRef & {
    readonly id: "ship_destroyed_02";
  };
  readonly destroyed_03: SoundRef & {
    readonly id: "ship_destroyed_03";
  };
  readonly destroyed_04: SoundRef & {
    readonly id: "ship_destroyed_04";
  };
  readonly destroyed_big_explosion_01: SoundRef & {
    readonly id: "ship_destroyed_big_explosion_01";
  };
  readonly engine_idle_01: SoundRef & {
    readonly id: "ship_engine_idle_01";
  };
  readonly explosion_01: SoundRef & {
    readonly id: "ship_explosion_01";
  };
  readonly explosion_02: SoundRef & {
    readonly id: "ship_explosion_02";
  };
  readonly explosion_03: SoundRef & {
    readonly id: "ship_explosion_03";
  };
  readonly explosion_large_01: SoundRef & {
    readonly id: "ship_explosion_large_01";
  };
  readonly explosion_lrg_01: SoundRef & {
    readonly id: "ship_explosion_lrg_01";
  };
  readonly explosion_lrg_02: SoundRef & {
    readonly id: "ship_explosion_lrg_02";
  };
  readonly explosion_lrg_03: SoundRef & {
    readonly id: "ship_explosion_lrg_03";
  };
  readonly explosion_lrg_04: SoundRef & {
    readonly id: "ship_explosion_lrg_04";
  };
  readonly explosion_med_01: SoundRef & {
    readonly id: "ship_explosion_med_01";
  };
  readonly explosion_med_02: SoundRef & {
    readonly id: "ship_explosion_med_02";
  };
  readonly explosion_med_03: SoundRef & {
    readonly id: "ship_explosion_med_03";
  };
  readonly explosion_sml_01: SoundRef & {
    readonly id: "ship_explosion_sml_01";
  };
  readonly explosion_sml_02: SoundRef & {
    readonly id: "ship_explosion_sml_02";
  };
  readonly explosion_sml_03: SoundRef & {
    readonly id: "ship_explosion_sml_03";
  };
  readonly explosion_sml_04: SoundRef & {
    readonly id: "ship_explosion_sml_04";
  };
  readonly explosion_xlrg_01: SoundRef & {
    readonly id: "ship_explosion_xlrg_01";
  };
  readonly explosion_xlrg_02: SoundRef & {
    readonly id: "ship_explosion_xlrg_02";
  };
  readonly explosion_xlrg_03: SoundRef & {
    readonly id: "ship_explosion_xlrg_03";
  };
  readonly explosion_xlrg_04: SoundRef & {
    readonly id: "ship_explosion_xlrg_04";
  };
  readonly explosion_xsml_01: SoundRef & {
    readonly id: "ship_explosion_xsml_01";
  };
  readonly explosion_xsml_02: SoundRef & {
    readonly id: "ship_explosion_xsml_02";
  };
  readonly explosion_xsml_03: SoundRef & {
    readonly id: "ship_explosion_xsml_03";
  };
  readonly explosion_xsml_04: SoundRef & {
    readonly id: "ship_explosion_xsml_04";
  };
  readonly explosion_xxlrg_01: SoundRef & {
    readonly id: "ship_explosion_xxlrg_01";
  };
  readonly explosion_xxlrg_02: SoundRef & {
    readonly id: "ship_explosion_xxlrg_02";
  };
  readonly explosion_xxlrg_03: SoundRef & {
    readonly id: "ship_explosion_xxlrg_03";
  };
  readonly explosion_xxlrg_04: SoundRef & {
    readonly id: "ship_explosion_xxlrg_04";
  };
  readonly explosion_xxsml_01: SoundRef & {
    readonly id: "ship_explosion_xxsml_01";
  };
  readonly explosion_xxsml_02: SoundRef & {
    readonly id: "ship_explosion_xxsml_02";
  };
  readonly explosion_xxsml_03: SoundRef & {
    readonly id: "ship_explosion_xxsml_03";
  };
  readonly explosion_xxsml_04: SoundRef & {
    readonly id: "ship_explosion_xxsml_04";
  };
  readonly hatch_open_01: SoundRef & {
    readonly id: "ship_hatch_open_01";
  };
  readonly hatch_open_02: SoundRef & {
    readonly id: "ship_hatch_open_02";
  };
  readonly hatch_open_03: SoundRef & {
    readonly id: "ship_hatch_open_03";
  };
  readonly hatch_open_04: SoundRef & {
    readonly id: "ship_hatch_open_04";
  };
};

export type VanillaSoundTrieShroud = {
  readonly creature_corrupted_layer_01: SoundRef & {
    readonly id: "shroud_creature_corrupted_layer_01";
  };
  readonly creature_death_01: SoundRef & {
    readonly id: "shroud_creature_death_01";
  };
  readonly creature_idle_01: SoundRef & {
    readonly id: "shroud_creature_idle_01";
  };
  readonly creature_idle_02: SoundRef & {
    readonly id: "shroud_creature_idle_02";
  };
  readonly eaten_planet_01: SoundRef & {
    readonly id: "shroud_eaten_planet_01";
  };
  readonly eaten_planet_02: SoundRef & {
    readonly id: "shroud_eaten_planet_02";
  };
  readonly eaten_planet_03: SoundRef & {
    readonly id: "shroud_eaten_planet_03";
  };
  readonly relic_core_of_the_reckoning: SoundRef & {
    readonly id: "shroud_relic_core_of_the_reckoning";
  };
  readonly relic_lost_patron: SoundRef & {
    readonly id: "shroud_relic_lost_patron";
  };
};

export type VanillaSoundTrieShrouded = {
  readonly planet_01: SoundRef & {
    readonly id: "shrouded_planet_01";
  };
  readonly planet_02: SoundRef & {
    readonly id: "shrouded_planet_02";
  };
};

export type VanillaSoundTrieSmall = {
  readonly leg_in_out_01: SoundRef & {
    readonly id: "small_leg_in_out_01";
  };
  readonly leg_in_out_02: SoundRef & {
    readonly id: "small_leg_in_out_02";
  };
  readonly leg_in_out_03: SoundRef & {
    readonly id: "small_leg_in_out_03";
  };
  readonly leg_in_out_04: SoundRef & {
    readonly id: "small_leg_in_out_04";
  };
  readonly leg_pouch_down_01: SoundRef & {
    readonly id: "small_leg_pouch_down_01";
  };
  readonly leg_pouch_suck_up: SoundRef & {
    readonly id: "small_leg_pouch_suck_up";
  };
  readonly leg_up_01: SoundRef & {
    readonly id: "small_leg_up_01";
  };
  readonly leg_up_02: SoundRef & {
    readonly id: "small_leg_up_02";
  };
  readonly legs_up: SoundRef & {
    readonly id: "small_legs_up";
  };
  readonly legs_up_down_01: SoundRef & {
    readonly id: "small_legs_up_down_01";
  };
  readonly legs_up_down_02: SoundRef & {
    readonly id: "small_legs_up_down_02";
  };
  readonly legs_up_down_03: SoundRef & {
    readonly id: "small_legs_up_down_03";
  };
  readonly legs_up_down_04: SoundRef & {
    readonly id: "small_legs_up_down_04";
  };
  readonly legs_up_down_05: SoundRef & {
    readonly id: "small_legs_up_down_05";
  };
  readonly legs_up_down_06: SoundRef & {
    readonly id: "small_legs_up_down_06";
  };
  readonly legs_up_down_07: SoundRef & {
    readonly id: "small_legs_up_down_07";
  };
  readonly legs_up_down_08: SoundRef & {
    readonly id: "small_legs_up_down_08";
  };
  readonly legs_up_down_09: SoundRef & {
    readonly id: "small_legs_up_down_09";
  };
  readonly legs_up_down_10: SoundRef & {
    readonly id: "small_legs_up_down_10";
  };
};

export type VanillaSoundTrieSpace = {
  readonly ambient04: SoundRef & {
    readonly id: "space_ambient04";
  };
  readonly ambient05: SoundRef & {
    readonly id: "space_ambient05";
  };
  readonly ambient06: SoundRef & {
    readonly id: "space_ambient06";
  };
  readonly ambient_01: SoundRef & {
    readonly id: "space_ambient_01";
  };
  readonly ambient_02: SoundRef & {
    readonly id: "space_ambient_02";
  };
  readonly ambient_03: SoundRef & {
    readonly id: "space_ambient_03";
  };
  readonly amoeba_death_01: SoundRef & {
    readonly id: "space_amoeba_death_01";
  };
  readonly amoeba_fire_01: SoundRef & {
    readonly id: "space_amoeba_fire_01";
  };
  readonly amoeba_hit_01: SoundRef & {
    readonly id: "space_amoeba_hit_01";
  };
  readonly amoeba_idle_01: SoundRef & {
    readonly id: "space_amoeba_idle_01";
  };
  readonly ark_idle_01: SoundRef & {
    readonly id: "space_ark_idle_01";
  };
  readonly cloud_attack_01: SoundRef & {
    readonly id: "space_cloud_attack_01";
  };
  readonly cloud_death_01: SoundRef & {
    readonly id: "space_cloud_death_01";
  };
  readonly cloud_idle_01: SoundRef & {
    readonly id: "space_cloud_idle_01";
  };
  readonly cloud_idle_02: SoundRef & {
    readonly id: "space_cloud_idle_02";
  };
  readonly cloud_idle_03: SoundRef & {
    readonly id: "space_cloud_idle_03";
  };
  readonly dragon_death_01: SoundRef & {
    readonly id: "space_dragon_death_01";
  };
  readonly dragon_idle_01: SoundRef & {
    readonly id: "space_dragon_idle_01";
  };
  readonly dragon_idle_02: SoundRef & {
    readonly id: "space_dragon_idle_02";
  };
  readonly dragon_idle_03: SoundRef & {
    readonly id: "space_dragon_idle_03";
  };
  readonly dragon_idle_04: SoundRef & {
    readonly id: "space_dragon_idle_04";
  };
  readonly dragon_moving_01: SoundRef & {
    readonly id: "space_dragon_moving_01";
  };
  readonly dragon_pulse_01: SoundRef & {
    readonly id: "space_dragon_pulse_01";
  };
  readonly dragon_pulse_02: SoundRef & {
    readonly id: "space_dragon_pulse_02";
  };
  readonly dragon_pulse_03: SoundRef & {
    readonly id: "space_dragon_pulse_03";
  };
  readonly dragon_pulse_04: SoundRef & {
    readonly id: "space_dragon_pulse_04";
  };
  readonly dragon_pulse_05: SoundRef & {
    readonly id: "space_dragon_pulse_05";
  };
  readonly dragon_pulse_06: SoundRef & {
    readonly id: "space_dragon_pulse_06";
  };
  readonly pirate_large_ship_01: SoundRef & {
    readonly id: "space_pirate_large_ship_01";
  };
  readonly pirate_large_ship_02: SoundRef & {
    readonly id: "space_pirate_large_ship_02";
  };
  readonly pirate_small_ship_01: SoundRef & {
    readonly id: "space_pirate_small_ship_01";
  };
  readonly pirate_small_ship_02: SoundRef & {
    readonly id: "space_pirate_small_ship_02";
  };
  readonly pirate_station_01: SoundRef & {
    readonly id: "space_pirate_station_01";
  };
  readonly whale_death_01: SoundRef & {
    readonly id: "space_whale_death_01";
  };
  readonly whale_fire_01: SoundRef & {
    readonly id: "space_whale_fire_01";
  };
  readonly whale_hit_01: SoundRef & {
    readonly id: "space_whale_hit_01";
  };
  readonly whale_idle_01: SoundRef & {
    readonly id: "space_whale_idle_01";
  };
};

export type VanillaSoundTrieSpaceport = {
  readonly amb_view: SoundRef & {
    readonly id: "spaceport_amb_view";
  };
  readonly build: SoundRef & {
    readonly id: "spaceport_build";
  };
  readonly complete_alert_01: SoundRef & {
    readonly id: "spaceport_complete_alert_01";
  };
  readonly hum_idle_01: SoundRef & {
    readonly id: "spaceport_hum_idle_01";
  };
};

export type VanillaSoundTrieSpark = {
  readonly electric_01: SoundRef & {
    readonly id: "spark_electric_01";
  };
  readonly electric_02: SoundRef & {
    readonly id: "spark_electric_02";
  };
  readonly electric_03: SoundRef & {
    readonly id: "spark_electric_03";
  };
  readonly electric_04: SoundRef & {
    readonly id: "spark_electric_04";
  };
  readonly electric_05: SoundRef & {
    readonly id: "spark_electric_05";
  };
  readonly electric_06: SoundRef & {
    readonly id: "spark_electric_06";
  };
  readonly electric_07: SoundRef & {
    readonly id: "spark_electric_07";
  };
  readonly electric_08: SoundRef & {
    readonly id: "spark_electric_08";
  };
  readonly electric_09: SoundRef & {
    readonly id: "spark_electric_09";
  };
};

export type VanillaSoundTrieSpiritualists = {
  readonly intro_holiness_01: SoundRef & {
    readonly id: "spiritualists_intro_holiness_01";
  };
};

export type VanillaSoundTrieSpy = {
  readonly orb_destroyed_01: SoundRef & {
    readonly id: "spy_orb_destroyed_01";
  };
  readonly orb_hum_01: SoundRef & {
    readonly id: "spy_orb_hum_01";
  };
  readonly orb_hum_02: SoundRef & {
    readonly id: "spy_orb_hum_02";
  };
  readonly orb_hum_03: SoundRef & {
    readonly id: "spy_orb_hum_03";
  };
  readonly orb_hum_04: SoundRef & {
    readonly id: "spy_orb_hum_04";
  };
};

export type VanillaSoundTrieStarbase = {
  readonly hum_layer_01: SoundRef & {
    readonly id: "starbase_hum_layer_01";
  };
  readonly hum_layer_02: SoundRef & {
    readonly id: "starbase_hum_layer_02";
  };
  readonly hum_layer_03: SoundRef & {
    readonly id: "starbase_hum_layer_03";
  };
};

export type VanillaSoundTrieStation = {
  readonly explosion_energy_01: SoundRef & {
    readonly id: "station_explosion_energy_01";
  };
  readonly explosion_large_01: SoundRef & {
    readonly id: "station_explosion_large_01";
  };
  readonly explosion_small_01: SoundRef & {
    readonly id: "station_explosion_small_01";
  };
  readonly explosion_small_02: SoundRef & {
    readonly id: "station_explosion_small_02";
  };
  readonly explosion_small_03: SoundRef & {
    readonly id: "station_explosion_small_03";
  };
  readonly explosion_small_04: SoundRef & {
    readonly id: "station_explosion_small_04";
  };
  readonly explosion_small_05: SoundRef & {
    readonly id: "station_explosion_small_05";
  };
};

export type VanillaSoundTrieStellar = {
  readonly ignition_star_effect_power_up_loop_01: SoundRef & {
    readonly id: "stellar_ignition_star_effect_power_up_loop_01";
  };
  readonly ignition_star_entity_loop_01: SoundRef & {
    readonly id: "stellar_ignition_star_entity_loop_01";
  };
  readonly ignition_star_entity_loop_02: SoundRef & {
    readonly id: "stellar_ignition_star_entity_loop_02";
  };
  readonly ignition_star_entity_loop_03: SoundRef & {
    readonly id: "stellar_ignition_star_entity_loop_03";
  };
  readonly ignition_star_entity_loop_04: SoundRef & {
    readonly id: "stellar_ignition_star_entity_loop_04";
  };
};

export type VanillaSoundTrieStellarite = {
  readonly attack_plasma_01: SoundRef & {
    readonly id: "stellarite_attack_plasma_01";
  };
  readonly attack_plasma_02: SoundRef & {
    readonly id: "stellarite_attack_plasma_02";
  };
  readonly attack_plasma_03: SoundRef & {
    readonly id: "stellarite_attack_plasma_03";
  };
  readonly attack_plasma_04: SoundRef & {
    readonly id: "stellarite_attack_plasma_04";
  };
  readonly attack_plasma_05: SoundRef & {
    readonly id: "stellarite_attack_plasma_05";
  };
};

export type VanillaSoundTrieStellarites = {
  readonly fire_beam_01: SoundRef & {
    readonly id: "stellarites_fire_beam_01";
  };
  readonly idle_breath_01: SoundRef & {
    readonly id: "stellarites_idle_breath_01";
  };
  readonly idle_breath_02: SoundRef & {
    readonly id: "stellarites_idle_breath_02";
  };
  readonly idle_breath_03: SoundRef & {
    readonly id: "stellarites_idle_breath_03";
  };
  readonly idle_death_01: SoundRef & {
    readonly id: "stellarites_idle_death_01";
  };
  readonly idle_drone_01: SoundRef & {
    readonly id: "stellarites_idle_drone_01";
  };
  readonly planet_heatup_01: SoundRef & {
    readonly id: "stellarites_planet_heatup_01";
  };
  readonly planet_heatup_02: SoundRef & {
    readonly id: "stellarites_planet_heatup_02";
  };
  readonly planet_heatup_03: SoundRef & {
    readonly id: "stellarites_planet_heatup_03";
  };
  readonly star_expand_01: SoundRef & {
    readonly id: "stellarites_star_expand_01";
  };
  readonly windup_beam_01: SoundRef & {
    readonly id: "stellarites_windup_beam_01";
  };
};

export type VanillaSoundTrieSurvey = {
  readonly complete: SoundRef & {
    readonly id: "survey_complete";
  };
  readonly progress_01: SoundRef & {
    readonly id: "survey_progress_01";
  };
};

export type VanillaSoundTrieSw = {
  readonly evn_blue_lava: SoundRef & {
    readonly id: "sw_evn_blue_lava";
  };
  readonly evn_bubbling_swamp: SoundRef & {
    readonly id: "sw_evn_bubbling_swamp";
  };
  readonly evn_creeping_coagulation: SoundRef & {
    readonly id: "sw_evn_creeping_coagulation";
  };
  readonly evn_darkmatter_aftermath: SoundRef & {
    readonly id: "sw_evn_darkmatter_aftermath";
  };
  readonly evn_darkmatter_eruption: SoundRef & {
    readonly id: "sw_evn_darkmatter_eruption";
  };
  readonly evn_eggs_hatching: SoundRef & {
    readonly id: "sw_evn_eggs_hatching";
  };
  readonly evn_falling_bodies: SoundRef & {
    readonly id: "sw_evn_falling_bodies";
  };
  readonly evn_ice_cracking: SoundRef & {
    readonly id: "sw_evn_ice_cracking";
  };
  readonly evn_magnetic_metal: SoundRef & {
    readonly id: "sw_evn_magnetic_metal";
  };
  readonly evn_mountain_forging: SoundRef & {
    readonly id: "sw_evn_mountain_forging";
  };
  readonly evn_nature_shock: SoundRef & {
    readonly id: "sw_evn_nature_shock";
  };
  readonly evn_shifting_sands: SoundRef & {
    readonly id: "sw_evn_shifting_sands";
  };
  readonly evn_sinister_slurping: SoundRef & {
    readonly id: "sw_evn_sinister_slurping";
  };
  readonly evn_small_explosions: SoundRef & {
    readonly id: "sw_evn_small_explosions";
  };
  readonly evn_thunderstorm: SoundRef & {
    readonly id: "sw_evn_thunderstorm";
  };
};

export type VanillaSoundTrieSwarm = {
  readonly big_station_idle_01: SoundRef & {
    readonly id: "swarm_big_station_idle_01";
  };
  readonly civilian_death_01: SoundRef & {
    readonly id: "swarm_civilian_death_01";
  };
  readonly civlian_ship_idle_01: SoundRef & {
    readonly id: "swarm_civlian_ship_idle_01";
  };
  readonly crisis_ambient_stage_01: SoundRef & {
    readonly id: "swarm_crisis_ambient_stage_01";
  };
  readonly crisis_ambient_stage_02: SoundRef & {
    readonly id: "swarm_crisis_ambient_stage_02";
  };
  readonly crisis_ambient_stage_03: SoundRef & {
    readonly id: "swarm_crisis_ambient_stage_03";
  };
  readonly crisis_ambient_stage_final_01: SoundRef & {
    readonly id: "swarm_crisis_ambient_stage_final_01";
  };
  readonly generic_idle_01: SoundRef & {
    readonly id: "swarm_generic_idle_01";
  };
  readonly generic_idle_02: SoundRef & {
    readonly id: "swarm_generic_idle_02";
  };
  readonly generic_idle_03: SoundRef & {
    readonly id: "swarm_generic_idle_03";
  };
  readonly generic_idle_04: SoundRef & {
    readonly id: "swarm_generic_idle_04";
  };
  readonly generic_idle_05: SoundRef & {
    readonly id: "swarm_generic_idle_05";
  };
  readonly generic_idle_06: SoundRef & {
    readonly id: "swarm_generic_idle_06";
  };
  readonly generic_idle_07: SoundRef & {
    readonly id: "swarm_generic_idle_07";
  };
  readonly large_warship_death_01: SoundRef & {
    readonly id: "swarm_large_warship_death_01";
  };
  readonly large_warship_idle_01: SoundRef & {
    readonly id: "swarm_large_warship_idle_01";
  };
  readonly queen_death_01: SoundRef & {
    readonly id: "swarm_queen_death_01";
  };
  readonly queen_idle_01_01: SoundRef & {
    readonly id: "swarm_queen_idle_01_01";
  };
  readonly queen_idle_02_01: SoundRef & {
    readonly id: "swarm_queen_idle_02_01";
  };
  readonly scroge_missile_fire_01: SoundRef & {
    readonly id: "swarm_scroge_missile_fire_01";
  };
  readonly scroge_missile_fire_02: SoundRef & {
    readonly id: "swarm_scroge_missile_fire_02";
  };
  readonly scroge_missile_fire_03: SoundRef & {
    readonly id: "swarm_scroge_missile_fire_03";
  };
  readonly scroge_missile_hit_01: SoundRef & {
    readonly id: "swarm_scroge_missile_hit_01";
  };
  readonly small_station_idle_01: SoundRef & {
    readonly id: "swarm_small_station_idle_01";
  };
  readonly small_warship_idle_01: SoundRef & {
    readonly id: "swarm_small_warship_idle_01";
  };
  readonly station_explosion_large_01: SoundRef & {
    readonly id: "swarm_station_explosion_large_01";
  };
  readonly station_explosion_small_01: SoundRef & {
    readonly id: "swarm_station_explosion_small_01";
  };
  readonly station_explosion_small_02: SoundRef & {
    readonly id: "swarm_station_explosion_small_02";
  };
  readonly station_explosion_small_03: SoundRef & {
    readonly id: "swarm_station_explosion_small_03";
  };
  readonly station_explosion_small_04: SoundRef & {
    readonly id: "swarm_station_explosion_small_04";
  };
  readonly station_explosion_small_05: SoundRef & {
    readonly id: "swarm_station_explosion_small_05";
  };
};

export type VanillaSoundTrieSwarmer = {
  readonly missile_fire_01: SoundRef & {
    readonly id: "swarmer_missile_fire_01";
  };
  readonly missile_fire_02: SoundRef & {
    readonly id: "swarmer_missile_fire_02";
  };
  readonly missile_fire_03: SoundRef & {
    readonly id: "swarmer_missile_fire_03";
  };
  readonly missile_hit_01: SoundRef & {
    readonly id: "swarmer_missile_hit_01";
  };
};

export type VanillaSoundTrieSyn = {
  readonly ship_battleship_idle_01: SoundRef & {
    readonly id: "syn_ship_battleship_idle_01";
  };
  readonly ship_battleship_idle_02: SoundRef & {
    readonly id: "syn_ship_battleship_idle_02";
  };
  readonly ship_battleship_idle_03: SoundRef & {
    readonly id: "syn_ship_battleship_idle_03";
  };
  readonly ship_battleship_move_01: SoundRef & {
    readonly id: "syn_ship_battleship_move_01";
  };
  readonly ship_battleship_move_02: SoundRef & {
    readonly id: "syn_ship_battleship_move_02";
  };
  readonly ship_battleship_move_03: SoundRef & {
    readonly id: "syn_ship_battleship_move_03";
  };
  readonly ship_colony_ship_idle_01: SoundRef & {
    readonly id: "syn_ship_colony_ship_idle_01";
  };
  readonly ship_colony_ship_idle_02: SoundRef & {
    readonly id: "syn_ship_colony_ship_idle_02";
  };
  readonly ship_colony_ship_idle_03: SoundRef & {
    readonly id: "syn_ship_colony_ship_idle_03";
  };
  readonly ship_colony_ship_move_01: SoundRef & {
    readonly id: "syn_ship_colony_ship_move_01";
  };
  readonly ship_colony_ship_move_02: SoundRef & {
    readonly id: "syn_ship_colony_ship_move_02";
  };
  readonly ship_colony_ship_move_03: SoundRef & {
    readonly id: "syn_ship_colony_ship_move_03";
  };
  readonly ship_colossus_closing_01: SoundRef & {
    readonly id: "syn_ship_colossus_closing_01";
  };
  readonly ship_colossus_closing_02: SoundRef & {
    readonly id: "syn_ship_colossus_closing_02";
  };
  readonly ship_colossus_closing_03: SoundRef & {
    readonly id: "syn_ship_colossus_closing_03";
  };
  readonly ship_colossus_idle_01: SoundRef & {
    readonly id: "syn_ship_colossus_idle_01";
  };
  readonly ship_colossus_idle_02: SoundRef & {
    readonly id: "syn_ship_colossus_idle_02";
  };
  readonly ship_colossus_idle_03: SoundRef & {
    readonly id: "syn_ship_colossus_idle_03";
  };
  readonly ship_colossus_move_01: SoundRef & {
    readonly id: "syn_ship_colossus_move_01";
  };
  readonly ship_colossus_move_02: SoundRef & {
    readonly id: "syn_ship_colossus_move_02";
  };
  readonly ship_colossus_move_03: SoundRef & {
    readonly id: "syn_ship_colossus_move_03";
  };
  readonly ship_colossus_open_01: SoundRef & {
    readonly id: "syn_ship_colossus_open_01";
  };
  readonly ship_colossus_open_02: SoundRef & {
    readonly id: "syn_ship_colossus_open_02";
  };
  readonly ship_colossus_open_03: SoundRef & {
    readonly id: "syn_ship_colossus_open_03";
  };
  readonly ship_construction_ship_idle_01: SoundRef & {
    readonly id: "syn_ship_construction_ship_idle_01";
  };
  readonly ship_construction_ship_idle_02: SoundRef & {
    readonly id: "syn_ship_construction_ship_idle_02";
  };
  readonly ship_construction_ship_idle_03: SoundRef & {
    readonly id: "syn_ship_construction_ship_idle_03";
  };
  readonly ship_construction_ship_move_01: SoundRef & {
    readonly id: "syn_ship_construction_ship_move_01";
  };
  readonly ship_construction_ship_move_02: SoundRef & {
    readonly id: "syn_ship_construction_ship_move_02";
  };
  readonly ship_construction_ship_move_03: SoundRef & {
    readonly id: "syn_ship_construction_ship_move_03";
  };
  readonly ship_corvette_idle_01: SoundRef & {
    readonly id: "syn_ship_corvette_idle_01";
  };
  readonly ship_corvette_idle_02: SoundRef & {
    readonly id: "syn_ship_corvette_idle_02";
  };
  readonly ship_corvette_idle_03: SoundRef & {
    readonly id: "syn_ship_corvette_idle_03";
  };
  readonly ship_corvette_move_01: SoundRef & {
    readonly id: "syn_ship_corvette_move_01";
  };
  readonly ship_corvette_move_02: SoundRef & {
    readonly id: "syn_ship_corvette_move_02";
  };
  readonly ship_corvette_move_03: SoundRef & {
    readonly id: "syn_ship_corvette_move_03";
  };
  readonly ship_cruiser_idle_01: SoundRef & {
    readonly id: "syn_ship_cruiser_idle_01";
  };
  readonly ship_cruiser_idle_02: SoundRef & {
    readonly id: "syn_ship_cruiser_idle_02";
  };
  readonly ship_cruiser_idle_03: SoundRef & {
    readonly id: "syn_ship_cruiser_idle_03";
  };
  readonly ship_cruiser_move_01: SoundRef & {
    readonly id: "syn_ship_cruiser_move_01";
  };
  readonly ship_cruiser_move_02: SoundRef & {
    readonly id: "syn_ship_cruiser_move_02";
  };
  readonly ship_cruiser_move_03: SoundRef & {
    readonly id: "syn_ship_cruiser_move_03";
  };
  readonly ship_destroyer_idle_01: SoundRef & {
    readonly id: "syn_ship_destroyer_idle_01";
  };
  readonly ship_destroyer_idle_02: SoundRef & {
    readonly id: "syn_ship_destroyer_idle_02";
  };
  readonly ship_destroyer_idle_03: SoundRef & {
    readonly id: "syn_ship_destroyer_idle_03";
  };
  readonly ship_destroyer_move_01: SoundRef & {
    readonly id: "syn_ship_destroyer_move_01";
  };
  readonly ship_destroyer_move_02: SoundRef & {
    readonly id: "syn_ship_destroyer_move_02";
  };
  readonly ship_destroyer_move_03: SoundRef & {
    readonly id: "syn_ship_destroyer_move_03";
  };
  readonly ship_habitat_idle_01: SoundRef & {
    readonly id: "syn_ship_habitat_idle_01";
  };
  readonly ship_habitat_idle_02: SoundRef & {
    readonly id: "syn_ship_habitat_idle_02";
  };
  readonly ship_habitat_idle_03: SoundRef & {
    readonly id: "syn_ship_habitat_idle_03";
  };
  readonly ship_juggernaut_idle_01: SoundRef & {
    readonly id: "syn_ship_juggernaut_idle_01";
  };
  readonly ship_juggernaut_idle_02: SoundRef & {
    readonly id: "syn_ship_juggernaut_idle_02";
  };
  readonly ship_juggernaut_idle_03: SoundRef & {
    readonly id: "syn_ship_juggernaut_idle_03";
  };
  readonly ship_juggernaut_move_01: SoundRef & {
    readonly id: "syn_ship_juggernaut_move_01";
  };
  readonly ship_juggernaut_move_02: SoundRef & {
    readonly id: "syn_ship_juggernaut_move_02";
  };
  readonly ship_juggernaut_move_03: SoundRef & {
    readonly id: "syn_ship_juggernaut_move_03";
  };
  readonly ship_science_ship_idle_01: SoundRef & {
    readonly id: "syn_ship_science_ship_idle_01";
  };
  readonly ship_science_ship_idle_02: SoundRef & {
    readonly id: "syn_ship_science_ship_idle_02";
  };
  readonly ship_science_ship_idle_03: SoundRef & {
    readonly id: "syn_ship_science_ship_idle_03";
  };
  readonly ship_science_ship_move_01: SoundRef & {
    readonly id: "syn_ship_science_ship_move_01";
  };
  readonly ship_science_ship_move_02: SoundRef & {
    readonly id: "syn_ship_science_ship_move_02";
  };
  readonly ship_science_ship_move_03: SoundRef & {
    readonly id: "syn_ship_science_ship_move_03";
  };
  readonly ship_starbase_idle_01: SoundRef & {
    readonly id: "syn_ship_starbase_idle_01";
  };
  readonly ship_starbase_idle_02: SoundRef & {
    readonly id: "syn_ship_starbase_idle_02";
  };
  readonly ship_starbase_idle_03: SoundRef & {
    readonly id: "syn_ship_starbase_idle_03";
  };
  readonly ship_titan_idle_01: SoundRef & {
    readonly id: "syn_ship_titan_idle_01";
  };
  readonly ship_titan_idle_02: SoundRef & {
    readonly id: "syn_ship_titan_idle_02";
  };
  readonly ship_titan_idle_03: SoundRef & {
    readonly id: "syn_ship_titan_idle_03";
  };
  readonly ship_titan_move_01: SoundRef & {
    readonly id: "syn_ship_titan_move_01";
  };
  readonly ship_titan_move_02: SoundRef & {
    readonly id: "syn_ship_titan_move_02";
  };
  readonly ship_titan_move_03: SoundRef & {
    readonly id: "syn_ship_titan_move_03";
  };
  readonly ship_transport_ship_idle_01: SoundRef & {
    readonly id: "syn_ship_transport_ship_idle_01";
  };
  readonly ship_transport_ship_idle_02: SoundRef & {
    readonly id: "syn_ship_transport_ship_idle_02";
  };
  readonly ship_transport_ship_idle_03: SoundRef & {
    readonly id: "syn_ship_transport_ship_idle_03";
  };
  readonly ship_transport_ship_move_01: SoundRef & {
    readonly id: "syn_ship_transport_ship_move_01";
  };
  readonly ship_transport_ship_move_02: SoundRef & {
    readonly id: "syn_ship_transport_ship_move_02";
  };
  readonly ship_transport_ship_move_03: SoundRef & {
    readonly id: "syn_ship_transport_ship_move_03";
  };
};

export type VanillaSoundTrieSynthqueen = {
  readonly ship_battleship_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_battleship_idle_01";
  };
  readonly ship_battleship_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_battleship_idle_02";
  };
  readonly ship_battleship_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_battleship_idle_03";
  };
  readonly ship_battleship_move_01: SoundRef & {
    readonly id: "synthqueen_ship_battleship_move_01";
  };
  readonly ship_battleship_move_02: SoundRef & {
    readonly id: "synthqueen_ship_battleship_move_02";
  };
  readonly ship_battleship_move_03: SoundRef & {
    readonly id: "synthqueen_ship_battleship_move_03";
  };
  readonly ship_colossus_closing_01: SoundRef & {
    readonly id: "synthqueen_ship_colossus_closing_01";
  };
  readonly ship_colossus_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_colossus_idle_01";
  };
  readonly ship_colossus_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_colossus_idle_02";
  };
  readonly ship_colossus_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_colossus_idle_03";
  };
  readonly ship_colossus_move_01: SoundRef & {
    readonly id: "synthqueen_ship_colossus_move_01";
  };
  readonly ship_colossus_move_02: SoundRef & {
    readonly id: "synthqueen_ship_colossus_move_02";
  };
  readonly ship_colossus_move_03: SoundRef & {
    readonly id: "synthqueen_ship_colossus_move_03";
  };
  readonly ship_colossus_open_01: SoundRef & {
    readonly id: "synthqueen_ship_colossus_open_01";
  };
  readonly ship_juggernaut_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_idle_01";
  };
  readonly ship_juggernaut_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_idle_02";
  };
  readonly ship_juggernaut_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_idle_03";
  };
  readonly ship_juggernaut_move_01: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_move_01";
  };
  readonly ship_juggernaut_move_02: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_move_02";
  };
  readonly ship_juggernaut_move_03: SoundRef & {
    readonly id: "synthqueen_ship_juggernaut_move_03";
  };
  readonly ship_small_ship_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_idle_01";
  };
  readonly ship_small_ship_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_idle_02";
  };
  readonly ship_small_ship_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_idle_03";
  };
  readonly ship_small_ship_move_01: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_move_01";
  };
  readonly ship_small_ship_move_02: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_move_02";
  };
  readonly ship_small_ship_move_03: SoundRef & {
    readonly id: "synthqueen_ship_small_ship_move_03";
  };
  readonly ship_small_starbase_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_small_starbase_idle_01";
  };
  readonly ship_small_starbase_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_small_starbase_idle_02";
  };
  readonly ship_small_starbase_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_small_starbase_idle_03";
  };
  readonly ship_starbase_idle_01: SoundRef & {
    readonly id: "synthqueen_ship_starbase_idle_01";
  };
  readonly ship_starbase_idle_02: SoundRef & {
    readonly id: "synthqueen_ship_starbase_idle_02";
  };
  readonly ship_starbase_idle_03: SoundRef & {
    readonly id: "synthqueen_ship_starbase_idle_03";
  };
};
