// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundRef } from "@pdx-ts/sdk";

export type VanillaSoundTrieZoom = {
  readonly amb_planet_class_02: SoundRef & {
    readonly id: "zoom_amb_planet_class_02";
  };
};
