/**
 * Regenerates `src/generated/` from the vendored cwtools config.
 *
 * Run with `npm run codegen`. The output is committed, so a rules bump shows up
 * as a reviewable diff on the SDK's public API.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";

import { CONTENT_MANIFEST, type ContentManifestEntry } from "./content-manifest.ts";
import { loadRules, scopeIndex, type ContentType } from "./cwt/rules.ts";
import { emitAliasStruct, type AliasStructEmission } from "./emit/alias-struct.ts";
import { emitContentType, type ContentEmission } from "./emit/content-type.ts";
import { emitEffects } from "./emit/effects.ts";
import { emitEvents } from "./emit/events.ts";
import { classifyLinks, emitTriggerLinks } from "./emit/links.ts";
import { emitModifiers, joinModifierScopes } from "./emit/modifiers.ts";
import { emitOnActions } from "./emit/on-actions.ts";
import type { SkippedRule } from "./emit/shape.ts";
import {
  canonicalScopes,
  emitEnums,
  emitRefs,
  emitScopes,
  emitValueSets,
  valuelessEnums,
} from "./emit/support.ts";
import { emitTriggers } from "./emit/triggers.ts";
import { Emitter, type Usage } from "./emit/types.ts";
import { parseModifierDocs } from "./logs/modifier-docs.ts";
import { parseScopeLinks } from "./logs/scopes.ts";
import { parseTriggerDocs } from "./logs/trigger-docs.ts";
import { camelCase, docComment, indefiniteArticle, pascalCase } from "./naming.ts";
import {
  CONTENT_CONTRIBUTION_SINKS,
  CONTENT_FIELD_OVERRIDES,
  CONTENT_PATCH_REGISTRIES,
  HAND_WRITTEN_CONTENT_DEFINERS,
  REPEATED_STRUCT_FIELD_OVERRIDES,
} from "./overlay.ts";
import { compareToBaseline, reconcile, type DriftReport } from "./reconcile.ts";

const VENDOR = "vendor/cwtools-stellaris-config";
const CONFIG = `${VENDOR}/config`;
/** The dump directory matching the game version these rules target. */
const DOCS = `${VENDOR}/script-docs/v4.4.1`;
const OUT = "src/generated";
const BASELINE = "tools/codegen/drift-baseline.json";

function upstreamCommit(): string {
  const version = readFileSync(`${VENDOR}/VERSION.md`, "utf8");
  return /`([0-9a-f]{40})`/.exec(version)?.[1] ?? "unknown";
}

function header(commit: string, sources: readonly string[]): string {
  return (
    "// Generated by tools/codegen. Do not edit.\n" +
    `// Source: cwtools-stellaris-config @ ${commit.slice(0, 12)}\n` +
    sources.map((source) => `// From: ${source}\n`).join("") +
    "\n"
  );
}

/**
 * Written through Prettier so the committed output matches the repo's style and
 * the pre-commit hook has nothing left to reformat — otherwise `lint-staged`
 * would rewrite these files and `codegen:check` would report a false diff.
 */
async function write(file: string, contents: string): Promise<void> {
  const target = path.join(OUT, file);
  const options = await resolveConfig(target);
  mkdirSync(OUT, { recursive: true });
  writeFileSync(target, await format(contents, { ...options, filepath: target }), "utf8");
}

function reportSection(title: string, lines: readonly string[]): void {
  if (lines.length === 0) {
    return;
  }
  console.log(`\n${title} (${lines.length}):`);
  for (const line of lines) {
    console.log(`  ${line}`);
  }
}

function checkDrift(report: DriftReport, rebaseline: boolean): void {
  if (rebaseline) {
    writeFileSync(BASELINE, `${JSON.stringify(report, null, 2)}\n`, "utf8");
    console.log(`Rebaselined drift: ${BASELINE}`);
    return;
  }
  // A baseline written before a join existed reads as that join being empty,
  // so adding a join reports its entire current state as drift to review
  // instead of crashing on the missing field.
  const baseline = {
    links: { rulesOnly: [], docsOnly: [] },
    ...(JSON.parse(readFileSync(BASELINE, "utf8")) as Partial<DriftReport>),
  } as DriftReport;
  const differences = compareToBaseline(report, baseline);
  if (differences.length === 0) {
    return;
  }
  console.error("\nThe two rule sources drifted since the recorded baseline:\n");
  console.error(differences.join("\n"));
  console.error(
    "\nEach line is a trigger, effect, or annotation that exists in one source and not\n" +
      "the other, which means codegen would emit a wrong signature or silently skip it.\n" +
      "Review the change, then re-run with --rebaseline to accept it."
  );
  process.exit(1);
}

async function main(): Promise<void> {
  const rebaseline = process.argv.includes("--rebaseline");
  const commit = upstreamCommit();

  const rules = loadRules(CONFIG);
  const docs = parseTriggerDocs(
    readFileSync(`${DOCS}/triggers.log`, "utf8"),
    readFileSync(`${DOCS}/effects.log`, "utf8")
  );
  const links = parseScopeLinks(readFileSync(`${DOCS}/scopes.log`, "utf8"));
  const modifierDocs = parseModifierDocs(readFileSync(`${DOCS}/modifiers.log`, "utf8"));

  checkDrift(reconcile(rules, docs, modifierDocs, links), rebaseline);

  const emitter = new Emitter(rules);
  const index = scopeIndex(rules);
  emitter.beginFile();
  const triggers = emitTriggers(emitter, docs.triggers, index);
  const triggerUsage = emitter.endFile();

  const dumpLinks = new Map(links.map((link) => [link.name, link]));
  const classifiedLinks = classifyLinks(emitter, dumpLinks, index);
  // The hand exports of src/triggers.ts share the links file's export
  // namespace through its `export *`, so they count as taken names too.
  const triggerLinks = emitTriggerLinks(
    classifiedLinks,
    index,
    new Set([...triggers.names, "trigger", "and", "or", "not", "nand", "nor", "target"])
  );

  emitter.beginFile();
  const effects = emitEffects(emitter, docs.effects, index, classifiedLinks.links);
  const effectUsage = emitter.endFile();

  // Categories a content field lowers onto via `shape: "aliasStruct"` each need
  // their own shared `<Name>Block` module — `government_trigger` is the first,
  // via `civic_or_origin.potential`/`possible`. Collected from the overlay
  // rather than hardcoded so a future aliasStruct consumer picks this up for
  // free.
  const aliasStructCategories = [
    ...CONTENT_FIELD_OVERRIDES.values(),
    ...REPEATED_STRUCT_FIELD_OVERRIDES.values(),
  ]
    .filter((override) => override.shape === "aliasStruct")
    .map((override) => override.category!)
    .filter((category, index, categories) => categories.indexOf(category) === index);
  const aliasStructs = new Map<string, AliasStructEmission & { usage: Usage }>();
  for (const category of aliasStructCategories) {
    const members = rules.aliasCategories.get(category);
    if (members === undefined || members.size === 0) {
      throw new Error(
        `overlay requests aliasStruct category "${category}" but the rules declare no ` +
          `alias[${category}:...] members — add it to EXTRA_ALIAS_CATEGORIES`
      );
    }
    emitter.beginFile();
    const emission = emitAliasStruct(emitter, category, members);
    const usage = emitter.endFile();
    aliasStructs.set(category, { ...emission, usage });
  }

  const contents: Array<{
    manifest: (typeof CONTENT_MANIFEST)[number];
    /** Registry name: the CWT type unless the manifest renames it via `as`. */
    registry: string;
    /** Top-level keyword, for registries CWT marks with `name_field`. */
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
    usage: ReturnType<Emitter["endFile"]>;
  }> = [];
  for (const manifest of CONTENT_MANIFEST) {
    const type = rules.contentTypes.get(manifest.type);
    const body = rules.bodies.get(manifest.type);
    if (type === undefined || body === undefined) {
      throw new Error(`${manifest.source} no longer declares type[${manifest.type}] and its body`);
    }
    const entry: ContentManifestEntry = manifest;
    const registry = entry.as ?? entry.type;
    const keyword = entry.keyword;
    // A keyword the rules do declare must match what the manifest claims;
    // silence here would emit a top-level key the game quietly ignores.
    if (keyword !== undefined && type.nameField === null) {
      throw new Error(`type[${manifest.type}] declares no name_field, so it has no keyword`);
    }
    if (keyword === undefined && type.nameField !== null) {
      throw new Error(
        `type[${manifest.type}] declares name_field=${type.nameField}, so the manifest ` +
          "entry needs the keyword its entries are written under"
      );
    }
    if (type.keyFilter !== null && keyword !== undefined && keyword !== type.keyFilter) {
      throw new Error(
        `type[${manifest.type}] declares ## type_key_filter = ${type.keyFilter} but the ` +
          `manifest claims keyword ${keyword}`
      );
    }
    emitter.beginFile();
    const emission = emitContentType(emitter, type, body, registry);
    const usage = emitter.endFile();
    contents.push({ manifest, registry, keyword, type, emission, usage });
  }

  await write(
    "scopes.ts",
    header(commit, ["scopes.cwt"]) + emitScopes(canonicalScopes(rules.scopes))
  );
  await write(
    "refs.ts",
    header(commit, ["type references across the rule files"]) + emitRefs(emitter)
  );
  await write("enums.ts", header(commit, ["enums.cwt"]) + emitEnums(emitter));
  await write(
    "value-sets.ts",
    header(commit, ["value sets referenced across the rule files"]) + emitValueSets(emitter)
  );
  const modifiers = emitModifiers(
    joinModifierScopes(rules, modifierDocs, (token) => emitter.canonicalScope(token))
  );
  await write(
    "modifiers.ts",
    header(commit, ["script-docs/v4.4.1/modifiers.log", "modifier_categories.cwt"]) +
      'import type { CustomModifiers } from "../content.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      modifiers.code
  );
  for (const [category, emission] of aliasStructs) {
    await write(
      `${category.replaceAll("_", "-")}.ts`,
      header(commit, [`alias[${category}:...] across the rule files`]) +
        'import { registerAliasStructFields, type ContentField } from "../content.ts";\n' +
        importList(
          "./enums.ts",
          emission.usage.enums.map((name) => emitter.enumTypeName(name))
        ) +
        importList(
          "./refs.ts",
          emission.usage.refs.map((name) => emitter.refTypeName(name))
        ) +
        importList(
          "./value-sets.ts",
          emission.usage.valueSets.map((name) => emitter.valueSetTypeName(name))
        ) +
        "\n" +
        emission.code
    );
  }
  for (const content of contents) {
    const runtimeTypes = [
      "ContentField",
      "ContentLocalisation",
      "DefinedContent",
      "EconomicResourceBlock",
      "EffectBlock",
      "ModifierBlock",
      "ModifierClosure",
      "TriggeredModifier",
      "WeightBlock",
      "WeightBlockWithLoc",
    ].filter((name) => content.emission.code.includes(name));
    // A field lowered through `shape: "aliasStruct"` (see civic_or_origin's
    // potential/possible) references a shared `<Name>Block` type generated
    // into its own category file. The type import alone would be erased at
    // build time, so a bare side-effect import guarantees the category's
    // `registerAliasStructFields` call actually runs before this registry's
    // definitions are ever serialized.
    const aliasStructImports = [...aliasStructs]
      .filter(([, aliasEmission]) => content.emission.code.includes(aliasEmission.typeName))
      .map(([category, aliasEmission]) => {
        const file = `./${category.replaceAll("_", "-")}.ts`;
        return (
          `import type { ${aliasEmission.typeName} } from ${JSON.stringify(file)};\n` +
          `import ${JSON.stringify(file)};\n`
        );
      })
      .join("");
    await write(
      `${content.registry.replaceAll("_", "-")}.ts`,
      header(commit, [content.manifest.source]) +
        importList("../content.ts", runtimeTypes) +
        (content.emission.code.includes("Trigger<")
          ? 'import type { Trigger } from "../trigger-core.ts";\n'
          : "") +
        (content.emission.code.includes("ScopeName")
          ? 'import type { ScopeName } from "./scopes.ts";\n'
          : "") +
        importList(
          "./enums.ts",
          content.usage.enums.map((name) => emitter.enumTypeName(name))
        ) +
        importList(
          "./refs.ts",
          content.usage.refs.map((name) => emitter.refTypeName(name))
        ) +
        importList(
          "./value-sets.ts",
          content.usage.valueSets.map((name) => emitter.valueSetTypeName(name))
        ) +
        aliasStructImports +
        "\n" +
        content.emission.code
    );
  }
  await write(
    "content-registry.ts",
    header(
      commit,
      CONTENT_MANIFEST.map((entry) => entry.source).filter(
        (source, index, sources) => sources.indexOf(source) === index
      )
    ) + contentRegistry(contents)
  );
  const factories = contentFactories(contents);
  await write(
    "content-factories.ts",
    header(
      commit,
      CONTENT_MANIFEST.map((entry) => entry.source).filter(
        (source, index, sources) => sources.indexOf(source) === index
      )
    ) + factories.code
  );
  await write(
    "triggers.ts",
    header(commit, ["triggers.cwt", "aliases.cwt", "script-docs/v4.4.1/triggers.log"]) +
      'import { block, cmp, kv, type PdxEntry, type PdxOp } from "@pdx-ts/pdxscript";\n' +
      'import { trigger, type Trigger } from "../trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        triggerUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        triggerUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        triggerUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      'import { refId } from "./refs.ts";\n\n' +
      triggers.code
  );
  await write(
    "links.ts",
    header(commit, ["links.cwt", "script-docs/v4.4.1/scopes.log"]) +
      'import { block } from "@pdx-ts/pdxscript";\n' +
      'import { trigger, type Trigger } from "../trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      triggerLinks.code
  );
  await write(
    "effects.ts",
    header(commit, [
      "effects.cwt",
      "aliases.cwt",
      "links.cwt",
      "script-docs/v4.4.1/effects.log",
      "script-docs/v4.4.1/scopes.log",
    ]) +
      'import type { PdxOp } from "@pdx-ts/pdxscript";\n' +
      'import type { Modifier, StructuralEffects } from "../effect-core.ts";\n' +
      'import type { Trigger } from "../trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        effectUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        effectUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        effectUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      "\n" +
      effects.interfaces
  );
  await write(
    "effect-meta.ts",
    header(commit, ["effects.cwt", "aliases.cwt", "links.cwt"]) + effects.meta
  );
  const events = emitEvents(emitter);
  await write(
    "events.ts",
    header(commit, ["events/events.cwt"]) +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.code
  );
  await write(
    "event-factory.ts",
    header(commit, ["events/events.cwt"]) +
      'import { buildEvent, type EventDef } from "../events.ts";\n' +
      'import { makeCollection } from "../factories.ts";\n' +
      'import { assertNamespace } from "../items.ts";\n' +
      'import type { Collection, EventItem, EventItemBase } from "../items.ts";\n' +
      'import type { EventKindKey } from "./events.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.factoryCode
  );
  await write(
    "event-fires.ts",
    header(commit, ["events/events.cwt", "effects.cwt"]) +
      'import type { FireEventArgs, WitnessedFireEventArgs } from "../events.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.firesCode
  );
  const onActions = emitOnActions(rules);
  await write("on-actions.ts", header(commit, ["on_actions.cwt"]) + onActions.code);

  console.log(`cwtools-stellaris-config @ ${commit.slice(0, 12)}`);
  console.log(
    `\nscopes: ${canonicalScopes(rules.scopes).length}` +
      ` | enums emitted: ${emitter.usedEnums.size}` +
      ` | refs emitted: ${emitter.usedRefs.size}` +
      ` | value sets emitted: ${emitter.usedValueSets.size}`
  );
  console.log(
    `scope links: ${triggerLinks.emitted} trigger fns, ${effects.linkEmitted} effect methods` +
      ` emitted of ${rules.links.size} declared`
  );
  console.log(
    `modifiers: ${modifiers.names} names emitted` +
      ` (${modifiers.universal} universal, ${modifiers.groups} scope-set groups,` +
      ` ${modifiers.scopes} scopes, ${modifiers.trieTypes} path types;` +
      ` ${rules.modifierTemplates.length} cwt template rows)`
  );
  console.log(
    `triggers: ${triggers.emitted} emitted of ${rules.triggers.size} declared` +
      ` (${[...triggers.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")})`
  );
  console.log(
    `effects: ${effects.emitted} emitted of ${rules.effects.size} declared` +
      ` (${[...effects.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")}` +
      `; clusters ${effects.clusterCount})`
  );
  for (const content of contents) {
    console.log(`${content.registry}: ${content.emission.emittedFields.length} fields emitted`);
  }
  console.log(
    `content factories: ${factories.factories} emitted` +
      ` (${CONTENT_PATCH_REGISTRIES.size} with patchX,` +
      ` ${CONTENT_CONTRIBUTION_SINKS.size} with a contribution sink)`
  );
  console.log(
    `event kinds: ${events.kinds} (${events.definers} factory definers, ` +
      `${events.fireMethods} typed fire methods)`
  );
  console.log(
    `on-actions: ${onActions.emitted} emitted (${onActions.noScope} scopeless and currently rejected)`
  );
  for (const [category, emission] of aliasStructs) {
    console.log(
      `${category}: ${emission.emittedMembers.length} alias-struct members emitted` +
        ` of ${rules.aliasCategories.get(category)?.size ?? 0} declared`
    );
    reportSection(`${category} members declined`, emission.declinedMembers);
  }

  reportSection("Triggers not emitted", summarise(triggers.skipped));
  reportSection("Effects not emitted", summarise(effects.skipped));
  reportSection(
    "Scope links not emitted",
    classifiedLinks.skipped.map((entry) => `${entry.name} — ${entry.reason}`)
  );
  reportSection("Effects emitted scalar-only (block overload dropped)", effects.scalarOnly);
  reportSection("On-actions not emitted", onActions.skipped);
  reportSection(
    "Event kinds without full typing",
    events.skipped.map((entry) => `${entry.name} — ${entry.reason}`)
  );
  reportSection("Enums widened to string (rules declare no values)", valuelessEnums(emitter));
  reportSection("Content definers taken from the hand-written grafts", factories.grafted);
  for (const content of contents) {
    const type = content.registry;
    console.log(`\n${type}: ${content.emission.emittedFields.length} fields emitted`);
    reportSection(`${type} fields declined`, content.emission.declinedFields);
    reportSection(
      `${type} alias categories spliced unkeyed at the top level`,
      content.emission.inlineSplices
    );
    reportSection(`${type} fields blocked on emitter machinery`, content.emission.machineryBacklog);
    reportSection(
      `${content.registry} fields the emitter could not lower`,
      content.emission.unsupported
    );
    reportSection(
      `${content.registry} localization aliases collapsed`,
      content.emission.localisationAliases
    );
  }
}

/**
 * One collection factory per registry: the pure authoring API's whole content
 * surface.
 *
 * The definers are literal-preserving (`<const Id extends string>`), so a
 * definition's id survives as its literal type all the way into the item the
 * definer returns — the property the deleted class methods, generic only in
 * the mod prefix, widened away.
 *
 * Three kinds of registry-specific member, each an overlay row rather than a
 * conditional in this emitter:
 * `HAND_WRITTEN_CONTENT_DEFINERS` replaces the mechanical `defineX` with a
 * graft from `src/factories.ts`, `CONTENT_PATCH_REGISTRIES` adds `patchX`, and
 * `CONTENT_CONTRIBUTION_SINKS` adds the id-less contribution method.
 */
function contentFactories(
  contents: readonly {
    manifest: (typeof CONTENT_MANIFEST)[number];
    registry: string;
    type: ContentType;
    emission: ContentEmission;
  }[]
): { code: string; factories: number; grafted: string[] } {
  const grafted: string[] = [];
  const grafts = new Set<string>();
  const runtimeItemTypes = new Set<string>(["Collection", "ContentItem"]);
  const chunks: string[] = [];

  for (const content of contents) {
    const { registry, emission } = content;
    const name = emission.typeName;
    const key = JSON.stringify(registry);
    const spoken = registry.replaceAll("_", " ");
    const article = indefiniteArticle(spoken);
    const graft = HAND_WRITTEN_CONTENT_DEFINERS.get(registry);
    const patchable = CONTENT_PATCH_REGISTRIES.get(registry);
    const contribution = CONTENT_CONTRIBUTION_SINKS.get(registry);

    const itemArms = [`ContentItem<${key}, ${name}Def>`];
    if (patchable !== undefined) {
      itemArms.push(`${name}PatchItem`);
      runtimeItemTypes.add(`${name}PatchItem`);
    }
    if (contribution !== undefined) {
      itemArms.push("ContributionItem");
      runtimeItemTypes.add("ContributionItem");
    }

    const members: string[] = [];
    const bindings: string[] = [];
    if (graft === undefined) {
      members.push(
        docComment(
          [`Defines ${article} ${spoken} in this mod, registering it in this collection.`],
          "  "
        ) +
          `  define${name}<const Id extends string>(\n` +
          `    def: ${name}Def<Id>\n` +
          `  ): ContentItem<${key}, ${name}Def<Id>>;\n`
      );
      bindings.push(
        `    define${name}(def) {\n` +
          `      const item = { itemKind: "content" as const, type: ${key} as const, ` +
          "id: def.id, def };\n" +
          "      items.push(item);\n" +
          "      return item;\n" +
          "    },\n"
      );
    } else {
      grafts.add(graft.definerFactory);
      grafts.add(`type ${graft.definerInterface}`);
      grafted.push(`${registry}.define${name} — ${graft.reason}`);
      bindings.push(`    ...${graft.definerFactory}(items),\n`);
    }
    if (patchable !== undefined) {
      members.push(
        docComment(
          [
            `Patches ${article} vanilla ${spoken} as a whole-object override. The transform`,
            "runs here (pure); the duplicate-key and one-view checks stay in",
            "`buildMod`, which sees every patch together, and the emitted filename",
            "is always resolver-computed — this collection's file stem names only",
            "the mod's own definitions file.",
          ],
          "  "
        ) +
          `  patch${name}<Source extends Parsed${name}>(\n` +
          `    ${camelCase(registry)}: Source,\n` +
          `    patch: (${camelCase(registry)}: Source) => ${name}Patch\n` +
          `  ): ${name}PatchItem;\n`
      );
      bindings.push(
        `    patch${name}(${camelCase(registry)}, patch) {\n` +
          `      const item = { itemKind: "patch" as const, patched: transform${name}(` +
          `${camelCase(registry)}, patch) };\n` +
          "      items.push(item);\n" +
          "      return item;\n" +
          "    },\n"
      );
    }
    if (contribution !== undefined) {
      members.push(
        docComment(
          [
            `Contributes to the shared additive \`default = { ${contribution.sink} = ... }\``,
            "sink: ids this mod names but does not own, with no author-named file.",
            "A ref listed twice is emitted once.",
          ],
          "  "
        ) +
          `  ${contribution.method}(\n` +
          `    ${camelCase(contribution.sink)}: readonly (TypedRef<${JSON.stringify(contribution.refRegistry)}> | string)[]\n` +
          "  ): void;\n"
      );
      bindings.push(
        `    ${contribution.method}(${camelCase(contribution.sink)}) {\n` +
          "      items.push({\n" +
          '        itemKind: "contribution",\n' +
          `        registry: ${JSON.stringify(contribution.sink)},\n` +
          `        ids: ${camelCase(contribution.sink)}.map((entry) => String(refId(entry))),\n` +
          "      });\n" +
          "    },\n"
      );
    }

    const extendsList = [
      `Collection<${name}Item>`,
      ...(graft === undefined ? [] : [graft.definerInterface]),
    ];
    chunks.push(
      docComment([`What ${article} ${spoken} collection can contain.`]) +
        `export type ${name}Item = ${itemArms.join(" | ")};\n\n` +
        `export interface ${name}Collection extends ${extendsList.join(", ")} {\n` +
        members.join("\n") +
        "}\n\n" +
        docComment([
          `A ${spoken} collection, optionally bound to a file stem: its definitions`,
          `land in \`${outputDirOf(content.type)}/<prefix>_<file>.txt\`, defaulting to the`,
          "registry's own file name. The definers register into the collection at",
          "the definition site, so creating a definition is registering it.",
        ]) +
        `export function create${pascalCase(content.manifest.plural)}(\n` +
        "  file?: string\n" +
        `): ${name}Collection {\n` +
        `  const { collection, items } = makeCollection<${name}Item>(file);\n` +
        "  return {\n" +
        "    ...collection,\n" +
        bindings.join("") +
        "  };\n" +
        "}\n"
    );
  }

  const patchNames = contents
    .filter((content) => CONTENT_PATCH_REGISTRIES.has(content.registry))
    .map((content) => content.emission.typeName);
  const refImports = contents.some((content) => CONTENT_CONTRIBUTION_SINKS.has(content.registry));
  const imports =
    `import { ${["makeCollection", ...grafts].sort().join(", ")} } from "../factories.ts";\n` +
    importList("../items.ts", [...runtimeItemTypes]) +
    (refImports ? 'import { refId, type TypedRef } from "./refs.ts";\n' : "") +
    patchNames
      .map(
        (name) =>
          `import { patch${name} as transform${name}, type ${name}Patch } ` +
          'from "../vanilla/patch.ts";\n' +
          `import type { Parsed${name} } from "../vanilla/surface.ts";\n`
      )
      .join("") +
    contents
      .map(
        (content) =>
          `import type { ${content.emission.typeName}Def } from ` +
          `${JSON.stringify(`./${content.registry.replaceAll("_", "-")}.ts`)};\n`
      )
      .join("");

  return { code: imports + "\n" + chunks.join("\n"), factories: contents.length, grafted };
}

/** `game/common/technology` → `common/technology`; the descriptor path already
 * validated in `contentRegistry`, so this is documentation, not a check. */
function outputDirOf(type: ContentType): string {
  return type.path === null ? "common" : type.path.replace(/^game\//, "");
}

function contentRegistry(
  contents: readonly {
    manifest: (typeof CONTENT_MANIFEST)[number];
    registry: string;
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
  }[]
): string {
  const imports = contents
    .map((content) => {
      const file = `./${content.registry.replaceAll("_", "-")}.ts`;
      const values = [content.emission.fieldsConstant, content.emission.localisationConstant];
      return `import { ${values.join(", ")} } from ${JSON.stringify(file)};\n`;
    })
    .join("");
  const descriptors = contents
    .map((content) => {
      const sourcePath = content.type.path;
      if (sourcePath === null || !sourcePath.startsWith("game/")) {
        throw new Error(`type[${content.registry}] has unusable path ${sourcePath}`);
      }
      const outputDir = sourcePath.slice("game/".length);
      const fileStem = path.posix.basename(outputDir);
      return (
        "  {\n" +
        `    type: ${JSON.stringify(content.registry)},\n` +
        `    outputDir: ${JSON.stringify(outputDir)},\n` +
        `    fileStem: ${JSON.stringify(fileStem)},\n` +
        `    fields: ${content.emission.fieldsConstant},\n` +
        `    localisation: ${content.emission.localisationConstant},\n` +
        (content.keyword === undefined
          ? ""
          : `    keyedBy: { keyword: ${JSON.stringify(content.keyword)}, ` +
            `nameField: ${JSON.stringify(content.type.nameField)} },\n`) +
        "  },\n"
      );
    })
    .join("");
  return (
    'import type { ContentRegistryDescriptor } from "../content.ts";\n' +
    imports +
    "\n" +
    "export const CONTENT_REGISTRIES = [\n" +
    descriptors +
    "] as const satisfies readonly ContentRegistryDescriptor[];\n\n" +
    'export type ContentTypeName = (typeof CONTENT_REGISTRIES)[number]["type"];\n'
  );
}

function importList(from: string, names: readonly string[]): string {
  if (names.length === 0) {
    return "";
  }
  return `import type { ${[...new Set(names)].sort().join(", ")} } from ${JSON.stringify(from)};\n`;
}

function summarise(skipped: readonly SkippedRule[]): string[] {
  const grouped = new Map<string, string[]>();
  for (const entry of skipped) {
    grouped.set(entry.reason, [...(grouped.get(entry.reason) ?? []), entry.name]);
  }
  return [...grouped]
    .sort((left, right) => right[1].length - left[1].length)
    .map(([reason, names]) => `${names.length} — ${reason}, e.g. ${names.slice(0, 3).join(", ")}`);
}

await main();
