/**
 * Regenerates `src/generated/` from the vendored cwtools config.
 *
 * Run with `npm run codegen`. The output is committed, so a rules bump shows up
 * as a reviewable diff on the SDK's public API.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { format, resolveConfig } from "prettier";

import { CONTENT_MANIFEST, type ContentManifestEntry } from "./content-manifest.ts";
import { loadRules, scopeIndex, type ContentType } from "./cwt/rules.ts";
import { emitContentType, type ContentEmission } from "./emit/content-type.ts";
import { emitEffects } from "./emit/effects.ts";
import { emitEvents } from "./emit/events.ts";
import { emitModifiers, joinModifierScopes } from "./emit/modifiers.ts";
import { emitOnActions } from "./emit/on-actions.ts";
import type { SkippedRule } from "./emit/shape.ts";
import {
  canonicalScopes,
  emitEnums,
  emitRefs,
  emitScopes,
  emitValueSets,
  valuelessEnums,
} from "./emit/support.ts";
import { emitTriggers } from "./emit/triggers.ts";
import { Emitter } from "./emit/types.ts";
import { parseModifierDocs } from "./logs/modifier-docs.ts";
import { parseScopeLinks } from "./logs/scopes.ts";
import { parseTriggerDocs } from "./logs/trigger-docs.ts";
import { compareToBaseline, reconcile, type DriftReport } from "./reconcile.ts";

const VENDOR = "vendor/cwtools-stellaris-config";
const CONFIG = `${VENDOR}/config`;
/** The dump directory matching the game version these rules target. */
const DOCS = `${VENDOR}/script-docs/v4.4.1`;
const OUT = "src/generated";
const BASELINE = "tools/codegen/drift-baseline.json";

function upstreamCommit(): string {
  const version = readFileSync(`${VENDOR}/VERSION.md`, "utf8");
  return /`([0-9a-f]{40})`/.exec(version)?.[1] ?? "unknown";
}

function header(commit: string, sources: readonly string[]): string {
  return (
    "// Generated by tools/codegen. Do not edit.\n" +
    `// Source: cwtools-stellaris-config @ ${commit.slice(0, 12)}\n` +
    sources.map((source) => `// From: ${source}\n`).join("") +
    "\n"
  );
}

/**
 * Written through Prettier so the committed output matches the repo's style and
 * the pre-commit hook has nothing left to reformat — otherwise `lint-staged`
 * would rewrite these files and `codegen:check` would report a false diff.
 */
async function write(file: string, contents: string): Promise<void> {
  const target = path.join(OUT, file);
  const options = await resolveConfig(target);
  mkdirSync(OUT, { recursive: true });
  writeFileSync(target, await format(contents, { ...options, filepath: target }), "utf8");
}

function reportSection(title: string, lines: readonly string[]): void {
  if (lines.length === 0) {
    return;
  }
  console.log(`\n${title} (${lines.length}):`);
  for (const line of lines) {
    console.log(`  ${line}`);
  }
}

function checkDrift(report: DriftReport, rebaseline: boolean): void {
  if (rebaseline) {
    writeFileSync(BASELINE, `${JSON.stringify(report, null, 2)}\n`, "utf8");
    console.log(`Rebaselined drift: ${BASELINE}`);
    return;
  }
  const baseline = JSON.parse(readFileSync(BASELINE, "utf8")) as DriftReport;
  const differences = compareToBaseline(report, baseline);
  if (differences.length === 0) {
    return;
  }
  console.error("\nThe two rule sources drifted since the recorded baseline:\n");
  console.error(differences.join("\n"));
  console.error(
    "\nEach line is a trigger, effect, or annotation that exists in one source and not\n" +
      "the other, which means codegen would emit a wrong signature or silently skip it.\n" +
      "Review the change, then re-run with --rebaseline to accept it."
  );
  process.exit(1);
}

async function main(): Promise<void> {
  const rebaseline = process.argv.includes("--rebaseline");
  const commit = upstreamCommit();

  const rules = loadRules(CONFIG);
  const docs = parseTriggerDocs(
    readFileSync(`${DOCS}/triggers.log`, "utf8"),
    readFileSync(`${DOCS}/effects.log`, "utf8")
  );
  const links = parseScopeLinks(readFileSync(`${DOCS}/scopes.log`, "utf8"));
  const modifierDocs = parseModifierDocs(readFileSync(`${DOCS}/modifiers.log`, "utf8"));

  checkDrift(reconcile(rules, docs, modifierDocs), rebaseline);

  const emitter = new Emitter(rules);
  const index = scopeIndex(rules);
  emitter.beginFile();
  const triggers = emitTriggers(emitter, docs.triggers, index);
  const triggerUsage = emitter.endFile();

  emitter.beginFile();
  const effects = emitEffects(emitter, docs.effects, index);
  const effectUsage = emitter.endFile();

  const contents: Array<{
    manifest: (typeof CONTENT_MANIFEST)[number];
    /** Registry name: the CWT type unless the manifest renames it via `as`. */
    registry: string;
    /** Top-level keyword, for registries CWT marks with `name_field`. */
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
    usage: ReturnType<Emitter["endFile"]>;
  }> = [];
  for (const manifest of CONTENT_MANIFEST) {
    const type = rules.contentTypes.get(manifest.type);
    const body = rules.bodies.get(manifest.type);
    if (type === undefined || body === undefined) {
      throw new Error(`${manifest.source} no longer declares type[${manifest.type}] and its body`);
    }
    const entry: ContentManifestEntry = manifest;
    const registry = entry.as ?? entry.type;
    const keyword = entry.keyword;
    // A keyword the rules do declare must match what the manifest claims;
    // silence here would emit a top-level key the game quietly ignores.
    if (keyword !== undefined && type.nameField === null) {
      throw new Error(`type[${manifest.type}] declares no name_field, so it has no keyword`);
    }
    if (keyword === undefined && type.nameField !== null) {
      throw new Error(
        `type[${manifest.type}] declares name_field=${type.nameField}, so the manifest ` +
          "entry needs the keyword its entries are written under"
      );
    }
    if (type.keyFilter !== null && keyword !== undefined && keyword !== type.keyFilter) {
      throw new Error(
        `type[${manifest.type}] declares ## type_key_filter = ${type.keyFilter} but the ` +
          `manifest claims keyword ${keyword}`
      );
    }
    emitter.beginFile();
    const emission = emitContentType(emitter, type, body, registry);
    const usage = emitter.endFile();
    contents.push({ manifest, registry, keyword, type, emission, usage });
  }

  await write(
    "scopes.ts",
    header(commit, ["scopes.cwt"]) + emitScopes(canonicalScopes(rules.scopes))
  );
  await write(
    "refs.ts",
    header(commit, ["type references across the rule files"]) + emitRefs(emitter)
  );
  await write("enums.ts", header(commit, ["enums.cwt"]) + emitEnums(emitter));
  await write(
    "value-sets.ts",
    header(commit, ["value sets referenced across the rule files"]) + emitValueSets(emitter)
  );
  const modifiers = emitModifiers(
    joinModifierScopes(rules, modifierDocs, (token) => emitter.canonicalScope(token))
  );
  await write(
    "modifiers.ts",
    header(commit, ["script-docs/v4.4.1/modifiers.log", "modifier_categories.cwt"]) +
      'import type { CustomModifiers } from "../content.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      modifiers.code
  );
  for (const content of contents) {
    const runtimeTypes = [
      "ContentField",
      "ContentLocalisation",
      "DefinedContent",
      "EconomicResourceBlock",
      "EffectBlock",
      "ModifierBlock",
      "ModifierClosure",
      "TriggeredModifier",
      "WeightBlock",
    ].filter((name) => content.emission.code.includes(name));
    await write(
      `${content.registry.replaceAll("_", "-")}.ts`,
      header(commit, [content.manifest.source]) +
        importList("../content.ts", runtimeTypes) +
        (content.emission.code.includes("Trigger<")
          ? 'import type { Trigger } from "../trigger-core.ts";\n'
          : "") +
        (content.emission.code.includes("ScopeName")
          ? 'import type { ScopeName } from "./scopes.ts";\n'
          : "") +
        importList(
          "./enums.ts",
          content.usage.enums.map((name) => emitter.enumTypeName(name))
        ) +
        importList(
          "./refs.ts",
          content.usage.refs.map((name) => emitter.refTypeName(name))
        ) +
        importList(
          "./value-sets.ts",
          content.usage.valueSets.map((name) => emitter.valueSetTypeName(name))
        ) +
        "\n" +
        content.emission.code
    );
  }
  await write(
    "content-registry.ts",
    header(
      commit,
      CONTENT_MANIFEST.map((entry) => entry.source).filter(
        (source, index, sources) => sources.indexOf(source) === index
      )
    ) + contentRegistry(contents)
  );
  await write(
    "triggers.ts",
    header(commit, ["triggers.cwt", "aliases.cwt", "script-docs/v4.4.1/triggers.log"]) +
      'import { block, cmp, kv, type PdxEntry, type PdxOp } from "@pdx-ts/pdxscript";\n' +
      'import { trigger, type Trigger } from "../trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        triggerUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        triggerUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        triggerUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      'import { refId } from "./refs.ts";\n\n' +
      triggers.code
  );
  await write(
    "effects.ts",
    header(commit, ["effects.cwt", "aliases.cwt", "script-docs/v4.4.1/effects.log"]) +
      'import type { PdxOp } from "@pdx-ts/pdxscript";\n' +
      'import type { Modifier, StructuralEffects } from "../effect-core.ts";\n' +
      'import type { Trigger } from "../trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        effectUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        effectUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        effectUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      "\n" +
      effects.interfaces
  );
  await write("effect-meta.ts", header(commit, ["effects.cwt", "aliases.cwt"]) + effects.meta);
  const events = emitEvents(emitter);
  await write(
    "events.ts",
    header(commit, ["events/events.cwt"]) +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.code
  );
  const onActions = emitOnActions(rules);
  await write("on-actions.ts", header(commit, ["on_actions.cwt"]) + onActions.code);

  console.log(`cwtools-stellaris-config @ ${commit.slice(0, 12)}`);
  console.log(
    `\nscopes: ${canonicalScopes(rules.scopes).length}` +
      ` | scope links read: ${links.length}` +
      ` | enums emitted: ${emitter.usedEnums.size}` +
      ` | refs emitted: ${emitter.usedRefs.size}` +
      ` | value sets emitted: ${emitter.usedValueSets.size}`
  );
  console.log(
    `modifiers: ${modifiers.names} names emitted` +
      ` (${modifiers.universal} universal, ${modifiers.groups} scope-set groups,` +
      ` ${modifiers.scopes} scopes, ${modifiers.trieTypes} path types;` +
      ` ${rules.modifierTemplates.length} cwt template rows)`
  );
  console.log(
    `triggers: ${triggers.emitted} emitted of ${rules.triggers.size} declared` +
      ` (${[...triggers.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")})`
  );
  console.log(
    `effects: ${effects.emitted} emitted of ${rules.effects.size} declared` +
      ` (${[...effects.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")}` +
      `; clusters ${effects.clusterCount})`
  );
  for (const content of contents) {
    console.log(`${content.registry}: ${content.emission.emittedFields.length} fields emitted`);
  }
  console.log(`event kinds: ${events.kinds}`);
  console.log(
    `on-actions: ${onActions.emitted} emitted (${onActions.noScope} scopeless and currently rejected)`
  );

  reportSection("Triggers not emitted", summarise(triggers.skipped));
  reportSection("Effects not emitted", summarise(effects.skipped));
  reportSection("Effects emitted scalar-only (block overload dropped)", effects.scalarOnly);
  reportSection("On-actions not emitted", onActions.skipped);
  reportSection("Enums widened to string (rules declare no values)", valuelessEnums(emitter));
  for (const content of contents) {
    const type = content.registry;
    console.log(`\n${type}: ${content.emission.emittedFields.length} fields emitted`);
    reportSection(`${type} fields declined`, content.emission.declinedFields);
    reportSection(`${type} fields blocked on emitter machinery`, content.emission.machineryBacklog);
    reportSection(
      `${content.registry} fields the emitter could not lower`,
      content.emission.unsupported
    );
    reportSection(
      `${content.registry} localization aliases collapsed`,
      content.emission.localisationAliases
    );
  }
}

function contentRegistry(
  contents: readonly {
    manifest: (typeof CONTENT_MANIFEST)[number];
    registry: string;
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
  }[]
): string {
  const imports = contents
    .map((content) => {
      const file = `./${content.registry.replaceAll("_", "-")}.ts`;
      const values = [content.emission.fieldsConstant, content.emission.localisationConstant];
      const types = [`${content.emission.typeName}Def`, `Defined${content.emission.typeName}`];
      return (
        `import { ${values.join(", ")} } from ${JSON.stringify(file)};\n` +
        `import type { ${types.join(", ")} } from ${JSON.stringify(file)};\n`
      );
    })
    .join("");
  const descriptors = contents
    .map((content) => {
      const sourcePath = content.type.path;
      if (sourcePath === null || !sourcePath.startsWith("game/")) {
        throw new Error(`type[${content.registry}] has unusable path ${sourcePath}`);
      }
      const outputDir = sourcePath.slice("game/".length);
      const fileStem = path.posix.basename(outputDir);
      return (
        "  {\n" +
        `    type: ${JSON.stringify(content.registry)},\n` +
        `    outputDir: ${JSON.stringify(outputDir)},\n` +
        `    fileStem: ${JSON.stringify(fileStem)},\n` +
        `    fields: ${content.emission.fieldsConstant},\n` +
        `    localisation: ${content.emission.localisationConstant},\n` +
        (content.keyword === undefined
          ? ""
          : `    keyedBy: { keyword: ${JSON.stringify(content.keyword)}, ` +
            `nameField: ${JSON.stringify(content.type.nameField)} },\n`) +
        "  },\n"
      );
    })
    .join("");
  const defMap = contents
    .map(
      (content) =>
        `  ${JSON.stringify(content.registry)}: ${content.emission.typeName}Def<PrefixedId<P>>;\n`
    )
    .join("");
  const definedMap = contents
    .map(
      (content) =>
        `  ${JSON.stringify(content.registry)}: Defined${content.emission.typeName}<PrefixedId<P>>;\n`
    )
    .join("");
  const methods = contents
    .map((content) => {
      const method = `define${content.emission.typeName}`;
      const key = JSON.stringify(content.registry);
      const article = /^[aeiou]/i.test(content.registry) ? "an" : "a";
      return (
        `  /** Defines ${article} ${content.registry.replaceAll("_", " ")} in this mod. */\n` +
        `  ${method}(def: ContentDefMap<P>[${key}]): DefinedContentMap<P>[${key}] {\n` +
        `    return this.defineGeneratedContent(${key}, def);\n` +
        "  }\n"
      );
    })
    .join("\n");
  return (
    'import type { ContentRegistryDescriptor } from "../content.ts";\n' +
    imports +
    "\n" +
    "export type PrefixedId<P extends string> = `${P}_${string}`;\n\n" +
    "export const CONTENT_REGISTRIES = [\n" +
    descriptors +
    "] as const satisfies readonly ContentRegistryDescriptor[];\n\n" +
    'export type ContentTypeName = (typeof CONTENT_REGISTRIES)[number]["type"];\n\n' +
    "export interface ContentDefMap<P extends string> {\n" +
    defMap +
    "}\n\n" +
    "export interface DefinedContentMap<P extends string> {\n" +
    definedMap +
    "}\n\n" +
    "export abstract class GeneratedContentMethods<const P extends string> {\n" +
    "  protected abstract defineGeneratedContent<K extends ContentTypeName>(\n" +
    "    type: K,\n" +
    "    def: ContentDefMap<P>[K]\n" +
    "  ): DefinedContentMap<P>[K];\n\n" +
    methods +
    "}\n"
  );
}

function importList(from: string, names: readonly string[]): string {
  if (names.length === 0) {
    return "";
  }
  return `import type { ${[...new Set(names)].sort().join(", ")} } from ${JSON.stringify(from)};\n`;
}

function summarise(skipped: readonly SkippedRule[]): string[] {
  const grouped = new Map<string, string[]>();
  for (const entry of skipped) {
    grouped.set(entry.reason, [...(grouped.get(entry.reason) ?? []), entry.name]);
  }
  return [...grouped]
    .sort((left, right) => right[1].length - left[1].length)
    .map(([reason, names]) => `${names.length} — ${reason}, e.g. ${names.slice(0, 3).join(", ")}`);
}

await main();
