// Generated by @pdx-ts/codegen-vanilla from Stellaris 4.4.6. Do not edit.

export type VanillaSectionSlotMember =
  | "1"
  | "2"
  | "3"
  | "4"
  | "5"
  | "6"
  | "bot_1"
  | "bot_2"
  | "bot_3"
  | "bow"
  | "core"
  | "east"
  | "mid"
  | "mutations"
  | "north"
  | "part1"
  | "ship"
  | "south"
  | "spinal_mount_1"
  | "stern"
  | "west";
