/**
 * The generated-file writing protocol: the header banner every generated
 * module carries, where it lands under `packages/sdk/src/generated/`, and
 * running it through Prettier so the committed output already matches the
 * repo's style — otherwise the pre-commit hook would rewrite it and
 * `codegen:check` would report a false diff.
 *
 * `write` and `writeModule` are what `main()` (`index.ts`) calls once per
 * generated file; `header` is spelled at most of those call sites directly,
 * since a handful of files (`content-shape.ts`, `scopes.ts`, …) carry no
 * computed-import needs of their own and skip `writeModule`'s machinery.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

import { assertRecordedImportsAreUsed, importList, renderImports } from "./emit/symbols.ts";
import { Emitter, type Usage } from "./emit/types.ts";
import { referencesIdentifier } from "./naming.ts";

/**
 * Every path this script touches is anchored to the module, not the process:
 * the inputs live in the repo, not in whatever directory `npm run codegen` was
 * invoked from, and a generator that silently reads a different rule set when
 * run from a subdirectory would be a nasty way to learn that.
 */
const ROOT = fileURLToPath(new URL("../../../", import.meta.url));
const OUT = path.join(ROOT, "packages/sdk/src/generated");

export function header(commit: string, sources: readonly string[]): string {
  return (
    "// Generated by @pdx-ts/codegen-cwt. Do not edit.\n" +
    `// Source: cwtools-stellaris-config @ ${commit.slice(0, 12)}\n` +
    sources.map((source) => `// From: ${source}\n`).join("") +
    "\n"
  );
}

/**
 * Written through Prettier so the committed output matches the repo's style and
 * the pre-commit hook has nothing left to reformat — otherwise `lint-staged`
 * would rewrite these files and `codegen:check` would report a false diff.
 */
export async function write(file: string, contents: string): Promise<void> {
  const target = path.join(OUT, file);
  const options = await resolveConfig(target);
  mkdirSync(OUT, { recursive: true });
  writeFileSync(target, await format(contents, { ...options, filepath: target }), "utf8");
}

/**
 * Writes one generated module whose imports are computed rather than scanned.
 *
 * Two sources, both recorded while the module was emitted: the SDK symbols its
 * emitters declared a use of (`Emitter.use`), and the enum, reference and
 * value-set aliases the emitter's own per-file tracking already resolves. What
 * the module needs is therefore a fact the emission produced, not one read back
 * out of the emitted text.
 *
 * The recorded set is checked one way before it is written — see
 * {@link assertRecordedImportsAreUsed}.
 */
export async function writeModule(
  file: string,
  commit: string,
  sources: readonly string[],
  emitter: Emitter,
  usage: Usage,
  body: string
): Promise<void> {
  assertRecordedImportsAreUsed(file, body, usage.imports, referencesIdentifier);
  await write(
    file,
    header(commit, sources) +
      importList(
        "./enums.ts",
        usage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        usage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        usage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      renderImports(usage.imports) +
      "\n" +
      body
  );
}
