/**
 * Regenerates `packages/sdk/src/generated/` from the vendored cwtools config.
 *
 * Run with `npm run codegen`. The output is committed, so a rules bump shows up
 * as a reviewable diff on the SDK's public API.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

import { contentFileLayout } from "./content-layout.ts";
import {
  CONTENT_MANIFEST,
  registryNameOf,
  VANILLA_REF_EXTRAS,
  type ContentManifestEntry,
} from "./content-manifest.ts";
import { referenceNameOf, typesReferencedBySubtype } from "./content-reference.ts";
import { emitContentShapeProtocol } from "./content-shape.ts";
import { deriveContentSwapIdentities, emitContentSwapProtocol } from "./content-swap-policy.ts";
import { loadRules, scopeIndex, type ContentType } from "./cwt/rules.ts";
import { createEffectPolicy, emitEffectPolicyProtocol } from "./effect-policy.ts";
import { emitAliasSplice, type AliasSpliceEmission } from "./emit/alias-splice.ts";
import { emitAliasStruct } from "./emit/alias-struct.ts";
import { emitContentFieldDocs, type FieldDocsModule } from "./emit/content-field-docs.ts";
import { emitContentType, type ContentEmission } from "./emit/content-type.ts";
import { emitEffects } from "./emit/effects.ts";
import { emitEvents } from "./emit/events.ts";
import {
  assertEveryAssetPathFieldApplied,
  constantCase,
  structuralSpliceOf,
  type DocTable,
  type FieldOmissionRow,
} from "./emit/fields.ts";
import { classifyLinks, emitScopeLinkNavigation, emitScopeLinks } from "./emit/links.ts";
import { emitModifiers, joinModifierScopes } from "./emit/modifiers.ts";
import { emitOnActions } from "./emit/on-actions.ts";
import type { SkippedRule } from "./emit/shape.ts";
import {
  canonicalScopes,
  emitEnums,
  emitRefs,
  emitScopes,
  emitValueSets,
  valuelessEnums,
} from "./emit/support.ts";
import { emitTriggers } from "./emit/triggers.ts";
import { Emitter, type Usage } from "./emit/types.ts";
import { emitVanillaRefs } from "./emit/vanilla-refs.ts";
import { createEventFieldPolicy, emitEventFieldProtocol } from "./event-field-policy.ts";
import { parseModifierDocs } from "./logs/modifier-docs.ts";
import { parseScopeLinks } from "./logs/scopes.ts";
import { parseTriggerDocs } from "./logs/trigger-docs.ts";
import { lowerRuleTable } from "./lowered-rule.ts";
import { createModifierOperationPolicy, emitModifierOperationProtocol } from "./modifier-policy.ts";
import {
  camelCase,
  docComment,
  indefiniteArticle,
  kebabCase,
  pascalCase,
  referencesIdentifier,
  spokenName,
} from "./naming.ts";
import {
  CONTENT_CONTRIBUTION_SINKS,
  CONTENT_FIELD_OVERRIDES,
  CONTENT_PATCH_REGISTRIES,
  CONTENT_SUBTYPE_REFERENCE_REFINEMENTS,
  EXACT_NAME_MINTS,
  FILE_STEM_OVERLAYS,
  HAND_WRITTEN_CONTENT_DEFINERS,
  MINT_SHAPE_OVERLAYS,
  REPEATED_STRUCT_FIELD_OVERRIDES,
  SHAPE_MINT_REGISTRY,
  SPRITE_SHAPE_MINTS,
  type HandWrittenDefiner,
  type SpriteShapeMint,
} from "./overlay.ts";
import {
  compareToBaseline,
  reconcile,
  updatedBaseline,
  type DriftBaseline,
  type DriftReport,
} from "./reconcile.ts";
import { RESERVED_TRIGGER_EXPORT_NAMES } from "./trigger-policy.ts";

/**
 * Every path this script touches is anchored to the module, not the process:
 * the inputs live in the repo, not in whatever directory `npm run codegen` was
 * invoked from, and a generator that silently reads a different rule set when
 * run from a subdirectory would be a nasty way to learn that.
 */
const ROOT = fileURLToPath(new URL("../../../", import.meta.url));
const VENDOR = path.join(ROOT, "vendor/cwtools-stellaris-config");
const CONFIG = path.join(VENDOR, "config");
/** The dump directory matching the game version these rules target. */
const DOCS = path.join(VENDOR, "script-docs/v4.4.1");
const OUT = path.join(ROOT, "packages/sdk/src/generated");
const BASELINE = fileURLToPath(new URL("./drift-baseline.json", import.meta.url));

function upstreamCommit(): string {
  const version = readFileSync(`${VENDOR}/VERSION.md`, "utf8");
  return /`([0-9a-f]{40})`/.exec(version)?.[1] ?? "unknown";
}

function header(commit: string, sources: readonly string[]): string {
  return (
    "// Generated by @pdx-ts/codegen-cwt. Do not edit.\n" +
    `// Source: cwtools-stellaris-config @ ${commit.slice(0, 12)}\n` +
    sources.map((source) => `// From: ${source}\n`).join("") +
    "\n"
  );
}

/**
 * Written through Prettier so the committed output matches the repo's style and
 * the pre-commit hook has nothing left to reformat — otherwise `lint-staged`
 * would rewrite these files and `codegen:check` would report a false diff.
 */
async function write(file: string, contents: string): Promise<void> {
  const target = path.join(OUT, file);
  const options = await resolveConfig(target);
  mkdirSync(OUT, { recursive: true });
  writeFileSync(target, await format(contents, { ...options, filepath: target }), "utf8");
}

/**
 * A registry's field count: its own keys, plus the fields lowered inside their
 * blocks where it has any. The two are counted apart because they are reached
 * differently — a nested field is authorable only through the member that owns
 * it, and only a `corpusDescents` walk measures it.
 */
function fieldCount(emission: ContentEmission): string {
  const nested = emission.nestedEmittedFields.length;
  return (
    `${emission.emittedFields.length} fields emitted` + (nested === 0 ? "" : ` (+${nested} nested)`)
  );
}

function reportSection(title: string, lines: readonly string[]): void {
  if (lines.length === 0) {
    return;
  }
  console.log(`\n${title} (${lines.length}):`);
  for (const line of lines) {
    console.log(`  ${line}`);
  }
}

function checkDrift(report: DriftReport, rebaseline: boolean): void {
  // A baseline written before a join existed reads as that join being empty,
  // so adding a join reports its entire current state as drift to review
  // instead of crashing on the missing field.
  const baseline = {
    links: { rulesOnly: [], docsOnly: [] },
    ...(JSON.parse(readFileSync(BASELINE, "utf8")) as Partial<DriftBaseline>),
  } as DriftBaseline;
  if (rebaseline) {
    writeFileSync(
      BASELINE,
      `${JSON.stringify(updatedBaseline(report, baseline), null, 2)}\n`,
      "utf8"
    );
    console.log(`Rebaselined drift: ${BASELINE}`);
    return;
  }
  const differences = compareToBaseline(report, baseline);
  if (differences.length === 0) {
    return;
  }
  console.error("\nThe two rule sources drifted since the recorded baseline:\n");
  console.error(differences.join("\n"));
  console.error(
    "\nEach line is a trigger, effect, or annotation that exists in one source and not\n" +
      "the other, which means codegen would emit a wrong signature or silently skip it.\n" +
      "Review the change, then re-run with --rebaseline to accept it."
  );
  process.exit(1);
}

async function main(): Promise<void> {
  const rebaseline = process.argv.includes("--rebaseline");
  const commit = upstreamCommit();

  const rules = loadRules(CONFIG);
  const docs = parseTriggerDocs(
    readFileSync(`${DOCS}/triggers.log`, "utf8"),
    readFileSync(`${DOCS}/effects.log`, "utf8")
  );
  const links = parseScopeLinks(readFileSync(`${DOCS}/scopes.log`, "utf8"));
  const modifierDocs = parseModifierDocs(readFileSync(`${DOCS}/modifiers.log`, "utf8"));

  checkDrift(reconcile(rules, docs, modifierDocs, links), rebaseline);

  const emitter = new Emitter(rules);
  const index = scopeIndex(rules);
  const effectPolicy = createEffectPolicy(rules);
  const modifierOperationPolicy = createModifierOperationPolicy(rules);
  const eventFieldPolicy = createEventFieldPolicy(rules);
  await write(
    "content-shape.ts",
    header(commit, ["codegen-cwt ContentShape protocol"]) + emitContentShapeProtocol()
  );
  emitter.beginFile();
  const loweredTriggers = lowerRuleTable(rules.triggers, docs.triggers, emitter, index);
  const triggers = emitTriggers(emitter, docs.triggers, loweredTriggers);
  const triggerUsage = emitter.endFile();

  const dumpLinks = new Map(links.map((link) => [link.name, link]));
  const classifiedLinks = classifyLinks(emitter, dumpLinks, index);
  // The hand exports of src/script/triggers.ts share the links file's export
  // namespace through its `export *`, so they count as taken names too.
  const scopeLinks = emitScopeLinks(
    classifiedLinks,
    index,
    new Set([...triggers.names, ...RESERVED_TRIGGER_EXPORT_NAMES])
  );

  emitter.beginFile();
  const loweredEffects = lowerRuleTable(rules.effects, docs.effects, emitter, index);
  const effects = emitEffects(
    emitter,
    docs.effects,
    index,
    loweredEffects,
    effectPolicy,
    classifiedLinks.links
  );
  const effectUsage = emitter.endFile();

  const contents: Array<{
    manifest: (typeof CONTENT_MANIFEST)[number];
    /** Registry name: the CWT type unless the manifest renames it via `as`. */
    registry: string;
    /** The CWT reference this registry's definitions satisfy. */
    referenceName: string;
    /** Top-level keyword, for registries CWT marks with `name_field`. */
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
    usage: ReturnType<Emitter["endFile"]>;
  }> = [];
  const registryNames = new Set<string>();
  const subtypeReferencedTypes = typesReferencedBySubtype(rules);
  for (const manifest of CONTENT_MANIFEST) {
    const type = rules.contentTypes.get(manifest.type);
    const body = rules.bodies.get(manifest.type);
    if (type === undefined || body === undefined) {
      throw new Error(`${manifest.source} no longer declares type[${manifest.type}] and its body`);
    }
    const entry: ContentManifestEntry = manifest;
    const registry = registryNameOf(entry);
    assertRegistryName(entry, registry, registryNames);
    const keyword = entry.keyword;
    // A keyword the rules do declare must match what the manifest claims;
    // silence here would emit a top-level key the game quietly ignores.
    if (keyword !== undefined && type.nameField === null) {
      throw new Error(`type[${manifest.type}] declares no name_field, so it has no keyword`);
    }
    if (keyword === undefined && type.nameField !== null) {
      throw new Error(
        `type[${manifest.type}] declares name_field=${type.nameField}, so the manifest ` +
          "entry needs the keyword its entries are written under"
      );
    }
    const filter = effectiveKeyFilter(type, entry.as);
    if (filter !== null && keyword !== undefined && keyword !== filter.key) {
      throw new Error(
        `${filter.source} declares ## type_key_filter = ${filter.key} but the ` +
          `manifest claims keyword ${keyword}`
      );
    }
    emitter.beginFile();
    const emission = emitContentType(emitter, type, body, registry, entry.as);
    const usage = emitter.endFile();
    contents.push({
      manifest,
      registry,
      referenceName: referenceNameOf(type, entry.as, subtypeReferencedTypes),
      keyword,
      type,
      emission,
      usage,
    });
  }

  assertEveryAssetPathFieldApplied();

  // An alias category emitted as its own shared module, from either of the two
  // reasons a category needs one: an overlay row lowering a *keyed* field onto
  // it (`civic_or_origin.potential` -> `government_trigger`), or a body
  // splicing it unkeyed (`solar_system_initializer` -> `planet_initializer`).
  // Both produce a named interface plus a `registerAliasStructFields` call, so
  // they share a write loop and a report line.
  //
  // A worklist rather than a flat list, because a spliced category can splice
  // further categories: `planet_initializer` reaches `moon_initializer`, which
  // reaches itself. Runs after the content loop so the splice seeds exist.
  const aliasCategories = new Map<
    string,
    {
      readonly code: string;
      readonly typeName: string;
      readonly usage: Usage;
      readonly emittedMembers: readonly string[];
      readonly declinedMembers: readonly string[];
      readonly omissions: readonly FieldOmissionRow[];
      readonly docTables: readonly DocTable[];
    }
  >();
  const aliasSplices = new Map<string, AliasSpliceEmission>();
  const emitCategory = (category: string, kind: "struct" | "splice"): void => {
    if (aliasCategories.has(category)) {
      return;
    }
    if (kind === "struct") {
      // An overlay row naming a category the rules do not declare is a
      // mistake in the row, so this throws rather than emitting nothing.
      const members = rules.aliasCategories.get(category);
      if (members === undefined || members.size === 0) {
        throw new Error(
          `overlay requests aliasStruct category "${category}" but the rules declare no ` +
            `alias[${category}:...] members — add it to EXTRA_ALIAS_CATEGORIES`
        );
      }
      emitter.beginFile();
      const emission = emitAliasStruct(emitter, category, members);
      aliasCategories.set(category, { ...emission, usage: emitter.endFile() });
      return;
    }
    // A splice seed is different: not every spliced category is structural, and
    // a non-structural one is not an error. `static_modifier` splices
    // `modifier`, whose authoring member is the `ModifierClosure` the runtime
    // already knows and whose members the rules keep outside `aliasCategories`
    // entirely — so there is no interface and no field table to emit.
    if (structuralSpliceOf(emitter, category) === null) {
      return;
    }
    emitter.beginFile();
    const emission = emitAliasSplice(emitter, category)!;
    const usage = emitter.endFile();
    aliasSplices.set(category, emission);
    aliasCategories.set(category, {
      code: emission.code,
      typeName: emission.typeName,
      usage,
      emittedMembers: emission.emittedFields.map((field) => field.field),
      declinedMembers: [...emission.declinedFields, ...emission.unsupported],
      omissions: emission.omissions,
      docTables: emission.docTables,
    });
    for (const nested of emission.spliceCategories) {
      emitCategory(nested, "splice");
    }
  };
  for (const override of [
    ...CONTENT_FIELD_OVERRIDES.values(),
    ...REPEATED_STRUCT_FIELD_OVERRIDES.values(),
  ]) {
    if (override.shape === "aliasStruct") {
      emitCategory(override.category!, "struct");
    }
  }
  for (const content of contents) {
    for (const category of content.emission.inlineSplices) {
      emitCategory(category, "splice");
    }
  }

  // Registers every ref this namespace names (including the ref-only extras —
  // sound, sound_effect, resource) with `emitter.usedRefs` before
  // `refs.ts` is written below, so their `XRef` aliases survive even if
  // nothing else in the rules happens to reference them.
  const vanillaRefs = emitVanillaRefs(
    emitter,
    CONTENT_MANIFEST,
    VANILLA_REF_EXTRAS,
    new Map(contents.map((content) => [content.registry, content.referenceName]))
  );

  await write(
    "scopes.ts",
    header(commit, ["scopes.cwt"]) + emitScopes(canonicalScopes(rules.scopes))
  );
  await write(
    "refs.ts",
    header(commit, ["type references across the rule files"]) + emitRefs(emitter)
  );
  await write(
    "enums.ts",
    header(commit, ["enums.cwt"]) +
      'import type { VanillaEnumMember } from "../identifiers/contracts.ts";\n\n' +
      emitEnums(emitter)
  );
  await write(
    "value-sets.ts",
    header(commit, ["value sets referenced across the rule files"]) + emitValueSets(emitter)
  );
  const modifiers = emitModifiers(
    joinModifierScopes(rules, modifierDocs, (token) => emitter.canonicalScope(token))
  );
  await write(
    "modifiers.ts",
    header(commit, ["script-docs/v4.4.1/modifiers.log", "modifier_categories.cwt"]) +
      'import type { CustomModifiers } from "../content/types.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      modifiers.code
  );
  await write(
    "modifier-policy.ts",
    header(commit, ["modifier_rule.cwt"]) + emitModifierOperationProtocol(modifierOperationPolicy)
  );
  // `Trigger` and `ScriptValue` both live in `trigger-core.ts`, so one clause
  // covers both — `Trigger<` stays a substring match (already precise; see
  // `GovernmentTriggerBlock`, which a bare "Trigger" match would false-hit),
  // `ScriptValue` a word-boundary one since it has no such collision.
  const triggerCoreImports = (code: string): string => {
    const names = [
      ...(code.includes("Trigger<") ? ["Trigger"] : []),
      ...(referencesIdentifier(code, "ScriptValue") ? ["ScriptValue"] : []),
    ];
    return names.length === 0
      ? ""
      : `import type { ${names.join(", ")} } from "../script/trigger-core.ts";\n`;
  };
  // A module referencing another alias category's interface needs both a type
  // import and a bare side-effect import: the type import is erased at build
  // time, and only the side effect guarantees that category's
  // `registerAliasStructFields` call has run before anything is serialized.
  // Categories reference each other (`planet_initializer` holds
  // `MoonInitializerFields`) and registries reference categories, so both write
  // loops resolve it the same way.
  const aliasCategoryImports = (code: string, self?: string): string =>
    [...aliasCategories]
      .filter(
        ([category, emission]) => category !== self && referencesIdentifier(code, emission.typeName)
      )
      .map(([category, emission]) => {
        const file = `./${category.replaceAll("_", "-")}.ts`;
        return (
          `import type { ${emission.typeName} } from ${JSON.stringify(file)};\n` +
          `import ${JSON.stringify(file)};\n`
        );
      })
      .join("");
  for (const [category, emission] of aliasCategories) {
    // `ContentField` is always used — every category emits a field table — and
    // the rest only when the category's own members reach for them. Matched on
    // `EffectBlock<`/`Trigger<` rather than the bare name, since `Trigger`
    // is a substring of `GovernmentTriggerBlock`.
    const runtimeTypes: string[] = ["ContentField", "EffectBlock<", "ModifierClosure"]
      .filter((name) =>
        name.endsWith("<")
          ? emission.code.includes(name)
          : referencesIdentifier(emission.code, name)
      )
      .map((name) => name.replace("<", ""));
    const schemaTypes = runtimeTypes.filter((name) => name === "ContentField");
    const typeTypes = runtimeTypes.filter((name) => name !== "ContentField");
    await write(
      `${category.replaceAll("_", "-")}.ts`,
      header(commit, [`alias[${category}:...] across the rule files`]) +
        'import { registerAliasStructFields } from "../content/schema.ts";\n' +
        importList("../content/schema.ts", schemaTypes) +
        importList("../content/types.ts", typeTypes) +
        triggerCoreImports(emission.code) +
        (emission.code.includes("ScopeName")
          ? 'import type { ScopeName } from "./scopes.ts";\n'
          : "") +
        importList(
          "./enums.ts",
          emission.usage.enums.map((name) => emitter.enumTypeName(name))
        ) +
        importList(
          "./refs.ts",
          emission.usage.refs.map((name) => emitter.refTypeName(name))
        ) +
        importList(
          "./value-sets.ts",
          emission.usage.valueSets.map((name) => emitter.valueSetTypeName(name))
        ) +
        // A category whose own interface is self-recursive imports nothing for
        // itself; `self` keeps it from importing its own module.
        aliasCategoryImports(emission.code, category) +
        "\n" +
        emission.code
    );
  }
  for (const content of contents) {
    const runtimeTypes: string[] = [
      "ContentField",
      "ContentLocalisation",
      "DefinedContent",
      "EconomicResourceBlock",
      "EconomicResourceBlockNoProduce",
      "EconomicResourceOperation",
      "EffectBlock",
      "ModifierBlock",
      "ModifierClosure",
      "TriggeredModifier",
      "WeightBlock",
      "WeightBlockWithLoc",
      "WithFrom",
    ].filter((name) => referencesIdentifier(content.emission.code, name));
    const schemaTypes: string[] = runtimeTypes.filter(
      (name) => name === "ContentField" || name === "ContentLocalisation"
    );
    const authoringTypes: string[] = runtimeTypes.filter((name) => name === "DefinedContent");
    const typeTypes: string[] = runtimeTypes.filter(
      (name) => !schemaTypes.includes(name) && !authoringTypes.includes(name)
    );
    const aliasStructImports = aliasCategoryImports(content.emission.code);
    // The patch surface a `CONTENT_PATCH_REGISTRIES` row generates: the generic
    // transform's types, and the parsed definition it transforms.
    const patchTypes = ["ContentPatchItem", "PatchInput", "PatchedContent"].filter((name) =>
      referencesIdentifier(content.emission.code, name)
    );
    const parsedTypes = ["AnyOf", `Parsed${content.emission.typeName}`].filter((name) =>
      referencesIdentifier(content.emission.code, name)
    );
    await write(
      `${kebabCase(content.registry)}.ts`,
      header(commit, [content.manifest.source]) +
        importList(
          "../authoring/assets.ts",
          ["AssetFileItem"].filter((name) => referencesIdentifier(content.emission.code, name))
        ) +
        importList("../content/schema.ts", schemaTypes) +
        importList("../content/authoring.ts", authoringTypes) +
        importList("../content/types.ts", typeTypes) +
        importList("../stellaris/vanilla/patch.ts", patchTypes) +
        importList("../stellaris/vanilla/view.ts", parsedTypes) +
        triggerCoreImports(content.emission.code) +
        (content.emission.code.includes("ScopeName")
          ? 'import type { ScopeName } from "./scopes.ts";\n'
          : "") +
        importList(
          "./enums.ts",
          content.usage.enums.map((name) => emitter.enumTypeName(name))
        ) +
        importList(
          "./refs.ts",
          content.usage.refs.map((name) => emitter.refTypeName(name))
        ) +
        importList(
          "./value-sets.ts",
          content.usage.valueSets.map((name) => emitter.valueSetTypeName(name))
        ) +
        aliasStructImports +
        "\n" +
        content.emission.code
    );
  }
  const contentSources = CONTENT_MANIFEST.map((entry) => entry.source).filter(
    (source, index, sources) => sources.indexOf(source) === index
  );
  await write("content-registry.ts", header(commit, contentSources) + contentRegistry(contents));
  // The field-docs ledger: every table's doc rows plus the omission rows the
  // report prints, one generated module the docs build can import. Emitted
  // from the same emissions as the tables themselves, so the two cannot drift.
  const fieldDocsModules: FieldDocsModule[] = [
    ...contents.map((content) => ({
      module: `./${kebabCase(content.registry)}.ts`,
      docTables: content.emission.docTables,
    })),
    ...[...aliasCategories].map(([category, emission]) => ({
      module: `./${category.replaceAll("_", "-")}.ts`,
      docTables: emission.docTables,
    })),
  ];
  await write(
    "content-field-docs.ts",
    header(commit, [...contentSources, "codegen-cwt field-docs ledger"]) +
      emitContentFieldDocs(
        fieldDocsModules,
        new Map(contents.map((content) => [content.registry, content.emission.omissions])),
        new Map([...aliasCategories].map(([category, emission]) => [category, emission.omissions]))
      )
  );
  const contentSwaps = deriveContentSwapIdentities(rules, contents);
  await write(
    "content-swaps.ts",
    header(commit, [...contentSources, "CWT base_type declarations"]) +
      emitContentSwapProtocol(contentSwaps)
  );
  const definers = contentDefiners(contents);
  await write("content-definers.ts", header(commit, contentSources) + definers.code);
  await write(
    "content-capability.ts",
    header(commit, [...contentSources, "content-manifest.ts"]) + definers.capabilityCode
  );
  await write(
    "vanilla-refs.ts",
    header(commit, [...contentSources, "content-manifest.ts (VANILLA_REF_EXTRAS)"]) +
      'import type { CheckedVanillaId, VanillaId, VanillaTrie } from "../identifiers/contracts.ts";\n' +
      'import { makeEventTrie, makeIdTrie } from "../identifiers/trie.ts";\n' +
      importList(
        "./refs.ts",
        vanillaRefs.refs.map((name) => emitter.refTypeName(name))
      ) +
      "\n" +
      vanillaRefs.code
  );
  await write(
    "triggers.ts",
    header(commit, ["triggers.cwt", "aliases.cwt", "script-docs/v4.4.1/triggers.log"]) +
      'import { block, cmp, kv, type PdxEntry, type PdxOp } from "@pdx-ts/pdxscript";\n' +
      'import type { ContentRefUse } from "../references.ts";\n' +
      (referencesIdentifier(triggers.code, "ScopeValue")
        ? 'import type { ScopeValue } from "../script/effects/types.ts";\n'
        : "") +
      `import { trigger, type Trigger${referencesIdentifier(triggers.code, "ScriptValue") ? ", type ScriptValue" : ""}` +
      `${referencesIdentifier(triggers.code, "scriptValueScalar") ? ", scriptValueScalar" : ""} } ` +
      'from "../script/trigger-core.ts";\n' +
      'import { refId } from "../script/scalar.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        triggerUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        triggerUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        triggerUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      "\n" +
      triggers.code
  );
  await write(
    "links.ts",
    header(commit, ["links.cwt", "script-docs/v4.4.1/scopes.log"]) +
      'import { block } from "@pdx-ts/pdxscript";\n' +
      'import { navigateScope } from "../script/effects/recorder.ts";\n' +
      'import type { ScopeRef, ScopeValue } from "../script/effects/types.ts";\n' +
      'import { trigger, type Trigger } from "../script/trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      scopeLinks.code
  );
  await write(
    "link-meta.ts",
    header(commit, ["links.cwt"]) +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      emitScopeLinkNavigation(classifiedLinks.navigation)
  );
  await write(
    "effects.ts",
    header(commit, [
      "effects.cwt",
      "aliases.cwt",
      "links.cwt",
      "script-docs/v4.4.1/effects.log",
      "script-docs/v4.4.1/scopes.log",
    ]) +
      'import type { PdxOp } from "@pdx-ts/pdxscript";\n' +
      `import type { EffectPath, Modifier, ${referencesIdentifier(effects.interfaces, "ScopeValue") ? "ScopeValue, " : ""}StructuralEffects } from "../script/effects/types.ts";\n` +
      `import type { Trigger${referencesIdentifier(effects.interfaces, "ScriptValue") ? ", ScriptValue" : ""} } ` +
      'from "../script/trigger-core.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n' +
      importList(
        "./enums.ts",
        effectUsage.enums.map((name) => emitter.enumTypeName(name))
      ) +
      importList(
        "./refs.ts",
        effectUsage.refs.map((name) => emitter.refTypeName(name))
      ) +
      importList(
        "./value-sets.ts",
        effectUsage.valueSets.map((name) => emitter.valueSetTypeName(name))
      ) +
      "\n" +
      effects.interfaces
  );
  await write(
    "effect-meta.ts",
    header(commit, ["effects.cwt", "aliases.cwt", "links.cwt"]) + effects.meta
  );
  await write(
    "effect-policy.ts",
    header(commit, ["effects.cwt", "events/events.cwt"]) + emitEffectPolicyProtocol(effectPolicy)
  );
  const events = emitEvents(emitter, effectPolicy);
  await write(
    "events.ts",
    header(commit, ["events/events.cwt"]) +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.code
  );
  await write(
    "event-definers.ts",
    header(commit, ["events/events.cwt"]) +
      'import { assertEventNumber, buildEvent } from "../events/lower.ts";\n' +
      'import type { EventDef, EventItem, EventRef } from "../events/types.ts";\n' +
      'import { assertNamespace } from "../authoring/feature.ts";\n' +
      'import { EVENT_KINDS, type EventKindKey } from "./events.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.definerCode
  );
  await write(
    "event-fires.ts",
    header(commit, ["events/events.cwt", "effects.cwt"]) +
      'import type { FireEventArgs, WitnessedFireEventArgs } from "../events/types.ts";\n' +
      'import type { ScopeName } from "./scopes.ts";\n\n' +
      events.firesCode
  );
  await write(
    "event-fields.ts",
    header(commit, ["events/events.cwt", "codegen-cwt event field support policy"]) +
      emitEventFieldProtocol(eventFieldPolicy)
  );
  const onActions = emitOnActions(rules);
  await write("on-actions.ts", header(commit, ["on_actions.cwt"]) + onActions.code);

  console.log(`cwtools-stellaris-config @ ${commit.slice(0, 12)}`);
  console.log(
    `\nscopes: ${canonicalScopes(rules.scopes).length}` +
      ` | scope groups: ${emitter.usedScopeGroups.size} lowered of ${rules.scopeGroups.size} parsed` +
      ` | enums emitted: ${emitter.usedEnums.size}` +
      ` | refs emitted: ${emitter.usedRefs.size}` +
      ` | value sets emitted: ${emitter.usedValueSets.size}`
  );
  console.log(
    `scope links: ${scopeLinks.emitted} trigger/value fns, ${effects.linkEmitted} effect paths` +
      ` emitted of ${rules.links.size} declared`
  );
  console.log(
    `modifiers: ${modifiers.names} names emitted` +
      ` (${modifiers.universal} universal, ${modifiers.groups} scope-set groups,` +
      ` ${modifiers.scopes} scopes, ${modifiers.trieTypes} path types;` +
      ` ${rules.modifierTemplates.length} cwt template rows)`
  );
  console.log(
    `triggers: ${triggers.emitted} emitted of ${rules.triggers.size} declared` +
      ` (${[...triggers.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")})`
  );
  console.log(
    `effects: ${effects.emitted} emitted of ${rules.effects.size} declared` +
      ` (${[...effects.byShape].map(([kind, n]) => `${kind} ${n}`).join(", ")}` +
      `; clusters ${effects.clusterCount})`
  );
  for (const content of contents) {
    console.log(`${content.registry}: ${fieldCount(content.emission)}`);
  }
  console.log(
    `content definers: ${definers.definers} emitted` +
      ` (${CONTENT_PATCH_REGISTRIES.size} free patchX,` +
      ` ${CONTENT_CONTRIBUTION_SINKS.size} free contribution adder,` +
      ` ${definers.grafted.length} re-exported from a hand-written graft)`
  );
  console.log(
    `vanilla refs: ${vanillaRefs.checked} checked constructors,` +
      ` ${vanillaRefs.tries} tries emitted (${vanillaRefs.refs.length} ref types registered)`
  );
  console.log(
    `event kinds: ${events.kinds} (${events.definers} definers, ` +
      `${events.fireMethods} typed fire methods)`
  );
  console.log(
    `on-actions: ${onActions.emitted} emitted (${onActions.noScope} scopeless and currently rejected)`
  );
  for (const [category, emission] of aliasCategories) {
    // The two kinds count different things, so they say different things. A
    // struct category lowers the category's own members, and the interesting
    // number is how many of them survived. A splice category has exactly one
    // member by construction; what it lowers is the fields *inside* that
    // member's block, so "of 1 declared" would be true and useless.
    const splice = aliasSplices.get(category);
    console.log(
      splice === undefined
        ? `${category}: ${emission.emittedMembers.length} alias-struct members emitted` +
            ` of ${rules.aliasCategories.get(category)?.size ?? 0} declared`
        : `${category}: ${emission.emittedMembers.length} fields emitted into ` +
            `${splice.typeName}, spliced as \`${splice.memberKey}\``
    );
    reportSection(`${category} members declined`, emission.declinedMembers);
  }

  reportSection("Triggers not emitted", summarise(triggers.skipped));
  reportSection("Effects not emitted", summarise(effects.skipped));
  reportSection(
    "Scope links not emitted",
    classifiedLinks.skipped.map((entry) => `${entry.name} — ${entry.reason}`)
  );
  reportSection("Effects emitted scalar-only (block overload dropped)", effects.scalarOnly);
  reportSection("Effect field types replaced by the overlay", effects.fieldTypeOverrides);
  reportSection("On-actions not emitted", onActions.skipped);
  reportSection(
    "Event kinds without full typing",
    events.skipped.map((entry) => `${entry.name} — ${entry.reason}`)
  );
  reportSection("Enums widened to string (rules declare no values)", valuelessEnums(emitter));
  reportSection(
    "Scope parameters widened to string (scopes.cwt declares no such scope)",
    [...emitter.unknownScopes].sort()
  );
  reportSection(
    "Scope parameters widened to string (scopes.cwt declares no such scope_group)",
    [...emitter.unknownScopeGroups].sort()
  );
  reportSection("Content definers taken from the hand-written grafts", definers.grafted);
  reportSection(
    "Body fields renamed off a colliding localization slot",
    contents.flatMap((content) => content.emission.localisationRenames)
  );
  for (const content of contents) {
    const type = content.registry;
    console.log(`\n${type}: ${fieldCount(content.emission)}`);
    reportSection(`${type} fields declined`, content.emission.declinedFields);
    reportSection(
      `${type} alias categories spliced unkeyed at the top level`,
      content.emission.inlineSplices
    );
    reportSection(
      `${content.registry} fields the emitter could not lower`,
      content.emission.unsupported
    );
    reportSection(
      `${content.registry} localization aliases collapsed`,
      content.emission.localisationAliases
    );
    reportSection(
      `${content.registry} fields a patch cannot carry`,
      content.emission.patchExclusions
    );
    reportSection(`${content.registry} patch members widened`, content.emission.patchWidenings);
    reportSection(`${content.registry} patch loc members`, content.emission.patchLocMembers);
  }
}

/**
 * One raw definer per registry: package-internal lowering for the capability
 * surface. A definition remains a pure value, but public authors create it
 * through a capability method and place it with `mod.feature(...)`.
 *
 * The definers are literal-preserving (`<const Id extends string>`), so a
 * definition's id survives as its literal type all the way into the item the
 * definer returns — the property the deleted class methods, generic only in
 * the mod prefix, widened away.
 *
 * Three kinds of registry-specific member, each an overlay row rather than a
 * conditional in this emitter: `CONTENT_PATCH_REGISTRIES` adds a free `patchX`,
 * `CONTENT_CONTRIBUTION_SINKS` a free `addX` for the id-less sink, and
 * `HAND_WRITTEN_CONTENT_DEFINERS` replaces the mechanical `defineX` with a
 * re-export from `src/content/situations.ts`, so the internal lowering surface remains
 * centralized in this module.
 *
 * The `XItem` union types are emitted here too. They remain public as type-only
 * exports even though their raw constructors are internal.
 */
function contentDefiners(
  contents: readonly {
    manifest: ContentManifestEntry;
    registry: string;
    referenceName: string;
    emission: ContentEmission;
  }[]
): {
  code: string;
  capabilityCode: string;
  definers: number;
  grafted: string[];
} {
  const grafted: string[] = [];
  const runtimeItemTypes = new Set<string>(["ContentItem"]);
  const chunks: string[] = [];
  const capabilityMembers: string[] = [];
  const capabilityBindings: string[] = [];
  const profileMembers: string[] = [];
  const defaultProfileMembers: string[] = [];
  const mintShapeRows: { method: string; head: string }[] = [];
  const exactNameRows: { method: string; namePattern: string; exactNamePattern: string }[] = [];
  const shapeMintTypes: string[] = [];
  const shapeMintRefTypes: string[] = [];
  const capabilityRuntimeDefiners = new Set<string>();
  const nestedDefinitionTables: string[] = [];
  const capabilityPatchTypes: { registry: string; emission: ContentEmission }[] = [];

  for (const content of contents) {
    const { registry, emission } = content;
    const name = emission.typeName;
    const key = JSON.stringify(registry);
    const spoken = spokenName(registry);
    const article = indefiniteArticle(spoken);
    const graft = HAND_WRITTEN_CONTENT_DEFINERS.get(registry);
    const patchable = CONTENT_PATCH_REGISTRIES.get(registry);
    const contribution = CONTENT_CONTRIBUTION_SINKS.get(registry);
    const referenceRefinement = CONTENT_SUBTYPE_REFERENCE_REFINEMENTS.get(registry);
    const method = camelCase(registry);
    const mintShape = MINT_SHAPE_OVERLAYS.get(registry);
    const exactName = EXACT_NAME_MINTS.get(registry);
    // An exact name is the complete id, so the mint must be bare: a fixed head
    // would still be prepended and the name would not be exact. The generic
    // member/binding emission below is the only shape the opt-out is written
    // for, so a grafted or scope-parameterised registry cannot carry a row.
    if (exactName !== undefined) {
      if (mintShape === undefined || mintShape.head !== undefined) {
        throw new Error(
          `EXACT_NAME_MINTS row "${registry}" requires a bare MINT_SHAPE_OVERLAYS row (no head)`
        );
      }
      if (graft !== undefined || emission.scopeParameter !== null) {
        throw new Error(
          `EXACT_NAME_MINTS row "${registry}" targets a grafted or scope-parameterised registry, ` +
            "which the emitted overloads do not carry"
        );
      }
    }
    // A shaped registry has no `IdProfile` member to index, so its minted type
    // is the segmentless one. `MintedIdOf` resolves both, and spelling the
    // narrower `MintedContentId` where it applies keeps the emitted signature
    // saying which of the two a registry uses.
    const minted =
      mintShape === undefined
        ? `MintedContentId<P, I, ${JSON.stringify(method)}, Name>`
        : `MintedIdOf<P, I, ${JSON.stringify(method)}, Name>`;
    const nestedDefinitionMembers = emission.emittedFields
      .filter((field) => field.shape === "repeatedStruct")
      .map((field) => camelCase(field.field))
      .sort();
    const nestedDefinitionTable = `${constantCase(emission.typeName)}_NESTED_DEFINITION_MEMBERS`;
    if (nestedDefinitionMembers.length > 0 && graft === undefined) {
      nestedDefinitionTables.push(
        `const ${nestedDefinitionTable} = ${JSON.stringify(nestedDefinitionMembers)} as const;\n`
      );
    }

    if (mintShape === undefined) {
      profileMembers.push(
        docComment(
          [
            `The segment inserted between the mod prefix and ${article} ${spoken}'s logical name.`,
            "Override it when this registry needs a different id convention.",
          ],
          "  "
        ) + `  readonly ${method}: string;`
      );
      defaultProfileMembers.push(
        `  ${method}: ${JSON.stringify(content.manifest.idSegment ?? registry)},`
      );
    } else {
      mintShapeRows.push({ method, head: mintShape.head ?? "" });
    }

    // A scope-parameterised registry erases S to `never`, not to its default:
    // `Trigger<S>` is contravariant, so `Def<Id, never>` is the supertype every
    // scoped variant satisfies, while `Def<Id, "planet">` would both exclude a
    // ship definition from this union and misreport its clauses as planet ones.
    const erased = emission.scopeParameter === null ? "" : "<string, never>";
    // The declared witness is not erased with it. It rides beside the def
    // precisely because it is not part of it, and an item type that dropped it
    // would be a supertype an author reaches by annotating — at which point the
    // effect consuming the definition has nothing left to check (SDK-181). The
    // parameter defaults to every declaration the registry admits, so a list of
    // items still holds declared and undeclared definitions together, and a
    // value widened to that union is ambiguous at the call site rather than
    // unchecked.
    const witness = declaredWitness(content, graft);
    const itemArms = [
      `ContentItem<${key}, ${name}Def${erased}>` +
        (witness === null ? "" : ` & { readonly ${witness.member}: W }`),
    ];
    if (patchable !== undefined) {
      itemArms.push(`${name}PatchItem`);
      runtimeItemTypes.add(`${name}PatchItem`);
    }
    if (contribution !== undefined) {
      itemArms.push("ContributionItem");
      runtimeItemTypes.add("ContributionItem");
    }

    if (graft === undefined) {
      const scoped = emission.scopeParameter;
      // A declared FROM stays a live parameter where S is erased: it is the
      // contract the starting effect's call sites are checked against, so it
      // rides on the item beside the erased def rather than inside it.
      const declaredFrom = scoped?.declaredFrom;
      const declaredFromParameter =
        declaredFrom === undefined
          ? ""
          : `\n    L extends ${declaredFrom.typeName} | undefined = undefined,`;
      const declaration =
        declaredFrom === undefined ? "" : ` & { readonly ${declaredFrom.member}: L }`;
      const parameters =
        scoped === null
          ? "<const Name extends string>"
          : `<\n    const Name extends string,\n    ${scoped.parameterName} extends ` +
            `${scoped.parameterType} = ${JSON.stringify(scoped.parameterFallback)},` +
            `${declaredFromParameter}\n  >`;
      const def =
        `${name}Def<${minted}${scoped === null ? "" : `, ${scoped.parameterName}`}` +
        `${declaredFrom === undefined ? "" : ", L"}>`;
      const input =
        scoped?.selector === undefined
          ? `Omit<${def}, "id">`
          : `${name}Fields<${scoped.parameterName}${declaredFrom === undefined ? "" : ", L"}>`;
      const result = `${name}Def<${minted}${scoped === null ? "" : ", never"}>`;
      const signatures =
        scoped?.selector === undefined
          ? (referenceRefinement === undefined
              ? ""
              : `  ${method}<const Name extends string>(\n` +
                `    name: Name,\n` +
                `    def: Omit<${def}, "id"> & { readonly ${referenceRefinement.member}: true }\n` +
                `  ): ContentItem<${key}, ${result} & { readonly ${referenceRefinement.member}: true }> & ` +
                `${pascalCase(referenceRefinement.reference)}Ref;\n`) +
            `  ${method}${parameters}(\n` +
            `    name: Name,\n` +
            `    def: ${input}\n` +
            `  ): ContentItem<${key}, ${result}>${declaration};`
          : `  ${method}<\n    const Name extends string,${declaredFromParameter}\n  >(\n` +
            `    name: Name,\n` +
            `    def: ` +
            Object.keys(scoped.selector.scopes)
              .map(
                (eventScope) =>
                  `${name}Fields<${JSON.stringify(eventScope)}` +
                  `${declaredFrom === undefined ? "" : ", L"}>`
              )
              .join(" | ") +
            `\n  ): ContentItem<${key}, ${name}Def<${minted}, never>>${declaration};`;
      if (exactName === undefined) {
        capabilityMembers.push(
          docComment(
            [
              `Defines ${article} ${spoken} from its logical name.`,
              "The capability mints and owns the full id; the returned branded reference",
              "flows into matching content-reference fields.",
              ...(nestedDefinitionMembers.length === 0
                ? []
                : [
                    "Nested-definition record keys are full ids and must belong to this capability's",
                    "prefix, because other fields may reference them directly.",
                  ]),
            ],
            "  "
          ) + signatures
        );
        capabilityBindings.push(
          capabilityBinding(
            method,
            parameters,
            input,
            `define${name}`,
            def,
            nestedDefinitionMembers,
            nestedDefinitionTable
          )
        );
      } else {
        // The exact-name pair (SDK-183): the ordinary prefixed mint with the
        // registry's widened charset, and the `prefix: false` overload under
        // which the author spells the complete name. One runtime binding
        // serves both — `mint` reads the option and the generated
        // `EXACT_NAME_MINTS` table, so the branch lives in data, not here.
        if (nestedDefinitionMembers.length > 0) {
          throw new Error(
            `EXACT_NAME_MINTS row "${registry}" has nested definition members, which the ` +
              "emitted overloads do not carry"
          );
        }
        exactNameRows.push({
          method,
          namePattern: exactName.namePattern,
          exactNamePattern: exactName.exactNamePattern,
        });
        capabilityMembers.push(
          docComment(
            [
              `Defines ${article} ${spoken} from its logical name.`,
              "The capability mints and owns the full id; the returned branded reference",
              "flows into matching content-reference fields.",
              `A ${spoken} name is a raw engine label, so the logical name accepts`,
              "interior uppercase after its leading lowercase letter ([a-z][A-Za-z0-9_]*).",
            ],
            "  "
          ) +
            `  ${method}<const Name extends string>(\n` +
            `    name: Name,\n` +
            `    def: ${input},\n` +
            `    options?: { readonly prefix?: true }\n` +
            `  ): ContentItem<${key}, ${result}>;\n` +
            docComment(
              [
                `Defines ${article} ${spoken} from its complete name.`,
                "`prefix: false` means only that the capability does not prepend the mod",
                "prefix — the prefix is still required inside `name` as a `_`-delimited",
                "segment (head, interior, or tail). The `Name` constraint enforces that at",
                "compile time and the mint re-checks it at runtime, so the name stays",
                "ownable and clear of other mods by construction. The minting capability",
                "is recorded and placement verifies the record, so a name carrying a",
                "second mod's prefix as another segment still places only with its minter.",
              ],
              "  "
            ) +
            `  ${method}<const Name extends ExactMintName<P>>(\n` +
            `    name: Name,\n` +
            `    def: Omit<${name}Def<Name>, "id">,\n` +
            `    options: { readonly prefix: false }\n` +
            `  ): ContentItem<${key}, ${name}Def<Name>>;`
        );
        capabilityBindings.push(
          `    ${method}: ${parameters}(name: Name, def: ${input}, options?: MintNameOptions) => {\n` +
            `      const item = define${name}({ ...def, id: mint(${JSON.stringify(method)}, name, options) } as ${def});\n` +
            `      return options?.prefix === false ? recordExactNameMint(item, mintOwner) : item;\n` +
            "    },"
        );
      }
      capabilityRuntimeDefiners.add(`define${name}`);
      for (const shape of shapesFor(registry)) {
        if (emission.scopeParameter !== null) {
          throw new Error(
            `Shape mint ${shape.method} targets scope-parameterised registry "${registry}", ` +
              "whose definitions take a scope argument the emitted signature does not carry"
          );
        }
        const emitted = shapeMintMethod(shape, name, contents);
        shapeMintTypes.push(emitted.type);
        capabilityMembers.push(emitted.member);
        capabilityBindings.push(emitted.binding);
        shapeMintRefTypes.push(...emitted.refTypes);
      }
    }
    if (patchable !== undefined) {
      capabilityMembers.push(
        docComment(
          [
            `Patches a vanilla ${spoken} as a whole-object override.`,
            "Unlike a capability definition method, it mints no id and owns no new content —",
            "but it does mint localisation keys for text it adds, from this capability's",
            "prefix, which is why the method is bound to the capability rather than free.",
          ],
          "  "
        ) +
          `  patch${name}<Source extends Parsed${name}>(\n` +
          `    ${camelCase(registry)}: Source,\n` +
          `    patch: (${camelCase(registry)}: Source) => ${name}Patch\n` +
          `  ): ${name}PatchItem;`
      );
      capabilityBindings.push(
        `    patch${name}: <Source extends Parsed${name}>(\n` +
          `      ${camelCase(registry)}: Source,\n` +
          `      patch: (${camelCase(registry)}: Source) => ${name}Patch\n` +
          `    ) => patch${name}(${camelCase(registry)}, patch, prefix),`
      );
      capabilityRuntimeDefiners.add(`patch${name}`);
      capabilityPatchTypes.push(content);
    }
    if (contribution !== undefined) {
      capabilityMembers.push(
        docComment(
          [
            `Adds ids to the shared ${contribution.sink} sink.`,
            "This is an id-less additive contribution, not a capability-owned definition.",
          ],
          "  "
        ) + `  readonly ${contribution.method}: typeof ${contribution.method};`
      );
      capabilityBindings.push(`    ${contribution.method},`);
      capabilityRuntimeDefiners.add(contribution.method);
    }

    const definitions: string[] = [];
    if (graft === undefined) {
      // A registry whose scopes are a property of the definition takes a second
      // type parameter and one extra authoring member. The member is stripped
      // before the def is stored: it is not a game key, and the returned item
      // erases S so a `"ship"` definition still belongs to this registry's item
      // union — `Trigger<S>` is contravariant, so a leaked S would make it not.
      const scoped = emission.scopeParameter;
      // A declared FROM is stripped like `scope` and, unlike it, kept: the
      // starting effect's call sites are checked against the declaration, so
      // the item carries it beside the def whose own parameter is erased.
      const declaredFrom = scoped?.declaredFrom;
      const declaredFromParameter =
        declaredFrom === undefined
          ? ""
          : `  L extends ${declaredFrom.typeName} | undefined = undefined,\n`;
      const declaration =
        declaredFrom === undefined ? "" : ` & { readonly ${declaredFrom.member}: L }`;
      const carried =
        declaredFrom === undefined ? "" : `, ${declaredFrom.member}: ${declaredFrom.member} as L`;
      const parameters =
        scoped === null
          ? "<const Id extends string>"
          : `<\n  const Id extends string,\n  ${scoped.parameterName} extends ` +
            `${scoped.parameterType} = ${JSON.stringify(scoped.parameterFallback)},\n` +
            `${declaredFromParameter}>`;
      const stripped = [
        ...(scoped !== null && scoped.selector === undefined ? ["scope"] : []),
        ...(declaredFrom === undefined ? [] : [declaredFrom.member]),
      ];
      const body =
        scoped === null
          ? `  return { itemKind: "content", type: ${key}, id: def.id, def };\n`
          : stripped.length === 0
            ? `  return { itemKind: "content", type: ${key}, id: def.id, ` +
              `def: def as unknown as ${name}Def<Id, never> };\n`
            : `  const { ${stripped.join(", ")}, ...rest } = def;\n` +
              `  return { itemKind: "content", type: ${key}, id: def.id, ` +
              `def: rest as unknown as ${name}Def<Id, never>${carried} };\n`;
      definitions.push(
        docComment([
          `Internal lowering primitive for ${article} ${spoken}. Public authors call`,
          `\`mod.${camelCase(registry)}(name, def)\`, then place the returned item with`,
          "`mod.feature(...)` before compiling the same capability.",
          ...(scoped === null
            ? []
            : [
                "",
                ...(scoped.selector === undefined
                  ? [
                      "`scope` names which scope this definition's clauses run in and emits",
                      `nothing; it defaults to \`${scoped.fallback}\`.`,
                    ]
                  : [
                      `\`${scoped.selector.member}\` selects which scope this definition's callbacks run in.`,
                    ]),
                ...(declaredFrom === undefined
                  ? []
                  : [
                      `\`${declaredFrom.member}\` declares the location scope \`${declaredFrom.effect}\``,
                      "hands the callbacks as FROM; it emits nothing and rides on the item,",
                      "where the effect's own call sites are checked against it.",
                    ]),
              ]),
        ]) +
          `export function define${name}${parameters}(\n` +
          `  def: ${name}Def<Id${scoped === null ? "" : `, ${scoped.parameterName}`}` +
          `${declaredFrom === undefined ? "" : ", L"}>\n` +
          `): ContentItem<${key}, ${name}Def<Id${scoped === null ? "" : ", never"}>>` +
          `${declaration} {\n` +
          body +
          "}\n"
      );
    } else {
      grafted.push(`${registry}.define${name} — ${graft.reason}`);
      definitions.push(
        `// define${name} is hand-written; re-exported here so every definer this\n` +
          "// SDK has comes from one module.\n" +
          `export { ${graft.definer} } from ${JSON.stringify(graft.module)};\n`
      );
    }
    if (patchable !== undefined) {
      definitions.push(
        docComment([
          `Internal lowering primitive for patching ${article} vanilla ${spoken}. The transform`,
          "runs here (pure); public authors call the capability method, while the duplicate-key",
          "and one-view checks stay in",
          "the internal fold, which sees every patch together, and the emitted filename",
          "is always resolver-computed — a patch item never carries a file of its own.",
          "",
          "`prefix` is the mod prefix the capability closure binds: a patch that mints a",
          "localisation key of its own derives it from `<prefix>_<vanilla id>`, so the key",
          "cannot collide with vanilla's by construction.",
        ]) +
          `export function patch${name}<Source extends Parsed${name}>(\n` +
          `  ${camelCase(registry)}: Source,\n` +
          `  patch: (${camelCase(registry)}: Source) => ${name}Patch,\n` +
          `  prefix: string\n` +
          `): ${name}PatchItem {\n` +
          `  return {\n` +
          `    itemKind: "patch",\n` +
          `    patched: patchContent(\n` +
          `      ${camelCase(registry)},\n` +
          `      patch,\n` +
          `      ${key},\n` +
          `      ${emission.fieldsConstant},\n` +
          `      ${emission.localisationConstant},\n` +
          `      prefix\n` +
          `    ),\n` +
          "  };\n" +
          "}\n"
      );
    }
    if (contribution !== undefined) {
      definitions.push(
        docComment([
          `Internal lowering primitive for the shared additive \`default = { ${contribution.sink} = ... }\``,
          "sink. Public authors call the capability method; ids this mod names but does not own",
          "have no author-named file.",
          "A ref listed twice is emitted once.",
        ]) +
          `export function ${contribution.method}(\n` +
          `  ${camelCase(contribution.sink)}: readonly (TypedRef<${JSON.stringify(contribution.refRegistry)}> | string)[]\n` +
          "): ContributionItem {\n" +
          "  return {\n" +
          '    itemKind: "contribution",\n' +
          `    registry: ${JSON.stringify(contribution.sink)},\n` +
          `    refRegistry: ${JSON.stringify(contribution.refRegistry)},\n` +
          `    ids: ${camelCase(contribution.sink)}.map((entry) => String(refId(entry))),\n` +
          "  };\n" +
          "}\n"
      );
    }

    chunks.push(
      docComment([
        `What ${article} ${spoken} feature can contain.`,
        ...(witness === null
          ? []
          : [
              `Parameterised by the declared \`${witness.member}\`, which the item carries`,
              "and the effect consuming it is checked against: naming this type without",
              "the parameter widens the declaration to every scope the registry admits,",
              "which is checkable as none of them.",
            ]),
      ]) +
        `export type ${name}Item${
          witness === null ? "" : `<W extends ${witness.type} = ${witness.type}>`
        } = ${itemArms.join(" | ")};\n\n` +
        definitions.join("\n")
    );
  }

  const patchContents = contents.filter((content) =>
    CONTENT_PATCH_REGISTRIES.has(content.registry)
  );
  const refImports = contents.some((content) => CONTENT_CONTRIBUTION_SINKS.has(content.registry));
  const contentItemTypes = [...runtimeItemTypes].filter((name) => !name.endsWith("PatchItem"));
  // A hand-written definer's declared witness is spelled in the overlay, so
  // the type it names has to be imported on its word rather than derived —
  // `ScopeName` is the only one so far, and it is the only scope type this
  // module could need.
  const witnessScopeName = contents.some((content) =>
    HAND_WRITTEN_CONTENT_DEFINERS.get(content.registry)?.witness?.type.includes("ScopeName")
  );
  const imports =
    importList("../content/types.ts", contentItemTypes) +
    (witnessScopeName ? 'import type { ScopeName } from "./scopes.ts";\n' : "") +
    (refImports ? 'import { refId, type TypedRef } from "../script/scalar.ts";\n' : "") +
    // One generic transform, called with the registry's own field descriptors:
    // the patch surface is descriptor-derived the whole way down, so nothing
    // per-registry is imported from a hand-written module.
    (patchContents.length === 0
      ? ""
      : 'import { patchContent } from "../stellaris/vanilla/patch.ts";\n') +
    patchContents
      .map(
        (content) =>
          `import type { Parsed${content.emission.typeName} } ` +
          'from "../stellaris/vanilla/view.ts";\n'
      )
      .join("") +
    contents
      .map((content) => {
        const from = `./${kebabCase(content.registry)}.ts`;
        const types = [
          `${content.emission.typeName}Def`,
          // A scope-parameterised definer constrains S by the registry's own
          // scope union, so that type has to travel with the Def.
          ...(content.emission.scopeParameter === null
            ? []
            : [content.emission.scopeParameter.typeName]),
          ...(content.emission.scopeParameter?.declaredFrom === undefined
            ? []
            : [content.emission.scopeParameter.declaredFrom.typeName]),
        ];
        if (!CONTENT_PATCH_REGISTRIES.has(content.registry)) {
          return importList(from, types);
        }
        const names = [
          content.emission.fieldsConstant,
          content.emission.localisationConstant,
          ...[
            ...types,
            `${content.emission.typeName}Patch`,
            `${content.emission.typeName}PatchItem`,
          ]
            .sort()
            .map((name) => `type ${name}`),
        ];
        return `import { ${names.join(", ")} } from ${JSON.stringify(from)};\n`;
      })
      .join("") +
    importList("./enums.ts", [
      ...new Set(
        contents.flatMap((content) =>
          content.emission.scopeParameter?.selector === undefined
            ? []
            : [content.emission.scopeParameter.parameterType]
        )
      ),
    ]);
  const capabilityImports =
    'import type { ContentItem } from "../content/types.ts";\n' +
    importList(
      "./refs.ts",
      [...CONTENT_SUBTYPE_REFERENCE_REFINEMENTS.values()].map(
        (refinement) => `${pascalCase(refinement.reference)}Ref`
      )
    ) +
    (shapeMintTypes.length === 0 && exactNameRows.length === 0
      ? ""
      : "import {\n" +
        (exactNameRows.length === 0 ? "" : "  recordExactNameMint,\n") +
        (shapeMintTypes.length === 0 ? "" : "  recordShapeMint,\n") +
        "  type MintCapabilityOwner,\n} " +
        'from "../content/mint-provenance.ts";\n') +
    (shapeMintTypes.length === 0
      ? ""
      : 'import { refId, type TypedRef } from "../script/scalar.ts";\n' +
        importList("./refs.ts", shapeMintRefTypes)) +
    (capabilityRuntimeDefiners.size === 0
      ? ""
      : `import { ${[...capabilityRuntimeDefiners].sort().join(", ")} } from "./content-definers.ts";\n`) +
    // The parsed side of every patchable registry: a capability's `patchX` is a
    // closure over the prefix rather than a re-export, so its signature is
    // spelled here and needs the same types the free function's does.
    capabilityPatchTypes
      .map(
        (content) =>
          `import type { Parsed${content.emission.typeName} } ` +
          'from "../stellaris/vanilla/view.ts";\n'
      )
      .join("") +
    contents
      .map((content) =>
        importList(`./${kebabCase(content.registry)}.ts`, [
          `${content.emission.typeName}Def`,
          ...(content.emission.scopeParameter?.selector === undefined
            ? []
            : [`${content.emission.typeName}Fields`]),
          ...(content.emission.scopeParameter === null
            ? []
            : [content.emission.scopeParameter.typeName]),
          ...(content.emission.scopeParameter?.declaredFrom === undefined
            ? []
            : [content.emission.scopeParameter.declaredFrom.typeName]),
          ...(CONTENT_PATCH_REGISTRIES.has(content.registry)
            ? [`${content.emission.typeName}Patch`, `${content.emission.typeName}PatchItem`]
            : []),
        ])
      )
      .join("") +
    importList("./enums.ts", [
      ...new Set(
        contents.flatMap((content) =>
          content.emission.scopeParameter?.selector === undefined
            ? []
            : [content.emission.scopeParameter.parameterType]
        )
      ),
    ]);
  const capability =
    nestedDefinitionTables.join("\n") +
    "type NestedDefinitionIdAsserter = (id: string) => void;\n\n" +
    (nestedDefinitionTables.length === 0
      ? ""
      : "function assertNestedDefinitionIds(\n" +
        "  def: object,\n" +
        "  assert: NestedDefinitionIdAsserter,\n" +
        "  members: readonly string[]\n" +
        "): void {\n" +
        "  for (const member of members) {\n" +
        "    const nested = (def as Readonly<Record<string, unknown>>)[member];\n" +
        "    if (nested === undefined) {\n" +
        "      continue;\n" +
        "    }\n" +
        "    Object.keys(nested as Readonly<Record<string, unknown>>).forEach(assert);\n" +
        "  }\n" +
        "}\n\n") +
    (shapeMintTypes.length === 0
      ? ""
      : "type LogicalNameAsserter = (name: string) => void;\n\n" +
        docComment([
          "The id a shape mint fills its hole with.",
          "",
          "A typed item or reference lowers to its id; an intentional raw string — a",
          "target this build does not contain — passes through. Neither may be empty or",
          "carry whitespace: the minted name is the single bare word the game looks the",
          "sprite up by, so a hole that swallowed a space would emit a definition nothing",
          "can reference.",
        ]) +
        "function shapeMintTarget(target: TypedRef<string> | string): string {\n" +
        '  const id = typeof target === "string" ? target : refId(target);\n' +
        '  if (typeof id !== "string" || id === "" || /\\s/.test(id)) {\n' +
        "    throw new Error(\n" +
        "      `A shape-minted sprite's target must be one bare word; received ${JSON.stringify(id)}`\n" +
        "    );\n" +
        "  }\n" +
        "  return id;\n" +
        "}\n\n" +
        docComment([
          "Records which capability minted a shape-minted definition, and under which",
          "shape.",
          "",
          "A shape mint may carry no mod prefix at all — the name is built from another",
          "definition's id — so a string-prefix test cannot decide whether the item",
          "belongs to the capability placing it. `recordShapeMint` puts the answer in a",
          "module-private `WeakMap` no caller can write to, which is what the placement",
          "check reads. The `minted` property beside it is informational only: it is a",
          "public object an author could attach to anything, so it proves nothing and is",
          "never consulted.",
        ]) +
        'function shapeMinted<T extends { readonly itemKind: "content" }>(\n' +
        "  item: T,\n" +
        "  owner: MintCapabilityOwner,\n" +
        "  shape: string\n" +
        "): T {\n" +
        "  return recordShapeMint(\n" +
        "    { ...item, minted: { prefix: owner.prefix, shape } } as T,\n" +
        "    owner,\n" +
        "    shape\n" +
        "  );\n" +
        "}\n\n") +
    docComment([
      "Registry-specific id segments used when a mod capability mints content ids.",
      "Each member may override the conventional segment for its registry.",
    ]) +
    "export interface IdProfile {\n" +
    profileMembers.join("\n") +
    "\n}\n\n" +
    docComment(["The conventional id segments used when no profile override is supplied."]) +
    "export const DEFAULT_ID_PROFILE = Object.freeze({\n" +
    defaultProfileMembers.join("\n") +
    "\n}) satisfies IdProfile;\n\n" +
    docComment([
      "The literal each segmentless registry's minted name carries before the mod prefix.",
      "",
      "A registry appears here exactly when it has no `IdProfile` segment: its name is",
      "`${head}${prefix}_${name}`, the head is fixed by the game rather than chosen by",
      "the author, and there is nothing for a profile to override. The empty string is a",
      "head — it says the mint is bare, not that the registry is absent.",
    ]) +
    "export const MINT_SHAPES = Object.freeze({\n" +
    mintShapeRows.map((row) => `  ${row.method}: ${JSON.stringify(row.head)},`).join("\n") +
    "\n} as const);\n\n" +
    docComment(["A registry whose name is minted without an id segment."]) +
    "export type MintShapedRegistry = keyof typeof MINT_SHAPES;\n\n" +
    docComment([
      "The registries whose names are raw engine labels (SDK-183). Each row widens",
      "the logical-name charset for the ordinary prefixed mint (`name`) and states",
      "the charset a complete `prefix: false` name must satisfy (`exact`). The",
      "runtime mint reads this table; the registries are the overlay's",
      "`EXACT_NAME_MINTS` rows, so the typed overloads and the runtime checks come",
      "from the same data.",
    ]) +
    "export const EXACT_NAME_MINTS = Object.freeze({\n" +
    exactNameRows
      .map(
        (row) =>
          `  ${row.method}: Object.freeze({ name: /${row.namePattern}/, ` +
          `exact: /${row.exactNamePattern}/ }),`
      )
      .join("\n") +
    "\n} as const);\n\n" +
    docComment(["A registry whose mint offers the exact-name opt-out."]) +
    "export type ExactNameRegistry = keyof typeof EXACT_NAME_MINTS;\n\n" +
    docComment([
      "A complete definition name an author may spell with `prefix: false`: the mod",
      "prefix must appear as a `_`-delimited segment — head, tail, or interior. The",
      "bare prefix alone matches no arm, so a name that is nothing but the prefix is",
      "a compile error, like a name missing the segment entirely.",
    ]) +
    "export type ExactMintName<P extends string> =\n" +
    "  | `${P}_${string}`\n" +
    "  | `${string}_${P}`\n" +
    "  | `${string}_${P}_${string}`;\n\n" +
    docComment([
      "Options an exact-name registry's capability method forwards to the mint.",
      "`prefix: false` means the name is the complete definition id; the default",
      "mints `${prefix}_${name}` as every other registry does.",
    ]) +
    "export type MintNameOptions = { readonly prefix?: boolean };\n\n" +
    docComment([
      "The literal id a capability mints for one logical content name, for a registry",
      "carrying an `IdProfile` segment.",
    ]) +
    "export type MintedContentId<\n" +
    "  P extends string,\n" +
    "  I extends IdProfile,\n" +
    "  K extends keyof I,\n" +
    "  Name extends string,\n" +
    "> = `${P}_${I[K] & string}_${Name}`;\n\n" +
    docComment([
      "The literal id a capability mints for one logical content name, for any registry.",
      "",
      "One arm per `MINT_SHAPES` member, then the segmented default. The arms are",
      "generated from the same table the runtime reads, so a registry cannot mint one",
      "shape and be typed as another.",
    ]) +
    "export type MintedIdOf<\n" +
    "  P extends string,\n" +
    "  I extends IdProfile,\n" +
    "  K extends keyof I | MintShapedRegistry,\n" +
    "  Name extends string,\n" +
    "> = " +
    mintShapeRows
      .map(
        (row) => `K extends ${JSON.stringify(row.method)}\n  ? \`${row.head}\${P}_\${Name}\`\n  : `
      )
      .join("") +
    "MintedContentId<P, I, K & keyof I, Name>;\n\n" +
    docComment([
      "The internal function that turns a registry key and logical name into an owned id.",
    ]) +
    "export type ContentIdMinter<P extends string, I extends IdProfile> = <\n" +
    "  const K extends keyof I | MintShapedRegistry,\n" +
    "  const Name extends string,\n" +
    ">(registry: K, name: Name, options?: MintNameOptions) => MintedIdOf<P, I, K, Name>;\n\n" +
    shapeMintTypes.join("\n") +
    (shapeMintTypes.length === 0 ? "" : "\n") +
    docComment(["Content authoring methods bound to one mod capability's prefix and id profile."]) +
    "export interface ContentCapabilityMethods<P extends string, I extends IdProfile> {\n" +
    capabilityMembers.join("\n") +
    "\n}\n\n" +
    docComment(["Builds the internal content-method table for a mod capability."]) +
    "export function contentCapabilityMethods<P extends string, I extends IdProfile>(\n" +
    "  mint: ContentIdMinter<P, I>,\n" +
    "  assertNestedId: NestedDefinitionIdAsserter,\n" +
    "  prefix: P" +
    // `assertName` only serves shape mints: it holds a name-derived mint to the
    // same logical-name rule every mint follows. `mintOwner` is the identity a
    // shape mint or an exact-name mint is recorded against. Emitting either
    // where no row needs it would leave the generated function with parameters
    // it never reads.
    (shapeMintTypes.length === 0 && exactNameRows.length === 0
      ? "\n"
      : shapeMintTypes.length === 0
        ? ",\n  mintOwner: MintCapabilityOwner\n"
        : ",\n  assertName: LogicalNameAsserter,\n  mintOwner: MintCapabilityOwner\n") +
    "): ContentCapabilityMethods<P, I> {\n" +
    "  return Object.freeze({\n" +
    capabilityBindings.join("\n") +
    "\n  }) as ContentCapabilityMethods<P, I>;\n" +
    "}\n";

  return {
    code: imports + "\n" + chunks.join("\n"),
    capabilityCode: capabilityImports + "\n" + capability,
    definers: contents.length,
    grafted,
  };
}

/** The audited shape mints one registry owns. */
function shapesFor(registry: string): readonly SpriteShapeMint[] {
  return registry === SHAPE_MINT_REGISTRY ? SPRITE_SHAPE_MINTS : [];
}

/**
 * One {@link SPRITE_SHAPE_MINTS} row as a capability method.
 *
 * Nothing here is per-row hand code: the name type, the signature, the runtime
 * mint and the provenance all come out of the row's head, hole and variants.
 * Adding a row adds a method; there is no second place to edit.
 *
 * The name type is emitted as its own alias so the signature stays readable and
 * so an author can spell the minted name themselves. Variants append their
 * literal in declaration order, on both sides — the type appends it behind a
 * conditional on the option's own boolean parameter, the runtime behind the
 * same option's value — so the two cannot disagree about what a variant is
 * called.
 */
function shapeMintMethod(
  shape: SpriteShapeMint,
  typeName: string,
  contents: readonly { readonly registry: string; readonly referenceName: string }[]
): {
  readonly type: string;
  readonly member: string;
  readonly binding: string;
  readonly refTypes: readonly string[];
} {
  const alias = `${pascalCase(shape.method)}Name`;
  const variants = shape.variants ?? [];
  const variantParameters = variants.map(
    (variant) => `${pascalCase(variant.option)} extends boolean = false`
  );
  const variantArguments = variants.map((variant) => pascalCase(variant.option));
  const variantTypeTail = variants
    .map(
      (variant) =>
        `\${${pascalCase(variant.option)} extends true ? ${JSON.stringify(variant.suffix)} : ""}`
    )
    .join("");
  const variantRuntimeTail = variants
    .map(
      (variant) =>
        `\${options?.${variant.option} === true ? ${JSON.stringify(variant.suffix)} : ""}`
    )
    .join("");
  const optionsParameter =
    variants.length === 0
      ? ""
      : `,\n    options?: { ${variants
          .map((variant) => `readonly ${variant.option}?: ${pascalCase(variant.option)}`)
          .join("; ")} }`;

  const named = shape.hole === "name";
  const target = named ? undefined : (shape.hole as { readonly targetRegistry: string });
  const targetContent =
    target === undefined
      ? undefined
      : contents.find((content) => content.registry === target.targetRegistry);
  if (target !== undefined && targetContent === undefined) {
    throw new Error(
      `Shape mint ${shape.method} targets registry "${target.targetRegistry}", which the content ` +
        "manifest does not expose"
    );
  }
  const refType =
    targetContent === undefined ? undefined : `${pascalCase(targetContent.referenceName)}Ref`;
  const parameterName = target === undefined ? "name" : camelCase(target.targetRegistry);

  const aliasParameters = named
    ? ["P extends string", "Name extends string", ...variantParameters]
    : ["Target extends string", ...variantParameters];
  const aliasBody = named
    ? `\`${shape.head}\${P}_\${Name}${variantTypeTail}\``
    : `\`${shape.head}\${Target}${variantTypeTail}\``;
  const nameType = named
    ? `${alias}<P, Name${variantArguments.map((one) => `, ${one}`).join("")}>`
    : `${alias}<Target${variantArguments.map((one) => `, ${one}`).join("")}>`;
  const def = `${typeName}Def<${nameType}>`;
  const methodParameters = [
    named ? "const Name extends string" : "const Target extends string",
    ...variantParameters.map((one) => `const ${one}`),
  ].join(",\n    ");
  const argument = named
    ? "name: Name"
    : `${parameterName}: Target | (${refType} & { readonly id: Target })`;
  const runtimeHole = named ? `\${prefix}_\${name}` : `\${shapeMintTarget(${parameterName})}`;

  return {
    type:
      docComment([`The name a \`${shape.method}\` mints.`, "", `Seed: ${shape.seed}.`]) +
      `export type ${alias}<\n  ${aliasParameters.join(",\n  ")},\n> = ${aliasBody};\n`,
    member:
      docComment(
        [
          `Defines the \`${shape.head}\`-led sprite the game generates${
            named ? " from a name" : ` from a ${spokenName(target!.targetRegistry)}`
          }.`,
          named
            ? "The capability mints and owns the full name, exactly as an ordinary definition does."
            : "The minted name carries the target's id rather than the mod prefix, so ownership " +
              "rides on the item as mint provenance instead of on the string.",
          `In every other respect this is an ordinary ${spokenName(SHAPE_MINT_REGISTRY)} definition.`,
          "",
          `Seed: ${shape.seed}`,
        ],
        "  "
      ) +
      `  ${shape.method}<\n    ${methodParameters},\n  >(\n` +
      `    ${argument},\n` +
      `    def: Omit<${def}, "id">${optionsParameter}\n` +
      `  ): ContentItem<${JSON.stringify(SHAPE_MINT_REGISTRY)}, ${def}>;`,
    binding:
      `    ${shape.method}: <\n      ${methodParameters},\n    >(\n` +
      `      ${argument},\n` +
      `      def: Omit<${def}, "id">${optionsParameter.replace("\n    ", "\n      ")}\n` +
      `    ) => {\n` +
      (named ? `      assertName(name);\n` : "") +
      `      return shapeMinted(\n` +
      `        define${typeName}({\n` +
      `          ...def,\n` +
      `          id: \`${shape.head}${runtimeHole}${variantRuntimeTail}\` as ${nameType},\n` +
      `        } as ${def}),\n` +
      `        mintOwner,\n` +
      `        ${JSON.stringify(shape.method)}\n` +
      `      );\n` +
      `    },`,
    refTypes: refType === undefined ? [] : [refType],
  };
}

/**
 * The declared contract a registry's item carries beside its def, from
 * whichever side owns the definer.
 *
 * Generated definers learn it from the overlay's `declaredFrom` row; a
 * hand-written one has to say so itself, since nothing in the rules mentions
 * the property it returns. Either way the item type has to match what the
 * definer actually returns, which is what this keeps in one place.
 */
function declaredWitness(
  content: { readonly emission: ContentEmission },
  graft: HandWrittenDefiner | undefined
): { readonly member: string; readonly type: string } | null {
  if (graft?.witness !== undefined) {
    return graft.witness;
  }
  const declaredFrom = content.emission.scopeParameter?.declaredFrom;
  return declaredFrom === undefined
    ? null
    : { member: declaredFrom.member, type: `${declaredFrom.typeName} | undefined` };
}

function capabilityBinding(
  method: string,
  parameters: string,
  definitionArgument: string,
  definer: string,
  definitionType: string,
  nestedDefinitionMembers: readonly string[],
  nestedDefinitionTable: string
): string {
  const withId = `{ ...def, id: mint(${JSON.stringify(method)}, name) }`;
  if (nestedDefinitionMembers.length === 0) {
    return (
      `    ${method}: ${parameters}(name: Name, def: ${definitionArgument}) =>\n` +
      `      ${definer}(${withId} as ${definitionType}),`
    );
  }
  return (
    `    ${method}: ${parameters}(name: Name, def: ${definitionArgument}) => {\n` +
    `      assertNestedDefinitionIds(def, assertNestedId, ${nestedDefinitionTable});\n` +
    `      return ${definer}(${withId} as ${definitionType});\n` +
    "    },"
  );
}

const REGISTRY_NAME = /^[A-Za-z][A-Za-z0-9_]*$/;

/**
 * Checks one row's resolved registry name before anything derives from it.
 *
 * The name reaches an exported symbol, a capability method, a generated file
 * stem and a fixture stem, so a name that is not an identifier stem fails the
 * build somewhere far from the row that caused it. A `name` that merely
 * restates what `as ?? type` already yields is dead weight that would drift,
 * and two rows resolving to one name would silently overwrite each other's
 * generated file.
 */
function assertRegistryName(
  entry: ContentManifestEntry,
  registry: string,
  seen: Set<string>
): void {
  if (!REGISTRY_NAME.test(registry)) {
    throw new Error(
      `The manifest resolves type[${entry.type}] to registry name "${registry}", which is not ` +
        "a legal identifier stem"
    );
  }
  if (entry.name !== undefined && entry.name === (entry.as ?? entry.type)) {
    throw new Error(
      `The manifest's name "${entry.name}" for type[${entry.type}] is what the row already ` +
        "resolves to, so the rename says nothing — drop it"
    );
  }
  if (seen.has(registry)) {
    throw new Error(
      `Two manifest rows resolve to the registry name "${registry}", so they would generate ` +
        "over each other"
    );
  }
  seen.add(registry);
}

/**
 * The `## type_key_filter` that constrains one manifest row's keyword.
 *
 * A type-level filter constrains every row reading that type. Where the type
 * declares none, an `as` row is one subtype of it, and it is that subtype's own
 * filter that says which key its definitions are written under — which is what
 * lets the three `component_template` keywords and `sprite`'s `spriteType` be
 * checked rather than trusted.
 *
 * A negated filter (`<> random_list`) names a key the entries are *not*
 * written under, so it constrains nothing about the keyword and is dropped
 * here rather than compared against.
 */
function effectiveKeyFilter(
  type: ContentType,
  as: string | undefined
): { readonly key: string; readonly source: string } | null {
  if (type.keyFilter !== null) {
    return type.keyFilter.negated
      ? null
      : { key: type.keyFilter.key, source: `type[${type.name}]` };
  }
  if (as === undefined) {
    return null;
  }
  const subtype = type.subtypes.find((candidate) => candidate.name === as);
  if (subtype?.keyFilter == null || subtype.keyFilter.negated) {
    return null;
  }
  return { key: subtype.keyFilter.key, source: `type[${type.name}] subtype[${as}]` };
}

function contentRegistry(
  contents: readonly {
    manifest: (typeof CONTENT_MANIFEST)[number];
    registry: string;
    referenceName: string;
    keyword: string | undefined;
    type: ContentType;
    emission: ContentEmission;
  }[]
): string {
  const imports = contents
    .map((content) => {
      const file = `./${kebabCase(content.registry)}.ts`;
      const values = [content.emission.fieldsConstant, content.emission.localisationConstant];
      return `import { ${values.join(", ")} } from ${JSON.stringify(file)};\n`;
    })
    .join("");
  const descriptors = contents
    .map((content) => {
      const sourcePath = content.type.path;
      if (sourcePath === null || !sourcePath.startsWith("game/")) {
        throw new Error(`type[${content.registry}] has unusable path ${sourcePath}`);
      }
      const outputDir = sourcePath.slice("game/".length);
      // The directory's own last component, unless SDK-121 fixed a canonical
      // stem for this registry — see `FILE_STEM_OVERLAYS`.
      const fileStem = FILE_STEM_OVERLAYS.get(content.registry) ?? path.posix.basename(outputDir);
      const layout = contentFileLayout(content.registry, content.type);
      const mintHead = MINT_SHAPE_OVERLAYS.get(content.registry)?.head;
      return (
        "  {\n" +
        `    type: ${JSON.stringify(content.registry)},\n` +
        `    referenceName: ${JSON.stringify(content.referenceName)},\n` +
        `    outputDir: ${JSON.stringify(outputDir)},\n` +
        `    fileStem: ${JSON.stringify(fileStem)},\n` +
        `    fileExtension: ${JSON.stringify(layout.fileExtension)},\n` +
        (mintHead === undefined ? "" : `    mintHead: ${JSON.stringify(mintHead)},\n`) +
        (EXACT_NAME_MINTS.has(content.registry) ? "    exactNames: true,\n" : "") +
        (layout.rootEnvelope === undefined
          ? ""
          : `    rootEnvelope: ${JSON.stringify(layout.rootEnvelope)},\n`) +
        `    fields: ${content.emission.fieldsConstant},\n` +
        `    localisation: ${content.emission.localisationConstant},\n` +
        (content.keyword === undefined
          ? ""
          : `    keyedBy: { keyword: ${JSON.stringify(content.keyword)}, ` +
            `nameField: ${JSON.stringify(content.type.nameField)} },\n`) +
        "  },\n"
      );
    })
    .join("");
  return (
    'import type { ContentRegistryDescriptor } from "../content/schema.ts";\n' +
    imports +
    "\n" +
    "export const CONTENT_REGISTRIES = [\n" +
    descriptors +
    "] as const satisfies readonly ContentRegistryDescriptor[];\n\n" +
    'export type ContentTypeName = (typeof CONTENT_REGISTRIES)[number]["type"];\n\n' +
    docComment([
      "The CWT reference a registry's definitions satisfy, as a type.",
      "",
      "The same thing `referenceName` carries as data, and the brand a",
      "`ContentItem` for that registry wears — which is what makes a defined",
      "component template reach a field holding `<component_template>`.",
    ]) +
    "export type ContentReferenceName<K extends ContentTypeName> = Extract<\n" +
    "  (typeof CONTENT_REGISTRIES)[number],\n" +
    "  { type: K }\n" +
    '>["referenceName"];\n'
  );
}

function importList(from: string, names: readonly string[]): string {
  if (names.length === 0) {
    return "";
  }
  return `import type { ${[...new Set(names)].sort().join(", ")} } from ${JSON.stringify(from)};\n`;
}

function summarise(skipped: readonly SkippedRule[]): string[] {
  const grouped = new Map<string, string[]>();
  for (const entry of skipped) {
    grouped.set(entry.reason, [...(grouped.get(entry.reason) ?? []), entry.name]);
  }
  return [...grouped]
    .sort((left, right) => right[1].length - left[1].length)
    .map(([reason, names]) => `${names.length} — ${reason}, e.g. ${names.slice(0, 3).join(", ")}`);
}

await main();
