/**
 * The technology recipe's slice of the matrix — see `recipe-matrix.test.ts` for
 * what the matrix as a whole proves and how it is split.
 *
 * One golden project hosts every compiler run in this file: the as-generated
 * gate, the uncommented examples, and the negative control. The harness's
 * incremental typecheck makes each run after the first a re-check of the one
 * swapped content file, and the negative control at the bottom is what proves
 * the compiler still sees that file.
 */

import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { CATALOG } from "../src/catalog/index.ts";
import type { GeneratedFeatureSource } from "../src/catalog/types.ts";
import { createGoldenProject, type GoldenProject } from "./helpers/golden-project.ts";
import {
  COMPILER_TIMEOUT,
  compileUncommented,
  describeSource,
  expectRefused,
  expectTypechecks,
  MATERIALIZATION_MANIFEST,
  NAME,
  NAMES,
  PREFIX,
  STEM,
} from "./helpers/matrix.ts";

const generate = (): GeneratedFeatureSource =>
  CATALOG.generate({ recipeId: "technology", names: NAMES, answers: {} });

describe("technology, with its only answer set", () => {
  describeSource("recipes/technology/default.ts", generate);
});

describe("technology, in a real project", () => {
  const generated = generate();
  let project: GoldenProject;

  beforeAll(() => {
    project = createGoldenProject();
    project.place(generated.basename, generated.contents);
  }, COMPILER_TIMEOUT);

  afterAll(() => project?.dispose());

  it("uses the source export condition only in the matrix harness", () => {
    expect(project.usesSourceCondition()).toBe(true);
  });

  it(
    "typechecks against the real SDK surface",
    () => {
      expectTypechecks(project);
    },
    COMPILER_TIMEOUT
  );

  it(
    "builds, and emits the technology and its localization",
    () => {
      const result = project.build();
      expect(result.status, result.output).toBe(0);

      const technology = `common/technology/${PREFIX}_${STEM}.txt`;
      const localization = `localisation/english/${PREFIX}_${STEM}_l_english.yml`;
      expect(project.outFiles()).toEqual([
        MATERIALIZATION_MANIFEST,
        technology,
        "descriptor.mod",
        localization,
      ]);
      expect(project.readOut(technology)).toContain(`${PREFIX}_tech_${STEM}`);
      expect(project.readOut(localization)).toContain(NAME);
    },
    COMPILER_TIMEOUT
  );

  /**
   * "Uncomment-ready" is a promise the curated starter policy makes, and it is
   * exactly the kind of promise that rots: an example naming a file that does
   * not exist reads fine and breaks the first author who takes it up. So the
   * examples are uncommented mechanically and put through the same compiler the
   * as-generated file passes. The golden stays the as-generated bytes; this is
   * a second program built from them.
   */
  it(
    "the commented examples compile as written, once their `// ` is removed",
    () => {
      compileUncommented(project, generate(), ["prerequisites"]);
    },
    COMPILER_TIMEOUT
  );

  it(
    "the compiler gate fails on a generated call the SDK would refuse",
    () => {
      // The negative control. Without it, a compiler step that silently stopped
      // seeing the generated file would pass forever, and the matrix above
      // would be proving nothing at all.
      expectRefused(project, generate(), 'area: "physics"', 'area: "chemistry"', "chemistry");
    },
    COMPILER_TIMEOUT
  );
});
