/**
 * Emitted TypeScript, and the one gate every identifier passes to get there.
 *
 * {@link assertVanillaIdentifier} is the licensing chokepoint. The package is
 * allowed to carry the *names* Paradox's files define and nothing else — no
 * script bodies, no localized text, no descriptions, no asset data — and the
 * only way to keep that true as the generator grows is to make it impossible to
 * write a string into an emitted file without passing it here first. Every
 * quoted literal in every emitter goes through {@link Chokepoint.literal},
 * which asserts and then quotes.
 *
 * The rejections are shaped after what a leak would actually look like: a
 * localisation sentence, a line of script, a fragment of a body. A name has no
 * braces, no `=`, no `$`, no quotes, no newlines, at most a couple of spaces,
 * and is short.
 */

import { pascalCase } from "@pdx-ts/codegen-cwt/naming";

import type { ScriptedDefinition } from "./read-scripted.ts";
import type { TrieNode } from "./trie.ts";

/**
 * Longest a real identifier gets; anything longer reads as prose.
 *
 * Measured, not guessed: across the whole 4.4.6 install the longest identifier
 * any of these registries defines is 84 characters
 * (`GFX_species_selected_background_trait_machine_pc_shattered_ring_habitable_preference`),
 * so a bound of 80 rejects real vanilla names. This is a backstop for "a whole
 * body slipped through" rather than the load-bearing rule — the forbidden
 * characters and the space limit are what actually separate a name from a
 * sentence — so it sits above the observed maximum with room for a patch to add
 * a longer one.
 */
const MAX_LENGTH = 120;

/** Characters no identifier contains, each of which script and prose do. */
const FORBIDDEN = ["\n", "\r", "\t", "{", "}", "=", '"', "$", "#"];

/** `has_country_flag = x`, `count < 3` — an assignment or comparison, not a name. */
const SCRIPT_SHAPE = /\w+\s*(=|<|>)/;

/**
 * Passes an identifier through, or throws naming what it was and where it came
 * from. Never returns a "safe" substitute: a silently repaired name would be a
 * wrong id emitted as a right-looking one.
 */
export function assertVanillaIdentifier(candidate: string, context: string): string {
  const reject = (reason: string): never => {
    throw new Error(
      `${context}: refusing to emit ${JSON.stringify(candidate.slice(0, 120))} — ${reason}. ` +
        "The vanilla package carries identifiers only; this looks like game content."
    );
  };
  if (candidate === "") {
    reject("empty");
  }
  if (candidate.length > MAX_LENGTH) {
    reject(`${candidate.length} characters, over the ${MAX_LENGTH} an identifier takes`);
  }
  for (const character of FORBIDDEN) {
    if (candidate.includes(character)) {
      reject(`contains ${JSON.stringify(character)}`);
    }
  }
  if ((candidate.match(/ /g) ?? []).length > 2) {
    reject("more spaces than a name has");
  }
  if (SCRIPT_SHAPE.test(candidate)) {
    reject("reads as a script assignment or comparison");
  }
  return candidate;
}

/**
 * Byte order, not locale order. Emission has to be reproducible on every
 * machine, and `localeCompare` is not: it treats `_` and case differently
 * depending on the environment's collation.
 */
export function compareIdentifiers(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Counts what the gate has seen, so the report can show it ran. */
export interface Chokepoint {
  /** Asserts, then quotes. The only way a string reaches emitted text. */
  literal(candidate: string, context: string): string;
  readonly checked: () => number;
}

export function createChokepoint(): Chokepoint {
  let seen = 0;
  return {
    literal(candidate, context) {
      seen += 1;
      return JSON.stringify(assertVanillaIdentifier(candidate, context));
    },
    checked: () => seen,
  };
}

export function header(gameVersion: string): string {
  return `// Generated by @pdx-ts/codegen-vanilla from Stellaris ${gameVersion}. Do not edit.\n\n`;
}

/** `ascension_perk` -> `ascension-perk`, matching the repo's generated files. */
export function kebabCase(name: string): string {
  return name.replaceAll("_", "-");
}

export function idTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Id`;
}

export function trieTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Trie`;
}

export function scriptedTypeName(registry: string): string {
  return `Vanilla${pascalCase(registry)}Params`;
}

/** `sprite` -> `SpriteRef`, the SDK's branded reference for that registry. */
export function refTypeName(registry: string): string {
  return `${pascalCase(registry)}Ref`;
}

export function registryFile(registry: string): string {
  return `registries/${kebabCase(registry)}.ts`;
}

export function trieIndexFile(registry: string): string {
  return `registries/${kebabCase(registry)}/index.ts`;
}

/**
 * The plural file the scripted parameter table lands in — `scripted_trigger`
 * defines many scripted triggers, and the interface is the whole table.
 */
export function scriptedFile(registry: string): string {
  return `${kebabCase(registry)}s.ts`;
}

export function emitIdUnion(
  registry: string,
  ids: readonly string[],
  gate: Chokepoint,
  gameVersion: string
): string {
  const context = `${registry} id`;
  const union = ids.length === 0 ? "never" : ids.map((id) => gate.literal(id, context)).join(" | ");
  return `${header(gameVersion)}export type ${idTypeName(registry)} = ${union};\n`;
}

export interface TrieEmission {
  /** Emitted path -> file text, the bucket files and the registry's index. */
  readonly files: ReadonlyMap<string, string>;
  /** Every exported type name, so the barrel can re-export them. */
  readonly exports: readonly { readonly name: string; readonly file: string }[];
}

/**
 * The trie as files: one per top-level bucket, plus the registry's index.
 *
 * The emitted layout follows the buckets, which follow vanilla's own files —
 * `registries/sprite/eventpictures.ts` holds what `interface/eventpictures.gfx`
 * defines, `registries/sound/toxoids.ts` holds the whole `sound/toxoids/`
 * subtree. A bucket's subtree is written inline inside its file however deep it
 * goes: splitting it further would name files after something other than the
 * game's own layout, which is the one thing making a regeneration diff readable.
 *
 * Ids from a file that names no bucket at all are leaves at the root, so they
 * are written into the index directly rather than becoming hundreds of one-line
 * files.
 */
export function emitTrie(
  registry: string,
  buckets: ReadonlyMap<string, TrieNode>,
  gate: Chokepoint,
  gameVersion: string
): TrieEmission {
  const context = `${registry} trie key`;
  const reference = refTypeName(registry);
  const root = trieTypeName(registry);
  const takenNames = new Set<string>([root]);
  // `index` is the registry's own index file, and two keys can mangle onto one
  // stem on a case-insensitive filesystem (`GFX_ship` and `gfx-ship`).
  const takenStems = new Set<string>(["index"]);

  /**
   * One node as a type.
   *
   * A node is a leaf, a branch, or both — an id spelled like the file or
   * directory its neighbours live in. The intersection is what makes the third
   * case navigable *and* usable: `.id` reads the id, and the remaining keys
   * keep descending.
   */
  const render = (node: TrieNode): string => {
    const members: string[] = [];
    if (node.id !== null) {
      members.push(`readonly id: ${gate.literal(node.id, `${context} leaf`)};`);
    }
    for (const [key, child] of node.children) {
      members.push(`readonly ${gate.literal(key, context)}: ${render(child)};`);
    }
    const body = `{\n${members.join("\n")}\n}`;
    return node.id === null ? body : `${reference} & ${body}`;
  };

  const dir = `registries/${kebabCase(registry)}`;
  const files = new Map<string, string>();
  const imports: string[] = [];
  const rootMembers: string[] = [];
  let rootLeaves = false;
  for (const [key, node] of buckets) {
    const quoted = gate.literal(key, context);
    if (node.children.size === 0) {
      rootLeaves = true;
      rootMembers.push(`readonly ${quoted}: ${render(node)};`);
      continue;
    }
    const name = unique(`${root}${pascalCase(key)}`, takenNames);
    const stem = unique(kebabCase(key), takenStems);
    files.set(
      `${dir}/${stem}.ts`,
      `${header(gameVersion)}import type { ${reference} } from "@pdx-ts/sdk";\n\n` +
        `export type ${name} = ${render(node)};\n`
    );
    imports.push(`import type { ${name} } from "./${stem}.ts";\n`);
    rootMembers.push(`readonly ${quoted}: ${name};`);
  }

  files.set(
    trieIndexFile(registry),
    header(gameVersion) +
      (rootLeaves ? `import type { ${reference} } from "@pdx-ts/sdk";\n` : "") +
      imports.join("") +
      `\nexport interface ${root} {\n${rootMembers.join("\n")}\n}\n`
  );
  // Only the root is public API. The per-bucket types are structural
  // intermediates the root already reaches; re-exporting a hundred of them
  // from the barrel would make the package's surface the trie's shape.
  return { files, exports: [{ name: root, file: trieIndexFile(registry) }] };
}

export function emitScriptedParams(
  registry: string,
  definitions: readonly ScriptedDefinition[],
  gate: Chokepoint,
  gameVersion: string
): string {
  const members = definitions.map((definition) => {
    const name = gate.literal(definition.name, `${registry} name`);
    const params = definition.params.map((param) => {
      const key = gate.literal(param.name, `${registry} ${definition.name} parameter`);
      return `readonly ${key}${param.optional ? "?" : ""}: string | number;`;
    });
    const shape = params.length === 0 ? "{}" : `{\n${params.join("\n")}\n}`;
    return `readonly ${name}: ${shape};`;
  });
  return (
    `${header(gameVersion)}export interface ${scriptedTypeName(registry)} {\n` +
    `${members.join("\n")}\n}\n`
  );
}

export interface AugmentPlan {
  /** Registry name -> its id union type and the file it lives in. */
  readonly ids: readonly { readonly registry: string; readonly file: string }[];
  /** Registry name -> its trie root type and file, for oversized registries. */
  readonly tries: readonly { readonly registry: string; readonly file: string }[];
  /** SDK merge target -> the emitted params interface, e.g. scripted triggers. */
  readonly scripted: readonly {
    readonly target: string;
    readonly registry: string;
    readonly file: string;
  }[];
}

/**
 * The single augmentation module.
 *
 * It is a `.ts` file with real imports on purpose: a file whose only statement
 * is `declare module` is a *script*, and a script's `declare module` declares a
 * new ambient module that shadows the SDK rather than merging into it. The
 * imports are what make this a module, and therefore an augmentation.
 */
export function emitAugment(plan: AugmentPlan, gate: Chokepoint, gameVersion: string): string {
  const imports = [
    ...plan.ids.map(({ registry, file }) => ({ name: idTypeName(registry), file })),
    ...plan.tries.map(({ registry, file }) => ({ name: trieTypeName(registry), file })),
    ...plan.scripted.map(({ registry, file }) => ({ name: scriptedTypeName(registry), file })),
  ]
    .map(({ name, file }) => `import type { ${name} } from "./${file}";\n`)
    .join("");

  const idMembers = plan.ids
    .map(
      ({ registry }) =>
        `readonly ${gate.literal(registry, "registry name")}: ${idTypeName(registry)};`
    )
    .join("\n");
  const trieMembers = plan.tries
    .map(
      ({ registry }) =>
        `readonly ${gate.literal(registry, "registry name")}: ${trieTypeName(registry)};`
    )
    .join("\n");
  const scriptedMembers = plan.scripted
    .map(({ target, registry }) => `interface ${target} extends ${scriptedTypeName(registry)} {}`)
    .join("\n");

  return (
    header(gameVersion) +
    imports +
    '\ndeclare module "@pdx-ts/sdk" {\n' +
    `interface VanillaIds {\n${idMembers}\n}\n` +
    (scriptedMembers === "" ? "" : `${scriptedMembers}\n`) +
    (plan.tries.length === 0 ? "" : `interface VanillaTries {\n${trieMembers}\n}\n`) +
    "}\n"
  );
}

/**
 * The barrel. The side-effect import of `./augment.ts` is the activation
 * guarantee — a type-only re-export would be erased in a build that never reads
 * the types, and the augmentation would silently not apply. Nothing else here
 * is a runtime export: the package is types and a version number.
 */
export function emitIndex(
  exports: readonly { readonly name: string; readonly file: string }[],
  gameVersion: string
): string {
  const lines = [...exports]
    .sort((left, right) => compareIdentifiers(left.name, right.name))
    .map(({ name, file }) => `export type { ${name} } from "./${file}";\n`)
    .join("");
  return `${header(gameVersion)}import "./augment.ts";\n\n${lines}`;
}

/**
 * Two bucket keys can mangle onto one type name or one file stem — `GFX_ship`
 * and `gfx-ship` share both. Buckets are walked in sorted order, so the
 * numbering is deterministic rather than machine-dependent.
 */
function unique(candidate: string, taken: Set<string>): string {
  let name = candidate;
  let suffix = 2;
  while (taken.has(name)) {
    name = `${candidate}${suffix}`;
    suffix += 1;
  }
  taken.add(name);
  return name;
}
