/**
 * Emits the committed, consumer-local projections of `VERIFIED_BUILD_PROJECTION`.
 * Unlike the vanilla identifier generator, this reads no game install.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { formatEmitted } from "./format.ts";
import {
  assertVerifiedBuildIdentifierEvidence,
  supportedVersionForVerifiedBuild,
  VERIFIED_BUILD_PROJECTION,
} from "./verified-build.ts";

const ROOT = fileURLToPath(new URL("../../../", import.meta.url));
const OUTPUTS = [
  path.join(ROOT, "packages/sdk/src/generated/verified-build.ts"),
  path.join(ROOT, "packages/create-stellaris-mod/src/generated/verified-build.ts"),
] as const;

function projectionSource(): string {
  const { gameVersion, provenance, installProtocol } = VERIFIED_BUILD_PROJECTION;
  const supportedVersion = supportedVersionForVerifiedBuild(VERIFIED_BUILD_PROJECTION);
  return `// Generated by @pdx-ts/codegen-vanilla from packages/codegen-vanilla/src/verified-build.ts. Do not edit.\n// ${provenance}\n\nexport const VERIFIED_STELLARIS_BUILD = ${JSON.stringify(gameVersion)};\nexport const VERIFIED_SUPPORTED_VERSION = ${JSON.stringify(supportedVersion)};\nexport const VERIFIED_BUILD_PROVENANCE = ${JSON.stringify(provenance)};\nexport const INSTALL_SENTINEL_PATH_SEGMENTS = ${JSON.stringify(installProtocol.sentinelPathSegments)} as const;\nexport const LAUNCHER_SETTINGS_FILENAME = ${JSON.stringify(installProtocol.launcherSettingsFilename)};\nexport const LAUNCHER_VERSION_FIELD = ${JSON.stringify(installProtocol.launcherVersionField)};\nexport const LAUNCHER_VERSION_PREFIX = ${JSON.stringify(installProtocol.launcherVersionPrefix)};\nexport const CORE_GAME_VERSION_PATTERN = new RegExp(${JSON.stringify(installProtocol.coreGameVersionPattern)});\nexport const SUPPORTED_VERSION_FROM_GAME_PATTERN = new RegExp(${JSON.stringify(installProtocol.supportedVersionFromGamePattern)});\nexport const SUPPORTED_VERSION_PATTERN = new RegExp(${JSON.stringify(installProtocol.supportedVersionPattern)});\nexport const PLATFORM_INSTALL_DEFAULTS = ${JSON.stringify(installProtocol.platformInstallDefaults, null, 2)} as const;\n`;
}

function readPackageVersion(): string {
  const packageJson = JSON.parse(
    readFileSync(path.join(ROOT, "packages/stellaris-ids/package.json"), "utf8")
  ) as { version?: unknown };
  if (typeof packageJson.version !== "string") {
    throw new Error("packages/stellaris-ids/package.json has no string version");
  }
  return packageJson.version;
}

function assertIdentifierEvidence(): void {
  const packageVersion = readPackageVersion();
  const provenance = readFileSync(path.join(ROOT, "packages/stellaris-ids/PROVENANCE.md"), "utf8");
  assertVerifiedBuildIdentifierEvidence(packageVersion, provenance);
}

async function main(): Promise<void> {
  assertIdentifierEvidence();
  const source = projectionSource();
  for (const output of OUTPUTS) {
    const formatted = await formatEmitted(
      new Map([["verified-build.ts", source]]),
      path.dirname(output)
    );
    mkdirSync(path.dirname(output), { recursive: true });
    writeFileSync(output, formatted.get("verified-build.ts")!, "utf8");
  }
  console.log(`verified build projection: Stellaris ${VERIFIED_BUILD_PROJECTION.gameVersion}`);
}

await main();
