/**
 * The vanilla identifier generator, measured against a fixture install.
 *
 * Hermetic and always-run: the install-gated gate (regenerating against the
 * real 4.4.6 install and comparing to committed output) can only run next to a
 * copy of the game, so everything that can be proved without one is proved
 * here — the readers' three id layouts, parameter optionality, the trie's
 * shape, and determinism.
 *
 * The fixture lowers the trie thresholds rather than shipping 2,000 fake
 * sprites: the thresholds are an option precisely so the *logic* can be
 * exercised at ten ids instead of ten thousand.
 */

import { describe, expect, it } from "vitest";

import { formatEmitted } from "../../../../tools/vanilla-codegen/format.ts";
import { generateVanillaPackage } from "../../../../tools/vanilla-codegen/generate.ts";

const OPTIONS = {
  installRoot: "packages/sdk/tests/fixtures/fake-install",
  gameVersion: "4.4.6",
  configRoot: "vendor/cwtools-stellaris-config/config",
  trie: { threshold: 5, leafSize: 4 },
};

const generated = generateVanillaPackage(OPTIONS);
const files = await formatEmitted(generated.files, "packages/stellaris-vanilla/src");

function file(name: string): string {
  const text = files.get(name);
  if (text === undefined) {
    throw new Error(`no emitted file ${name}; emitted ${[...files.keys()].join(", ")}`);
  }
  return text;
}

function registryReport(name: string) {
  const found = generated.report.registries.find((one) => one.registry === name);
  if (found === undefined) {
    throw new Error(`no report row for ${name}`);
  }
  return found;
}

describe("emitted file set", () => {
  it("emits one file per registry, plus the barrel and the augmentation", () => {
    expect(files.has("index.ts")).toBe(true);
    expect(files.has("augment.ts")).toBe(true);
    for (const row of generated.report.registries) {
      expect(files.has(`registries/${row.registry.replaceAll("_", "-")}.ts`)).toBe(true);
    }
    expect(files.has("scripted-triggers.ts")).toBe(true);
    expect(files.has("scripted-effects.ts")).toBe(true);
  });

  it("names every emitted registry in the augmentation", () => {
    const augment = file("augment.ts");
    for (const row of generated.report.registries) {
      expect(augment).toContain(`readonly ${row.registry}:`);
    }
    expect(augment).toContain(
      "interface VanillaScriptedTriggers extends VanillaScriptedTriggerParams {}"
    );
    expect(augment).toContain(
      "interface VanillaScriptedEffects extends VanillaScriptedEffectParams {}"
    );
  });

  it("re-exports every public type from the barrel with no runtime exports", () => {
    const barrel = file("index.ts");
    expect(barrel).toContain('import "./augment.ts";');
    expect(barrel).toContain(
      'export type { VanillaSpriteTrie } from "./registries/sprite/index.ts";'
    );
    expect(barrel).not.toMatch(/export (const|function|class|default)\b/);
  });

  it("carries the game version in every header", () => {
    for (const [name, text] of files) {
      expect(
        text.startsWith("// Generated by tools/vanilla-codegen from Stellaris 4.4.6."),
        name
      ).toBe(true);
    }
  });
});

describe("registry readers", () => {
  it("reads id-keyed registries from the top-level keys", () => {
    expect(file("registries/technology.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export type VanillaTechnologyId = "tech_fake_farming" | "tech_gene_tailoring";
      "
    `);
  });

  it("does not descend a path_strict registry's subdirectories", () => {
    // `common/technology/category` holds `technology_category` definitions, a
    // different CWT type; the fixture puts `biology` there. Reading it as a
    // technology is exactly the silent over-approximation `path_strict = yes`
    // exists to prevent, and `stellaris.load()` skips the same two subdirs.
    expect(registryReport("technology").ids).toBe(2);
    expect(file("registries/technology.ts")).not.toContain("biology");
  });

  it("reads name_field registries from the keyword's body field", () => {
    expect(registryReport("ambient_object").ids).toBe(2);
    expect(file("registries/ambient-object.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export type VanillaAmbientObjectId = "fake_ambient_beacon" | "fake_ambient_relay";
      "
    `);
  });

  it("walks nested directories and honours the declared extension", () => {
    // Two `.asset` files, one of them a directory down; `category` is a
    // different CWT type and contributes nothing.
    expect(registryReport("sound").files).toBe(2);
    expect(file("registries/sound.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export type VanillaSoundId = "fake_alert_one" | "fake_alert_two";
      "
    `);
    expect(file("registries/sound-effect.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export type VanillaSoundEffectId = "fake_effect_alpha" | "fake_effect_beta";
      "
    `);
  });

  it("descends skip_root_key registries by the presence of the name field", () => {
    // Six of the ten sprites are written under a subtype keyword other than
    // `spriteType`; matching on keywords would have dropped them.
    expect(registryReport("sprite").ids).toBe(10);
    expect(file("registries/sprite.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export type VanillaSpriteId =
        | "GFX_icon_alert"
        | "GFX_icon_warning"
        | "GFX_odd.name"
        | "GFX_planet_barren"
        | "GFX_planet_ocean"
        | "GFX_planet_toxic"
        | "GFX_ship"
        | "GFX_ship_combat"
        | "GFX_ship_combat_1"
        | "GFX_ship_combat_2";
      "
    `);
  });

  it("reports a registry the install does not have rather than failing", () => {
    const missing = registryReport("building");
    expect(missing).toMatchObject({ ids: 0, files: 0, missing: true });
    expect(file("registries/building.ts")).toContain("= never;");
  });
});

describe("scripted parameters", () => {
  it("makes defaulted and conditional parameters optional and the rest required", () => {
    expect(file("scripted-triggers.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export interface VanillaScriptedTriggerParams {
        readonly fake_conditional: {
          readonly FLAG?: string | number;
          readonly NAME?: string | number;
        };
        readonly fake_defaulted: {
          readonly YEARS: string | number;
        };
        readonly fake_no_params: {};
        readonly fake_required: {
          readonly TECH: string | number;
        };
      }
      "
    `);
  });

  it("unions a redefined trigger's parameters, required winning over optional", () => {
    // `$YEARS|10$` in the first file, bare `$YEARS$` in the second: a caller
    // who passes it satisfies whichever body the game loads.
    expect(file("scripted-triggers.ts")).toContain("readonly YEARS: string | number;");
  });

  it("reads effects the same way", () => {
    expect(file("scripted-effects.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      export interface VanillaScriptedEffectParams {
        readonly fake_effect_params: {
          readonly AMOUNT: string | number;
          readonly REASON?: string | number;
        };
        readonly fake_effect_simple: {};
      }
      "
    `);
  });

  it("counts definitions and parameterized definitions", () => {
    expect(generated.report.scripted).toMatchObject([
      { registry: "scripted_trigger", definitions: 4, parameterized: 3, files: 2 },
      { registry: "scripted_effect", definitions: 2, parameterized: 1, files: 1 },
    ]);
  });
});

describe("trie", () => {
  it("fuses the uniform prefix into the root keys", () => {
    // Every fixture sprite starts `GFX`, so a lone `GFX` node would be a
    // single-child ladder rung. The root menu is `GFX_icon`/`GFX_planet`/
    // `GFX_ship` instead.
    expect(file("registries/sprite/index.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      import type {
        VanillaSpriteTrieGFXIcon,
        VanillaSpriteTrieGFXPlanet,
        VanillaSpriteTrieGFXShip,
      } from "./g.ts";

      export interface VanillaSpriteTrie {
        readonly GFX_icon: VanillaSpriteTrieGFXIcon;
        readonly GFX_planet: VanillaSpriteTrieGFXPlanet;
        readonly GFX_ship: VanillaSpriteTrieGFXShip;
      }
      "
    `);
  });

  it("spells a leaf's remaining tail as one key and gives a branching id both roles", () => {
    // `GFX_ship` is a complete sprite and the prefix of three more, so its type
    // intersects the ref with the node; `combat_1` is a two-segment tail
    // collapsed into one property.
    expect(file("registries/sprite/g.ts")).toMatchInlineSnapshot(`
      "// Generated by tools/vanilla-codegen from Stellaris 4.4.6. Do not edit.

      import type { SpriteRef } from "@pdx-ts/sdk";

      export type VanillaSpriteTrieGFXIcon = {
        readonly alert: SpriteRef & {
          readonly id: "GFX_icon_alert";
        };
        readonly warning: SpriteRef & {
          readonly id: "GFX_icon_warning";
        };
      };

      export type VanillaSpriteTrieGFXPlanet = {
        readonly barren: SpriteRef & {
          readonly id: "GFX_planet_barren";
        };
        readonly ocean: SpriteRef & {
          readonly id: "GFX_planet_ocean";
        };
        readonly toxic: SpriteRef & {
          readonly id: "GFX_planet_toxic";
        };
      };

      export type VanillaSpriteTrieGFXShip = SpriteRef & {
        readonly id: "GFX_ship";
        readonly combat: SpriteRef & {
          readonly id: "GFX_ship_combat";
        };
        readonly combat_1: SpriteRef & {
          readonly id: "GFX_ship_combat_1";
        };
        readonly combat_2: SpriteRef & {
          readonly id: "GFX_ship_combat_2";
        };
      };
      "
    `);
  });

  it("routes an id that cannot survive property navigation to the flat union only", () => {
    expect(registryReport("sprite").trie).toMatchObject({ buckets: 3, flatOnly: 1 });
    expect(file("registries/sprite.ts")).toContain('"GFX_odd.name"');
    for (const [name, text] of files) {
      if (name.startsWith("registries/sprite/")) {
        expect(text, name).not.toContain("odd");
      }
    }
  });

  it("leaves registries under the threshold flat", () => {
    expect(registryReport("sound").trie).toBeNull();
    expect(files.has("registries/sound/index.ts")).toBe(false);
  });
});

describe("determinism", () => {
  it("emits byte-identical output on a second run", () => {
    const again = generateVanillaPackage(OPTIONS);
    expect([...again.files.keys()]).toEqual([...generated.files.keys()]);
    for (const [name, text] of again.files) {
      expect(text, name).toBe(generated.files.get(name));
    }
    expect(again.report).toEqual(generated.report);
  });
});

describe("report", () => {
  it("counts what it read and what the licensing gate saw", () => {
    expect(generated.report.rejections).toBe(0);
    expect(generated.report.identifiersChecked).toBeGreaterThan(50);
    expect(generated.report.diagnostics).toBe(0);
    expect(generated.report.emittedFiles).toBe(generated.files.size);
  });
});
