// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieAquatics = {
  readonly dragon: {
    readonly aqu_dragon: {
      readonly aqu_dragon_attack_mouth: SoundEffectRef & {
        readonly id: "aqu_dragon_attack_mouth";
      };
      readonly aqu_dragon_attack_mouth_deluge: SoundEffectRef & {
        readonly id: "aqu_dragon_attack_mouth_deluge";
      };
      readonly aqu_dragon_death: SoundEffectRef & {
        readonly id: "aqu_dragon_death";
      };
      readonly aqu_dragon_idle: SoundEffectRef & {
        readonly id: "aqu_dragon_idle";
      };
      readonly aqu_dragon_move: SoundEffectRef & {
        readonly id: "aqu_dragon_move";
      };
    };
  };
  readonly events: {
    readonly aqu_events: {
      readonly event_aqu_dragon: SoundEffectRef & {
        readonly id: "event_aqu_dragon";
      };
      readonly event_first_contact_aquatic: SoundEffectRef & {
        readonly id: "event_first_contact_aquatic";
      };
    };
  };
  readonly portraits: {
    readonly aqu_portraits: {
      readonly aqu_portrait_01: SoundEffectRef & {
        readonly id: "aqu_portrait_01";
      };
      readonly aqu_portrait_02: SoundEffectRef & {
        readonly id: "aqu_portrait_02";
      };
      readonly aqu_portrait_03: SoundEffectRef & {
        readonly id: "aqu_portrait_03";
      };
      readonly aqu_portrait_04: SoundEffectRef & {
        readonly id: "aqu_portrait_04";
      };
      readonly aqu_portrait_05: SoundEffectRef & {
        readonly id: "aqu_portrait_05";
      };
      readonly aqu_portrait_06: SoundEffectRef & {
        readonly id: "aqu_portrait_06";
      };
      readonly aqu_portrait_07: SoundEffectRef & {
        readonly id: "aqu_portrait_07";
      };
      readonly aqu_portrait_08: SoundEffectRef & {
        readonly id: "aqu_portrait_08";
      };
      readonly aqu_portrait_09: SoundEffectRef & {
        readonly id: "aqu_portrait_09";
      };
      readonly aqu_portrait_10: SoundEffectRef & {
        readonly id: "aqu_portrait_10";
      };
      readonly aqu_portrait_11: SoundEffectRef & {
        readonly id: "aqu_portrait_11";
      };
      readonly aqu_portrait_12: SoundEffectRef & {
        readonly id: "aqu_portrait_12";
      };
      readonly aqu_portrait_13: SoundEffectRef & {
        readonly id: "aqu_portrait_13";
      };
      readonly aqu_portrait_14: SoundEffectRef & {
        readonly id: "aqu_portrait_14";
      };
      readonly aqu_portrait_15: SoundEffectRef & {
        readonly id: "aqu_portrait_15";
      };
      readonly aqu_portrait_machine: SoundEffectRef & {
        readonly id: "aqu_portrait_machine";
      };
    };
  };
  readonly ships: {
    readonly aqu_ships: {
      readonly aqu_ship_battleship_idle: SoundEffectRef & {
        readonly id: "aqu_ship_battleship_idle";
      };
      readonly aqu_ship_battleship_move: SoundEffectRef & {
        readonly id: "aqu_ship_battleship_move";
      };
      readonly aqu_ship_colony_ship_idle: SoundEffectRef & {
        readonly id: "aqu_ship_colony_ship_idle";
      };
      readonly aqu_ship_colony_ship_move: SoundEffectRef & {
        readonly id: "aqu_ship_colony_ship_move";
      };
      readonly aqu_ship_colossus_close: SoundEffectRef & {
        readonly id: "aqu_ship_colossus_close";
      };
      readonly aqu_ship_colossus_idle: SoundEffectRef & {
        readonly id: "aqu_ship_colossus_idle";
      };
      readonly aqu_ship_colossus_move: SoundEffectRef & {
        readonly id: "aqu_ship_colossus_move";
      };
      readonly aqu_ship_colossus_open: SoundEffectRef & {
        readonly id: "aqu_ship_colossus_open";
      };
      readonly aqu_ship_construction_ship_idle: SoundEffectRef & {
        readonly id: "aqu_ship_construction_ship_idle";
      };
      readonly aqu_ship_construction_ship_move: SoundEffectRef & {
        readonly id: "aqu_ship_construction_ship_move";
      };
      readonly aqu_ship_corvette_01_idle: SoundEffectRef & {
        readonly id: "aqu_ship_corvette_01_idle";
      };
      readonly aqu_ship_corvette_01_move: SoundEffectRef & {
        readonly id: "aqu_ship_corvette_01_move";
      };
      readonly aqu_ship_corvette_02_idle: SoundEffectRef & {
        readonly id: "aqu_ship_corvette_02_idle";
      };
      readonly aqu_ship_corvette_02_move: SoundEffectRef & {
        readonly id: "aqu_ship_corvette_02_move";
      };
      readonly aqu_ship_cruiser_idle: SoundEffectRef & {
        readonly id: "aqu_ship_cruiser_idle";
      };
      readonly aqu_ship_cruiser_move: SoundEffectRef & {
        readonly id: "aqu_ship_cruiser_move";
      };
      readonly aqu_ship_destroyer_idle: SoundEffectRef & {
        readonly id: "aqu_ship_destroyer_idle";
      };
      readonly aqu_ship_destroyer_move: SoundEffectRef & {
        readonly id: "aqu_ship_destroyer_move";
      };
      readonly aqu_ship_habitat_idle: SoundEffectRef & {
        readonly id: "aqu_ship_habitat_idle";
      };
      readonly aqu_ship_juggernaut_idle: SoundEffectRef & {
        readonly id: "aqu_ship_juggernaut_idle";
      };
      readonly aqu_ship_juggernaut_move: SoundEffectRef & {
        readonly id: "aqu_ship_juggernaut_move";
      };
      readonly aqu_ship_military_defense_station_idle: SoundEffectRef & {
        readonly id: "aqu_ship_military_defense_station_idle";
      };
      readonly aqu_ship_mining_station_idle: SoundEffectRef & {
        readonly id: "aqu_ship_mining_station_idle";
      };
      readonly aqu_ship_research_station_idle: SoundEffectRef & {
        readonly id: "aqu_ship_research_station_idle";
      };
      readonly aqu_ship_science_ship_idle: SoundEffectRef & {
        readonly id: "aqu_ship_science_ship_idle";
      };
      readonly aqu_ship_science_ship_move: SoundEffectRef & {
        readonly id: "aqu_ship_science_ship_move";
      };
      readonly aqu_ship_starbase_idle: SoundEffectRef & {
        readonly id: "aqu_ship_starbase_idle";
      };
      readonly aqu_ship_titan_idle: SoundEffectRef & {
        readonly id: "aqu_ship_titan_idle";
      };
      readonly aqu_ship_titan_move: SoundEffectRef & {
        readonly id: "aqu_ship_titan_move";
      };
      readonly aqu_ship_transport_ship_idle: SoundEffectRef & {
        readonly id: "aqu_ship_transport_ship_idle";
      };
      readonly aqu_ship_transport_ship_move: SoundEffectRef & {
        readonly id: "aqu_ship_transport_ship_move";
      };
    };
  };
  readonly weapons: {
    readonly aqu_colossus_weapon: {
      readonly aqu_wep_colossus_megastructure_hit: SoundEffectRef & {
        readonly id: "aqu_wep_colossus_megastructure_hit";
      };
      readonly aqu_wep_colossus_muzzle: SoundEffectRef & {
        readonly id: "aqu_wep_colossus_muzzle";
      };
      readonly aqu_wep_colossus_planet_hit: SoundEffectRef & {
        readonly id: "aqu_wep_colossus_planet_hit";
      };
      readonly aqu_wep_colossus_windup: SoundEffectRef & {
        readonly id: "aqu_wep_colossus_windup";
      };
    };
  };
};
