// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieFederations = {
  readonly federations: {
    readonly bg_federation: SoundEffectRef & {
      readonly id: "bg_federation";
    };
    readonly bg_galactic_community: SoundEffectRef & {
      readonly id: "bg_galactic_community";
    };
    readonly bg_senate_floor: SoundEffectRef & {
      readonly id: "bg_senate_floor";
    };
    readonly button_federation_centralization_vote: SoundEffectRef & {
      readonly id: "button_federation_centralization_vote";
    };
    readonly button_senate_floor_propose_law: SoundEffectRef & {
      readonly id: "button_senate_floor_propose_law";
    };
    readonly button_senate_floor_vote: SoundEffectRef & {
      readonly id: "button_senate_floor_vote";
    };
    readonly event_announcement: SoundEffectRef & {
      readonly id: "event_announcement";
    };
    readonly event_assembly_fight: SoundEffectRef & {
      readonly id: "event_assembly_fight";
    };
    readonly event_galactic_community: SoundEffectRef & {
      readonly id: "event_galactic_community";
    };
    readonly event_vote: SoundEffectRef & {
      readonly id: "event_vote";
    };
    readonly juggernaut_arthropoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_arthropoid_idle";
    };
    readonly juggernaut_arthropoid_move: SoundEffectRef & {
      readonly id: "juggernaut_arthropoid_move";
    };
    readonly juggernaut_avian_idle: SoundEffectRef & {
      readonly id: "juggernaut_avian_idle";
    };
    readonly juggernaut_avian_move: SoundEffectRef & {
      readonly id: "juggernaut_avian_move";
    };
    readonly juggernaut_fungoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_fungoid_idle";
    };
    readonly juggernaut_fungoid_move: SoundEffectRef & {
      readonly id: "juggernaut_fungoid_move";
    };
    readonly juggernaut_humanoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_humanoid_idle";
    };
    readonly juggernaut_humanoid_move: SoundEffectRef & {
      readonly id: "juggernaut_humanoid_move";
    };
    readonly juggernaut_lithoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_lithoid_idle";
    };
    readonly juggernaut_lithoid_move: SoundEffectRef & {
      readonly id: "juggernaut_lithoid_move";
    };
    readonly juggernaut_mammalian_idle: SoundEffectRef & {
      readonly id: "juggernaut_mammalian_idle";
    };
    readonly juggernaut_mammalian_move: SoundEffectRef & {
      readonly id: "juggernaut_mammalian_move";
    };
    readonly juggernaut_molluscoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_molluscoid_idle";
    };
    readonly juggernaut_molluscoid_move: SoundEffectRef & {
      readonly id: "juggernaut_molluscoid_move";
    };
    readonly juggernaut_plantoid_idle: SoundEffectRef & {
      readonly id: "juggernaut_plantoid_idle";
    };
    readonly juggernaut_plantoid_move: SoundEffectRef & {
      readonly id: "juggernaut_plantoid_move";
    };
    readonly juggernaut_reptilian_idle: SoundEffectRef & {
      readonly id: "juggernaut_reptilian_idle";
    };
    readonly juggernaut_reptilian_move: SoundEffectRef & {
      readonly id: "juggernaut_reptilian_move";
    };
    readonly mega_shipyard_electricity_amb: SoundEffectRef & {
      readonly id: "mega_shipyard_electricity_amb";
    };
    readonly mega_shipyard_idle: SoundEffectRef & {
      readonly id: "mega_shipyard_idle";
    };
    readonly mega_shipyard_metal_amb: SoundEffectRef & {
      readonly id: "mega_shipyard_metal_amb";
    };
    readonly notification_alert_breach: SoundEffectRef & {
      readonly id: "notification_alert_breach";
    };
    readonly notification_denounced: SoundEffectRef & {
      readonly id: "notification_denounced";
    };
    readonly notification_galactic_focus: SoundEffectRef & {
      readonly id: "notification_galactic_focus";
    };
    readonly notification_low_cohesion: SoundEffectRef & {
      readonly id: "notification_low_cohesion";
    };
    readonly notification_player_level_up: SoundEffectRef & {
      readonly id: "notification_player_level_up";
    };
    readonly notification_player_lose_xp: SoundEffectRef & {
      readonly id: "notification_player_lose_xp";
    };
    readonly notification_resolution_defeated: SoundEffectRef & {
      readonly id: "notification_resolution_defeated";
    };
    readonly notification_resolution_passed: SoundEffectRef & {
      readonly id: "notification_resolution_passed";
    };
    readonly notification_resolution_vetoed: SoundEffectRef & {
      readonly id: "notification_resolution_vetoed";
    };
  };
};
