// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieIncoming = {
  readonly ai_message_beep: SoundEffectRef & {
    readonly id: "incoming_ai_message_beep";
  };
  readonly ai_message_state_01: SoundEffectRef & {
    readonly id: "incoming_ai_message_state_01";
  };
  readonly diplomatic_shroud_amb: SoundEffectRef & {
    readonly id: "incoming_diplomatic_shroud_amb";
  };
  readonly ex_message_state_01: SoundEffectRef & {
    readonly id: "incoming_ex_message_state_01";
  };
  readonly ex_message_state_02: SoundEffectRef & {
    readonly id: "incoming_ex_message_state_02";
  };
  readonly ex_message_state_03: SoundEffectRef & {
    readonly id: "incoming_ex_message_state_03";
  };
  readonly swarm_message_state_1: SoundEffectRef & {
    readonly id: "incoming_swarm_message_state_1";
  };
  readonly swarm_message_state_2: SoundEffectRef & {
    readonly id: "incoming_swarm_message_state_2";
  };
  readonly wormhole: SoundEffectRef & {
    readonly id: "incoming_wormhole";
  };
};

export type VanillaSoundEffectTrieIncrement = {
  readonly click: SoundEffectRef & {
    readonly id: "increment_click";
  };
};

export type VanillaSoundEffectTrieInf = {
  readonly portrait_01: SoundEffectRef & {
    readonly id: "inf_portrait_01";
  };
  readonly portrait_02: SoundEffectRef & {
    readonly id: "inf_portrait_02";
  };
  readonly portrait_03: SoundEffectRef & {
    readonly id: "inf_portrait_03";
  };
  readonly portrait_04: SoundEffectRef & {
    readonly id: "inf_portrait_04";
  };
  readonly portrait_05: SoundEffectRef & {
    readonly id: "inf_portrait_05";
  };
  readonly portrait_06: SoundEffectRef & {
    readonly id: "inf_portrait_06";
  };
  readonly portrait_07: SoundEffectRef & {
    readonly id: "inf_portrait_07";
  };
  readonly portrait_08: SoundEffectRef & {
    readonly id: "inf_portrait_08";
  };
  readonly portrait_09: SoundEffectRef & {
    readonly id: "inf_portrait_09";
  };
  readonly portrait_10: SoundEffectRef & {
    readonly id: "inf_portrait_10";
  };
};

export type VanillaSoundEffectTrieInvalid = {
  readonly action: SoundEffectRef & {
    readonly id: "invalid_action";
  };
};

export type VanillaSoundEffectTrieIon = {
  readonly cannon_fire: SoundEffectRef & {
    readonly id: "ion_cannon_fire";
  };
  readonly cannon_hit: SoundEffectRef & {
    readonly id: "ion_cannon_hit";
  };
  readonly cannon_windup: SoundEffectRef & {
    readonly id: "ion_cannon_windup";
  };
};
