// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieJuggernaut = {
  readonly arthropoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_arthropoid_idle";
  };
  readonly arthropoid_move: SoundEffectRef & {
    readonly id: "juggernaut_arthropoid_move";
  };
  readonly avian_idle: SoundEffectRef & {
    readonly id: "juggernaut_avian_idle";
  };
  readonly avian_move: SoundEffectRef & {
    readonly id: "juggernaut_avian_move";
  };
  readonly fungoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_fungoid_idle";
  };
  readonly fungoid_move: SoundEffectRef & {
    readonly id: "juggernaut_fungoid_move";
  };
  readonly humanoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_humanoid_idle";
  };
  readonly humanoid_move: SoundEffectRef & {
    readonly id: "juggernaut_humanoid_move";
  };
  readonly lithoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_lithoid_idle";
  };
  readonly lithoid_move: SoundEffectRef & {
    readonly id: "juggernaut_lithoid_move";
  };
  readonly mammalian_idle: SoundEffectRef & {
    readonly id: "juggernaut_mammalian_idle";
  };
  readonly mammalian_move: SoundEffectRef & {
    readonly id: "juggernaut_mammalian_move";
  };
  readonly molluscoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_molluscoid_idle";
  };
  readonly molluscoid_move: SoundEffectRef & {
    readonly id: "juggernaut_molluscoid_move";
  };
  readonly necroid_idle: SoundEffectRef & {
    readonly id: "juggernaut_necroid_idle";
  };
  readonly necroid_move: SoundEffectRef & {
    readonly id: "juggernaut_necroid_move";
  };
  readonly plantoid_idle: SoundEffectRef & {
    readonly id: "juggernaut_plantoid_idle";
  };
  readonly plantoid_move: SoundEffectRef & {
    readonly id: "juggernaut_plantoid_move";
  };
  readonly reptilian_idle: SoundEffectRef & {
    readonly id: "juggernaut_reptilian_idle";
  };
  readonly reptilian_move: SoundEffectRef & {
    readonly id: "juggernaut_reptilian_move";
  };
};
