// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieMammalianPortraitPack = {
  readonly mammalian_greetings: {
    readonly mammalian_portrait_10_mouse_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_10_mouse_f";
    };
    readonly mammalian_portrait_10_mouse_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_10_mouse_m";
    };
    readonly mammalian_portrait_1_giraffe_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_1_giraffe_f";
    };
    readonly mammalian_portrait_1_giraffe_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_1_giraffe_m";
    };
    readonly mammalian_portrait_2_pangolin_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_2_pangolin_f";
    };
    readonly mammalian_portrait_2_pangolin_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_2_pangolin_m";
    };
    readonly mammalian_portrait_3_rabbit_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_3_rabbit_f";
    };
    readonly mammalian_portrait_3_rabbit_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_3_rabbit_m";
    };
    readonly mammalian_portrait_4_goat_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_4_goat_f";
    };
    readonly mammalian_portrait_4_goat_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_4_goat_m";
    };
    readonly mammalian_portrait_5_hippo_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_5_hippo_f";
    };
    readonly mammalian_portrait_5_hippo_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_5_hippo_m";
    };
    readonly mammalian_portrait_6_bat_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_6_bat_f";
    };
    readonly mammalian_portrait_6_bat_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_6_bat_m";
    };
    readonly mammalian_portrait_7_lion_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_7_lion_f";
    };
    readonly mammalian_portrait_7_lion_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_7_lion_m";
    };
    readonly mammalian_portrait_8_wolf_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_8_wolf_f";
    };
    readonly mammalian_portrait_8_wolf_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_8_wolf_m";
    };
    readonly mammalian_portrait_9_rhino_f: SoundEffectRef & {
      readonly id: "mammalian_portrait_9_rhino_f";
    };
    readonly mammalian_portrait_9_rhino_m: SoundEffectRef & {
      readonly id: "mammalian_portrait_9_rhino_m";
    };
  };
};
