// Generated by @pdx-ts/vanilla-codegen from Stellaris 4.4.6. Do not edit.

import type { SoundEffectRef } from "@pdx-ts/sdk";

export type VanillaSoundEffectTrieQueing = {
  readonly spaceport_module: SoundEffectRef & {
    readonly id: "queing_spaceport_module";
  };
};

export type VanillaSoundEffectTrieQueuing = {
  readonly army: SoundEffectRef & {
    readonly id: "queuing_army";
  };
  readonly building: SoundEffectRef & {
    readonly id: "queuing_building";
  };
  readonly ship: SoundEffectRef & {
    readonly id: "queuing_ship";
  };
};
